CREATE OR REPLACE TYPE sa."BEN_EARNINGS_RULE" FORCE
IS
  Object
  (
    X_TRANSACTION_TYPE      VARCHAR2(100),
    X_BENEFITS_EARNED       NUMBER,
    X_POINT_COOLDOWN_DAYS	  NUMBER,         -- CR41473 LRP2
    X_POINT_EXPIRATION_DAYS	NUMBER,           -- CR41473 LRP2
    X_CATALOG_PROVIDER      VARCHAR2(30 CHAR) -- CR41473 LRP2
  );
/