CREATE OR REPLACE type sa.master_inv_obj as object  (
           STATE varchar2(2 char),
           ZONE varchar2(100 char),
           MARKETID number,
           MARKET_NAME varchar2(255 char),
           CARRIER_ID number,
           CARRIER_NAME varchar2(255 char),
           TECHNOLOGY varchar2(20 char),
           FREQUENCY1 integer,
           FREQUENCY2 integer,
           SID varchar2(10 char),
           LEAD_TIME integer,
           TARGET_INV_LEVEL integer,
           NEW_AVAILABLE integer,
           USED_AVAILABLE integer,
           NEWHOLD_AVAILABLE integer,
           USEDHOLD_AVAILABLE integer,
           ACTIVE_LINES integer,
           TOTAL_AVAILABLE integer,
           COOLING_LINES integer,
           EXCESSIVE_INVENTORY integer,
           AVERAGE_UTILIZATION integer,
           MAX_UTILIZATION integer,
           EXCESS integer,
           CUSHION integer,
           REORDER_POINT integer,
           SUGGESTED_AMOUNT integer,
           MAX_INVENTORY integer
           );
/