CREATE OR REPLACE TYPE sa."PL_ACKRETURN_STRUCTURE"                                                                          AS OBJECT
(
    FIRST_STRING        VARCHAR2(100),
    SECOND_STRING       VARCHAR2(100),
    THIRD_STRING        VARCHAR2(100),
    FOURTH_STRING       VARCHAR2(100),
    FIFTH_STRING        VARCHAR2(100),
    SIXTH_STRING        VARCHAR2(100),
    SEVENTH_STRING      VARCHAR2(100),
    EIGHTH_STRING       VARCHAR2(100),
    NINTH_STRING        VARCHAR2(100),
    TENTH_STRING        VARCHAR2(100)
)
/