CREATE OR REPLACE TYPE sa."PL_COMMAND_STRUCTURE"                                                                          AS OBJECT
(
    COMMAND             NUMBER,
    FIRST_DOUBLE        NUMBER,
    SECOND_DOUBLE       NUMBER,
    THIRD_DOUBLE        NUMBER,
    FOURTH_DOUBLE       NUMBER,
    FIFTH_DOUBLE        NUMBER,
    SIXTH_DOUBLE        NUMBER,
    SERVENTH_DOUBLE     NUMBER,
    EIGHT_DOUBLE        NUMBER,
    NINTH_DOUBLE        NUMBER,
    TENTH_DOUBLE        NUMBER,
    FIRST_STRING        VARCHAR2(200),
    SECOND_STRING       VARCHAR2(200),
    THIRD_STRING        VARCHAR2(200),
    FOURTH_STRING       VARCHAR2(200),
    FIFTH_STRING        VARCHAR2(200),
    SIXTH_STRING        VARCHAR2(200),
    SEVENTH_STRING      VARCHAR2(200),
    EIGHTH_STRING       VARCHAR2(200),
    NINTH_STRING        VARCHAR2(200),
    TENTH_STRING        VARCHAR2(200)
)
/