CREATE OR REPLACE TYPE sa."PL_REDEMPTION_STRUCTURE"                                                                          AS OBJECT
(
    FIRST_STRING        VARCHAR2(100),
    FIRST_DENOMINATION  VARCHAR2(100),
    FIRST_PROMO_CODE    VARCHAR2(100),
    SECOND_STRING       VARCHAR2(100),
    SECOND_DENOMINATION VARCHAR2(100),
    SECOND_PROMO_CODE   VARCHAR2(100),
    THIRD_STRING        VARCHAR2(100),
    THIRD_DENOMINATION  VARCHAR2(100),
    THIRD_PROMO_CODE    VARCHAR2(100)
)
/