CREATE OR REPLACE TYPE sa.purchase_add_info_Obj IS object
(
	afs_reason_code			VARCHAR2(50),
	afs_result				VARCHAR2(50),
	hostserverity			VARCHAR2(50),
	consumer_local_time		VARCHAR2(30),
	afs_factor_code			VARCHAR2(100),
	addr_info_code			VARCHAR2(100),
	internet_info_code		VARCHAR2(100),
	suspicious_info_code	VARCHAR2(100),
	velocity_info_code		VARCHAR2(100),
	score_model_used		VARCHAR2(100),
	bin_country				VARCHAR2(50),
	card_scheme				VARCHAR2(100),
	device_fp_cookiesenabled			VARCHAR2(30),
	device_fp_flash_enabled				VARCHAR2(30),
	device_fp_images_enabled			VARCHAR2(30),
	device_fp_java_script_enabled		VARCHAR2(30),
	device_fp_true_IP_address			VARCHAR2(30),
	device_fp_true_IP_addr_attbr		VARCHAR2(100),
	dav_reason_code			VARCHAR2(50),
	address_type			VARCHAR2(30),
	bar_code				VARCHAR2(50),
	barcode_checkdigit		VARCHAR2(30),
	match_score				VARCHAR2(50),
	std_addr				VARCHAR2(100),
	std_addr_NoApt			VARCHAR2(100),
	std_city				VARCHAR2(100),
	std_county				VARCHAR2(100),
	std_CSP					VARCHAR2(100),
	std_state				VARCHAR2(50),
	std_postal_code			VARCHAR2(50),
	std_country				VARCHAR2(50),
	std_iso_country			VARCHAR2(50),
	us_info					VARCHAR2(50)
 );
/