CREATE OR REPLACE TYPE sa.Purch_hdr_rec
IS
  object
  (
    IN_RQST_SOURCE        VARCHAR2(50),
    IN_CHANNEL            VARCHAR2(50),
    IN_ORDER_TYPE         VARCHAR2(50),
    IN_C_ORDERID          VARCHAR2(50),
    IN_ACCOUNT_ID         VARCHAR2(50),
    IN_AUTH_REQUEST_ID    VARCHAR2 (40),
    IN_GROUPIDENTIFIER    VARCHAR2(30),
    IN_RQST_TYPE          VARCHAR2(20),
    IN_RQST_DATE          DATE,
    In_Ics_Applications   VARCHAR2(50),
    in_merchant_id        varchar2(30),
    IN_OFFER_NUM          VARCHAR2(10),
    IN_QUANTITY           NUMBER,
    in_ignore_avs         varchar2(10),
    IN_AVS                VARCHAR2(30),
    IN_DISABLE_AVS        VARCHAR2(30),
    IN_CUSTOMER_HOSTNAME  VARCHAR2(60),
    IN_CUSTOMER_IPADDRESS VARCHAR2(30),
    IN_CUSTOMER_FIRSTNAME VARCHAR2(20),
    IN_CUSTOMER_LASTNAME  VARCHAR2(20),
    IN_CUSTOMER_PHONE     VARCHAR2(20),
    IN_CUSTOMER_EMAIL     VARCHAR2(50),
    in_status             varchar2(20),
    IN_ESN                VARCHAR2(20),
    IN_AMOUNT             NUMBER(19,2),
    IN_TAX_AMOUNT         NUMBER(19,2),
    IN_sales_TAX_AMOUNT   NUMBER,
    IN_E911_TAX_AMOUNT    NUMBER,
    IN_USF_TAXAMOUNT      NUMBER,
    IN_RCRF_TAX_AMOUNT    NUMBER,
    IN_ADD_TAX1           NUMBER,
    IN_ADD_TAX2           NUMBER,
    IN_DISCOUNT_AMOUNT    NUMBER,
    IN_FREIGHT_AMOUNT     NUMBER,
    IN_AUTH_AMOUNT        NUMBER,
    IN_OTHER_FUNDS        NUMBER,
    IN_USER               VARCHAR2(80),
    IN_PYMT_SRC_id        NUMBER,
    IN_WEB_USER           VARCHAR2(50),
    IN_PAYMENT_TYPE       VARCHAR2(50),
    IN_PROCESS_DATE       DATE)
/