CREATE OR REPLACE TYPE sa.Purch_dtl_rec
IS
  object
  (
    IN_X_ESN         VARCHAR2(50),
    IN_LINE_AMOUNT   NUMBER(19,2),
    IN_LINE_NUMBER   NUMBER,
    IN_PART_NUMBER   VARCHAR2(50),
    IN_LINE_QUANTITY NUMBER,
    IN_DOMAIN        VARCHAR2(100),
    IN_SALES_RATE FLOAT(126),
    IN_SALESTAX_AMOUNT NUMBER,
    IN_E911_RATE FLOAT(126),
    IN_E911_TAX_AMOUNT NUMBER,
    IN_USF_RATE FLOAT(126),
    IN_USF_TAXAMOUNT NUMBER,
    IN_RCRF_RATE FLOAT(126),
    IN_RCRF_TAX_AMOUNT      NUMBER,
    IN_TOTAL_TAX_AMOUNT     NUMBER,
    IN_TOTAL_AMOUNT         NUMBER,
    IN_LINE_FREIGHT_AMOUNT  NUMBER,
    IN_LINE_FREIGHT_METHOD  VARCHAR2(100),
    IN_LINE_FREIGHT_CARRIER VARCHAR2(100),
    IN_LINE_DISCOUNT_AMOUNT NUMBER,
    IN_ADD_TAX_1            NUMBER,
    IN_ADD_TAX_2            NUMBER)
/