CREATE OR REPLACE TYPE sa.REFUND_OUT_REC
IS
 OBJECT
 ( ESN           VARCHAR2(50),
   SMP           VARCHAR2(30),
   LINE_NUMBER   NUMBER,
   PART_NUMBER   VARCHAR2(50),
   UNIT_PRICE    NUMBER,
   QUANTITY      NUMBER,
   SALES_TAXAMOUNT NUMBER,
   E911_TAXAMOUNT    NUMBER,
   USF_TAXAMOUNT   NUMBER,
   RCRF_TAXAMOUNT  NUMBER,
   TOTAL_TAXAMOUNT NUMBER,
   TOTAL_AMOUNT    NUMBER);
/