CREATE OR REPLACE TYPE sa.SMARTPAY_ORD_LOG_HDR_REC_TYPE
IS
  OBJECT
  (
    COMMERCE_ORDER_ID        VARCHAR2(50 BYTE),
    COMMERCE_ORDER_TYPE      VARCHAR2(50 BYTE),
    BUS_ORG_ID               VARCHAR2(40 BYTE),
    REQUEST_SOURCE           VARCHAR2(20 BYTE),
    CLIENT_ID                VARCHAR2(100 BYTE),
    AMOUNT                   NUMBER(19, 2),
    TOTAL_AMOUNT             NUMBER(19, 2),
    DECISION                 VARCHAR2(20 BYTE),
    AUTH_REQUEST_ID          VARCHAR2(30 BYTE),
    MERCHANT_REF_NUMBER      VARCHAR2(50 BYTE),
    CUSTOMER_FIRSTNAME       VARCHAR2(20 BYTE),
    CUSTOMER_LASTNAME        VARCHAR2(20 BYTE),
    CUSTOMER_PHONE           VARCHAR2(20 BYTE),
    CUSTOMER_EMAIL           VARCHAR2(50 BYTE),
    SHIP_ADDRESS1            VARCHAR2(200 BYTE),
    SHIP_ADDRESS2            VARCHAR2(200 BYTE),
    SHIP_CITY                VARCHAR2(30 BYTE),
    SHIP_STATE               VARCHAR2(40 BYTE),
    SHIP_ZIP                 VARCHAR2(20 BYTE),
    SHIP_COUNTRY             VARCHAR2(20 BYTE),
    RESPONSE_CODE            VARCHAR2(100 BYTE),
    RESPONSE_MESSAGE         VARCHAR2(1000 BYTE),
    INSERT_TIMESTAMP         DATE,
    UPDATE_TIMESTAMP         DATE
  );
/