CREATE OR REPLACE TYPE sa.TF_SOAPROCESS_NOTIFICATIONTYPE IS OBJECT (
   NOTIFICATIONMODE                   NUMBER,
   NOTIFICATIONSENT                   VARCHAR2 (30),
   NOTIFICATIONPHONE                  TF_SOAPROCESS_PHONETYPE,
   NOTIFICATIONEMAIL                  TF_SOAPROCESS_EMAILTYPE,
   NOTIFICATIONRESPONSE               VARCHAR2 (150));
/