CREATE OR REPLACE TYPE sa.TYP_REWARD_VOUCHERS IS OBJECT (
    VOUCHER_ID                VARCHAR2(50)           ---table_x_vouchers.objid
    ,BENEFIT_ID               NUMBER           ---Table_x_benefits.objid
    ,BENEFIT_TYPE             VARCHAR2(100)    ---"REWARD_BENEFITS"
    ,BENEFIT_PROGRAM_NAME     VARCHAR2(100)    ---"UPGRADE_PLANS"
    ,BENEFIT_PROGRAM_OBJID    NUMBER     			 ---TABLE_X_BENEFIT_PROGRAMS.objid - lookup table objid
    ,BENEFIT_UNIT             VARCHAR2(100)    ---"DOLLARS"
    ,BENEFIT_VALUE            VARCHAR2(100)    ---"300" OR "200"
    ,PARTIAL_USAGE_ALLOWED    VARCHAR2(1)      ---"N"
    ,PURCH_USAGE_ALLOWED      VARCHAR2(100)    ---"DEVICE_ONLY"
		,STATIC FUNCTION INITIALIZE RETURN  TYP_REWARD_VOUCHERS
)
/
CREATE OR REPLACE TYPE BODY sa.TYP_REWARD_VOUCHERS IS
	STATIC FUNCTION INITIALIZE RETURN TYP_REWARD_VOUCHERS IS
	BEGIN
		RETURN  TYP_REWARD_VOUCHERS (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
	END INITIALIZE;
END;
/