CREATE OR REPLACE TYPE sa.TYP_REWARD_BENEFITS IS OBJECT (
     BENEFIT_ID               NUMBER           ---Table_x_benefits.objid
    ,BENEFIT_TYPE             VARCHAR2(100)    ---"REWARD_BENEFITS"
    ,BENEFIT_PROGRAM_NAME     VARCHAR2(100)    ---"UPGRADE_PLANS"
    ,BENEFIT_PROGRAM_OBJID    NUMBER           ---TABLE_X_BENEFIT_PROGRAMS.objid - lookup table objid
    ,BENEFIT_UNIT             VARCHAR2(100)    ---"DOLLARS"
    ,BENEFIT_VALUE            VARCHAR2(100)    ---"300" OR "200"
    ,PARTIAL_USAGE_ALLOWED    VARCHAR2(1)      ---"N"   { Y | N }
    ,PURCH_USAGE_ALLOWED      VARCHAR2(100)    ---"DEVICE_ONLY"
		,STATIC FUNCTION INITIALIZE RETURN TYP_REWARD_BENEFITS
)
/
CREATE OR REPLACE TYPE BODY sa.TYP_REWARD_BENEFITS IS
	STATIC FUNCTION INITIALIZE RETURN TYP_REWARD_BENEFITS IS
	BEGIN
		RETURN  TYP_REWARD_BENEFITS (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
	END INITIALIZE;
END;
/