CREATE OR REPLACE PROCEDURE sa.CLOSE_DBLINK(P_ENV IN VARCHAR2) IS

V_LINK_CNT NUMBER :=0;

BEGIN

SELECT COUNT(*)
INTO V_LINK_CNT
FROM  V$DBLINK
WHERE DB_LINK=P_ENV||'.WORLD' AND OWNER_ID=38;

IF V_LINK_CNT > 0 THEN
EXECUTE IMMEDIATE 'ALTER SESSION CLOSE  DATABASE LINK '||P_ENV||'.WORLD';
COMMIT;
END IF;
END;
/