CREATE OR REPLACE procedure sa.load_vmbc_request(file_name in varchar2,
                                              op_sqlcode out number,
                                              op_sqlerrm out varchar2) is
    --LV_DATA_SOURCE            VARCHAR2(50);                                              
begin
        
                    sa.ota_util_pkg.err_log (
                p_action => 'before insert into xsu_vmbc_request table step 1',
                p_error_date => sysdate,
                p_key => 'file_name',
                p_program_name => 'load_vmbc_request',
                p_error_text =>  '--op_sqlcode: '||op_sqlcode||' op_sqlerrm: '||op_sqlerrm);
                
    




    IF UPPER(file_name ) LIKE 'VMBC%'
    THEN
    --LV_DATA_SOURCE    := 'VMBC';

                        
        
 insert into sa.xsu_vmbc_request
      (REQUESTTYPE,
       REQUESTID,
       ENROLLREQUEST,
       LID,
       CONTACT,
       NAME,
       ADDRESS,
       ADDRESS2,
       CITY,
       STATE,
       ZIP,
       ZIP2,
       COUNTRY,
       HOMENUMBER,
       EMAIL,
       ALLOWPRERECORDED,
       EMAILPREF,
       APPLICATION,
       APPLYDATE,
       ESN,
       ISCUSTOMER,
       TRACFONENUMBER,
       QUALIFYSTATUS,
       QUALIFYMETHOD,
       QUALIFYTYPE,
       QUALIFYDATE,
       UNQUALIFYCODE,
       RETAILERCODE,
       CHANNELTYPE,
       BRIBEMINUTES,
       REGISTRATIONLANGUAGE,
       BATCHDATE,
       PLAN,
       REF_FNAME,
       REF_LNAME,
       REF_MIN,
       REF_LID,
       REF_STATUS,
       EXTERNAL_ACCOUNT,
       QUALIFYPROGRAMS,
       x_campaign,
       x_promotion,
       x_promocode,
       x_shp_address,
       x_shp_address2,
       x_shp_city,
       x_shp_state,
       x_shp_zip,
         addressiscommercial,
       addressisduplicated,
       addressisinvalid,
       addressistemporary,
       stateidname,
       stateidvalue,
       adl,
       usacform,
       celltelephone,
       eligiblefirstname,
       eligiblelastname,
       eligiblemiddlenameinitial,
       haspromotionalplan,
       hmodisclaimer,
       ipaddress,
       personid,
       personisinvalid,
       shippingaddresshash,
       stateagencyqualification,
       transferflag,
       old_lid,
       status,
       lastmodified,
       dobisinvalid,
       ssnisinvalid,
       disablemanualverification,
       device_type,
       byop_device_state,
       byop_carrier,
       byop_sim,
       byop_esn,
       byop_act_zip
        ,data_source        -- Added for CR38122
       )
select REQUEST_TYPE,
       REQUESTID,
       ENROLL_REQUEST,
       LID,
       null,
       NAME,
       ADDRESS,
       ADDRESS2,
       CITY,
       STATE,
       ZIP,
       ZIP2,
       COUNTRY,
       HOMENUMBER,
       EMAIL,
       ALLOWPRERECORDED,
       EMAILPREF,
       null,
       APPLYDATE,
       ESN,
       ISCUSTOMER,
       TRACFONENUMBER,
       QUALIFYSTATUS,
       QUALIFYMETHOD,
       QUALIFYTYPE,
       QUALIFYDATE,
       UNQUALIFYCODE,
       RETAILERCODE,
       CHANNELTYPE,
       BRIBEMINUTES,
       REGISTRATIONLANGUAGE,
       sysdate,
       PLAN,
       REF_FNAME,
       REF_LNAME,
       REF_MIN,
       REF_LID,
       REF_STATUS,
       EXTERNAL_ACCOUNT,
        extractvalue(qualifyPrograms,'qualifyPrograms[1]',
                     'xmlns="http://schemas.vmbc.com/enrollment"')||','||
        extractvalue(qualifyPrograms,'qualifyPrograms[2]',
                     'xmlns="http://schemas.vmbc.com/enrollment"')||','||
        extractvalue(qualifyPrograms,'qualifyPrograms[3]',
                     'xmlns="http://schemas.vmbc.com/enrollment"')||','||
        extractvalue(qualifyPrograms,'qualifyPrograms[4]',
                     'xmlns="http://schemas.vmbc.com/enrollment"') qp,
       x_campaign,
       x_promotion,
       x_promocode,
       x_shp_address,
       x_shp_address2,
       x_shp_city,
       x_shp_state,
       x_shp_zip,
         addressiscommercial,
       addressisduplicated,
       addressisinvalid,
       addressistemporary,
       stateidname,
       stateidvalue,
       adl,
       usacform,
       celltelephone,
       eligiblefirstname,
       eligiblelastname,
       eligiblemiddlenameinitial,
       haspromotionalplan,
       hmodisclaimer,
       ipaddress,
       personid,
       personisinvalid,
       shippingaddresshash,
       stateagencyqualification,
       transferflag,
       old_lid,
       status,
       lastmodified,
       dobisinvalid,
       ssnisinvalid,
       disablemanualverification,
       device_type,
       byop_device_state,
       byop_carrier,
       byop_sim,
       byop_esn,
       byop_act_zip
    --    ,LV_DATA_SOURCE        -- Added for CR38122
        ,'VMBC'
from xmltable(
    xmlnamespaces('http://www.w3.org/2001/XMLSchema-instance' as "xsi",
            'http://www.w3.org/2001/XMLSchema' as "xsd",
            'http://schemas.vmbc.com/enrollment/20110517_TF_LL_Subscription.xsd' as "schemaLocation",
            default 'http://schemas.vmbc.com/enrollment' ) ,
        '/tracfone/request'
        passing xmltype( bfilename('XML_FOLDER',file_name ), nls_charset_id('AL32UTF8') )
         columns
            request_type         varchar2(50)   path 'requestType',
            requestid            varchar2(50)   path 'requestID',
            enroll_request       varchar2(100)  path 'enrollRequest',
            lid                  number         path 'lid',
            contact              varchar2(100)  path 'contact',
            name                 varchar2(100)  path 'contact/name',
            address              varchar2(200)  path 'contact/address',
            address2             varchar2(100)  path 'contact/address2',
            city                 varchar2(100)  path 'contact/city',
            state                varchar2(50)   path 'contact/state',
            zip                  varchar2(100)  path 'contact/zip',
            zip2                 varchar2(100)  path 'contact/zip2',
            country              varchar2(100)  path 'contact/country',
            homeNumber           varchar2(100)  path 'contact/homeNumber',
            email                varchar2(100)  path 'contact/email',
            allowPrerecorded     varchar2(100)  path 'contact/allowPrerecorded',
            emailPref            varchar2(100)  path 'contact/emailPref',
            dob                  varchar2(100)  path 'contact/dob',
            external_account     varchar2(100)  path 'contact/externalAccount',
            application          varchar2(100)  path 'application',
            applyDate            varchar2(100)  path 'application/applyDate',
            esn                  varchar2(30)   path 'application/esn',
            isCustomer           varchar2(100)  path 'application/isCustomer',
            tracfoneNumber       varchar2(100)  path 'application/tracfoneNumber',
            qualifyStatus        varchar2(100)  path 'application/qualifyStatus',
            qualifyMethod        varchar2(100)  path 'application/qualifyMethod',
            qualifyType          varchar2(100)  path 'application/qualifyType',
            qualifyPrograms      xmltype        path 'application/qualifyPrograms',
            qualifyDate          varchar2(100)  path 'application/qualifyDate',
            unqualifyCode        varchar2(100)  path 'application/unqualifyCode',
            retailerCode         varchar2(100)  path 'application/retailerCode',
            channelType          varchar2(100)  path 'application/channelType',
            bribeMinutes         varchar2(100)  path 'application/bribeMinutes',
            registrationLanguage varchar2(100)  path 'application/registrationLanguage',
            plan                 varchar2(100)  path 'application/plan',
            ref_fname            varchar2(100)  path 'referral/ref_fname',
            ref_lname            varchar2(100)  path 'referral/ref_lname',
            ref_min              varchar2(100)  path 'referral/ref_min',
            ref_lid              varchar2(100)  path 'referral/ref_lid',
            ref_status           varchar2(100)  path 'referral/ref_status',
            x_campaign           varchar2(30)   path 'referral/campaign',
            x_promotion          varchar2(50)   path 'referral/promotion',
            x_promocode          varchar2(50)   path 'referral/promo_code',
            x_shp_address        varchar2(50)   path 'contact/shippingAddress',
            x_shp_address2       varchar2(50)   path 'contact/shippingAddress2',
            x_shp_city           varchar2(50)   path 'contact/shippingCity',
            x_shp_state          varchar2(50)   path 'contact/shippingState',
            x_shp_zip            varchar2(30)   path 'contact/shippingZip',
            addressiscommercial  char(1)        path 'contact/addressIsCommercial',
            addressisduplicated  char(1)        path 'contact/addressIsDuplicated',
            addressisinvalid     char(1)        path 'contact/addressIsInvalid',
            addressistemporary   char(1)        path 'contact/addressIsTemporary',
            stateidname          varchar2(200)  path 'application/stateIdName',
            stateidvalue         varchar2(200)  path 'application/stateIdValue',
            adl                  varchar2(200)  path 'application/adl',
            usacform             varchar2(200)  path 'application/usacForm',
            celltelephone        varchar2(200)  path 'contact/cellTelephone',
            eligiblefirstname    varchar2(200)  path 'application/eligibleFirstName',
            eligiblelastname     varchar2(200)  path 'application/eligibleLastName',
            eligiblemiddlenameinitial     varchar2(200)     path 'application/eligibleMiddleNameInitial',
            haspromotionalplan    varchar2(200) path 'application/hasPromotionalPlan',
            hmodisclaimer        char(1)        path 'application/hmoDisclaimer',
            ipaddress            varchar2(200)  path 'application/ipAddress',
            personid             varchar2(200)  path 'personId',
            personisinvalid      char(1)        path 'application/personIsInvalid',
            shippingaddresshash  varchar2(200)  path 'contact/shippingAddressHash',
            stateagencyqualification     char(1) path 'application/stateAgencyQualification',
            transferflag         char(1)         path 'application/transferFlag',
            old_lid              varchar2(200)   path 'application/old_lid',
            status               varchar2(200)   path 'application/status',
            lastmodified         varchar2(200)   path 'application/lastModified',
            dobisinvalid         char(1)         path 'application/dobIsInvalid',
            ssnisinvalid         char(1)         path 'application/ssnIsInvalid',
            disablemanualverification     varchar2(200)     path 'application/disableManualVerification',
            device_type                   varchar2(200)     path 'device_type',   
            byop_device_state             varchar2(200)     path 'byop_device_state',
            byop_carrier                  varchar2(200)     path 'byop_carrier',
            byop_sim                      varchar2(200)     path 'byop_sim',
            byop_esn                      varchar2(200)     path 'byop_esn',
            byop_act_zip                  varchar2(200)     path 'byop_act_zip'          
            ) x;
            
                           sa.ota_util_pkg.err_log (
                p_action => '--after insert into xsu_vmbc_request table step 2',
                p_error_date => sysdate,
                p_key => 'file_name',
                p_program_name => 'load_vmbc_request',
                p_error_text =>  'op_sqlcode: '||op_sqlcode||' op_sqlerrm: '||op_sqlerrm||' rowcount: '||sql%rowcount);
    
    ELSIF    UPPER(file_name ) LIKE 'SOLIX%'
    THEN

          
 insert into sa.xsu_vmbc_request
      (REQUESTTYPE,
       REQUESTID,
       ENROLLREQUEST,
       LID,
       CONTACT,
       NAME,
       ADDRESS,
       ADDRESS2,
       CITY,
       STATE,
       ZIP,
       ZIP2,
       COUNTRY,
       HOMENUMBER,
       EMAIL,
       ALLOWPRERECORDED,
       EMAILPREF,
       APPLICATION,
       APPLYDATE,
       ESN,
       ISCUSTOMER,
       TRACFONENUMBER,
       QUALIFYSTATUS,
       QUALIFYMETHOD,
       QUALIFYTYPE,
       QUALIFYDATE,
       UNQUALIFYCODE,
       RETAILERCODE,
       CHANNELTYPE,
       BRIBEMINUTES,
       REGISTRATIONLANGUAGE,
       BATCHDATE,
       PLAN,
       REF_FNAME,
       REF_LNAME,
       REF_MIN,
       REF_LID,
       REF_STATUS,
       EXTERNAL_ACCOUNT,
       QUALIFYPROGRAMS,
       x_campaign,
       x_promotion,
       x_promocode,
       x_shp_address,
       x_shp_address2,
       x_shp_city,
       x_shp_state,
       x_shp_zip,
         addressiscommercial,
       addressisduplicated,
       addressisinvalid,
       addressistemporary,
       stateidname,
       stateidvalue,
       adl,
       usacform,
       celltelephone,
       eligiblefirstname,
       eligiblelastname,
       eligiblemiddlenameinitial,
       haspromotionalplan,
       hmodisclaimer,
       ipaddress,
       personid,
       personisinvalid,
       shippingaddresshash,
       stateagencyqualification,
       transferflag,
       old_lid,
       status,
       lastmodified,
       dobisinvalid,
       ssnisinvalid,
       disablemanualverification,
       device_type,
       byop_device_state,
       byop_carrier,
       byop_sim,
       byop_esn,
       byop_act_zip
        ,data_source        -- Added for CR38122
       )
select REQUEST_TYPE,
       REQUESTID,
       ENROLL_REQUEST,
       LID,
       null,
       NAME,
       ADDRESS,
       ADDRESS2,
       CITY,
       STATE,
       ZIP,
       ZIP2,
       COUNTRY,
       HOMENUMBER,
       EMAIL,
       ALLOWPRERECORDED,
       EMAILPREF,
       null,
       APPLYDATE,
       ESN,
       ISCUSTOMER,
       TRACFONENUMBER,
       QUALIFYSTATUS,
       QUALIFYMETHOD,
       QUALIFYTYPE,
       QUALIFYDATE,
       UNQUALIFYCODE,
       RETAILERCODE,
       CHANNELTYPE,
       BRIBEMINUTES,
       REGISTRATIONLANGUAGE,
       sysdate,
       PLAN,
       REF_FNAME,
       REF_LNAME,
       REF_MIN,
       REF_LID,
       REF_STATUS,
       EXTERNAL_ACCOUNT,
        extractvalue(qualifyPrograms,'qualifyPrograms[1]',
                     'xmlns="http://www.tracfone.com/solix/enrollment"')||','||
        extractvalue(qualifyPrograms,'qualifyPrograms[2]',
                     'xmlns="http://www.tracfone.com/solix/enrollment"')||','||
        extractvalue(qualifyPrograms,'qualifyPrograms[3]',
                     'xmlns="http://www.tracfone.com/solix/enrollment"')||','||
        extractvalue(qualifyPrograms,'qualifyPrograms[4]',
                     'xmlns="http://www.tracfone.com/solix/enrollment"') qp,
       x_campaign,
       x_promotion,
       x_promocode,
       x_shp_address,
       x_shp_address2,
       x_shp_city,
       x_shp_state,
       x_shp_zip,
         addressiscommercial,
       addressisduplicated,
       addressisinvalid,
       addressistemporary,
       stateidname,
       stateidvalue,
       adl,
       usacform,
       celltelephone,
       eligiblefirstname,
       eligiblelastname,
       eligiblemiddlenameinitial,
       haspromotionalplan,
       hmodisclaimer,
       ipaddress,
       personid,
       personisinvalid,
       shippingaddresshash,
       stateagencyqualification,
       transferflag,
       old_lid,
       status,
       lastmodified,
       dobisinvalid,
       ssnisinvalid,
       disablemanualverification,
       device_type,
       byop_device_state,
       byop_carrier,
       byop_sim,
       byop_esn,
       byop_act_zip
    --    ,LV_DATA_SOURCE        -- Added for CR38122
        ,'SOLIX'
from xmltable(
    xmlnamespaces('http://www.w3.org/2001/XMLSchema-instance' as "xsi",
            'http://www.w3.org/2001/XMLSchema' as "xsd",
            'http://www.tracfone.com/schemas/solix/inbound/Subscription.xsd' as "schemaLocation",
            default 'http://www.tracfone.com/solix/enrollment' ) ,
        '/tracfone/request'
        passing xmltype( bfilename('XML_FOLDER',file_name ), nls_charset_id('AL32UTF8') )
         columns
            request_type         varchar2(50)   path 'requestType',
            requestid            varchar2(50)   path 'requestID',
            enroll_request       varchar2(100)  path 'enrollRequest',
            lid                  number         path 'lid',
            contact              varchar2(100)  path 'contact',
            name                 varchar2(100)  path 'contact/name',
            address              varchar2(200)  path 'contact/address',
            address2             varchar2(100)  path 'contact/address2',
            city                 varchar2(100)  path 'contact/city',
            state                varchar2(50)   path 'contact/state',
            zip                  varchar2(100)  path 'contact/zip',
            zip2                 varchar2(100)  path 'contact/zip2',
            country              varchar2(100)  path 'contact/country',
            homeNumber           varchar2(100)  path 'contact/homeNumber',
            email                varchar2(100)  path 'contact/email',
            allowPrerecorded     varchar2(100)  path 'contact/allowPrerecorded',
            emailPref            varchar2(100)  path 'contact/emailPref',
            dob                  varchar2(100)  path 'contact/dob',
            external_account     varchar2(100)  path 'contact/externalAccount',
            application          varchar2(100)  path 'application',
            applyDate            varchar2(100)  path 'application/applyDate',
            esn                  varchar2(30)   path 'application/esn',
            isCustomer           varchar2(100)  path 'application/isCustomer',
            tracfoneNumber       varchar2(100)  path 'application/tracfoneNumber',
            qualifyStatus        varchar2(100)  path 'application/qualifyStatus',
            qualifyMethod        varchar2(100)  path 'application/qualifyMethod',
            qualifyType          varchar2(100)  path 'application/qualifyType',
            qualifyPrograms      xmltype        path 'application/qualifyPrograms',
            qualifyDate          varchar2(100)  path 'application/qualifyDate',
            unqualifyCode        varchar2(100)  path 'application/unqualifyCode',
            retailerCode         varchar2(100)  path 'application/retailerCode',
            channelType          varchar2(100)  path 'application/channelType',
            bribeMinutes         varchar2(100)  path 'application/bribeMinutes',
            registrationLanguage varchar2(100)  path 'application/registrationLanguage',
            plan                 varchar2(100)  path 'application/plan',
            ref_fname            varchar2(100)  path 'referral/ref_fname',
            ref_lname            varchar2(100)  path 'referral/ref_lname',
            ref_min              varchar2(100)  path 'referral/ref_min',
            ref_lid              varchar2(100)  path 'referral/ref_lid',
            ref_status           varchar2(100)  path 'referral/ref_status',
            x_campaign           varchar2(30)   path 'referral/campaign',
            x_promotion          varchar2(50)   path 'referral/promotion',
            x_promocode          varchar2(50)   path 'referral/promo_code',
            x_shp_address        varchar2(50)   path 'contact/shippingAddress',
            x_shp_address2       varchar2(50)   path 'contact/shippingAddress2',
            x_shp_city           varchar2(50)   path 'contact/shippingCity',
            x_shp_state          varchar2(50)   path 'contact/shippingState',
            x_shp_zip            varchar2(30)   path 'contact/shippingZip',
            addressiscommercial  char(1)        path 'contact/addressIsCommercial',
            addressisduplicated  char(1)        path 'contact/addressIsDuplicated',
            addressisinvalid     char(1)        path 'contact/addressIsInvalid',
            addressistemporary   char(1)        path 'contact/addressIsTemporary',
            stateidname          varchar2(200)  path 'application/stateIdName',
            stateidvalue         varchar2(200)  path 'application/stateIdValue',
            adl                  varchar2(200)  path 'application/adl',
            usacform             varchar2(200)  path 'application/usacForm',
            celltelephone        varchar2(200)  path 'contact/cellTelephone',
            eligiblefirstname    varchar2(200)  path 'application/eligibleFirstName',
            eligiblelastname     varchar2(200)  path 'application/eligibleLastName',
            eligiblemiddlenameinitial     varchar2(200)     path 'application/eligibleMiddleNameInitial',
            haspromotionalplan    varchar2(200) path 'application/hasPromotionalPlan',
            hmodisclaimer        char(1)        path 'application/hmoDisclaimer',
            ipaddress            varchar2(200)  path 'application/ipAddress',
            personid             varchar2(200)  path 'personId',
            personisinvalid      char(1)        path 'application/personIsInvalid',
            shippingaddresshash  varchar2(200)  path 'contact/shippingAddressHash',
            stateagencyqualification     char(1) path 'application/stateAgencyQualification',
            transferflag         char(1)         path 'application/transferFlag',
            old_lid              varchar2(200)   path 'application/old_lid',
            status               varchar2(200)   path 'application/status',
            lastmodified         varchar2(200)   path 'application/lastModified',
            dobisinvalid         char(1)         path 'application/dobIsInvalid',
            ssnisinvalid         char(1)         path 'application/ssnIsInvalid',
            disablemanualverification     varchar2(200)     path 'application/disableManualVerification',
            device_type                   varchar2(200)     path 'device_type',   
            byop_device_state             varchar2(200)     path 'byop_device_state',
            byop_carrier                  varchar2(200)     path 'byop_carrier',
            byop_sim                      varchar2(200)     path 'byop_sim',
            byop_esn                      varchar2(200)     path 'byop_esn',
            byop_act_zip                  varchar2(200)     path 'byop_act_zip'          
            ) x;
            
                           sa.ota_util_pkg.err_log (
                p_action => '--after insert into xsu_vmbc_request table step 2',
                p_error_date => sysdate,
                p_key => 'file_name',
                p_program_name => 'load_vmbc_request',
                p_error_text =>  'op_sqlcode: '||op_sqlcode||' op_sqlerrm: '||op_sqlerrm||' rowcount: '||sql%rowcount);
    

    END IF;

-- CR38122 End    
   op_sqlcode := 0;
   op_sqlerrm := null;
   
exception
 when others then
   op_sqlcode := sqlcode;
   op_sqlerrm := sqlerrm;
   
                sa.ota_util_pkg.err_log (
                p_action => '--error insert into xsu_vmbc_request table step 3',
                p_error_date => sysdate,
                p_key => 'file_name',
                p_program_name => 'load_vmbc_request',
                p_error_text =>  'op_sqlcode: '||op_sqlcode||' op_sqlerrm: '||op_sqlerrm);
        
end;
/