CREATE OR REPLACE PROCEDURE sa.OFS_PHONE (P_ESN_LIST IN VARCHAR2) AS

V_ESN_LIST VARCHAR2(4000);
V_CNT NUMBER :=0;

BEGIN

V_ESN_LIST:=''''||REPLACE(P_ESN_LIST, ',', ''',''')||'''';

EXECUTE IMMEDIATE 'DROP TABLE TF_OF_ITEM_V_PHONE_INV';
EXECUTE IMMEDIATE 'CREATE TABLE TF_OF_ITEM_V_PHONE_INV AS (SELECT * FROM TF_OF_ITEM_V@OFSPRD)';

SELECT COUNT(*)
INTO V_CNT
FROM ALL_TABLES
WHERE TABLE_NAME = 'TF_TOSS_INTERFACE_PHONE_INV';

IF V_CNT > 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE TF_TOSS_INTERFACE_PHONE_INV';
END IF;

EXECUTE IMMEDIATE 'CREATE TABLE TF_TOSS_INTERFACE_PHONE_INV AS (SELECT A.ROWID ROW_ID, A.*
                                                                FROM TF.TF_TOSS_INTERFACE_TABLE@OFSPRD A
                                                                WHERE TF_SERIAL_NUM IN ('||V_ESN_LIST||'))';
EXECUTE IMMEDIATE 'ALTER TABLE TF_TOSS_INTERFACE_PHONE_INV ADD (OLD_TOSS_EXTRACT_FLAG DATE, OLD_LAST_UPDATE_DATE DATE, TOSS_PART_NUM VARCHAR2(30))';
commit;
END;
/