CREATE OR REPLACE PROCEDURE sa."PORTCASEJOB"
 IS

 CURSOR PORT_CLOSE IS
  SELECT  C.CUSTOMER_CODE AS P_SRCESYSTEM, C.OBJID AS          P_USROBJID, C.X_ESN    AS P_ESN               ,C. X_MIN AS P_MIN
    FROM sa.TABLE_CASE C, sa.TABLE_SITE_PART SP,sa.TABLE_CLOSE_CASE CC,sa.TABLE_X_CASE_RESOLUTIONS CR, TABLE_CONDITION CO, TABLE_GBST_ELM GB, TABLE_PART_INST PI
    WHERE 1 = 1
    AND C.X_ESN = SP.X_SERVICE_ID
    And PI.PART_SERIAL_NO =SP.X_SERVICE_ID
    AND SP.PART_STATUS  IN  'CarrierPending'
    AND C.X_CASE_TYPE = 'Port In'
    AND pi.X_PART_INST_STATUS!='52'
    AND CC.LAST_CLOSE2CASE = C.OBJID
    AND C.CREATION_TIME >=TRUNC(SYSDATE-30)
    AND C.CREATION_TIME <=TRUNC(SYSDATE-7)
    AND CR.OBJID  = CC.CLOSE_CASE2CASE_RESOL
    AND C.CASE_STATE2CONDITION = CO.OBJID
    AND C.CASESTS2GBST_ELM = GB.OBJID
    AND CO.S_TITLE  LIKE '%CLOSED%' ;




  P_SRCESYSTEM VARCHAR2(200);
  P_USROBJID VARCHAR2(200);
  P_ESN VARCHAR2(200);
  P_MIN VARCHAR2(200);
  FETCH_STATUS  VARCHAR2(30);
  OP_RETURN VARCHAR2(200);
  OP_RETURNMSG VARCHAR2(200);

 BEGIN
 OPEN PORT_CLOSE;

 FETCH PORT_CLOSE  INTO P_SRCESYSTEM,	P_USROBJID,	P_ESN	,P_MIN	;

 WHILE FETCH_STATUS = 0

   LOOP       PORT_PKG.CANCEL_PORT_PRC
  (
    P_SRCESYSTEM =>  P_SRCESYSTEM
   ,P_USROBJID  => P_USROBJID
   ,P_ESN    =>    P_ESN
   ,P_MIN    =>  P_MIN
   ,OP_RETURN => OP_RETURN
   ,OP_RETURNMSG => OP_RETURNMSG
  );

   -- FETCH NEXT FROM CUR INTO P_SRCESYSTEM,	P_USROBJID,	P_ESN	,P_MIN

    CLOSE PORT_CLOSE;
    END LOOP;
END;
/