CREATE OR REPLACE PROCEDURE sa.sp_messagebroker_ild (
   server_host                         VARCHAR2,
   server_port                         VARCHAR2,
   auth_code                           VARCHAR2,
   bill_address1                       VARCHAR2,
   bill_address2                       VARCHAR2,
   bill_city                           VARCHAR2,
   bill_country                        VARCHAR2,
   bill_state                          VARCHAR2,
   bill_zip                            VARCHAR2,
   currency                            VARCHAR2,
   customer_cc_cv_number               VARCHAR2,
   customer_cc_expmo                   VARCHAR2,
   customer_cc_expyr                   VARCHAR2,
   customer_cc_number                  VARCHAR2,
   customer_email                      VARCHAR2,
   customer_firstname                  VARCHAR2,
   customer_lastname                   VARCHAR2,
   customer_hostname                   VARCHAR2,
   customer_ipaddress                  VARCHAR2,
   customer_phone                      VARCHAR2,
   decline_avs_flags                   VARCHAR2,
   disable_avs                         VARCHAR2,
   ics_applications                    VARCHAR2,
   ignore_avs                          VARCHAR2,
   ignore_bad_cv                       VARCHAR2,
   merchant_descriptor                 VARCHAR2,
   merchant_descriptor_contact         VARCHAR2,
   merchant_id                         VARCHAR2,
   merchant_ref_number                 VARCHAR2,
   timeout                             VARCHAR2,
   offer0                              VARCHAR2,
   ics_rcode                     OUT   VARCHAR2,
   avs                           OUT   VARCHAR2,
   auth_auth_amount              OUT   VARCHAR2,
   auth_auth_avs                 OUT   VARCHAR2,
   auth_auth_code                OUT   VARCHAR2,
   auth_auth_response            OUT   VARCHAR2,
   auth_auth_time                OUT   VARCHAR2,
   auth_cv_result                OUT   VARCHAR2,
   auth_rcode                    OUT   VARCHAR2,
   auth_request_id               OUT   VARCHAR2,
   auth_rflag                    OUT   VARCHAR2,
   auth_rmsg                     OUT   VARCHAR2,
   bill_bill_amount              OUT   VARCHAR2,
   bill_bill_request_time        OUT   VARCHAR2,
   bill_rcode                    OUT   VARCHAR2,
   bill_rflag                    OUT   VARCHAR2,
   bill_rmsg                     OUT   VARCHAR2,
   bill_trans_ref_no             OUT   VARCHAR2,
   ics_rflag                     OUT   VARCHAR2,
   ics_rmsg                      OUT   VARCHAR2,
   request_id                    OUT   VARCHAR2,
   score_factors                 OUT   VARCHAR2,
   score_host_severity           OUT   VARCHAR2,
   score_rcode                   OUT   VARCHAR2,
   score_rflag                   OUT   VARCHAR2,
   score_rmsg                    OUT   VARCHAR2,
   score_score_result            OUT   VARCHAR2,
   score_time_local              OUT   VARCHAR2,
   time_local                    OUT   VARCHAR2,
   host_severity                 OUT   VARCHAR2,
   score_ifs4_score              OUT   VARCHAR2,
   factors                       OUT   VARCHAR2,
   credit_credit_amount          OUT   VARCHAR2,
   credit_credit_request_time    OUT   VARCHAR2,
   credit_rcode                  OUT   VARCHAR2,
   credit_rflag                  OUT   VARCHAR2,
   credit_rmsg                   OUT   VARCHAR2,
   credit_trans_ref_no           OUT   VARCHAR2,
   credit_auth_response          OUT   VARCHAR2,
   out_status                    OUT   VARCHAR2
)
AS
BEGIN
   out_status :=
      f_messagebroker_ild (
         server_host,
         server_port,
         auth_code,
         bill_address1,
         bill_address2,
         bill_city,
         bill_country,
         bill_state,
         bill_zip,
         currency,
         customer_cc_cv_number,
         customer_cc_expmo,
         customer_cc_expyr,
         customer_cc_number,
         customer_email,
         customer_firstname,
         customer_lastname,
         customer_hostname,
         customer_ipaddress,
         customer_phone,
         decline_avs_flags,
         disable_avs,
         ics_applications,
         ignore_avs,
         ignore_bad_cv,
         merchant_descriptor,
         merchant_descriptor_contact,
         merchant_id,
         merchant_ref_number,
         timeout,
         offer0,
         ics_rcode,
         avs,
         auth_auth_amount,
         auth_auth_avs,
         auth_auth_code,
         auth_auth_response,
         auth_auth_time,
         auth_cv_result,
         auth_rcode,
         auth_request_id,
         auth_rflag,
         auth_rmsg,
         bill_bill_amount,
         bill_bill_request_time,
         bill_rcode,
         bill_rflag,
         bill_rmsg,
         bill_trans_ref_no,
         ics_rflag,
         ics_rmsg,
         request_id,
         score_factors,
         score_host_severity,
         score_rcode,
         score_rflag,
         score_rmsg,
         score_score_result,
         score_time_local,
         time_local,
         host_severity,
         score_ifs4_score,
         factors,
         credit_credit_amount,
         credit_credit_request_time,
         credit_rcode,
         credit_rflag,
         credit_rmsg,
         credit_trans_ref_no,
         credit_auth_response
      );
END;
/