CREATE OR REPLACE FUNCTION sa.f_messagebroker_ild
( server_host      varchar2,
  server_port      varchar2,
  auth_code      varchar2,
  bill_address1      varchar2,
  bill_address2      varchar2,
bill_city      varchar2,
bill_country      varchar2,
bill_state      varchar2,
bill_zip      varchar2,
currency      varchar2,
customer_cc_cv_number varchar2,
customer_cc_expmo      varchar2,
customer_cc_expyr      varchar2,
customer_cc_number      varchar2,
customer_email      varchar2,
customer_firstname      varchar2,
customer_lastname      varchar2,
customer_hostname      varchar2,
customer_ipaddress      varchar2,
customer_phone      varchar2,
decline_avs_flags   varchar2,
disable_avs      varchar2,
Ics_applications      varchar2,
ignore_avs      varchar2,
ignore_bad_cv      varchar2,
merchant_descriptor      varchar2,
merchant_descriptor_contact      varchar2,
merchant_id      varchar2,
merchant_ref_number      varchar2,
timeout      varchar2,
offer0      varchar2,
Ics_rcode     in out varchar2,
avs     in out  varchar2,
auth_auth_amount     in out  varchar2,
auth_auth_avs      in out varchar2,
auth_auth_code      in out varchar2,
auth_auth_response     in out  varchar2,
auth_auth_time      in out varchar2,
auth_cv_result     in out  varchar2,
auth_rcode      in out varchar2,
auth_request_id      in out varchar2,
auth_rflag      in out varchar2,
auth_rmsg      in out varchar2,
bill_bill_amount     in out  varchar2,
bill_bill_request_time     in out  varchar2,
bill_rcode     in out  varchar2,
bill_rflag     in out  varchar2,
bill_rmsg     in out  varchar2,
bill_trans_ref_no     in out  varchar2,
Ics_rflag in out      varchar2,
ics_rmsg       in out    varchar2,
request_id     in out  varchar2,
score_factors      in out varchar2,
score_host_severity     in out  varchar2,
score_rcode     in out  varchar2,
score_rflag      in out varchar2,
score_rmsg     in out  varchar2,
score_score_result     in out  varchar2,
score_time_local     in out  varchar2,
time_local      in out varchar2,
host_severity      in out varchar2,
score_ifs4_score     in out  varchar2,
factors     in out  varchar2,
Credit_credit_amount in out  varchar2,
Credit_credit_request_time in out  varchar2,
Credit_rcode in out  varchar2,
Credit_rflag in out  varchar2,
Credit_rmsg in out  varchar2,
credit_trans_ref_no in out  varchar2,
Credit_auth_response in out  varchar2
)  return pls_integer as
   language C
   library libmessage_ild
   name "messagebroker2"
   parameters
(server_host    string,
--server_host    indicator,
server_port    string,
--server_port    indicator,
auth_code    string,
auth_code    indicator,
bill_address1    string,
--bill_address1    indicator,
bill_address2    string,
bill_address2    indicator,
bill_city    string,
bill_city    indicator,
bill_country    string,
bill_country    indicator,
bill_state    string,
bill_state    indicator,
bill_zip    string,
bill_zip    indicator,
currency    string,
--currency    indicator,
customer_cc_cv_number string,
customer_cc_cv_number    indicator,
customer_cc_expmo    string,
--customer_cc_expmo    indicator,
customer_cc_expyr    string,
--customer_cc_expyr    indicator,
customer_cc_number    string,
--customer_cc_number    indicator,
customer_email    string,
customer_email    indicator,
customer_firstname    string,
--customer_firstname    indicator,
customer_lastname    string,
--customer_lastname    indicator,
customer_hostname    string,
customer_hostname    indicator,
customer_ipaddress    string,
customer_ipaddress    indicator,
customer_phone    string,
customer_phone    indicator,
decline_avs_flags    string,
decline_avs_flags    indicator,
disable_avs    string,
--disable_avs    indicator,
Ics_applications    string,
Ics_applications    indicator,
ignore_avs    string,
ignore_avs    indicator,
ignore_bad_cv    string,
ignore_bad_cv    indicator,
merchant_descriptor    string,
--merchant_descriptor    indicator,
merchant_descriptor_contact    string,
--merchant_descriptor_contact    indicator,
merchant_id    string,
--merchant_id    indicator,
merchant_ref_number    string,
--merchant_ref_number    indicator,
timeout    string,
timeout    indicator,
offer0    string,
--offer0    indicator,
Ics_rcode    string,
Ics_rcode    indicator,
avs    string,
avs    indicator,
auth_auth_amount    string,
auth_auth_amount    indicator,
auth_auth_avs    string,
auth_auth_avs    indicator,
auth_auth_code    string,
auth_auth_code    indicator,
auth_auth_response    string,
auth_auth_response    indicator,
auth_auth_time    string,
auth_auth_time    indicator,
auth_cv_result    string,
auth_cv_result    indicator,
auth_rcode    string,
auth_rcode    indicator,
auth_request_id    string,
auth_request_id    indicator,
auth_rflag    string,
auth_rflag    indicator,
auth_rmsg    string,
auth_rmsg    indicator,
bill_bill_amount    string,
bill_bill_amount    indicator,
bill_bill_request_time    string,
bill_bill_request_time    indicator,
bill_rcode    string,
bill_rcode    indicator,
bill_rflag    string,
bill_rflag    indicator,
bill_rmsg    string,
bill_rmsg    indicator,
bill_trans_ref_no    string,
bill_trans_ref_no    indicator,
Ics_rflag    string,
Ics_rflag    indicator,
ics_rmsg        string,
ics_rmsg        indicator,
request_id    string,
request_id    indicator,
score_factors    string,
score_factors    indicator,
score_host_severity    string,
score_host_severity    indicator,
score_rcode    string,
score_rcode    indicator,
score_rflag    string,
score_rflag    indicator,
score_rmsg    string,
score_rmsg    indicator,
score_score_result    string,
score_score_result    indicator,
score_time_local    string,
score_time_local    indicator,
time_local    string,
time_local    indicator,
host_severity    string,
host_severity    indicator,
score_ifs4_score    string,
score_ifs4_score    indicator,
factors    string,
factors    indicator,
Credit_credit_amount string,
Credit_credit_amount indicator,
Credit_credit_request_time string,
Credit_credit_request_time indicator,
Credit_rcode string,
Credit_rcode indicator,
Credit_rflag string,
Credit_rflag indicator,
Credit_rmsg string,
Credit_rmsg indicator,
credit_trans_ref_no string,
credit_trans_ref_no indicator,
Credit_auth_response string,
Credit_auth_response indicator,
return int);
/