CREATE OR REPLACE FUNCTION sa.GET_ESN_BY_SIM_FUN(IP_SIM IN VARCHAR2)
	RETURN VARCHAR2 IS
	V_ESN	sa.TABLE_PART_INST.PART_SERIAL_NO%TYPE;
  V_NO_DATA_FOUND           PLS_INTEGER := 0;
BEGIN
	BEGIN
		SELECT 	PART_SERIAL_NO
		INTO	V_ESN
		FROM 	TABLE_PART_INST PI
		WHERE 	X_ICCID = IP_SIM
		AND 	PART_SERIAL_NO <> SUBSTR(X_ICCID, 5, LENGTH(X_ICCID));
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
        V_NO_DATA_FOUND := 1;
		WHEN OTHERS THEN
			RAISE;
	END;
  IF V_NO_DATA_FOUND = 1 THEN
    BEGIN
      SELECT 	PART_SERIAL_NO
      INTO	V_ESN
      FROM 	TABLE_PART_INST PI
      WHERE 	X_ICCID = IP_SIM;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        V_ESN := 0;
      WHEN OTHERS THEN
        RAISE;
    END;
  END IF;
	RETURN V_ESN;
EXCEPTION
	WHEN OTHERS THEN
		RAISE;
END;
/