CREATE OR REPLACE FUNCTION sa.PSMSNokia2126Unix
  ( INS   IN     PLTOSL
   ,OUTS  IN OUT SLTOPL )
RETURN NUMBER
AS
    LANGUAGE C
    NAME "pl_ota_nokia2126"
    LIBRARY sa.LIBPSMS_OTA
    WITH CONTEXT
    PARAMETERS
     (
       CONTEXT,
       INS,
       INS INDICATOR STRUCT,
       INS TDO,
       OUTS BY REFERENCE,
       OUTS INDICATOR STRUCT,
       OUTS TDO,
       RETURN INDICATOR
     );
/