CREATE MATERIALIZED VIEW sa.service_plan_feat_pivot_mv (service_plan_objid,mkt_name,description,add_on_data_replacement_plan,add_on_ild,app_display,benefit_type,benefit_type_flag,biz_line,block_ild_transaction,block_ttoff_for_sp,broadband,carrier_bucket,carrier_bucket_dom,carrier_bucket_dom_intl_flag,carrier_bucket_intl,carrier_bucket_shared,carrier_bucket_sms,carrier_bucket_verizon,carrier_bucket_voice,click_type,"COS",exception_cos,"EXCEPTIONS",coverage_script,cust_profile_script,data_counter_days_tmobile,"DATA",data_intl,data_display,data_roam,device_group_type,display_plan_info,handset_voice,high_speed_data,ignore_ig_flag,ild,ild_permited,ild_product,ild_roam,ild_plan_reference,international_sms_allowed,intl_roam_data,intl_roam_sms,intl_roam_voice,legacy,mobile_description1,mobile_description2,mobile_description3,mobile_description4,mobile_plan_category,number_of_lines,"PARENT",parent_service_plan,plan_category,plan_type,plan_purchase_part_number,plan_purch_pn_b2b,product_selection,promo_type,recurring_service_plan,replacement_part_number,rewards_points,rim_rate_plan,root_plan,safelink_only,script_type,service_days,service_plan_group,service_plan_purchase,service_plan_purchase_tas,short_script,sibling_priority,sms,sms_display,sms_roam,soc_data_name,soc_message_name,soc_rate_plan,soc_voice_name,sp_add_promo_script,sub_brand,supported_part_class,switch_based,tax_type,trans_summ_script,voice,voice_display,voice_roam,data_bucket_name,data_bucket_value,sms_bucket_name,sms_bucket_value,voice_bucket_name,voice_bucket_value,wallet_ild,ild_bucket_name,ild_bucket_value,ild_benefit_type,wallet_intl_roam,intl_bucket_name,intl_bucket_value,rollover_flag,addon_compatible_flag,"DAYS",family_plan_discount_flag,multi_purch_plan_disc_flag,recurring_plan_only_flag,expire_previous_add_on,ll_tribal_serv_type,ll_serv_type,promo_ild_product_id)
ORGANIZATION HEAP 
REFRESH COMPLETE START WITH TO_DATE('2018-7-14 1:0:0', 'yyyy-mm-dd hh24:mi:ss') NEXT TRUNC(SYSDATE)+ 1 + 01/24 
AS SELECT  a.service_plan_objid,
        a.mkt_name,
        a.description,
        a.add_on_data_replacement_plan,
        a.add_on_ild,
        a.app_display,
        a.benefit_type,
        a.benefit_type_flag,
        a.biz_line,
        a.block_ild_transaction,
        a.block_ttoff_for_sp,
        a.broadband,
        a.carrier_bucket,
        a.carrier_bucket_dom,
        a.carrier_bucket_dom_intl_flag,
        a.carrier_bucket_intl,
        a.carrier_bucket_shared,
        a.carrier_bucket_sms,
        a.carrier_bucket_verizon,
        a.carrier_bucket_voice,
        a.click_type,
        a.cos,
        a.exception_cos,
        a.exceptions,
        a.coverage_script,
        a.cust_profile_script,
        a.data_counter_days_tmobile,
        a.data,
        a.data_intl,
        a.data_display,
        a.data_roam,
        a.device_group_type,
        a.display_plan_info,
        a.handset_voice,
        a.high_speed_data,
        a.ignore_ig_flag,
        a.ild,
        a.ild_permited,
        a.ild_product,
        a.ild_roam,
        a.ild_plan_reference,
        a.international_sms_allowed,
        a.intl_roam_data,
        a.intl_roam_sms,
        a.intl_roam_voice,
        a.legacy,
        a.mobile_description1,
        a.mobile_description2,
        a.mobile_description3,
        a.mobile_description4,
        a.mobile_plan_category,
        a.number_of_lines,
        a.parent,
        a.parent_service_plan,
        a.plan_category,
        a.plan_type,
        a.plan_purchase_part_number,
        a.plan_purch_pn_b2b,
        a.product_selection,
        a.promo_type,
        a.recurring_service_plan,
        a.replacement_part_number,
        a.rewards_points,
        a.rim_rate_plan,
        a.root_plan,
        a.safelink_only,
        a.script_type,
        a.service_days,
        a.service_plan_group,
        a.service_plan_purchase,
        a.service_plan_purchase_tas,
        a.short_script,
        a.sibling_priority,
        a.sms,
        a.sms_display,
        a.sms_roam,
        a.soc_data_name,
        a.soc_message_name,
        a.soc_rate_plan,
        a.soc_voice_name,
        a.sp_add_promo_script,
        a.sub_brand,
        a.supported_part_class,
        a.switch_based,
        a.tax_type,
        a.trans_summ_script,
        a.voice,
        a.voice_display,
        a.voice_roam,
        a.data_bucket_name,
        a.data_bucket_value,
        a.sms_bucket_name,
        a.sms_bucket_value,
        a.voice_bucket_name,
        a.voice_bucket_value,
        a.wallet_ild,
        a.ild_bucket_name,
        a.ild_bucket_value,
        a.ild_benefit_type,
        a.wallet_intl_roam,
        a.intl_bucket_name,
        a.intl_bucket_value,
        a.rollover_flag,
        a.addon_compatible_flag,
        TO_NUMBER(TRIM(regexp_replace(NVL(a.service_days,0),'[[:alpha:]]',''))) days,
        a.family_plan_discount_flag,
        a.multi_purch_plan_disc_flag,
        a.recurring_plan_only_flag,
		    a.expire_previous_add_on,
        a.ll_tribal_serv_type,
        a.ll_serv_type,
		a.promo_ild_product_id
  FROM (SELECT *
          FROM (SELECT service_plan_objid,
                       mkt_name,
                       description,
                       fea_name,
                       fea_display
                  FROM (SELECT DISTINCT sp.objid service_plan_objid,
                                        sp.mkt_name mkt_name,
                                        sp.description description,
                                        spfvdef.value_name fea_name,
                                        spfvdef2.display_name fea_display
                          FROM sa.x_serviceplanfeaturevalue_def spfvdef,
                               sa.x_serviceplanfeature_value spfv,
                               sa.x_service_plan_feature spf,
                               sa.x_serviceplanfeaturevalue_def spfvdef2,
                               sa.x_serviceplanfeaturevalue_def spfvdef3,
                               sa.x_service_plan sp
                         WHERE     spf.sp_feature2rest_value_def = spfvdef.objid
                               AND spf.objid = spfv.spf_value2spf
                               AND spfvdef2.objid = spfv.value_ref
                               AND spfvdef3.objid(+) = spfv.child_value_ref
                               AND sp.objid = spf.sp_feature2service_plan)) PIVOT (MAX (
                                                                                      fea_display)
                                                                            FOR fea_name
                                                                            IN  ( 'ADD_ON_DATA_REPLACEMENT_PLAN'      AS ADD_ON_DATA_REPLACEMENT_PLAN,
                                                                                  'ADD_ON_ILD'                        AS ADD_ON_ILD,
                                                                                  'APP_DISPLAY'                       AS APP_DISPLAY,
                                                                                  'BENEFIT_TYPE'                      AS BENEFIT_TYPE,
                                                                                  'BENEFIT_TYPE_FLAG'                 AS BENEFIT_TYPE_FLAG,
                                                                                  'BIZ LINE'                          AS BIZ_LINE,
                                                                                  'BLOCK_ILD_TRANSACTION'             AS BLOCK_ILD_TRANSACTION,
                                                                                  'BLOCK_TTOFF_FOR_SP'                AS BLOCK_TTOFF_FOR_SP,
                                                                                  'BROADBAND'                         AS BROADBAND,
                                                                                  'CARRIER_BUCKET'                    AS CARRIER_BUCKET,
                                                                                  'CARRIER_BUCKET_DOM'                AS CARRIER_BUCKET_DOM,
                                                                                  'CARRIER_BUCKET_DOM_INTL_FLAG'      AS CARRIER_BUCKET_DOM_INTL_FLAG,
                                                                                  'CARRIER_BUCKET_INTL'               AS CARRIER_BUCKET_INTL,
                                                                                  'CARRIER_BUCKET_SHARED'             AS CARRIER_BUCKET_SHARED,
                                                                                  'CARRIER_BUCKET_SMS'                AS CARRIER_BUCKET_SMS,
                                                                                  'CARRIER_BUCKET_VERIZON'            AS CARRIER_BUCKET_VERIZON,
                                                                                  'CARRIER_BUCKET_VOICE'              AS CARRIER_BUCKET_VOICE,
                                                                                  'CLICK TYPE'                        AS CLICK_TYPE,
                                                                                  'COS'                               AS COS,
                                                                                  'EXCEPTION_COS'                     AS EXCEPTION_COS,
                                                                                  'EXCEPTIONS'                        AS EXCEPTIONS,
                                                                                  'COVERAGE_SCRIPT'                   AS COVERAGE_SCRIPT,
                                                                                  'CUST_PROFILE_SCRIPT'               AS CUST_PROFILE_SCRIPT,
                                                                                  'DATA COUNTER DAYS TMOBILE'         AS DATA_COUNTER_DAYS_TMOBILE,
                                                                                  'DATA'                              AS DATA,
                                                                                  'DATA_INTL'                         AS DATA_INTL,
                                                                                  'DATA_DISPLAY'                      AS DATA_DISPLAY,
                                                                                  'DATA_ROAM'                         AS DATA_ROAM,
                                                                                  'DEVICE_GROUP_TYPE'                 AS DEVICE_GROUP_TYPE,
                                                                                  'DISPLAY_PLAN_INFO'                 AS DISPLAY_PLAN_INFO,
                                                                                  'HANDSET VOICE'                     AS HANDSET_VOICE,
                                                                                  'HIGH_SPEED_DATA'                   AS HIGH_SPEED_DATA,
                                                                                  'IGNORE_IG_FLAG'                    AS IGNORE_IG_FLAG,
                                                                                  'ILD'                               AS ILD,
                                                                                  'ILD_PERMITED'                      AS ILD_PERMITED,
                                                                                  'ILD_PLAN_REFERENCE'                AS ILD_PLAN_REFERENCE,
                                                                                  'ILD_PRODUCT'                       AS ILD_PRODUCT,
                                                                                  'ILD_ROAM'                          AS ILD_ROAM,
                                                                                  'INTERNATIONAL_SMS_ALLOWED'         AS INTERNATIONAL_SMS_ALLOWED,
                                                                                  'INTL_ROAM_DATA'                    AS INTL_ROAM_DATA,
                                                                                  'INTL_ROAM_SMS'                     AS INTL_ROAM_SMS,
                                                                                  'INTL_ROAM_VOICE'                   AS INTL_ROAM_VOICE,
                                                                                  'LEGACY'                            AS LEGACY,
                                                                                  'MOBILE_DESCRIPTION1'               AS MOBILE_DESCRIPTION1,
                                                                                  'MOBILE_DESCRIPTION2'               AS MOBILE_DESCRIPTION2,
                                                                                  'MOBILE_DESCRIPTION3'               AS MOBILE_DESCRIPTION3,
                                                                                  'MOBILE_DESCRIPTION4'               AS MOBILE_DESCRIPTION4,
                                                                                  'MOBILE_PLAN_CATEGORY'              AS MOBILE_PLAN_CATEGORY,
                                                                                  'NUMBER_OF_LINES'                   AS NUMBER_OF_LINES,
                                                                                  'PARENT'                            AS PARENT,
                                                                                  'PARENT_SERVICE_PLAN'               AS PARENT_SERVICE_PLAN,
                                                                                  'PLAN_CATEGORY'                     AS PLAN_CATEGORY,
                                                                                  'PLAN TYPE'                         AS PLAN_TYPE,
                                                                                  'PLAN_PURCHASE_PART_NUMBER'         AS PLAN_PURCHASE_PART_NUMBER,
                                                                                  'PLAN_PURCH_PN_B2B'                 AS PLAN_PURCH_PN_B2B,
                                                                                  'PRODUCT_SELECTION'                 AS PRODUCT_SELECTION,
                                                                                  'PROMO TYPE'                        AS PROMO_TYPE,
                                                                                  'RECURRING_SERVICE_PLAN'            AS RECURRING_SERVICE_PLAN,
                                                                                  'REPLACEMENT_PART_NUMBER'           AS REPLACEMENT_PART_NUMBER,
                                                                                  'REWARDS_POINTS'                    AS REWARDS_POINTS,
                                                                                  'RIM_RATE_PLAN'                     AS RIM_RATE_PLAN,
                                                                                  'ROOT_PLAN'                         AS ROOT_PLAN,
                                                                                  'SAFELINK_ONLY'                     AS SAFELINK_ONLY,
                                                                                  'SCRIPT TYPE'                       AS SCRIPT_TYPE,
                                                                                  'SERVICE DAYS'                      AS SERVICE_DAYS,
                                                                                  'SERVICE_PLAN_GROUP'                AS SERVICE_PLAN_GROUP,
                                                                                  'SERVICE_PLAN_PURCHASE'             AS SERVICE_PLAN_PURCHASE,
                                                                                  'SERVICE_PLAN_PURCHASE_TAS'         AS SERVICE_PLAN_PURCHASE_TAS,
                                                                                  'SHORT_SCRIPT'                      AS SHORT_SCRIPT,
                                                                                  'SIBLING PRIORITY'                  AS SIBLING_PRIORITY,
                                                                                  'SMS'                               AS SMS,
                                                                                  'SMS_DISPLAY'                       AS SMS_DISPLAY,
                                                                                  'SMS_ROAM'                          AS SMS_ROAM,
                                                                                  'SOC_DATA_NAME'                     AS SOC_DATA_NAME,
                                                                                  'SOC_MESSAGE_NAME'                  AS SOC_MESSAGE_NAME,
                                                                                  'SOC_RATE_PLAN'                     AS SOC_RATE_PLAN,
                                                                                  'SOC_VOICE_NAME'                    AS SOC_VOICE_NAME,
                                                                                  'SP_ADD_PROMO_SCRIPT'               AS SP_ADD_PROMO_SCRIPT,
                                                                                  'SUB_BRAND'                         AS SUB_BRAND,
                                                                                  'SUPPORTED PART CLASS'              AS SUPPORTED_PART_CLASS,
                                                                                  'SWITCH BASED'                      AS SWITCH_BASED,
                                                                                  'TAX TYPE'                          AS TAX_TYPE,
                                                                                  'TRANS_SUMM_SCRIPT'                 AS TRANS_SUMM_SCRIPT,
                                                                                  'VOICE'                             AS VOICE,
                                                                                  'VOICE_DISPLAY'                     AS VOICE_DISPLAY,
                                                                                  'VOICE_ROAM'                        AS VOICE_ROAM,
                                                                                  'DATA_BUCKET_NAME'                  AS DATA_BUCKET_NAME,
                                                                                  'DATA_BUCKET_VALUE'                 AS DATA_BUCKET_VALUE,
                                                                                  'SMS_BUCKET_NAME'                   AS SMS_BUCKET_NAME,
                                                                                  'SMS_BUCKET_VALUE'                  AS SMS_BUCKET_VALUE,
                                                                                  'VOICE_BUCKET_NAME'                 AS VOICE_BUCKET_NAME,
                                                                                  'VOICE_BUCKET_VALUE'                AS VOICE_BUCKET_VALUE,
                                                                                  'WALLET_ILD'                        AS WALLET_ILD,
                                                                                  'ILD_BUCKET_NAME'                   AS ILD_BUCKET_NAME,
                                                                                  'ILD_BUCKET_VALUE'                  AS ILD_BUCKET_VALUE,
                                                                                  'ILD_BENEFIT_TYPE'                  AS ILD_BENEFIT_TYPE,
                                                                                  'WALLET_INTL_ROAM'                  AS WALLET_INTL_ROAM,
                                                                                  'INTL_BUCKET_NAME'                  AS INTL_BUCKET_NAME,
                                                                                  'INTL_BUCKET_VALUE'                 AS INTL_BUCKET_VALUE,
                                                                                  'ROLLOVER_FLAG'                     AS ROLLOVER_FLAG,
                                                                                  'ADDON_COMPATIBLE_FLAG'             AS ADDON_COMPATIBLE_FLAG,
                                                                                  'FAMILY_PLAN_DISCOUNT_FLAG'         AS FAMILY_PLAN_DISCOUNT_FLAG,
                                                                                  'MULTI_PURCHASE_PLAN_DISCOUNT_FLAG' AS MULTI_PURCH_PLAN_DISC_FLAG,
                                                                                  'RECURRING_PLAN_ONLY_FLAG'          AS RECURRING_PLAN_ONLY_FLAG,
																				  'EXPIRE_PREVIOUS_ADD_ON'	          AS EXPIRE_PREVIOUS_ADD_ON,
                                                                                  'LL_TRIBAL_SERV_TYPE'               AS LL_TRIBAL_SERV_TYPE,
                                                                                  'LL_SERV_TYPE'                      AS LL_SERV_TYPE,
																				  'PROMO_ILD_PRODUCT_ID'			AS PROMO_ILD_PRODUCT_ID
                                        ))) a;