GRANT EXECUTE ON sa.account_services_pkg TO cbo;
GRANT EXECUTE ON sa.account_services_pkg TO clarify_user;
GRANT EXECUTE ON sa.account_services_pkg TO corecbo;
GRANT EXECUTE ON sa.account_services_pkg TO csrcbo;
GRANT EXECUTE ON sa.account_services_pkg TO gw1;
GRANT EXECUTE ON sa.account_services_pkg TO mobapp_data;
GRANT EXECUTE ON sa.account_services_pkg TO role_sa_update;
GRANT EXECUTE ON sa.account_services_pkg TO soacbo;
GRANT EXECUTE ON sa.account_services_pkg TO webcbo;