GRANT ALTER ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT ALTER ON sa.adfcrm_part2ff_center_hist TO role_sa_update;
GRANT DEBUG ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT DEBUG ON sa.adfcrm_part2ff_center_hist TO role_sa_update;
GRANT DELETE ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT DELETE ON sa.adfcrm_part2ff_center_hist TO clarify_administrator;
GRANT DELETE ON sa.adfcrm_part2ff_center_hist TO clarify_user;
GRANT DELETE ON sa.adfcrm_part2ff_center_hist TO role_sa_update;
GRANT FLASHBACK ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT FLASHBACK ON sa.adfcrm_part2ff_center_hist TO role_sa_update;
GRANT INDEX ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT INSERT ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT INSERT ON sa.adfcrm_part2ff_center_hist TO clarify_administrator;
GRANT INSERT ON sa.adfcrm_part2ff_center_hist TO clarify_user;
GRANT INSERT ON sa.adfcrm_part2ff_center_hist TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT ON COMMIT REFRESH ON sa.adfcrm_part2ff_center_hist TO role_sa_update;
GRANT QUERY REWRITE ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT QUERY REWRITE ON sa.adfcrm_part2ff_center_hist TO role_sa_update;
GRANT READ ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT READ ON sa.adfcrm_part2ff_center_hist TO role_sa_update;
GRANT REFERENCES ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT SELECT ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT SELECT ON sa.adfcrm_part2ff_center_hist TO clarify_administrator;
GRANT SELECT ON sa.adfcrm_part2ff_center_hist TO clarify_reporter;
GRANT SELECT ON sa.adfcrm_part2ff_center_hist TO clarify_user;
GRANT SELECT ON sa.adfcrm_part2ff_center_hist TO dbit_mtoribiolopez;
GRANT SELECT ON sa.adfcrm_part2ff_center_hist TO role_sa_select;
GRANT SELECT ON sa.adfcrm_part2ff_center_hist TO role_sa_update;
GRANT SELECT ON sa.adfcrm_part2ff_center_hist TO role_tf_select;
GRANT UPDATE ON sa.adfcrm_part2ff_center_hist TO cbo;
GRANT UPDATE ON sa.adfcrm_part2ff_center_hist TO clarify_administrator;
GRANT UPDATE ON sa.adfcrm_part2ff_center_hist TO clarify_user;
GRANT UPDATE ON sa.adfcrm_part2ff_center_hist TO role_sa_update;