GRANT SELECT ON sa.apex_hotline_drop_down_options TO cbo;
GRANT SELECT ON sa.apex_hotline_drop_down_options TO clarify_administrator;
GRANT SELECT ON sa.apex_hotline_drop_down_options TO clarify_user;
GRANT SELECT ON sa.apex_hotline_drop_down_options TO csrcbo;
GRANT SELECT ON sa.apex_hotline_drop_down_options TO dbit_mtoribiolopez;
GRANT SELECT ON sa.apex_hotline_drop_down_options TO role_sa_select;
GRANT SELECT ON sa.apex_hotline_drop_down_options TO role_sa_update;
GRANT SELECT ON sa.apex_hotline_drop_down_options TO soacbo;
GRANT SELECT ON sa.apex_hotline_drop_down_options TO webcbo;