GRANT ALTER ON sa.asurion_outbound_positive TO etladmin;
GRANT ALTER ON sa.asurion_outbound_positive TO report;
GRANT DEBUG ON sa.asurion_outbound_positive TO etladmin;
GRANT DEBUG ON sa.asurion_outbound_positive TO report;
GRANT DELETE ON sa.asurion_outbound_positive TO etladmin;
GRANT DELETE ON sa.asurion_outbound_positive TO report;
GRANT FLASHBACK ON sa.asurion_outbound_positive TO etladmin;
GRANT FLASHBACK ON sa.asurion_outbound_positive TO report;
GRANT INDEX ON sa.asurion_outbound_positive TO etladmin;
GRANT INDEX ON sa.asurion_outbound_positive TO report;
GRANT INSERT ON sa.asurion_outbound_positive TO etladmin;
GRANT INSERT ON sa.asurion_outbound_positive TO report;
GRANT ON COMMIT REFRESH ON sa.asurion_outbound_positive TO etladmin;
GRANT ON COMMIT REFRESH ON sa.asurion_outbound_positive TO report;
GRANT QUERY REWRITE ON sa.asurion_outbound_positive TO etladmin;
GRANT QUERY REWRITE ON sa.asurion_outbound_positive TO report;
GRANT READ ON sa.asurion_outbound_positive TO etladmin;
GRANT READ ON sa.asurion_outbound_positive TO report;
GRANT REFERENCES ON sa.asurion_outbound_positive TO etladmin;
GRANT REFERENCES ON sa.asurion_outbound_positive TO report;
GRANT SELECT ON sa.asurion_outbound_positive TO etladmin;
GRANT SELECT ON sa.asurion_outbound_positive TO report;
GRANT SELECT ON sa.asurion_outbound_positive TO role_sa_select;
GRANT SELECT ON sa.asurion_outbound_positive TO role_tf_select;
GRANT SELECT ON sa.asurion_outbound_positive TO role_web_report;
GRANT UPDATE ON sa.asurion_outbound_positive TO etladmin;
GRANT UPDATE ON sa.asurion_outbound_positive TO report;