GRANT EXECUTE ON sa.billing_parseaction TO clarify_administrator;
GRANT EXECUTE ON sa.billing_parseaction TO clarify_billing;
GRANT EXECUTE ON sa.billing_parseaction TO clarify_reporter;
GRANT EXECUTE ON sa.billing_parseaction TO clarify_user;
GRANT EXECUTE ON sa.billing_parseaction TO report;
GRANT EXECUTE ON sa.billing_parseaction TO role_clarify_custom;
GRANT EXECUTE ON sa.billing_parseaction TO role_sa_update;
GRANT EXECUTE ON sa.billing_parseaction TO role_web_report;
GRANT EXECUTE ON sa.billing_parseaction TO select_no_pin;