GRANT EXECUTE ON sa.billing_get_cp_rule_engine TO clarify_administrator;
GRANT EXECUTE ON sa.billing_get_cp_rule_engine TO clarify_billing;
GRANT EXECUTE ON sa.billing_get_cp_rule_engine TO clarify_reporter;
GRANT EXECUTE ON sa.billing_get_cp_rule_engine TO clarify_user;
GRANT EXECUTE ON sa.billing_get_cp_rule_engine TO report;
GRANT EXECUTE ON sa.billing_get_cp_rule_engine TO role_clarify_custom;
GRANT EXECUTE ON sa.billing_get_cp_rule_engine TO role_sa_update;
GRANT EXECUTE ON sa.billing_get_cp_rule_engine TO role_web_report;
GRANT EXECUTE ON sa.billing_get_cp_rule_engine TO select_no_pin;