GRANT EXECUTE ON sa.billing_insert_prog_trans TO clarify_administrator;
GRANT EXECUTE ON sa.billing_insert_prog_trans TO clarify_billing;
GRANT EXECUTE ON sa.billing_insert_prog_trans TO clarify_reporter;
GRANT EXECUTE ON sa.billing_insert_prog_trans TO clarify_user;
GRANT EXECUTE ON sa.billing_insert_prog_trans TO report;
GRANT EXECUTE ON sa.billing_insert_prog_trans TO role_clarify_custom;
GRANT EXECUTE ON sa.billing_insert_prog_trans TO role_sa_update;
GRANT EXECUTE ON sa.billing_insert_prog_trans TO role_web_report;
GRANT EXECUTE ON sa.billing_insert_prog_trans TO select_no_pin;