GRANT EXECUTE ON sa.billing_deactprotect TO clarify_administrator;
GRANT EXECUTE ON sa.billing_deactprotect TO clarify_billing;
GRANT EXECUTE ON sa.billing_deactprotect TO clarify_reporter;
GRANT EXECUTE ON sa.billing_deactprotect TO clarify_user;
GRANT EXECUTE ON sa.billing_deactprotect TO report;
GRANT EXECUTE ON sa.billing_deactprotect TO role_clarify_custom;
GRANT EXECUTE ON sa.billing_deactprotect TO role_sa_update;
GRANT EXECUTE ON sa.billing_deactprotect TO role_web_report;
GRANT EXECUTE ON sa.billing_deactprotect TO select_no_pin;