GRANT EXECUTE ON sa.billing_admin_console_notify TO clarify_administrator;
GRANT EXECUTE ON sa.billing_admin_console_notify TO clarify_billing;
GRANT EXECUTE ON sa.billing_admin_console_notify TO clarify_reporter;
GRANT EXECUTE ON sa.billing_admin_console_notify TO clarify_user;
GRANT EXECUTE ON sa.billing_admin_console_notify TO report;
GRANT EXECUTE ON sa.billing_admin_console_notify TO role_clarify_custom;
GRANT EXECUTE ON sa.billing_admin_console_notify TO role_sa_update;
GRANT EXECUTE ON sa.billing_admin_console_notify TO role_web_report;
GRANT EXECUTE ON sa.billing_admin_console_notify TO select_no_pin;