GRANT EXECUTE ON sa.billing_extend_servicedays TO clarify_administrator;
GRANT EXECUTE ON sa.billing_extend_servicedays TO clarify_billing;
GRANT EXECUTE ON sa.billing_extend_servicedays TO clarify_reporter;
GRANT EXECUTE ON sa.billing_extend_servicedays TO clarify_user;
GRANT EXECUTE ON sa.billing_extend_servicedays TO report;
GRANT EXECUTE ON sa.billing_extend_servicedays TO role_clarify_custom;
GRANT EXECUTE ON sa.billing_extend_servicedays TO role_sa_update;
GRANT EXECUTE ON sa.billing_extend_servicedays TO role_web_report;
GRANT EXECUTE ON sa.billing_extend_servicedays TO select_no_pin;