GRANT EXECUTE ON sa.billing_can_paynow TO clarify_administrator;
GRANT EXECUTE ON sa.billing_can_paynow TO clarify_billing;
GRANT EXECUTE ON sa.billing_can_paynow TO clarify_reporter;
GRANT EXECUTE ON sa.billing_can_paynow TO clarify_user;
GRANT EXECUTE ON sa.billing_can_paynow TO report;
GRANT EXECUTE ON sa.billing_can_paynow TO role_clarify_custom;
GRANT EXECUTE ON sa.billing_can_paynow TO role_sa_update;
GRANT EXECUTE ON sa.billing_can_paynow TO role_web_report;
GRANT EXECUTE ON sa.billing_can_paynow TO select_no_pin;