GRANT EXECUTE ON sa.billing_de_register TO clarify_administrator;
GRANT EXECUTE ON sa.billing_de_register TO clarify_billing;
GRANT EXECUTE ON sa.billing_de_register TO clarify_reporter;
GRANT EXECUTE ON sa.billing_de_register TO clarify_user;
GRANT EXECUTE ON sa.billing_de_register TO report;
GRANT EXECUTE ON sa.billing_de_register TO role_clarify_custom;
GRANT EXECUTE ON sa.billing_de_register TO role_sa_update;
GRANT EXECUTE ON sa.billing_de_register TO role_web_report;
GRANT EXECUTE ON sa.billing_de_register TO select_no_pin;