GRANT EXECUTE ON sa.billing_get_pay_type TO clarify_administrator;
GRANT EXECUTE ON sa.billing_get_pay_type TO clarify_billing;
GRANT EXECUTE ON sa.billing_get_pay_type TO clarify_reporter;
GRANT EXECUTE ON sa.billing_get_pay_type TO clarify_user;
GRANT EXECUTE ON sa.billing_get_pay_type TO report;
GRANT EXECUTE ON sa.billing_get_pay_type TO role_clarify_custom;
GRANT EXECUTE ON sa.billing_get_pay_type TO role_sa_update;
GRANT EXECUTE ON sa.billing_get_pay_type TO role_web_report;
GRANT EXECUTE ON sa.billing_get_pay_type TO select_no_pin;