GRANT EXECUTE ON sa.bucket_id_type TO cbo;
GRANT EXECUTE ON sa.bucket_id_type TO clarify_administrator;
GRANT EXECUTE ON sa.bucket_id_type TO clarify_user;
GRANT EXECUTE ON sa.bucket_id_type TO csrcbo;
GRANT EXECUTE ON sa.bucket_id_type TO gw1;
GRANT EXECUTE ON sa.bucket_id_type TO report;
GRANT EXECUTE ON sa.bucket_id_type TO role_sa_update;
GRANT EXECUTE ON sa.bucket_id_type TO soacbo;
GRANT EXECUTE ON sa.bucket_id_type TO webcbo;