GRANT EXECUTE ON sa.bucket_balance_usage_tab TO cbo;
GRANT EXECUTE ON sa.bucket_balance_usage_tab TO clarify_administrator;
GRANT EXECUTE ON sa.bucket_balance_usage_tab TO clarify_user;
GRANT EXECUTE ON sa.bucket_balance_usage_tab TO csrcbo;
GRANT EXECUTE ON sa.bucket_balance_usage_tab TO gw1;
GRANT EXECUTE ON sa.bucket_balance_usage_tab TO report;
GRANT EXECUTE ON sa.bucket_balance_usage_tab TO role_sa_update;
GRANT EXECUTE ON sa.bucket_balance_usage_tab TO soacbo;
GRANT EXECUTE ON sa.bucket_balance_usage_tab TO webcbo;