GRANT DEBUG ON sa.byop_service_pkg TO itds_user;
GRANT EXECUTE ON sa.byop_service_pkg TO cbo;
GRANT EXECUTE ON sa.byop_service_pkg TO corecbo;
GRANT EXECUTE ON sa.byop_service_pkg TO csrcbo;
GRANT EXECUTE ON sa.byop_service_pkg TO gw1;
GRANT EXECUTE ON sa.byop_service_pkg TO itds_user;
GRANT EXECUTE ON sa.byop_service_pkg TO role_sa_update;
GRANT EXECUTE ON sa.byop_service_pkg TO soacbo;
GRANT EXECUTE ON sa.byop_service_pkg TO webcbo;