GRANT EXECUTE ON sa.canenroll TO clarify_administrator;
GRANT EXECUTE ON sa.canenroll TO clarify_billing;
GRANT EXECUTE ON sa.canenroll TO clarify_reporter;
GRANT EXECUTE ON sa.canenroll TO clarify_user;
GRANT EXECUTE ON sa.canenroll TO report;
GRANT EXECUTE ON sa.canenroll TO role_clarify_custom;
GRANT EXECUTE ON sa.canenroll TO role_sa_select;
GRANT EXECUTE ON sa.canenroll TO role_sa_update;
GRANT EXECUTE ON sa.canenroll TO role_web_report;