GRANT EXECUTE ON sa.customer_contact_info_type_tab TO cbo;
GRANT EXECUTE ON sa.customer_contact_info_type_tab TO clarify_administrator;
GRANT EXECUTE ON sa.customer_contact_info_type_tab TO clarify_user;
GRANT EXECUTE ON sa.customer_contact_info_type_tab TO corecbo;
GRANT EXECUTE ON sa.customer_contact_info_type_tab TO csrcbo;
GRANT EXECUTE ON sa.customer_contact_info_type_tab TO role_sa_update;
GRANT EXECUTE ON sa.customer_contact_info_type_tab TO soacbo;
GRANT EXECUTE ON sa.customer_contact_info_type_tab TO w3ci;
GRANT EXECUTE ON sa.customer_contact_info_type_tab TO webcbo;