GRANT DELETE ON sa.daily_carrier_act TO role_sa_update;
GRANT INSERT ON sa.daily_carrier_act TO role_sa_update;
GRANT SELECT ON sa.daily_carrier_act TO dbit_mtoribiolopez;
GRANT SELECT ON sa.daily_carrier_act TO nap_select_role;
GRANT SELECT ON sa.daily_carrier_act TO role_sa_select;
GRANT SELECT ON sa.daily_carrier_act TO role_sa_update;
GRANT SELECT ON sa.daily_carrier_act TO role_tf_select;
GRANT SELECT ON sa.daily_carrier_act TO select_no_pin;
GRANT UPDATE ON sa.daily_carrier_act TO role_sa_update;