GRANT SELECT ON sa.data_config_mapping_log TO cbo;
GRANT SELECT ON sa.data_config_mapping_log TO clarify_administrator;
GRANT SELECT ON sa.data_config_mapping_log TO clarify_user;
GRANT SELECT ON sa.data_config_mapping_log TO csrcbo;
GRANT SELECT ON sa.data_config_mapping_log TO dbit_mtoribiolopez;
GRANT SELECT ON sa.data_config_mapping_log TO role_sa_select;
GRANT SELECT ON sa.data_config_mapping_log TO role_sa_update;
GRANT SELECT ON sa.data_config_mapping_log TO soacbo;
GRANT SELECT ON sa.data_config_mapping_log TO webcbo;