GRANT ALTER ON sa.dealer_commissions_stage TO clarify_administrator;
GRANT ALTER ON sa.dealer_commissions_stage TO role_sa_update;
GRANT DEBUG ON sa.dealer_commissions_stage TO clarify_administrator;
GRANT DEBUG ON sa.dealer_commissions_stage TO role_sa_update;
GRANT DELETE ON sa.dealer_commissions_stage TO clarify_administrator;
GRANT DELETE ON sa.dealer_commissions_stage TO role_sa_update;
GRANT FLASHBACK ON sa.dealer_commissions_stage TO clarify_administrator;
GRANT FLASHBACK ON sa.dealer_commissions_stage TO role_sa_update;
GRANT INSERT ON sa.dealer_commissions_stage TO clarify_administrator;
GRANT INSERT ON sa.dealer_commissions_stage TO dwreport;
GRANT INSERT ON sa.dealer_commissions_stage TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.dealer_commissions_stage TO clarify_administrator;
GRANT ON COMMIT REFRESH ON sa.dealer_commissions_stage TO role_sa_update;
GRANT QUERY REWRITE ON sa.dealer_commissions_stage TO clarify_administrator;
GRANT QUERY REWRITE ON sa.dealer_commissions_stage TO role_sa_update;
GRANT SELECT ON sa.dealer_commissions_stage TO clarify_administrator;
GRANT SELECT ON sa.dealer_commissions_stage TO dbit_mtoribiolopez;
GRANT SELECT ON sa.dealer_commissions_stage TO dwreport;
GRANT SELECT ON sa.dealer_commissions_stage TO role_sa_update;
GRANT UPDATE ON sa.dealer_commissions_stage TO clarify_administrator;
GRANT UPDATE ON sa.dealer_commissions_stage TO role_sa_update;