GRANT EXECUTE ON sa.discount_code_tab TO cbo;
GRANT EXECUTE ON sa.discount_code_tab TO clarify_administrator;
GRANT EXECUTE ON sa.discount_code_tab TO clarify_user;
GRANT EXECUTE ON sa.discount_code_tab TO csrcbo;
GRANT EXECUTE ON sa.discount_code_tab TO gw1;
GRANT EXECUTE ON sa.discount_code_tab TO report;
GRANT EXECUTE ON sa.discount_code_tab TO soacbo;
GRANT EXECUTE ON sa.discount_code_tab TO webcbo;
GRANT EXECUTE ON sa.discount_code_tab TO wfmmig;