GRANT EXECUTE ON sa.enqueue_transactions_pkg TO cbo;
GRANT EXECUTE ON sa.enqueue_transactions_pkg TO clarify_administrator;
GRANT EXECUTE ON sa.enqueue_transactions_pkg TO clarify_user;
GRANT EXECUTE ON sa.enqueue_transactions_pkg TO csrcbo;
GRANT EXECUTE ON sa.enqueue_transactions_pkg TO gw1;
GRANT EXECUTE ON sa.enqueue_transactions_pkg TO igate_batch;
GRANT EXECUTE ON sa.enqueue_transactions_pkg TO report;
GRANT EXECUTE ON sa.enqueue_transactions_pkg TO soacbo;
GRANT EXECUTE ON sa.enqueue_transactions_pkg TO webcbo;