GRANT ALTER ON sa.file_versions TO role_sa_update;
GRANT DEBUG ON sa.file_versions TO cbo;
GRANT DEBUG ON sa.file_versions TO corecbo;
GRANT DEBUG ON sa.file_versions TO csrcbo;
GRANT DEBUG ON sa.file_versions TO role_sa_update;
GRANT DEBUG ON sa.file_versions TO soacbo;
GRANT DEBUG ON sa.file_versions TO webcbo;
GRANT DELETE ON sa.file_versions TO cbo;
GRANT DELETE ON sa.file_versions TO corecbo;
GRANT DELETE ON sa.file_versions TO csrcbo;
GRANT DELETE ON sa.file_versions TO role_sa_update;
GRANT DELETE ON sa.file_versions TO soacbo;
GRANT DELETE ON sa.file_versions TO webcbo;
GRANT FLASHBACK ON sa.file_versions TO cbo;
GRANT FLASHBACK ON sa.file_versions TO corecbo;
GRANT FLASHBACK ON sa.file_versions TO csrcbo;
GRANT FLASHBACK ON sa.file_versions TO role_sa_update;
GRANT FLASHBACK ON sa.file_versions TO soacbo;
GRANT FLASHBACK ON sa.file_versions TO webcbo;
GRANT INDEX ON sa.file_versions TO cbo;
GRANT INDEX ON sa.file_versions TO corecbo;
GRANT INDEX ON sa.file_versions TO csrcbo;
GRANT INDEX ON sa.file_versions TO soacbo;
GRANT INDEX ON sa.file_versions TO webcbo;
GRANT INSERT ON sa.file_versions TO cbo;
GRANT INSERT ON sa.file_versions TO corecbo;
GRANT INSERT ON sa.file_versions TO csrcbo;
GRANT INSERT ON sa.file_versions TO role_sa_update;
GRANT INSERT ON sa.file_versions TO soacbo;
GRANT INSERT ON sa.file_versions TO webcbo;
GRANT ON COMMIT REFRESH ON sa.file_versions TO cbo;
GRANT ON COMMIT REFRESH ON sa.file_versions TO corecbo;
GRANT ON COMMIT REFRESH ON sa.file_versions TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.file_versions TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.file_versions TO soacbo;
GRANT ON COMMIT REFRESH ON sa.file_versions TO webcbo;
GRANT QUERY REWRITE ON sa.file_versions TO cbo;
GRANT QUERY REWRITE ON sa.file_versions TO corecbo;
GRANT QUERY REWRITE ON sa.file_versions TO csrcbo;
GRANT QUERY REWRITE ON sa.file_versions TO role_sa_update;
GRANT QUERY REWRITE ON sa.file_versions TO soacbo;
GRANT QUERY REWRITE ON sa.file_versions TO webcbo;
GRANT REFERENCES ON sa.file_versions TO cbo;
GRANT REFERENCES ON sa.file_versions TO corecbo;
GRANT REFERENCES ON sa.file_versions TO csrcbo;
GRANT REFERENCES ON sa.file_versions TO soacbo;
GRANT REFERENCES ON sa.file_versions TO webcbo;
GRANT SELECT ON sa.file_versions TO cbo;
GRANT SELECT ON sa.file_versions TO clarify_user;
GRANT SELECT ON sa.file_versions TO corecbo;
GRANT SELECT ON sa.file_versions TO csrcbo;
GRANT SELECT ON sa.file_versions TO dbit_mtoribiolopez;
GRANT SELECT ON sa.file_versions TO role_sa_select;
GRANT SELECT ON sa.file_versions TO role_sa_update;
GRANT SELECT ON sa.file_versions TO role_tf_select;
GRANT SELECT ON sa.file_versions TO select_role;
GRANT SELECT ON sa.file_versions TO soacbo;
GRANT SELECT ON sa.file_versions TO webcbo;
GRANT UPDATE ON sa.file_versions TO cbo;
GRANT UPDATE ON sa.file_versions TO corecbo;
GRANT UPDATE ON sa.file_versions TO csrcbo;
GRANT UPDATE ON sa.file_versions TO role_sa_update;
GRANT UPDATE ON sa.file_versions TO soacbo;
GRANT UPDATE ON sa.file_versions TO webcbo;