GRANT EXECUTE ON sa.get_mobile_complete_url_by_esn TO cbo;
GRANT EXECUTE ON sa.get_mobile_complete_url_by_esn TO clarify_administrator;
GRANT EXECUTE ON sa.get_mobile_complete_url_by_esn TO clarify_user;
GRANT EXECUTE ON sa.get_mobile_complete_url_by_esn TO corecbo;
GRANT EXECUTE ON sa.get_mobile_complete_url_by_esn TO csrcbo;
GRANT EXECUTE ON sa.get_mobile_complete_url_by_esn TO role_sa_select;
GRANT EXECUTE ON sa.get_mobile_complete_url_by_esn TO role_sa_update;
GRANT EXECUTE ON sa.get_mobile_complete_url_by_esn TO soacbo;
GRANT EXECUTE ON sa.get_mobile_complete_url_by_esn TO webcbo;