GRANT EXECUTE ON sa.ig_transaction_buckets_type TO cbo;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO clarify_administrator;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO clarify_user;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO csrcbo;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO gw1;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO igate_batch;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO role_report_select;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO role_sa_select;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO role_sa_update;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO role_tf_select;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO soacbo;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO webcbo;
GRANT EXECUTE ON sa.ig_transaction_buckets_type TO wfmmig WITH GRANT OPTION;