GRANT EXECUTE ON sa.ll_subscriber_pkg TO cbo;
GRANT EXECUTE ON sa.ll_subscriber_pkg TO clarify_administrator;
GRANT EXECUTE ON sa.ll_subscriber_pkg TO clarify_user;
GRANT EXECUTE ON sa.ll_subscriber_pkg TO corecbo;
GRANT EXECUTE ON sa.ll_subscriber_pkg TO csrcbo;
GRANT EXECUTE ON sa.ll_subscriber_pkg TO igate_batch;
GRANT EXECUTE ON sa.ll_subscriber_pkg TO itds_user;
GRANT EXECUTE ON sa.ll_subscriber_pkg TO soacbo;
GRANT EXECUTE ON sa.ll_subscriber_pkg TO webcbo;