GRANT DELETE ON sa.monitor_err TO role_sa_update;
GRANT INSERT ON sa.monitor_err TO role_sa_update;
GRANT SELECT ON sa.monitor_err TO dbit_mtoribiolopez;
GRANT SELECT ON sa.monitor_err TO role_sa_select;
GRANT SELECT ON sa.monitor_err TO role_sa_update;
GRANT SELECT ON sa.monitor_err TO role_tf_select;
GRANT SELECT ON sa.monitor_err TO select_no_pin;
GRANT SELECT ON sa.monitor_err TO select_role;
GRANT UPDATE ON sa.monitor_err TO role_sa_update;