GRANT DELETE ON sa.monitor_stg TO role_sa_update;
GRANT INSERT ON sa.monitor_stg TO role_sa_update;
GRANT SELECT ON sa.monitor_stg TO dbit_mtoribiolopez;
GRANT SELECT ON sa.monitor_stg TO role_sa_select;
GRANT SELECT ON sa.monitor_stg TO role_sa_update;
GRANT SELECT ON sa.monitor_stg TO role_tf_select;
GRANT SELECT ON sa.monitor_stg TO select_no_pin;
GRANT SELECT ON sa.monitor_stg TO select_role;
GRANT UPDATE ON sa.monitor_stg TO role_sa_update;