GRANT ALTER ON sa.mtm_parent2parent_ordertype TO cbo;
GRANT ALTER ON sa.mtm_parent2parent_ordertype TO corecbo;
GRANT ALTER ON sa.mtm_parent2parent_ordertype TO csrcbo;
GRANT ALTER ON sa.mtm_parent2parent_ordertype TO role_sa_update;
GRANT ALTER ON sa.mtm_parent2parent_ordertype TO soacbo;
GRANT ALTER ON sa.mtm_parent2parent_ordertype TO webcbo;
GRANT DEBUG ON sa.mtm_parent2parent_ordertype TO cbo;
GRANT DEBUG ON sa.mtm_parent2parent_ordertype TO corecbo;
GRANT DEBUG ON sa.mtm_parent2parent_ordertype TO csrcbo;
GRANT DEBUG ON sa.mtm_parent2parent_ordertype TO role_sa_update;
GRANT DEBUG ON sa.mtm_parent2parent_ordertype TO soacbo;
GRANT DEBUG ON sa.mtm_parent2parent_ordertype TO webcbo;
GRANT DELETE ON sa.mtm_parent2parent_ordertype TO cbo;
GRANT DELETE ON sa.mtm_parent2parent_ordertype TO clarify_administrator;
GRANT DELETE ON sa.mtm_parent2parent_ordertype TO clarify_user;
GRANT DELETE ON sa.mtm_parent2parent_ordertype TO corecbo;
GRANT DELETE ON sa.mtm_parent2parent_ordertype TO csrcbo;
GRANT DELETE ON sa.mtm_parent2parent_ordertype TO role_sa_update;
GRANT DELETE ON sa.mtm_parent2parent_ordertype TO soacbo;
GRANT DELETE ON sa.mtm_parent2parent_ordertype TO webcbo;
GRANT FLASHBACK ON sa.mtm_parent2parent_ordertype TO cbo;
GRANT FLASHBACK ON sa.mtm_parent2parent_ordertype TO corecbo;
GRANT FLASHBACK ON sa.mtm_parent2parent_ordertype TO csrcbo;
GRANT FLASHBACK ON sa.mtm_parent2parent_ordertype TO role_sa_update;
GRANT FLASHBACK ON sa.mtm_parent2parent_ordertype TO soacbo;
GRANT FLASHBACK ON sa.mtm_parent2parent_ordertype TO webcbo;
GRANT INDEX ON sa.mtm_parent2parent_ordertype TO cbo;
GRANT INDEX ON sa.mtm_parent2parent_ordertype TO corecbo;
GRANT INDEX ON sa.mtm_parent2parent_ordertype TO csrcbo;
GRANT INDEX ON sa.mtm_parent2parent_ordertype TO soacbo;
GRANT INDEX ON sa.mtm_parent2parent_ordertype TO webcbo;
GRANT INSERT ON sa.mtm_parent2parent_ordertype TO cbo;
GRANT INSERT ON sa.mtm_parent2parent_ordertype TO clarify_administrator;
GRANT INSERT ON sa.mtm_parent2parent_ordertype TO clarify_user;
GRANT INSERT ON sa.mtm_parent2parent_ordertype TO corecbo;
GRANT INSERT ON sa.mtm_parent2parent_ordertype TO csrcbo;
GRANT INSERT ON sa.mtm_parent2parent_ordertype TO role_sa_update;
GRANT INSERT ON sa.mtm_parent2parent_ordertype TO soacbo;
GRANT INSERT ON sa.mtm_parent2parent_ordertype TO webcbo;
GRANT ON COMMIT REFRESH ON sa.mtm_parent2parent_ordertype TO cbo;
GRANT ON COMMIT REFRESH ON sa.mtm_parent2parent_ordertype TO corecbo;
GRANT ON COMMIT REFRESH ON sa.mtm_parent2parent_ordertype TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.mtm_parent2parent_ordertype TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.mtm_parent2parent_ordertype TO soacbo;
GRANT ON COMMIT REFRESH ON sa.mtm_parent2parent_ordertype TO webcbo;
GRANT QUERY REWRITE ON sa.mtm_parent2parent_ordertype TO cbo;
GRANT QUERY REWRITE ON sa.mtm_parent2parent_ordertype TO corecbo;
GRANT QUERY REWRITE ON sa.mtm_parent2parent_ordertype TO csrcbo;
GRANT QUERY REWRITE ON sa.mtm_parent2parent_ordertype TO role_sa_update;
GRANT QUERY REWRITE ON sa.mtm_parent2parent_ordertype TO soacbo;
GRANT QUERY REWRITE ON sa.mtm_parent2parent_ordertype TO webcbo;
GRANT REFERENCES ON sa.mtm_parent2parent_ordertype TO cbo;
GRANT REFERENCES ON sa.mtm_parent2parent_ordertype TO corecbo;
GRANT REFERENCES ON sa.mtm_parent2parent_ordertype TO csrcbo;
GRANT REFERENCES ON sa.mtm_parent2parent_ordertype TO soacbo;
GRANT REFERENCES ON sa.mtm_parent2parent_ordertype TO webcbo;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO cbo;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO clarify_administrator;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO clarify_reporter;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO clarify_user;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO corecbo;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO csrcbo;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO dbit_mtoribiolopez;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO role_sa_select;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO role_sa_update;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO role_tf_select;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO select_role;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO soacbo;
GRANT SELECT ON sa.mtm_parent2parent_ordertype TO webcbo;
GRANT UPDATE ON sa.mtm_parent2parent_ordertype TO cbo;
GRANT UPDATE ON sa.mtm_parent2parent_ordertype TO clarify_administrator;
GRANT UPDATE ON sa.mtm_parent2parent_ordertype TO clarify_user;
GRANT UPDATE ON sa.mtm_parent2parent_ordertype TO corecbo;
GRANT UPDATE ON sa.mtm_parent2parent_ordertype TO csrcbo;
GRANT UPDATE ON sa.mtm_parent2parent_ordertype TO role_sa_update;
GRANT UPDATE ON sa.mtm_parent2parent_ordertype TO soacbo;
GRANT UPDATE ON sa.mtm_parent2parent_ordertype TO webcbo;