GRANT ALTER ON sa.mtm_thresh_threshtype TO cbo;
GRANT ALTER ON sa.mtm_thresh_threshtype TO corecbo;
GRANT ALTER ON sa.mtm_thresh_threshtype TO csrcbo;
GRANT ALTER ON sa.mtm_thresh_threshtype TO soacbo;
GRANT ALTER ON sa.mtm_thresh_threshtype TO webcbo;
GRANT DEBUG ON sa.mtm_thresh_threshtype TO cbo;
GRANT DEBUG ON sa.mtm_thresh_threshtype TO corecbo;
GRANT DEBUG ON sa.mtm_thresh_threshtype TO csrcbo;
GRANT DEBUG ON sa.mtm_thresh_threshtype TO soacbo;
GRANT DEBUG ON sa.mtm_thresh_threshtype TO webcbo;
GRANT DELETE ON sa.mtm_thresh_threshtype TO cbo;
GRANT DELETE ON sa.mtm_thresh_threshtype TO corecbo;
GRANT DELETE ON sa.mtm_thresh_threshtype TO csrcbo;
GRANT DELETE ON sa.mtm_thresh_threshtype TO soacbo;
GRANT DELETE ON sa.mtm_thresh_threshtype TO webcbo;
GRANT FLASHBACK ON sa.mtm_thresh_threshtype TO cbo;
GRANT FLASHBACK ON sa.mtm_thresh_threshtype TO corecbo;
GRANT FLASHBACK ON sa.mtm_thresh_threshtype TO csrcbo;
GRANT FLASHBACK ON sa.mtm_thresh_threshtype TO soacbo;
GRANT FLASHBACK ON sa.mtm_thresh_threshtype TO webcbo;
GRANT INDEX ON sa.mtm_thresh_threshtype TO cbo;
GRANT INDEX ON sa.mtm_thresh_threshtype TO corecbo;
GRANT INDEX ON sa.mtm_thresh_threshtype TO csrcbo;
GRANT INDEX ON sa.mtm_thresh_threshtype TO soacbo;
GRANT INDEX ON sa.mtm_thresh_threshtype TO webcbo;
GRANT INSERT ON sa.mtm_thresh_threshtype TO cbo;
GRANT INSERT ON sa.mtm_thresh_threshtype TO corecbo;
GRANT INSERT ON sa.mtm_thresh_threshtype TO csrcbo;
GRANT INSERT ON sa.mtm_thresh_threshtype TO soacbo;
GRANT INSERT ON sa.mtm_thresh_threshtype TO webcbo;
GRANT ON COMMIT REFRESH ON sa.mtm_thresh_threshtype TO cbo;
GRANT ON COMMIT REFRESH ON sa.mtm_thresh_threshtype TO corecbo;
GRANT ON COMMIT REFRESH ON sa.mtm_thresh_threshtype TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.mtm_thresh_threshtype TO soacbo;
GRANT ON COMMIT REFRESH ON sa.mtm_thresh_threshtype TO webcbo;
GRANT QUERY REWRITE ON sa.mtm_thresh_threshtype TO cbo;
GRANT QUERY REWRITE ON sa.mtm_thresh_threshtype TO corecbo;
GRANT QUERY REWRITE ON sa.mtm_thresh_threshtype TO csrcbo;
GRANT QUERY REWRITE ON sa.mtm_thresh_threshtype TO soacbo;
GRANT QUERY REWRITE ON sa.mtm_thresh_threshtype TO webcbo;
GRANT REFERENCES ON sa.mtm_thresh_threshtype TO cbo;
GRANT REFERENCES ON sa.mtm_thresh_threshtype TO corecbo;
GRANT REFERENCES ON sa.mtm_thresh_threshtype TO csrcbo;
GRANT REFERENCES ON sa.mtm_thresh_threshtype TO soacbo;
GRANT REFERENCES ON sa.mtm_thresh_threshtype TO webcbo;
GRANT SELECT ON sa.mtm_thresh_threshtype TO cbo;
GRANT SELECT ON sa.mtm_thresh_threshtype TO corecbo;
GRANT SELECT ON sa.mtm_thresh_threshtype TO csrcbo;
GRANT SELECT ON sa.mtm_thresh_threshtype TO dbit_mtoribiolopez;
GRANT SELECT ON sa.mtm_thresh_threshtype TO role_tf_select;
GRANT SELECT ON sa.mtm_thresh_threshtype TO select_role;
GRANT SELECT ON sa.mtm_thresh_threshtype TO soacbo;
GRANT SELECT ON sa.mtm_thresh_threshtype TO webcbo;
GRANT UPDATE ON sa.mtm_thresh_threshtype TO cbo;
GRANT UPDATE ON sa.mtm_thresh_threshtype TO corecbo;
GRANT UPDATE ON sa.mtm_thresh_threshtype TO csrcbo;
GRANT UPDATE ON sa.mtm_thresh_threshtype TO soacbo;
GRANT UPDATE ON sa.mtm_thresh_threshtype TO webcbo;