GRANT ALTER ON sa.mtm_part_class6_x_scripts1 TO clarify_administrator;
GRANT DEBUG ON sa.mtm_part_class6_x_scripts1 TO clarify_administrator;
GRANT DELETE ON sa.mtm_part_class6_x_scripts1 TO clarify_administrator;
GRANT DELETE ON sa.mtm_part_class6_x_scripts1 TO clarify_user;
GRANT FLASHBACK ON sa.mtm_part_class6_x_scripts1 TO clarify_administrator;
GRANT INSERT ON sa.mtm_part_class6_x_scripts1 TO clarify_administrator;
GRANT INSERT ON sa.mtm_part_class6_x_scripts1 TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.mtm_part_class6_x_scripts1 TO clarify_administrator;
GRANT QUERY REWRITE ON sa.mtm_part_class6_x_scripts1 TO clarify_administrator;
GRANT SELECT ON sa.mtm_part_class6_x_scripts1 TO clarify_administrator;
GRANT SELECT ON sa.mtm_part_class6_x_scripts1 TO clarify_reporter;
GRANT SELECT ON sa.mtm_part_class6_x_scripts1 TO clarify_user;
GRANT SELECT ON sa.mtm_part_class6_x_scripts1 TO dbit_mtoribiolopez;
GRANT SELECT ON sa.mtm_part_class6_x_scripts1 TO role_tf_select;
GRANT SELECT ON sa.mtm_part_class6_x_scripts1 TO role_web_report;
GRANT SELECT ON sa.mtm_part_class6_x_scripts1 TO script_manager;
GRANT SELECT ON sa.mtm_part_class6_x_scripts1 TO select_role;
GRANT UPDATE ON sa.mtm_part_class6_x_scripts1 TO clarify_administrator;
GRANT UPDATE ON sa.mtm_part_class6_x_scripts1 TO clarify_user;