GRANT ALTER ON sa.mtm_partnum_promogrp TO cbo;
GRANT ALTER ON sa.mtm_partnum_promogrp TO clarify_user;
GRANT ALTER ON sa.mtm_partnum_promogrp TO corecbo;
GRANT ALTER ON sa.mtm_partnum_promogrp TO csrcbo;
GRANT ALTER ON sa.mtm_partnum_promogrp TO role_sa_update;
GRANT ALTER ON sa.mtm_partnum_promogrp TO soacbo;
GRANT ALTER ON sa.mtm_partnum_promogrp TO webcbo;
GRANT DEBUG ON sa.mtm_partnum_promogrp TO cbo;
GRANT DEBUG ON sa.mtm_partnum_promogrp TO clarify_user;
GRANT DEBUG ON sa.mtm_partnum_promogrp TO corecbo;
GRANT DEBUG ON sa.mtm_partnum_promogrp TO csrcbo;
GRANT DEBUG ON sa.mtm_partnum_promogrp TO role_sa_update;
GRANT DEBUG ON sa.mtm_partnum_promogrp TO soacbo;
GRANT DEBUG ON sa.mtm_partnum_promogrp TO webcbo;
GRANT DELETE ON sa.mtm_partnum_promogrp TO cbo;
GRANT DELETE ON sa.mtm_partnum_promogrp TO clarify_user;
GRANT DELETE ON sa.mtm_partnum_promogrp TO corecbo;
GRANT DELETE ON sa.mtm_partnum_promogrp TO csrcbo;
GRANT DELETE ON sa.mtm_partnum_promogrp TO role_sa_update;
GRANT DELETE ON sa.mtm_partnum_promogrp TO soacbo;
GRANT DELETE ON sa.mtm_partnum_promogrp TO webcbo;
GRANT FLASHBACK ON sa.mtm_partnum_promogrp TO cbo;
GRANT FLASHBACK ON sa.mtm_partnum_promogrp TO clarify_user;
GRANT FLASHBACK ON sa.mtm_partnum_promogrp TO corecbo;
GRANT FLASHBACK ON sa.mtm_partnum_promogrp TO csrcbo;
GRANT FLASHBACK ON sa.mtm_partnum_promogrp TO role_sa_update;
GRANT FLASHBACK ON sa.mtm_partnum_promogrp TO soacbo;
GRANT FLASHBACK ON sa.mtm_partnum_promogrp TO webcbo;
GRANT INDEX ON sa.mtm_partnum_promogrp TO cbo;
GRANT INDEX ON sa.mtm_partnum_promogrp TO corecbo;
GRANT INDEX ON sa.mtm_partnum_promogrp TO csrcbo;
GRANT INDEX ON sa.mtm_partnum_promogrp TO soacbo;
GRANT INDEX ON sa.mtm_partnum_promogrp TO webcbo;
GRANT INSERT ON sa.mtm_partnum_promogrp TO cbo;
GRANT INSERT ON sa.mtm_partnum_promogrp TO clarify_user;
GRANT INSERT ON sa.mtm_partnum_promogrp TO corecbo;
GRANT INSERT ON sa.mtm_partnum_promogrp TO csrcbo;
GRANT INSERT ON sa.mtm_partnum_promogrp TO role_sa_update;
GRANT INSERT ON sa.mtm_partnum_promogrp TO soacbo;
GRANT INSERT ON sa.mtm_partnum_promogrp TO webcbo;
GRANT ON COMMIT REFRESH ON sa.mtm_partnum_promogrp TO cbo;
GRANT ON COMMIT REFRESH ON sa.mtm_partnum_promogrp TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.mtm_partnum_promogrp TO corecbo;
GRANT ON COMMIT REFRESH ON sa.mtm_partnum_promogrp TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.mtm_partnum_promogrp TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.mtm_partnum_promogrp TO soacbo;
GRANT ON COMMIT REFRESH ON sa.mtm_partnum_promogrp TO webcbo;
GRANT QUERY REWRITE ON sa.mtm_partnum_promogrp TO cbo;
GRANT QUERY REWRITE ON sa.mtm_partnum_promogrp TO clarify_user;
GRANT QUERY REWRITE ON sa.mtm_partnum_promogrp TO corecbo;
GRANT QUERY REWRITE ON sa.mtm_partnum_promogrp TO csrcbo;
GRANT QUERY REWRITE ON sa.mtm_partnum_promogrp TO role_sa_update;
GRANT QUERY REWRITE ON sa.mtm_partnum_promogrp TO soacbo;
GRANT QUERY REWRITE ON sa.mtm_partnum_promogrp TO webcbo;
GRANT REFERENCES ON sa.mtm_partnum_promogrp TO cbo;
GRANT REFERENCES ON sa.mtm_partnum_promogrp TO corecbo;
GRANT REFERENCES ON sa.mtm_partnum_promogrp TO csrcbo;
GRANT REFERENCES ON sa.mtm_partnum_promogrp TO soacbo;
GRANT REFERENCES ON sa.mtm_partnum_promogrp TO webcbo;
GRANT SELECT ON sa.mtm_partnum_promogrp TO cbo;
GRANT SELECT ON sa.mtm_partnum_promogrp TO clarify_user;
GRANT SELECT ON sa.mtm_partnum_promogrp TO corecbo;
GRANT SELECT ON sa.mtm_partnum_promogrp TO csrcbo;
GRANT SELECT ON sa.mtm_partnum_promogrp TO dbit_mtoribiolopez;
GRANT SELECT ON sa.mtm_partnum_promogrp TO role_sa_select;
GRANT SELECT ON sa.mtm_partnum_promogrp TO role_sa_update;
GRANT SELECT ON sa.mtm_partnum_promogrp TO role_tf_select;
GRANT SELECT ON sa.mtm_partnum_promogrp TO select_role;
GRANT SELECT ON sa.mtm_partnum_promogrp TO soacbo;
GRANT SELECT ON sa.mtm_partnum_promogrp TO webcbo;
GRANT UPDATE ON sa.mtm_partnum_promogrp TO cbo;
GRANT UPDATE ON sa.mtm_partnum_promogrp TO clarify_user;
GRANT UPDATE ON sa.mtm_partnum_promogrp TO corecbo;
GRANT UPDATE ON sa.mtm_partnum_promogrp TO csrcbo;
GRANT UPDATE ON sa.mtm_partnum_promogrp TO role_sa_update;
GRANT UPDATE ON sa.mtm_partnum_promogrp TO soacbo;
GRANT UPDATE ON sa.mtm_partnum_promogrp TO webcbo;