GRANT ALTER ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;
GRANT DEBUG ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;
GRANT DELETE ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;
GRANT FLASHBACK ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;
GRANT INDEX ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;
GRANT INSERT ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;
GRANT ON COMMIT REFRESH ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;
GRANT QUERY REWRITE ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;
GRANT READ ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;
GRANT REFERENCES ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO cbo;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO clarify_administrator;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO clarify_user;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO corecbo;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO csrcbo;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO dbit_mtoribiolopez;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO igate_batch;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO role_report_select;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO role_sa_select;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO role_sa_update;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO role_tf_select;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO soacbo;
GRANT SELECT ON sa.mtm_sp_carrierfeatures_dflt TO webcbo;
GRANT UPDATE ON sa.mtm_sp_carrierfeatures_dflt TO PUBLIC;