GRANT DELETE ON sa.national_phones_topp TO role_sa_update;
GRANT INSERT ON sa.national_phones_topp TO role_sa_update;
GRANT SELECT ON sa.national_phones_topp TO dbit_mtoribiolopez;
GRANT SELECT ON sa.national_phones_topp TO role_sa_select;
GRANT SELECT ON sa.national_phones_topp TO role_sa_update;
GRANT SELECT ON sa.national_phones_topp TO role_tf_select;
GRANT SELECT ON sa.national_phones_topp TO select_no_pin;
GRANT SELECT ON sa.national_phones_topp TO select_role;
GRANT UPDATE ON sa.national_phones_topp TO role_sa_update;