GRANT DELETE ON sa.part_to_site2 TO role_sa_update;
GRANT INSERT ON sa.part_to_site2 TO role_sa_update;
GRANT SELECT ON sa.part_to_site2 TO dbit_mtoribiolopez;
GRANT SELECT ON sa.part_to_site2 TO role_sa_select;
GRANT SELECT ON sa.part_to_site2 TO role_sa_update;
GRANT SELECT ON sa.part_to_site2 TO role_tf_select;
GRANT SELECT ON sa.part_to_site2 TO select_no_pin;
GRANT SELECT ON sa.part_to_site2 TO select_role;
GRANT UPDATE ON sa.part_to_site2 TO role_sa_update;