GRANT EXECUTE ON sa.payment_source_detail_type TO cbo;
GRANT EXECUTE ON sa.payment_source_detail_type TO clarify_administrator;
GRANT EXECUTE ON sa.payment_source_detail_type TO clarify_user;
GRANT EXECUTE ON sa.payment_source_detail_type TO csrcbo;
GRANT EXECUTE ON sa.payment_source_detail_type TO igate_batch;
GRANT EXECUTE ON sa.payment_source_detail_type TO role_report_select;
GRANT EXECUTE ON sa.payment_source_detail_type TO role_tf_select;
GRANT EXECUTE ON sa.payment_source_detail_type TO soacbo;
GRANT EXECUTE ON sa.payment_source_detail_type TO webcbo;