GRANT EXECUTE ON sa.payment_source_detail_tab TO cbo;
GRANT EXECUTE ON sa.payment_source_detail_tab TO clarify_administrator;
GRANT EXECUTE ON sa.payment_source_detail_tab TO clarify_user;
GRANT EXECUTE ON sa.payment_source_detail_tab TO csrcbo;
GRANT EXECUTE ON sa.payment_source_detail_tab TO igate_batch;
GRANT EXECUTE ON sa.payment_source_detail_tab TO role_report_select;
GRANT EXECUTE ON sa.payment_source_detail_tab TO role_tf_select;
GRANT EXECUTE ON sa.payment_source_detail_tab TO soacbo;
GRANT EXECUTE ON sa.payment_source_detail_tab TO webcbo;