GRANT EXECUTE ON sa.pcrf_trans_det_low_prty_type TO cbo;
GRANT EXECUTE ON sa.pcrf_trans_det_low_prty_type TO clarify_administrator;
GRANT EXECUTE ON sa.pcrf_trans_det_low_prty_type TO clarify_user;
GRANT EXECUTE ON sa.pcrf_trans_det_low_prty_type TO csrcbo;
GRANT EXECUTE ON sa.pcrf_trans_det_low_prty_type TO gw1;
GRANT EXECUTE ON sa.pcrf_trans_det_low_prty_type TO igate_batch;
GRANT EXECUTE ON sa.pcrf_trans_det_low_prty_type TO soacbo;
GRANT EXECUTE ON sa.pcrf_trans_det_low_prty_type TO w3ci;
GRANT EXECUTE ON sa.pcrf_trans_det_low_prty_type TO webcbo;