GRANT DELETE ON sa.persupdate TO role_sa_update;
GRANT INSERT ON sa.persupdate TO role_sa_update;
GRANT SELECT ON sa.persupdate TO dbit_mtoribiolopez;
GRANT SELECT ON sa.persupdate TO role_sa_select;
GRANT SELECT ON sa.persupdate TO role_sa_update;
GRANT SELECT ON sa.persupdate TO role_tf_select;
GRANT SELECT ON sa.persupdate TO select_no_pin;
GRANT SELECT ON sa.persupdate TO select_role;
GRANT UPDATE ON sa.persupdate TO role_sa_update;