GRANT EXECUTE ON sa.process_order_type TO cbo;
GRANT EXECUTE ON sa.process_order_type TO clarify_administrator;
GRANT EXECUTE ON sa.process_order_type TO clarify_user;
GRANT EXECUTE ON sa.process_order_type TO csrcbo;
GRANT EXECUTE ON sa.process_order_type TO gw1;
GRANT EXECUTE ON sa.process_order_type TO igate_batch;
GRANT EXECUTE ON sa.process_order_type TO soacbo;
GRANT EXECUTE ON sa.process_order_type TO w3ci;
GRANT EXECUTE ON sa.process_order_type TO webcbo;