GRANT DELETE ON sa.product TO role_sa_update;
GRANT INSERT ON sa.product TO role_sa_update;
GRANT SELECT ON sa.product TO dbit_mtoribiolopez;
GRANT SELECT ON sa.product TO role_sa_select;
GRANT SELECT ON sa.product TO role_sa_update;
GRANT SELECT ON sa.product TO role_tf_select;
GRANT SELECT ON sa.product TO select_no_pin;
GRANT SELECT ON sa.product TO select_role;
GRANT UPDATE ON sa.product TO role_sa_update;