GRANT EXECUTE ON sa.red_card_pin_days_tab TO cbo;
GRANT EXECUTE ON sa.red_card_pin_days_tab TO clarify_administrator;
GRANT EXECUTE ON sa.red_card_pin_days_tab TO clarify_user;
GRANT EXECUTE ON sa.red_card_pin_days_tab TO csrcbo;
GRANT EXECUTE ON sa.red_card_pin_days_tab TO gw1;
GRANT EXECUTE ON sa.red_card_pin_days_tab TO igate_batch;
GRANT EXECUTE ON sa.red_card_pin_days_tab TO soacbo;
GRANT EXECUTE ON sa.red_card_pin_days_tab TO w3ci;
GRANT EXECUTE ON sa.red_card_pin_days_tab TO webcbo;