GRANT EXECUTE ON sa.red_card_pin_type TO cbo;
GRANT EXECUTE ON sa.red_card_pin_type TO clarify_administrator;
GRANT EXECUTE ON sa.red_card_pin_type TO clarify_user;
GRANT EXECUTE ON sa.red_card_pin_type TO csrcbo;
GRANT EXECUTE ON sa.red_card_pin_type TO gw1;
GRANT EXECUTE ON sa.red_card_pin_type TO igate_batch;
GRANT EXECUTE ON sa.red_card_pin_type TO soacbo;
GRANT EXECUTE ON sa.red_card_pin_type TO w3ci;
GRANT EXECUTE ON sa.red_card_pin_type TO webcbo;