GRANT DELETE ON sa.redsample TO role_sa_update;
GRANT INSERT ON sa.redsample TO role_sa_update;
GRANT SELECT ON sa.redsample TO dbit_mtoribiolopez;
GRANT SELECT ON sa.redsample TO role_sa_select;
GRANT SELECT ON sa.redsample TO role_sa_update;
GRANT SELECT ON sa.redsample TO role_tf_select;
GRANT SELECT ON sa.redsample TO select_no_pin;
GRANT SELECT ON sa.redsample TO select_role;
GRANT UPDATE ON sa.redsample TO role_sa_update;