GRANT EXECUTE ON sa.return_bucket_bal_tbl TO cbo;
GRANT EXECUTE ON sa.return_bucket_bal_tbl TO clarify_administrator;
GRANT EXECUTE ON sa.return_bucket_bal_tbl TO clarify_user;
GRANT EXECUTE ON sa.return_bucket_bal_tbl TO csrcbo;
GRANT EXECUTE ON sa.return_bucket_bal_tbl TO gw1;
GRANT EXECUTE ON sa.return_bucket_bal_tbl TO report;
GRANT EXECUTE ON sa.return_bucket_bal_tbl TO role_sa_update;
GRANT EXECUTE ON sa.return_bucket_bal_tbl TO soacbo;
GRANT EXECUTE ON sa.return_bucket_bal_tbl TO webcbo;