GRANT DELETE ON sa.scrub180 TO role_sa_update;
GRANT INSERT ON sa.scrub180 TO role_sa_update;
GRANT SELECT ON sa.scrub180 TO dbit_mtoribiolopez;
GRANT SELECT ON sa.scrub180 TO role_sa_select;
GRANT SELECT ON sa.scrub180 TO role_sa_update;
GRANT SELECT ON sa.scrub180 TO role_tf_select;
GRANT SELECT ON sa.scrub180 TO select_no_pin;
GRANT SELECT ON sa.scrub180 TO select_role;
GRANT UPDATE ON sa.scrub180 TO role_sa_update;