GRANT EXECUTE ON sa.smplist TO cbo;
GRANT EXECUTE ON sa.smplist TO clarify_administrator;
GRANT EXECUTE ON sa.smplist TO clarify_user;
GRANT EXECUTE ON sa.smplist TO csrcbo;
GRANT EXECUTE ON sa.smplist TO igate_batch;
GRANT EXECUTE ON sa.smplist TO role_report_select;
GRANT EXECUTE ON sa.smplist TO role_tf_select;
GRANT EXECUTE ON sa.smplist TO soacbo;
GRANT EXECUTE ON sa.smplist TO webcbo;