GRANT DEBUG ON sa.table_x_act_deact_hist TO clarify_administrator;
GRANT DELETE ON sa.table_x_act_deact_hist TO clarify_administrator;
GRANT DELETE ON sa.table_x_act_deact_hist TO clarify_user;
GRANT DELETE ON sa.table_x_act_deact_hist TO role_sqa_tester;
GRANT FLASHBACK ON sa.table_x_act_deact_hist TO clarify_administrator;
GRANT INSERT ON sa.table_x_act_deact_hist TO clarify_administrator;
GRANT INSERT ON sa.table_x_act_deact_hist TO clarify_user;
GRANT INSERT ON sa.table_x_act_deact_hist TO role_sqa_tester;
GRANT ON COMMIT REFRESH ON sa.table_x_act_deact_hist TO clarify_administrator;
GRANT QUERY REWRITE ON sa.table_x_act_deact_hist TO clarify_administrator;
GRANT SELECT ON sa.table_x_act_deact_hist TO clarify_administrator;
GRANT SELECT ON sa.table_x_act_deact_hist TO clarify_reporter;
GRANT SELECT ON sa.table_x_act_deact_hist TO clarify_user;
GRANT SELECT ON sa.table_x_act_deact_hist TO dbit_mtoribiolopez;
GRANT SELECT ON sa.table_x_act_deact_hist TO role_sqa_tester;
GRANT UPDATE ON sa.table_x_act_deact_hist TO clarify_administrator;
GRANT UPDATE ON sa.table_x_act_deact_hist TO clarify_user;
GRANT UPDATE ON sa.table_x_act_deact_hist TO role_sqa_tester;