GRANT ALTER ON sa.table_x_ild_transaction TO cbo;
GRANT ALTER ON sa.table_x_ild_transaction TO clarify_administrator;
GRANT ALTER ON sa.table_x_ild_transaction TO clarify_user;
GRANT ALTER ON sa.table_x_ild_transaction TO corecbo;
GRANT ALTER ON sa.table_x_ild_transaction TO csrcbo;
GRANT ALTER ON sa.table_x_ild_transaction TO role_sa_update;
GRANT ALTER ON sa.table_x_ild_transaction TO soacbo;
GRANT ALTER ON sa.table_x_ild_transaction TO webcbo;
GRANT DEBUG ON sa.table_x_ild_transaction TO cbo;
GRANT DEBUG ON sa.table_x_ild_transaction TO clarify_administrator;
GRANT DEBUG ON sa.table_x_ild_transaction TO clarify_user;
GRANT DEBUG ON sa.table_x_ild_transaction TO corecbo;
GRANT DEBUG ON sa.table_x_ild_transaction TO csrcbo;
GRANT DEBUG ON sa.table_x_ild_transaction TO role_sa_update;
GRANT DEBUG ON sa.table_x_ild_transaction TO soacbo;
GRANT DEBUG ON sa.table_x_ild_transaction TO webcbo;
GRANT DELETE ON sa.table_x_ild_transaction TO cbo;
GRANT DELETE ON sa.table_x_ild_transaction TO clarify_administrator;
GRANT DELETE ON sa.table_x_ild_transaction TO clarify_user;
GRANT DELETE ON sa.table_x_ild_transaction TO corecbo;
GRANT DELETE ON sa.table_x_ild_transaction TO csrcbo;
GRANT DELETE ON sa.table_x_ild_transaction TO role_sa_update;
GRANT DELETE ON sa.table_x_ild_transaction TO role_sqa_tester;
GRANT DELETE ON sa.table_x_ild_transaction TO soacbo;
GRANT DELETE ON sa.table_x_ild_transaction TO webcbo;
GRANT FLASHBACK ON sa.table_x_ild_transaction TO cbo;
GRANT FLASHBACK ON sa.table_x_ild_transaction TO clarify_administrator;
GRANT FLASHBACK ON sa.table_x_ild_transaction TO clarify_user;
GRANT FLASHBACK ON sa.table_x_ild_transaction TO corecbo;
GRANT FLASHBACK ON sa.table_x_ild_transaction TO csrcbo;
GRANT FLASHBACK ON sa.table_x_ild_transaction TO role_sa_update;
GRANT FLASHBACK ON sa.table_x_ild_transaction TO soacbo;
GRANT FLASHBACK ON sa.table_x_ild_transaction TO webcbo;
GRANT INDEX ON sa.table_x_ild_transaction TO cbo;
GRANT INDEX ON sa.table_x_ild_transaction TO corecbo;
GRANT INDEX ON sa.table_x_ild_transaction TO csrcbo;
GRANT INDEX ON sa.table_x_ild_transaction TO soacbo;
GRANT INDEX ON sa.table_x_ild_transaction TO webcbo;
GRANT INSERT ON sa.table_x_ild_transaction TO cbo;
GRANT INSERT ON sa.table_x_ild_transaction TO clarify_administrator;
GRANT INSERT ON sa.table_x_ild_transaction TO clarify_user;
GRANT INSERT ON sa.table_x_ild_transaction TO corecbo;
GRANT INSERT ON sa.table_x_ild_transaction TO csrcbo;
GRANT INSERT ON sa.table_x_ild_transaction TO igate_batch;
GRANT INSERT ON sa.table_x_ild_transaction TO role_sa_update;
GRANT INSERT ON sa.table_x_ild_transaction TO role_sqa_tester;
GRANT INSERT ON sa.table_x_ild_transaction TO soacbo;
GRANT INSERT ON sa.table_x_ild_transaction TO webcbo;
GRANT ON COMMIT REFRESH ON sa.table_x_ild_transaction TO cbo;
GRANT ON COMMIT REFRESH ON sa.table_x_ild_transaction TO clarify_administrator;
GRANT ON COMMIT REFRESH ON sa.table_x_ild_transaction TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.table_x_ild_transaction TO corecbo;
GRANT ON COMMIT REFRESH ON sa.table_x_ild_transaction TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.table_x_ild_transaction TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.table_x_ild_transaction TO soacbo;
GRANT ON COMMIT REFRESH ON sa.table_x_ild_transaction TO webcbo;
GRANT QUERY REWRITE ON sa.table_x_ild_transaction TO cbo;
GRANT QUERY REWRITE ON sa.table_x_ild_transaction TO clarify_administrator;
GRANT QUERY REWRITE ON sa.table_x_ild_transaction TO clarify_user;
GRANT QUERY REWRITE ON sa.table_x_ild_transaction TO corecbo;
GRANT QUERY REWRITE ON sa.table_x_ild_transaction TO csrcbo;
GRANT QUERY REWRITE ON sa.table_x_ild_transaction TO role_sa_update;
GRANT QUERY REWRITE ON sa.table_x_ild_transaction TO soacbo;
GRANT QUERY REWRITE ON sa.table_x_ild_transaction TO webcbo;
GRANT REFERENCES ON sa.table_x_ild_transaction TO cbo;
GRANT REFERENCES ON sa.table_x_ild_transaction TO corecbo;
GRANT REFERENCES ON sa.table_x_ild_transaction TO csrcbo;
GRANT REFERENCES ON sa.table_x_ild_transaction TO soacbo;
GRANT REFERENCES ON sa.table_x_ild_transaction TO webcbo;
GRANT SELECT ON sa.table_x_ild_transaction TO cbo;
GRANT SELECT ON sa.table_x_ild_transaction TO clarify_administrator;
GRANT SELECT ON sa.table_x_ild_transaction TO clarify_reporter;
GRANT SELECT ON sa.table_x_ild_transaction TO clarify_user;
GRANT SELECT ON sa.table_x_ild_transaction TO corecbo;
GRANT SELECT ON sa.table_x_ild_transaction TO csrcbo;
GRANT SELECT ON sa.table_x_ild_transaction TO dbit_mtoribiolopez;
GRANT SELECT ON sa.table_x_ild_transaction TO igate_batch;
GRANT SELECT ON sa.table_x_ild_transaction TO openview;
GRANT SELECT ON sa.table_x_ild_transaction TO pws_select_role;
GRANT SELECT ON sa.table_x_ild_transaction TO report;
GRANT SELECT ON sa.table_x_ild_transaction TO role_carrier_ops;
GRANT SELECT ON sa.table_x_ild_transaction TO role_clarify_custom;
GRANT SELECT ON sa.table_x_ild_transaction TO role_sa_select;
GRANT SELECT ON sa.table_x_ild_transaction TO role_sa_update;
GRANT SELECT ON sa.table_x_ild_transaction TO role_sqa_tester;
GRANT SELECT ON sa.table_x_ild_transaction TO role_tf_select;
GRANT SELECT ON sa.table_x_ild_transaction TO role_web_report;
GRANT SELECT ON sa.table_x_ild_transaction TO select_role;
GRANT SELECT ON sa.table_x_ild_transaction TO soacbo;
GRANT SELECT ON sa.table_x_ild_transaction TO web_report;
GRANT SELECT ON sa.table_x_ild_transaction TO webcbo;
GRANT UPDATE ON sa.table_x_ild_transaction TO cbo;
GRANT UPDATE ON sa.table_x_ild_transaction TO clarify_administrator;
GRANT UPDATE ON sa.table_x_ild_transaction TO clarify_user;
GRANT UPDATE ON sa.table_x_ild_transaction TO corecbo;
GRANT UPDATE ON sa.table_x_ild_transaction TO csrcbo;
GRANT UPDATE ON sa.table_x_ild_transaction TO igate_batch;
GRANT UPDATE ON sa.table_x_ild_transaction TO role_sa_update;
GRANT UPDATE ON sa.table_x_ild_transaction TO role_sqa_tester;
GRANT UPDATE ON sa.table_x_ild_transaction TO soacbo;
GRANT UPDATE ON sa.table_x_ild_transaction TO webcbo;