GRANT DEBUG ON sa.table_n_products TO clarify_administrator;
GRANT DELETE ON sa.table_n_products TO clarify_administrator;
GRANT DELETE ON sa.table_n_products TO clarify_user;
GRANT FLASHBACK ON sa.table_n_products TO clarify_administrator;
GRANT INSERT ON sa.table_n_products TO clarify_administrator;
GRANT INSERT ON sa.table_n_products TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.table_n_products TO clarify_administrator;
GRANT QUERY REWRITE ON sa.table_n_products TO clarify_administrator;
GRANT SELECT ON sa.table_n_products TO clarify_administrator;
GRANT SELECT ON sa.table_n_products TO clarify_reporter;
GRANT SELECT ON sa.table_n_products TO clarify_user;
GRANT SELECT ON sa.table_n_products TO dbit_mtoribiolopez;
GRANT UPDATE ON sa.table_n_products TO clarify_administrator;
GRANT UPDATE ON sa.table_n_products TO clarify_user;