GRANT ALTER ON sa.table_x_case_resolutions TO clarify_administrator;
GRANT DEBUG ON sa.table_x_case_resolutions TO clarify_administrator;
GRANT DELETE ON sa.table_x_case_resolutions TO clarify_administrator;
GRANT DELETE ON sa.table_x_case_resolutions TO clarify_user;
GRANT FLASHBACK ON sa.table_x_case_resolutions TO clarify_administrator;
GRANT INSERT ON sa.table_x_case_resolutions TO clarify_administrator;
GRANT INSERT ON sa.table_x_case_resolutions TO clarify_user;
GRANT INSERT ON sa.table_x_case_resolutions TO dbsqa_mbelottini;
GRANT ON COMMIT REFRESH ON sa.table_x_case_resolutions TO clarify_administrator;
GRANT QUERY REWRITE ON sa.table_x_case_resolutions TO clarify_administrator;
GRANT SELECT ON sa.table_x_case_resolutions TO clarify_administrator;
GRANT SELECT ON sa.table_x_case_resolutions TO clarify_reporter;
GRANT SELECT ON sa.table_x_case_resolutions TO clarify_user;
GRANT SELECT ON sa.table_x_case_resolutions TO dbit_mtoribiolopez;
GRANT SELECT ON sa.table_x_case_resolutions TO dbsqa_mbelottini;
GRANT SELECT ON sa.table_x_case_resolutions TO role_tf_select;
GRANT SELECT ON sa.table_x_case_resolutions TO select_role;
GRANT UPDATE ON sa.table_x_case_resolutions TO clarify_administrator;
GRANT UPDATE ON sa.table_x_case_resolutions TO clarify_user;
GRANT UPDATE ON sa.table_x_case_resolutions TO dbsqa_mbelottini;