GRANT ALTER ON sa.table_sec_threshold_types TO cbo;
GRANT ALTER ON sa.table_sec_threshold_types TO corecbo;
GRANT ALTER ON sa.table_sec_threshold_types TO csrcbo;
GRANT ALTER ON sa.table_sec_threshold_types TO soacbo;
GRANT ALTER ON sa.table_sec_threshold_types TO webcbo;
GRANT DEBUG ON sa.table_sec_threshold_types TO cbo;
GRANT DEBUG ON sa.table_sec_threshold_types TO corecbo;
GRANT DEBUG ON sa.table_sec_threshold_types TO csrcbo;
GRANT DEBUG ON sa.table_sec_threshold_types TO soacbo;
GRANT DEBUG ON sa.table_sec_threshold_types TO webcbo;
GRANT DELETE ON sa.table_sec_threshold_types TO cbo;
GRANT DELETE ON sa.table_sec_threshold_types TO corecbo;
GRANT DELETE ON sa.table_sec_threshold_types TO csrcbo;
GRANT DELETE ON sa.table_sec_threshold_types TO soacbo;
GRANT DELETE ON sa.table_sec_threshold_types TO webcbo;
GRANT FLASHBACK ON sa.table_sec_threshold_types TO cbo;
GRANT FLASHBACK ON sa.table_sec_threshold_types TO corecbo;
GRANT FLASHBACK ON sa.table_sec_threshold_types TO csrcbo;
GRANT FLASHBACK ON sa.table_sec_threshold_types TO soacbo;
GRANT FLASHBACK ON sa.table_sec_threshold_types TO webcbo;
GRANT INDEX ON sa.table_sec_threshold_types TO cbo;
GRANT INDEX ON sa.table_sec_threshold_types TO corecbo;
GRANT INDEX ON sa.table_sec_threshold_types TO csrcbo;
GRANT INDEX ON sa.table_sec_threshold_types TO soacbo;
GRANT INDEX ON sa.table_sec_threshold_types TO webcbo;
GRANT INSERT ON sa.table_sec_threshold_types TO cbo;
GRANT INSERT ON sa.table_sec_threshold_types TO corecbo;
GRANT INSERT ON sa.table_sec_threshold_types TO csrcbo;
GRANT INSERT ON sa.table_sec_threshold_types TO soacbo;
GRANT INSERT ON sa.table_sec_threshold_types TO webcbo;
GRANT ON COMMIT REFRESH ON sa.table_sec_threshold_types TO cbo;
GRANT ON COMMIT REFRESH ON sa.table_sec_threshold_types TO corecbo;
GRANT ON COMMIT REFRESH ON sa.table_sec_threshold_types TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.table_sec_threshold_types TO soacbo;
GRANT ON COMMIT REFRESH ON sa.table_sec_threshold_types TO webcbo;
GRANT QUERY REWRITE ON sa.table_sec_threshold_types TO cbo;
GRANT QUERY REWRITE ON sa.table_sec_threshold_types TO corecbo;
GRANT QUERY REWRITE ON sa.table_sec_threshold_types TO csrcbo;
GRANT QUERY REWRITE ON sa.table_sec_threshold_types TO soacbo;
GRANT QUERY REWRITE ON sa.table_sec_threshold_types TO webcbo;
GRANT REFERENCES ON sa.table_sec_threshold_types TO cbo;
GRANT REFERENCES ON sa.table_sec_threshold_types TO corecbo;
GRANT REFERENCES ON sa.table_sec_threshold_types TO csrcbo;
GRANT REFERENCES ON sa.table_sec_threshold_types TO soacbo;
GRANT REFERENCES ON sa.table_sec_threshold_types TO webcbo;
GRANT SELECT ON sa.table_sec_threshold_types TO cbo;
GRANT SELECT ON sa.table_sec_threshold_types TO corecbo;
GRANT SELECT ON sa.table_sec_threshold_types TO csrcbo;
GRANT SELECT ON sa.table_sec_threshold_types TO dbit_mtoribiolopez;
GRANT SELECT ON sa.table_sec_threshold_types TO role_tf_select;
GRANT SELECT ON sa.table_sec_threshold_types TO select_role;
GRANT SELECT ON sa.table_sec_threshold_types TO soacbo;
GRANT SELECT ON sa.table_sec_threshold_types TO webcbo;
GRANT UPDATE ON sa.table_sec_threshold_types TO cbo;
GRANT UPDATE ON sa.table_sec_threshold_types TO corecbo;
GRANT UPDATE ON sa.table_sec_threshold_types TO csrcbo;
GRANT UPDATE ON sa.table_sec_threshold_types TO soacbo;
GRANT UPDATE ON sa.table_sec_threshold_types TO webcbo;