GRANT SELECT ON sa.table_x_data_config_log TO cbo;
GRANT SELECT ON sa.table_x_data_config_log TO clarify_administrator;
GRANT SELECT ON sa.table_x_data_config_log TO clarify_user;
GRANT SELECT ON sa.table_x_data_config_log TO csrcbo;
GRANT SELECT ON sa.table_x_data_config_log TO dbit_mtoribiolopez;
GRANT SELECT ON sa.table_x_data_config_log TO role_sa_select;
GRANT SELECT ON sa.table_x_data_config_log TO role_sa_update;
GRANT SELECT ON sa.table_x_data_config_log TO soacbo;
GRANT SELECT ON sa.table_x_data_config_log TO webcbo;