GRANT ALTER ON sa.table_x_part_request TO clarify_administrator;
GRANT DEBUG ON sa.table_x_part_request TO clarify_administrator;
GRANT DELETE ON sa.table_x_part_request TO clarify_administrator;
GRANT DELETE ON sa.table_x_part_request TO clarify_user;
GRANT FLASHBACK ON sa.table_x_part_request TO clarify_administrator;
GRANT INSERT ON sa.table_x_part_request TO clarify_administrator;
GRANT INSERT ON sa.table_x_part_request TO clarify_user;
GRANT INSERT ON sa.table_x_part_request TO itds_user;
GRANT ON COMMIT REFRESH ON sa.table_x_part_request TO clarify_administrator;
GRANT QUERY REWRITE ON sa.table_x_part_request TO clarify_administrator;
GRANT SELECT ON sa.table_x_part_request TO clarify_administrator;
GRANT SELECT ON sa.table_x_part_request TO clarify_reporter;
GRANT SELECT ON sa.table_x_part_request TO clarify_user;
GRANT SELECT ON sa.table_x_part_request TO dbbu_gigutierrez;
GRANT SELECT ON sa.table_x_part_request TO dbit_mtoribiolopez;
GRANT SELECT ON sa.table_x_part_request TO openview;
GRANT SELECT ON sa.table_x_part_request TO role_carrier_ops;
GRANT SELECT ON sa.table_x_part_request TO role_sa_select;
GRANT SELECT ON sa.table_x_part_request TO role_tf_select;
GRANT SELECT ON sa.table_x_part_request TO select_no_pin;
GRANT SELECT ON sa.table_x_part_request TO select_role;
GRANT SELECT ON sa.table_x_part_request TO web_report;
GRANT UPDATE ON sa.table_x_part_request TO clarify_administrator;
GRANT UPDATE ON sa.table_x_part_request TO clarify_user;
GRANT UPDATE ON sa.table_x_part_request TO itds_user;
GRANT UPDATE ON sa.table_x_part_request TO role_crmteam_update;