GRANT ALTER ON sa.table_x_not_certify_models TO clarify_administrator;
GRANT ALTER ON sa.table_x_not_certify_models TO db_psi;
GRANT DEBUG ON sa.table_x_not_certify_models TO cbo;
GRANT DEBUG ON sa.table_x_not_certify_models TO clarify_administrator;
GRANT DEBUG ON sa.table_x_not_certify_models TO corecbo;
GRANT DEBUG ON sa.table_x_not_certify_models TO csrcbo;
GRANT DEBUG ON sa.table_x_not_certify_models TO db_psi;
GRANT DEBUG ON sa.table_x_not_certify_models TO soacbo;
GRANT DEBUG ON sa.table_x_not_certify_models TO webcbo;
GRANT DELETE ON sa.table_x_not_certify_models TO cbo;
GRANT DELETE ON sa.table_x_not_certify_models TO clarify_administrator;
GRANT DELETE ON sa.table_x_not_certify_models TO clarify_user;
GRANT DELETE ON sa.table_x_not_certify_models TO corecbo;
GRANT DELETE ON sa.table_x_not_certify_models TO csrcbo;
GRANT DELETE ON sa.table_x_not_certify_models TO db_psi;
GRANT DELETE ON sa.table_x_not_certify_models TO soacbo;
GRANT DELETE ON sa.table_x_not_certify_models TO webcbo;
GRANT FLASHBACK ON sa.table_x_not_certify_models TO cbo;
GRANT FLASHBACK ON sa.table_x_not_certify_models TO clarify_administrator;
GRANT FLASHBACK ON sa.table_x_not_certify_models TO corecbo;
GRANT FLASHBACK ON sa.table_x_not_certify_models TO csrcbo;
GRANT FLASHBACK ON sa.table_x_not_certify_models TO db_psi;
GRANT FLASHBACK ON sa.table_x_not_certify_models TO soacbo;
GRANT FLASHBACK ON sa.table_x_not_certify_models TO webcbo;
GRANT INDEX ON sa.table_x_not_certify_models TO cbo;
GRANT INDEX ON sa.table_x_not_certify_models TO corecbo;
GRANT INDEX ON sa.table_x_not_certify_models TO csrcbo;
GRANT INDEX ON sa.table_x_not_certify_models TO db_psi;
GRANT INDEX ON sa.table_x_not_certify_models TO soacbo;
GRANT INDEX ON sa.table_x_not_certify_models TO webcbo;
GRANT INSERT ON sa.table_x_not_certify_models TO cbo;
GRANT INSERT ON sa.table_x_not_certify_models TO clarify_administrator;
GRANT INSERT ON sa.table_x_not_certify_models TO clarify_user;
GRANT INSERT ON sa.table_x_not_certify_models TO corecbo;
GRANT INSERT ON sa.table_x_not_certify_models TO csrcbo;
GRANT INSERT ON sa.table_x_not_certify_models TO db_psi;
GRANT INSERT ON sa.table_x_not_certify_models TO soacbo;
GRANT INSERT ON sa.table_x_not_certify_models TO webcbo;
GRANT ON COMMIT REFRESH ON sa.table_x_not_certify_models TO cbo;
GRANT ON COMMIT REFRESH ON sa.table_x_not_certify_models TO clarify_administrator;
GRANT ON COMMIT REFRESH ON sa.table_x_not_certify_models TO corecbo;
GRANT ON COMMIT REFRESH ON sa.table_x_not_certify_models TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.table_x_not_certify_models TO db_psi;
GRANT ON COMMIT REFRESH ON sa.table_x_not_certify_models TO soacbo;
GRANT ON COMMIT REFRESH ON sa.table_x_not_certify_models TO webcbo;
GRANT QUERY REWRITE ON sa.table_x_not_certify_models TO cbo;
GRANT QUERY REWRITE ON sa.table_x_not_certify_models TO clarify_administrator;
GRANT QUERY REWRITE ON sa.table_x_not_certify_models TO corecbo;
GRANT QUERY REWRITE ON sa.table_x_not_certify_models TO csrcbo;
GRANT QUERY REWRITE ON sa.table_x_not_certify_models TO db_psi;
GRANT QUERY REWRITE ON sa.table_x_not_certify_models TO soacbo;
GRANT QUERY REWRITE ON sa.table_x_not_certify_models TO webcbo;
GRANT REFERENCES ON sa.table_x_not_certify_models TO cbo;
GRANT REFERENCES ON sa.table_x_not_certify_models TO corecbo;
GRANT REFERENCES ON sa.table_x_not_certify_models TO csrcbo;
GRANT REFERENCES ON sa.table_x_not_certify_models TO db_psi;
GRANT REFERENCES ON sa.table_x_not_certify_models TO soacbo;
GRANT REFERENCES ON sa.table_x_not_certify_models TO webcbo;
GRANT SELECT ON sa.table_x_not_certify_models TO cbo;
GRANT SELECT ON sa.table_x_not_certify_models TO clarify_administrator;
GRANT SELECT ON sa.table_x_not_certify_models TO clarify_reporter;
GRANT SELECT ON sa.table_x_not_certify_models TO clarify_user;
GRANT SELECT ON sa.table_x_not_certify_models TO corecbo;
GRANT SELECT ON sa.table_x_not_certify_models TO csrcbo;
GRANT SELECT ON sa.table_x_not_certify_models TO db_psi;
GRANT SELECT ON sa.table_x_not_certify_models TO dbit_mtoribiolopez;
GRANT SELECT ON sa.table_x_not_certify_models TO role_sa_select;
GRANT SELECT ON sa.table_x_not_certify_models TO role_tf_select;
GRANT SELECT ON sa.table_x_not_certify_models TO select_role;
GRANT SELECT ON sa.table_x_not_certify_models TO soacbo;
GRANT SELECT ON sa.table_x_not_certify_models TO webcbo;
GRANT UPDATE ON sa.table_x_not_certify_models TO cbo;
GRANT UPDATE ON sa.table_x_not_certify_models TO clarify_administrator;
GRANT UPDATE ON sa.table_x_not_certify_models TO clarify_user;
GRANT UPDATE ON sa.table_x_not_certify_models TO corecbo;
GRANT UPDATE ON sa.table_x_not_certify_models TO csrcbo;
GRANT UPDATE ON sa.table_x_not_certify_models TO db_psi;
GRANT UPDATE ON sa.table_x_not_certify_models TO soacbo;
GRANT UPDATE ON sa.table_x_not_certify_models TO webcbo;