GRANT ALTER ON sa.table_x_part_class_values TO cbo;
GRANT ALTER ON sa.table_x_part_class_values TO corecbo;
GRANT ALTER ON sa.table_x_part_class_values TO csrcbo;
GRANT ALTER ON sa.table_x_part_class_values TO db_psi;
GRANT ALTER ON sa.table_x_part_class_values TO soacbo;
GRANT ALTER ON sa.table_x_part_class_values TO webcbo;
GRANT DEBUG ON sa.table_x_part_class_values TO cbo;
GRANT DEBUG ON sa.table_x_part_class_values TO corecbo;
GRANT DEBUG ON sa.table_x_part_class_values TO csrcbo;
GRANT DEBUG ON sa.table_x_part_class_values TO db_psi;
GRANT DEBUG ON sa.table_x_part_class_values TO soacbo;
GRANT DEBUG ON sa.table_x_part_class_values TO webcbo;
GRANT DELETE ON sa.table_x_part_class_values TO cbo;
GRANT DELETE ON sa.table_x_part_class_values TO clarify_administrator;
GRANT DELETE ON sa.table_x_part_class_values TO clarify_user;
GRANT DELETE ON sa.table_x_part_class_values TO corecbo;
GRANT DELETE ON sa.table_x_part_class_values TO csrcbo;
GRANT DELETE ON sa.table_x_part_class_values TO db_psi;
GRANT DELETE ON sa.table_x_part_class_values TO soacbo;
GRANT DELETE ON sa.table_x_part_class_values TO webcbo;
GRANT FLASHBACK ON sa.table_x_part_class_values TO cbo;
GRANT FLASHBACK ON sa.table_x_part_class_values TO corecbo;
GRANT FLASHBACK ON sa.table_x_part_class_values TO csrcbo;
GRANT FLASHBACK ON sa.table_x_part_class_values TO db_psi;
GRANT FLASHBACK ON sa.table_x_part_class_values TO soacbo;
GRANT FLASHBACK ON sa.table_x_part_class_values TO webcbo;
GRANT INDEX ON sa.table_x_part_class_values TO cbo;
GRANT INDEX ON sa.table_x_part_class_values TO corecbo;
GRANT INDEX ON sa.table_x_part_class_values TO csrcbo;
GRANT INDEX ON sa.table_x_part_class_values TO db_psi;
GRANT INDEX ON sa.table_x_part_class_values TO soacbo;
GRANT INDEX ON sa.table_x_part_class_values TO webcbo;
GRANT INSERT ON sa.table_x_part_class_values TO cbo;
GRANT INSERT ON sa.table_x_part_class_values TO clarify_administrator;
GRANT INSERT ON sa.table_x_part_class_values TO clarify_user;
GRANT INSERT ON sa.table_x_part_class_values TO corecbo;
GRANT INSERT ON sa.table_x_part_class_values TO csrcbo;
GRANT INSERT ON sa.table_x_part_class_values TO db_psi;
GRANT INSERT ON sa.table_x_part_class_values TO soacbo;
GRANT INSERT ON sa.table_x_part_class_values TO webcbo;
GRANT ON COMMIT REFRESH ON sa.table_x_part_class_values TO cbo;
GRANT ON COMMIT REFRESH ON sa.table_x_part_class_values TO clarify_administrator;
GRANT ON COMMIT REFRESH ON sa.table_x_part_class_values TO corecbo;
GRANT ON COMMIT REFRESH ON sa.table_x_part_class_values TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.table_x_part_class_values TO db_psi;
GRANT ON COMMIT REFRESH ON sa.table_x_part_class_values TO soacbo;
GRANT ON COMMIT REFRESH ON sa.table_x_part_class_values TO webcbo;
GRANT QUERY REWRITE ON sa.table_x_part_class_values TO cbo;
GRANT QUERY REWRITE ON sa.table_x_part_class_values TO clarify_administrator;
GRANT QUERY REWRITE ON sa.table_x_part_class_values TO corecbo;
GRANT QUERY REWRITE ON sa.table_x_part_class_values TO csrcbo;
GRANT QUERY REWRITE ON sa.table_x_part_class_values TO db_psi;
GRANT QUERY REWRITE ON sa.table_x_part_class_values TO soacbo;
GRANT QUERY REWRITE ON sa.table_x_part_class_values TO webcbo;
GRANT REFERENCES ON sa.table_x_part_class_values TO cbo;
GRANT REFERENCES ON sa.table_x_part_class_values TO corecbo;
GRANT REFERENCES ON sa.table_x_part_class_values TO csrcbo;
GRANT REFERENCES ON sa.table_x_part_class_values TO db_psi;
GRANT REFERENCES ON sa.table_x_part_class_values TO soacbo;
GRANT REFERENCES ON sa.table_x_part_class_values TO webcbo;
GRANT SELECT ON sa.table_x_part_class_values TO cbo;
GRANT SELECT ON sa.table_x_part_class_values TO clarify_administrator;
GRANT SELECT ON sa.table_x_part_class_values TO clarify_reporter;
GRANT SELECT ON sa.table_x_part_class_values TO clarify_user;
GRANT SELECT ON sa.table_x_part_class_values TO corecbo;
GRANT SELECT ON sa.table_x_part_class_values TO csrcbo;
GRANT SELECT ON sa.table_x_part_class_values TO db_psi;
GRANT SELECT ON sa.table_x_part_class_values TO dbit_mtoribiolopez;
GRANT SELECT ON sa.table_x_part_class_values TO digadmin WITH GRANT OPTION;
GRANT SELECT ON sa.table_x_part_class_values TO gw1;
GRANT SELECT ON sa.table_x_part_class_values TO role_crmteam_update;
GRANT SELECT ON sa.table_x_part_class_values TO role_sqa_tester;
GRANT SELECT ON sa.table_x_part_class_values TO script_manager;
GRANT SELECT ON sa.table_x_part_class_values TO soacbo;
GRANT SELECT ON sa.table_x_part_class_values TO w3ci;
GRANT SELECT ON sa.table_x_part_class_values TO webcbo;
GRANT UPDATE ON sa.table_x_part_class_values TO cbo;
GRANT UPDATE ON sa.table_x_part_class_values TO clarify_administrator;
GRANT UPDATE ON sa.table_x_part_class_values TO clarify_user;
GRANT UPDATE ON sa.table_x_part_class_values TO corecbo;
GRANT UPDATE ON sa.table_x_part_class_values TO csrcbo;
GRANT UPDATE ON sa.table_x_part_class_values TO db_psi;
GRANT UPDATE ON sa.table_x_part_class_values TO soacbo;
GRANT UPDATE ON sa.table_x_part_class_values TO webcbo;