GRANT ALTER ON sa.table_x_case_conf_dtl TO clarify_administrator;
GRANT DEBUG ON sa.table_x_case_conf_dtl TO clarify_administrator;
GRANT DELETE ON sa.table_x_case_conf_dtl TO clarify_administrator;
GRANT DELETE ON sa.table_x_case_conf_dtl TO clarify_user;
GRANT DELETE ON sa.table_x_case_conf_dtl TO script_manager;
GRANT FLASHBACK ON sa.table_x_case_conf_dtl TO clarify_administrator;
GRANT INSERT ON sa.table_x_case_conf_dtl TO clarify_administrator;
GRANT INSERT ON sa.table_x_case_conf_dtl TO clarify_user;
GRANT INSERT ON sa.table_x_case_conf_dtl TO script_manager;
GRANT ON COMMIT REFRESH ON sa.table_x_case_conf_dtl TO clarify_administrator;
GRANT QUERY REWRITE ON sa.table_x_case_conf_dtl TO clarify_administrator;
GRANT SELECT ON sa.table_x_case_conf_dtl TO clarify_administrator;
GRANT SELECT ON sa.table_x_case_conf_dtl TO clarify_reporter;
GRANT SELECT ON sa.table_x_case_conf_dtl TO clarify_user;
GRANT SELECT ON sa.table_x_case_conf_dtl TO dbit_mtoribiolopez;
GRANT SELECT ON sa.table_x_case_conf_dtl TO role_tf_select;
GRANT SELECT ON sa.table_x_case_conf_dtl TO script_manager;
GRANT SELECT ON sa.table_x_case_conf_dtl TO select_role;
GRANT UPDATE ON sa.table_x_case_conf_dtl TO clarify_administrator;
GRANT UPDATE ON sa.table_x_case_conf_dtl TO clarify_user;
GRANT UPDATE ON sa.table_x_case_conf_dtl TO script_manager;