GRANT ALTER ON sa.table_x_data_config TO clarify_administrator;
GRANT ALTER ON sa.table_x_data_config TO clarify_user;
GRANT ALTER ON sa.table_x_data_config TO db_psi;
GRANT ALTER ON sa.table_x_data_config TO role_sa_update;
GRANT DEBUG ON sa.table_x_data_config TO cbo;
GRANT DEBUG ON sa.table_x_data_config TO clarify_administrator;
GRANT DEBUG ON sa.table_x_data_config TO clarify_user;
GRANT DEBUG ON sa.table_x_data_config TO corecbo;
GRANT DEBUG ON sa.table_x_data_config TO csrcbo;
GRANT DEBUG ON sa.table_x_data_config TO db_psi;
GRANT DEBUG ON sa.table_x_data_config TO role_sa_update;
GRANT DEBUG ON sa.table_x_data_config TO soacbo;
GRANT DEBUG ON sa.table_x_data_config TO webcbo;
GRANT DELETE ON sa.table_x_data_config TO cbo;
GRANT DELETE ON sa.table_x_data_config TO clarify_administrator;
GRANT DELETE ON sa.table_x_data_config TO clarify_user;
GRANT DELETE ON sa.table_x_data_config TO corecbo;
GRANT DELETE ON sa.table_x_data_config TO csrcbo;
GRANT DELETE ON sa.table_x_data_config TO db_psi;
GRANT DELETE ON sa.table_x_data_config TO role_sa_update;
GRANT DELETE ON sa.table_x_data_config TO soacbo;
GRANT DELETE ON sa.table_x_data_config TO webcbo;
GRANT FLASHBACK ON sa.table_x_data_config TO cbo;
GRANT FLASHBACK ON sa.table_x_data_config TO clarify_administrator;
GRANT FLASHBACK ON sa.table_x_data_config TO clarify_user;
GRANT FLASHBACK ON sa.table_x_data_config TO corecbo;
GRANT FLASHBACK ON sa.table_x_data_config TO csrcbo;
GRANT FLASHBACK ON sa.table_x_data_config TO db_psi;
GRANT FLASHBACK ON sa.table_x_data_config TO role_sa_update;
GRANT FLASHBACK ON sa.table_x_data_config TO soacbo;
GRANT FLASHBACK ON sa.table_x_data_config TO webcbo;
GRANT INDEX ON sa.table_x_data_config TO cbo;
GRANT INDEX ON sa.table_x_data_config TO corecbo;
GRANT INDEX ON sa.table_x_data_config TO csrcbo;
GRANT INDEX ON sa.table_x_data_config TO db_psi;
GRANT INDEX ON sa.table_x_data_config TO soacbo;
GRANT INDEX ON sa.table_x_data_config TO webcbo;
GRANT INSERT ON sa.table_x_data_config TO cbo;
GRANT INSERT ON sa.table_x_data_config TO clarify_administrator;
GRANT INSERT ON sa.table_x_data_config TO clarify_user;
GRANT INSERT ON sa.table_x_data_config TO corecbo;
GRANT INSERT ON sa.table_x_data_config TO csrcbo;
GRANT INSERT ON sa.table_x_data_config TO db_psi;
GRANT INSERT ON sa.table_x_data_config TO role_sa_update;
GRANT INSERT ON sa.table_x_data_config TO soacbo;
GRANT INSERT ON sa.table_x_data_config TO webcbo;
GRANT ON COMMIT REFRESH ON sa.table_x_data_config TO cbo;
GRANT ON COMMIT REFRESH ON sa.table_x_data_config TO clarify_administrator;
GRANT ON COMMIT REFRESH ON sa.table_x_data_config TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.table_x_data_config TO corecbo;
GRANT ON COMMIT REFRESH ON sa.table_x_data_config TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.table_x_data_config TO db_psi;
GRANT ON COMMIT REFRESH ON sa.table_x_data_config TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.table_x_data_config TO soacbo;
GRANT ON COMMIT REFRESH ON sa.table_x_data_config TO webcbo;
GRANT QUERY REWRITE ON sa.table_x_data_config TO cbo;
GRANT QUERY REWRITE ON sa.table_x_data_config TO clarify_administrator;
GRANT QUERY REWRITE ON sa.table_x_data_config TO clarify_user;
GRANT QUERY REWRITE ON sa.table_x_data_config TO corecbo;
GRANT QUERY REWRITE ON sa.table_x_data_config TO csrcbo;
GRANT QUERY REWRITE ON sa.table_x_data_config TO db_psi;
GRANT QUERY REWRITE ON sa.table_x_data_config TO role_sa_update;
GRANT QUERY REWRITE ON sa.table_x_data_config TO soacbo;
GRANT QUERY REWRITE ON sa.table_x_data_config TO webcbo;
GRANT REFERENCES ON sa.table_x_data_config TO cbo;
GRANT REFERENCES ON sa.table_x_data_config TO corecbo;
GRANT REFERENCES ON sa.table_x_data_config TO csrcbo;
GRANT REFERENCES ON sa.table_x_data_config TO db_psi;
GRANT REFERENCES ON sa.table_x_data_config TO soacbo;
GRANT REFERENCES ON sa.table_x_data_config TO webcbo;
GRANT SELECT ON sa.table_x_data_config TO cbo;
GRANT SELECT ON sa.table_x_data_config TO clarify_administrator;
GRANT SELECT ON sa.table_x_data_config TO clarify_user;
GRANT SELECT ON sa.table_x_data_config TO corecbo;
GRANT SELECT ON sa.table_x_data_config TO csrcbo;
GRANT SELECT ON sa.table_x_data_config TO db_psi;
GRANT SELECT ON sa.table_x_data_config TO dbit_mtoribiolopez;
GRANT SELECT ON sa.table_x_data_config TO digadmin WITH GRANT OPTION;
GRANT SELECT ON sa.table_x_data_config TO role_sa_select;
GRANT SELECT ON sa.table_x_data_config TO role_sa_update;
GRANT SELECT ON sa.table_x_data_config TO role_tf_select;
GRANT SELECT ON sa.table_x_data_config TO script_manager;
GRANT SELECT ON sa.table_x_data_config TO select_role;
GRANT SELECT ON sa.table_x_data_config TO soacbo;
GRANT SELECT ON sa.table_x_data_config TO webcbo;
GRANT UPDATE ON sa.table_x_data_config TO cbo;
GRANT UPDATE ON sa.table_x_data_config TO clarify_administrator;
GRANT UPDATE ON sa.table_x_data_config TO clarify_user;
GRANT UPDATE ON sa.table_x_data_config TO corecbo;
GRANT UPDATE ON sa.table_x_data_config TO csrcbo;
GRANT UPDATE ON sa.table_x_data_config TO db_psi;
GRANT UPDATE ON sa.table_x_data_config TO role_sa_update;
GRANT UPDATE ON sa.table_x_data_config TO soacbo;
GRANT UPDATE ON sa.table_x_data_config TO webcbo;