GRANT ALTER ON sa.table_x_case_detail TO clarify_administrator;
GRANT DEBUG ON sa.table_x_case_detail TO clarify_administrator;
GRANT DELETE ON sa.table_x_case_detail TO clarify_administrator;
GRANT DELETE ON sa.table_x_case_detail TO clarify_user;
GRANT FLASHBACK ON sa.table_x_case_detail TO clarify_administrator;
GRANT INSERT ON sa.table_x_case_detail TO clarify_administrator;
GRANT INSERT ON sa.table_x_case_detail TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.table_x_case_detail TO clarify_administrator;
GRANT QUERY REWRITE ON sa.table_x_case_detail TO clarify_administrator;
GRANT SELECT ON sa.table_x_case_detail TO clarify_administrator;
GRANT SELECT ON sa.table_x_case_detail TO clarify_reporter;
GRANT SELECT ON sa.table_x_case_detail TO clarify_user;
GRANT SELECT ON sa.table_x_case_detail TO dbbu_gigutierrez;
GRANT SELECT ON sa.table_x_case_detail TO dbit_mtoribiolopez;
GRANT SELECT ON sa.table_x_case_detail TO dbsqa_aquadri;
GRANT SELECT ON sa.table_x_case_detail TO openview;
GRANT SELECT ON sa.table_x_case_detail TO role_carrier_ops;
GRANT SELECT ON sa.table_x_case_detail TO role_sa_select;
GRANT SELECT ON sa.table_x_case_detail TO role_tf_select;
GRANT SELECT ON sa.table_x_case_detail TO select_role;
GRANT SELECT ON sa.table_x_case_detail TO w3ci;
GRANT UPDATE ON sa.table_x_case_detail TO clarify_administrator;
GRANT UPDATE ON sa.table_x_case_detail TO clarify_user;
GRANT UPDATE ON sa.table_x_case_detail TO role_crmteam_update;