GRANT EXECUTE ON sa.typ_pymt_src_dtls_rec TO cbo;
GRANT EXECUTE ON sa.typ_pymt_src_dtls_rec TO clarify_administrator;
GRANT EXECUTE ON sa.typ_pymt_src_dtls_rec TO clarify_user;
GRANT EXECUTE ON sa.typ_pymt_src_dtls_rec TO csrcbo;
GRANT EXECUTE ON sa.typ_pymt_src_dtls_rec TO igate_batch;
GRANT EXECUTE ON sa.typ_pymt_src_dtls_rec TO role_report_select;
GRANT EXECUTE ON sa.typ_pymt_src_dtls_rec TO role_tf_select;
GRANT EXECUTE ON sa.typ_pymt_src_dtls_rec TO soacbo;
GRANT EXECUTE ON sa.typ_pymt_src_dtls_rec TO webcbo;