GRANT EXECUTE ON sa.udp_tx_logging_pkg TO cbo;
GRANT EXECUTE ON sa.udp_tx_logging_pkg TO clarify_user;
GRANT EXECUTE ON sa.udp_tx_logging_pkg TO corecbo;
GRANT EXECUTE ON sa.udp_tx_logging_pkg TO csrcbo;
GRANT EXECUTE ON sa.udp_tx_logging_pkg TO gw1;
GRANT EXECUTE ON sa.udp_tx_logging_pkg TO igate_batch;
GRANT EXECUTE ON sa.udp_tx_logging_pkg TO role_sa_update;
GRANT EXECUTE ON sa.udp_tx_logging_pkg TO soacbo;
GRANT EXECUTE ON sa.udp_tx_logging_pkg TO webcbo;