GRANT ALTER ON sa.x_job_data TO cbo;
GRANT ALTER ON sa.x_job_data TO clarify_user;
GRANT ALTER ON sa.x_job_data TO corecbo;
GRANT ALTER ON sa.x_job_data TO csrcbo;
GRANT ALTER ON sa.x_job_data TO role_sa_update;
GRANT ALTER ON sa.x_job_data TO soacbo;
GRANT ALTER ON sa.x_job_data TO webcbo;
GRANT DEBUG ON sa.x_job_data TO cbo;
GRANT DEBUG ON sa.x_job_data TO clarify_user;
GRANT DEBUG ON sa.x_job_data TO corecbo;
GRANT DEBUG ON sa.x_job_data TO csrcbo;
GRANT DEBUG ON sa.x_job_data TO role_sa_update;
GRANT DEBUG ON sa.x_job_data TO soacbo;
GRANT DEBUG ON sa.x_job_data TO webcbo;
GRANT DELETE ON sa.x_job_data TO cbo;
GRANT DELETE ON sa.x_job_data TO clarify_user;
GRANT DELETE ON sa.x_job_data TO corecbo;
GRANT DELETE ON sa.x_job_data TO csrcbo;
GRANT DELETE ON sa.x_job_data TO dqietl;
GRANT DELETE ON sa.x_job_data TO report;
GRANT DELETE ON sa.x_job_data TO role_sa_update;
GRANT DELETE ON sa.x_job_data TO soacbo;
GRANT DELETE ON sa.x_job_data TO webcbo;
GRANT FLASHBACK ON sa.x_job_data TO cbo;
GRANT FLASHBACK ON sa.x_job_data TO clarify_user;
GRANT FLASHBACK ON sa.x_job_data TO corecbo;
GRANT FLASHBACK ON sa.x_job_data TO csrcbo;
GRANT FLASHBACK ON sa.x_job_data TO role_sa_update;
GRANT FLASHBACK ON sa.x_job_data TO soacbo;
GRANT FLASHBACK ON sa.x_job_data TO webcbo;
GRANT INDEX ON sa.x_job_data TO cbo;
GRANT INDEX ON sa.x_job_data TO corecbo;
GRANT INDEX ON sa.x_job_data TO csrcbo;
GRANT INDEX ON sa.x_job_data TO soacbo;
GRANT INDEX ON sa.x_job_data TO webcbo;
GRANT INSERT ON sa.x_job_data TO apex_sl_role;
GRANT INSERT ON sa.x_job_data TO cbo;
GRANT INSERT ON sa.x_job_data TO clarify_user;
GRANT INSERT ON sa.x_job_data TO corecbo;
GRANT INSERT ON sa.x_job_data TO csrcbo;
GRANT INSERT ON sa.x_job_data TO dqietl;
GRANT INSERT ON sa.x_job_data TO role_sa_update;
GRANT INSERT ON sa.x_job_data TO soacbo;
GRANT INSERT ON sa.x_job_data TO webcbo;
GRANT ON COMMIT REFRESH ON sa.x_job_data TO cbo;
GRANT ON COMMIT REFRESH ON sa.x_job_data TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.x_job_data TO corecbo;
GRANT ON COMMIT REFRESH ON sa.x_job_data TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.x_job_data TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.x_job_data TO soacbo;
GRANT ON COMMIT REFRESH ON sa.x_job_data TO webcbo;
GRANT QUERY REWRITE ON sa.x_job_data TO cbo;
GRANT QUERY REWRITE ON sa.x_job_data TO clarify_user;
GRANT QUERY REWRITE ON sa.x_job_data TO corecbo;
GRANT QUERY REWRITE ON sa.x_job_data TO csrcbo;
GRANT QUERY REWRITE ON sa.x_job_data TO role_sa_update;
GRANT QUERY REWRITE ON sa.x_job_data TO soacbo;
GRANT QUERY REWRITE ON sa.x_job_data TO webcbo;
GRANT REFERENCES ON sa.x_job_data TO cbo;
GRANT REFERENCES ON sa.x_job_data TO corecbo;
GRANT REFERENCES ON sa.x_job_data TO csrcbo;
GRANT REFERENCES ON sa.x_job_data TO soacbo;
GRANT REFERENCES ON sa.x_job_data TO webcbo;
GRANT SELECT ON sa.x_job_data TO apex_sl_role;
GRANT SELECT ON sa.x_job_data TO cbo;
GRANT SELECT ON sa.x_job_data TO clarify_user;
GRANT SELECT ON sa.x_job_data TO corecbo;
GRANT SELECT ON sa.x_job_data TO csrcbo;
GRANT SELECT ON sa.x_job_data TO dbit_mtoribiolopez;
GRANT SELECT ON sa.x_job_data TO dqietl;
GRANT SELECT ON sa.x_job_data TO role_sa_select;
GRANT SELECT ON sa.x_job_data TO role_sa_update;
GRANT SELECT ON sa.x_job_data TO role_tf_select;
GRANT SELECT ON sa.x_job_data TO select_role;
GRANT SELECT ON sa.x_job_data TO soacbo;
GRANT SELECT ON sa.x_job_data TO webcbo;
GRANT UPDATE ON sa.x_job_data TO cbo;
GRANT UPDATE ON sa.x_job_data TO clarify_user;
GRANT UPDATE ON sa.x_job_data TO corecbo;
GRANT UPDATE ON sa.x_job_data TO csrcbo;
GRANT UPDATE ON sa.x_job_data TO role_sa_update;
GRANT UPDATE ON sa.x_job_data TO soacbo;
GRANT UPDATE ON sa.x_job_data TO webcbo;