GRANT SELECT ON sa.x_job_activations_v TO cbo;
GRANT SELECT ON sa.x_job_activations_v TO clarify_administrator;
GRANT SELECT ON sa.x_job_activations_v TO clarify_user;
GRANT SELECT ON sa.x_job_activations_v TO csrcbo;
GRANT SELECT ON sa.x_job_activations_v TO dbit_mtoribiolopez;
GRANT SELECT ON sa.x_job_activations_v TO role_sa_select;
GRANT SELECT ON sa.x_job_activations_v TO role_sa_update;
GRANT SELECT ON sa.x_job_activations_v TO soacbo;
GRANT SELECT ON sa.x_job_activations_v TO webcbo;