GRANT ALTER ON sa.x_lb_offer TO cbo;
GRANT ALTER ON sa.x_lb_offer TO corecbo;
GRANT ALTER ON sa.x_lb_offer TO csrcbo;
GRANT ALTER ON sa.x_lb_offer TO role_sa_update;
GRANT ALTER ON sa.x_lb_offer TO soacbo;
GRANT ALTER ON sa.x_lb_offer TO webcbo;
GRANT DEBUG ON sa.x_lb_offer TO cbo;
GRANT DEBUG ON sa.x_lb_offer TO corecbo;
GRANT DEBUG ON sa.x_lb_offer TO csrcbo;
GRANT DEBUG ON sa.x_lb_offer TO role_sa_update;
GRANT DEBUG ON sa.x_lb_offer TO soacbo;
GRANT DEBUG ON sa.x_lb_offer TO webcbo;
GRANT DELETE ON sa.x_lb_offer TO cbo;
GRANT DELETE ON sa.x_lb_offer TO clarify_administrator;
GRANT DELETE ON sa.x_lb_offer TO clarify_user;
GRANT DELETE ON sa.x_lb_offer TO corecbo;
GRANT DELETE ON sa.x_lb_offer TO csrcbo;
GRANT DELETE ON sa.x_lb_offer TO role_sa_update;
GRANT DELETE ON sa.x_lb_offer TO soacbo;
GRANT DELETE ON sa.x_lb_offer TO webcbo;
GRANT FLASHBACK ON sa.x_lb_offer TO cbo;
GRANT FLASHBACK ON sa.x_lb_offer TO corecbo;
GRANT FLASHBACK ON sa.x_lb_offer TO csrcbo;
GRANT FLASHBACK ON sa.x_lb_offer TO role_sa_update;
GRANT FLASHBACK ON sa.x_lb_offer TO soacbo;
GRANT FLASHBACK ON sa.x_lb_offer TO webcbo;
GRANT INDEX ON sa.x_lb_offer TO cbo;
GRANT INDEX ON sa.x_lb_offer TO corecbo;
GRANT INDEX ON sa.x_lb_offer TO csrcbo;
GRANT INDEX ON sa.x_lb_offer TO soacbo;
GRANT INDEX ON sa.x_lb_offer TO webcbo;
GRANT INSERT ON sa.x_lb_offer TO cbo;
GRANT INSERT ON sa.x_lb_offer TO clarify_administrator;
GRANT INSERT ON sa.x_lb_offer TO clarify_user;
GRANT INSERT ON sa.x_lb_offer TO corecbo;
GRANT INSERT ON sa.x_lb_offer TO csrcbo;
GRANT INSERT ON sa.x_lb_offer TO role_sa_update;
GRANT INSERT ON sa.x_lb_offer TO soacbo;
GRANT INSERT ON sa.x_lb_offer TO webcbo;
GRANT ON COMMIT REFRESH ON sa.x_lb_offer TO cbo;
GRANT ON COMMIT REFRESH ON sa.x_lb_offer TO corecbo;
GRANT ON COMMIT REFRESH ON sa.x_lb_offer TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.x_lb_offer TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.x_lb_offer TO soacbo;
GRANT ON COMMIT REFRESH ON sa.x_lb_offer TO webcbo;
GRANT QUERY REWRITE ON sa.x_lb_offer TO cbo;
GRANT QUERY REWRITE ON sa.x_lb_offer TO corecbo;
GRANT QUERY REWRITE ON sa.x_lb_offer TO csrcbo;
GRANT QUERY REWRITE ON sa.x_lb_offer TO role_sa_update;
GRANT QUERY REWRITE ON sa.x_lb_offer TO soacbo;
GRANT QUERY REWRITE ON sa.x_lb_offer TO webcbo;
GRANT REFERENCES ON sa.x_lb_offer TO cbo;
GRANT REFERENCES ON sa.x_lb_offer TO corecbo;
GRANT REFERENCES ON sa.x_lb_offer TO csrcbo;
GRANT REFERENCES ON sa.x_lb_offer TO soacbo;
GRANT REFERENCES ON sa.x_lb_offer TO webcbo;
GRANT SELECT ON sa.x_lb_offer TO cbo;
GRANT SELECT ON sa.x_lb_offer TO clarify_administrator;
GRANT SELECT ON sa.x_lb_offer TO clarify_user;
GRANT SELECT ON sa.x_lb_offer TO corecbo;
GRANT SELECT ON sa.x_lb_offer TO csrcbo;
GRANT SELECT ON sa.x_lb_offer TO dbit_mtoribiolopez;
GRANT SELECT ON sa.x_lb_offer TO role_sa_select;
GRANT SELECT ON sa.x_lb_offer TO role_sa_update;
GRANT SELECT ON sa.x_lb_offer TO role_tf_select;
GRANT SELECT ON sa.x_lb_offer TO select_role;
GRANT SELECT ON sa.x_lb_offer TO soacbo;
GRANT SELECT ON sa.x_lb_offer TO webcbo;
GRANT UPDATE ON sa.x_lb_offer TO cbo;
GRANT UPDATE ON sa.x_lb_offer TO clarify_administrator;
GRANT UPDATE ON sa.x_lb_offer TO clarify_user;
GRANT UPDATE ON sa.x_lb_offer TO corecbo;
GRANT UPDATE ON sa.x_lb_offer TO csrcbo;
GRANT UPDATE ON sa.x_lb_offer TO role_sa_update;
GRANT UPDATE ON sa.x_lb_offer TO soacbo;
GRANT UPDATE ON sa.x_lb_offer TO webcbo;