GRANT ALTER ON sa.x_ota_admin_resend TO db_psi;
GRANT ALTER ON sa.x_ota_admin_resend TO toppapp;
GRANT DEBUG ON sa.x_ota_admin_resend TO cbo;
GRANT DEBUG ON sa.x_ota_admin_resend TO corecbo;
GRANT DEBUG ON sa.x_ota_admin_resend TO csrcbo;
GRANT DEBUG ON sa.x_ota_admin_resend TO db_psi;
GRANT DEBUG ON sa.x_ota_admin_resend TO soacbo;
GRANT DEBUG ON sa.x_ota_admin_resend TO toppapp;
GRANT DEBUG ON sa.x_ota_admin_resend TO webcbo;
GRANT DELETE ON sa.x_ota_admin_resend TO cbo;
GRANT DELETE ON sa.x_ota_admin_resend TO corecbo;
GRANT DELETE ON sa.x_ota_admin_resend TO csrcbo;
GRANT DELETE ON sa.x_ota_admin_resend TO db_psi;
GRANT DELETE ON sa.x_ota_admin_resend TO soacbo;
GRANT DELETE ON sa.x_ota_admin_resend TO toppapp;
GRANT DELETE ON sa.x_ota_admin_resend TO webcbo;
GRANT FLASHBACK ON sa.x_ota_admin_resend TO cbo;
GRANT FLASHBACK ON sa.x_ota_admin_resend TO corecbo;
GRANT FLASHBACK ON sa.x_ota_admin_resend TO csrcbo;
GRANT FLASHBACK ON sa.x_ota_admin_resend TO db_psi;
GRANT FLASHBACK ON sa.x_ota_admin_resend TO soacbo;
GRANT FLASHBACK ON sa.x_ota_admin_resend TO toppapp;
GRANT FLASHBACK ON sa.x_ota_admin_resend TO webcbo;
GRANT INDEX ON sa.x_ota_admin_resend TO cbo;
GRANT INDEX ON sa.x_ota_admin_resend TO corecbo;
GRANT INDEX ON sa.x_ota_admin_resend TO csrcbo;
GRANT INDEX ON sa.x_ota_admin_resend TO db_psi;
GRANT INDEX ON sa.x_ota_admin_resend TO soacbo;
GRANT INDEX ON sa.x_ota_admin_resend TO toppapp;
GRANT INDEX ON sa.x_ota_admin_resend TO webcbo;
GRANT INSERT ON sa.x_ota_admin_resend TO cbo;
GRANT INSERT ON sa.x_ota_admin_resend TO corecbo;
GRANT INSERT ON sa.x_ota_admin_resend TO csrcbo;
GRANT INSERT ON sa.x_ota_admin_resend TO db_psi;
GRANT INSERT ON sa.x_ota_admin_resend TO soacbo;
GRANT INSERT ON sa.x_ota_admin_resend TO toppapp;
GRANT INSERT ON sa.x_ota_admin_resend TO webcbo;
GRANT ON COMMIT REFRESH ON sa.x_ota_admin_resend TO cbo;
GRANT ON COMMIT REFRESH ON sa.x_ota_admin_resend TO corecbo;
GRANT ON COMMIT REFRESH ON sa.x_ota_admin_resend TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.x_ota_admin_resend TO db_psi;
GRANT ON COMMIT REFRESH ON sa.x_ota_admin_resend TO soacbo;
GRANT ON COMMIT REFRESH ON sa.x_ota_admin_resend TO toppapp;
GRANT ON COMMIT REFRESH ON sa.x_ota_admin_resend TO webcbo;
GRANT QUERY REWRITE ON sa.x_ota_admin_resend TO cbo;
GRANT QUERY REWRITE ON sa.x_ota_admin_resend TO corecbo;
GRANT QUERY REWRITE ON sa.x_ota_admin_resend TO csrcbo;
GRANT QUERY REWRITE ON sa.x_ota_admin_resend TO db_psi;
GRANT QUERY REWRITE ON sa.x_ota_admin_resend TO soacbo;
GRANT QUERY REWRITE ON sa.x_ota_admin_resend TO toppapp;
GRANT QUERY REWRITE ON sa.x_ota_admin_resend TO webcbo;
GRANT REFERENCES ON sa.x_ota_admin_resend TO cbo;
GRANT REFERENCES ON sa.x_ota_admin_resend TO corecbo;
GRANT REFERENCES ON sa.x_ota_admin_resend TO csrcbo;
GRANT REFERENCES ON sa.x_ota_admin_resend TO db_psi;
GRANT REFERENCES ON sa.x_ota_admin_resend TO soacbo;
GRANT REFERENCES ON sa.x_ota_admin_resend TO toppapp;
GRANT REFERENCES ON sa.x_ota_admin_resend TO webcbo;
GRANT SELECT ON sa.x_ota_admin_resend TO cbo;
GRANT SELECT ON sa.x_ota_admin_resend TO corecbo;
GRANT SELECT ON sa.x_ota_admin_resend TO csrcbo;
GRANT SELECT ON sa.x_ota_admin_resend TO db_psi;
GRANT SELECT ON sa.x_ota_admin_resend TO dbit_mtoribiolopez;
GRANT SELECT ON sa.x_ota_admin_resend TO role_ota_select;
GRANT SELECT ON sa.x_ota_admin_resend TO role_sa_select;
GRANT SELECT ON sa.x_ota_admin_resend TO role_sa_update;
GRANT SELECT ON sa.x_ota_admin_resend TO soacbo;
GRANT SELECT ON sa.x_ota_admin_resend TO toppapp;
GRANT SELECT ON sa.x_ota_admin_resend TO webcbo;
GRANT UPDATE ON sa.x_ota_admin_resend TO cbo;
GRANT UPDATE ON sa.x_ota_admin_resend TO corecbo;
GRANT UPDATE ON sa.x_ota_admin_resend TO csrcbo;
GRANT UPDATE ON sa.x_ota_admin_resend TO db_psi;
GRANT UPDATE ON sa.x_ota_admin_resend TO role_sa_update;
GRANT UPDATE ON sa.x_ota_admin_resend TO soacbo;
GRANT UPDATE ON sa.x_ota_admin_resend TO toppapp;
GRANT UPDATE ON sa.x_ota_admin_resend TO webcbo;