GRANT ALTER ON sa.x_pending_payment TO clarify_administrator;
GRANT ALTER ON sa.x_pending_payment TO clarify_user;
GRANT ALTER ON sa.x_pending_payment TO db_psi;
GRANT ALTER ON sa.x_pending_payment TO posaapp_role;
GRANT ALTER ON sa.x_pending_payment TO role_sa_update;
GRANT DEBUG ON sa.x_pending_payment TO cbo;
GRANT DEBUG ON sa.x_pending_payment TO clarify_administrator;
GRANT DEBUG ON sa.x_pending_payment TO clarify_user;
GRANT DEBUG ON sa.x_pending_payment TO corecbo;
GRANT DEBUG ON sa.x_pending_payment TO csrcbo;
GRANT DEBUG ON sa.x_pending_payment TO db_psi;
GRANT DEBUG ON sa.x_pending_payment TO posaapp_role;
GRANT DEBUG ON sa.x_pending_payment TO role_sa_update;
GRANT DEBUG ON sa.x_pending_payment TO soacbo;
GRANT DEBUG ON sa.x_pending_payment TO webcbo;
GRANT DELETE ON sa.x_pending_payment TO cbo;
GRANT DELETE ON sa.x_pending_payment TO clarify_administrator;
GRANT DELETE ON sa.x_pending_payment TO clarify_user;
GRANT DELETE ON sa.x_pending_payment TO corecbo;
GRANT DELETE ON sa.x_pending_payment TO csrcbo;
GRANT DELETE ON sa.x_pending_payment TO db_psi;
GRANT DELETE ON sa.x_pending_payment TO posaapp_role;
GRANT DELETE ON sa.x_pending_payment TO role_sa_update;
GRANT DELETE ON sa.x_pending_payment TO soacbo;
GRANT DELETE ON sa.x_pending_payment TO webcbo;
GRANT FLASHBACK ON sa.x_pending_payment TO cbo;
GRANT FLASHBACK ON sa.x_pending_payment TO clarify_administrator;
GRANT FLASHBACK ON sa.x_pending_payment TO clarify_user;
GRANT FLASHBACK ON sa.x_pending_payment TO corecbo;
GRANT FLASHBACK ON sa.x_pending_payment TO csrcbo;
GRANT FLASHBACK ON sa.x_pending_payment TO db_psi;
GRANT FLASHBACK ON sa.x_pending_payment TO posaapp_role;
GRANT FLASHBACK ON sa.x_pending_payment TO role_sa_update;
GRANT FLASHBACK ON sa.x_pending_payment TO soacbo;
GRANT FLASHBACK ON sa.x_pending_payment TO webcbo;
GRANT INDEX ON sa.x_pending_payment TO cbo;
GRANT INDEX ON sa.x_pending_payment TO corecbo;
GRANT INDEX ON sa.x_pending_payment TO csrcbo;
GRANT INDEX ON sa.x_pending_payment TO db_psi;
GRANT INDEX ON sa.x_pending_payment TO soacbo;
GRANT INDEX ON sa.x_pending_payment TO webcbo;
GRANT INSERT ON sa.x_pending_payment TO cbo;
GRANT INSERT ON sa.x_pending_payment TO clarify_administrator;
GRANT INSERT ON sa.x_pending_payment TO clarify_user;
GRANT INSERT ON sa.x_pending_payment TO corecbo;
GRANT INSERT ON sa.x_pending_payment TO csrcbo;
GRANT INSERT ON sa.x_pending_payment TO db_psi;
GRANT INSERT ON sa.x_pending_payment TO posaapp_role;
GRANT INSERT ON sa.x_pending_payment TO role_sa_update;
GRANT INSERT ON sa.x_pending_payment TO soacbo;
GRANT INSERT ON sa.x_pending_payment TO webcbo;
GRANT ON COMMIT REFRESH ON sa.x_pending_payment TO cbo;
GRANT ON COMMIT REFRESH ON sa.x_pending_payment TO clarify_administrator;
GRANT ON COMMIT REFRESH ON sa.x_pending_payment TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.x_pending_payment TO corecbo;
GRANT ON COMMIT REFRESH ON sa.x_pending_payment TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.x_pending_payment TO db_psi;
GRANT ON COMMIT REFRESH ON sa.x_pending_payment TO posaapp_role;
GRANT ON COMMIT REFRESH ON sa.x_pending_payment TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.x_pending_payment TO soacbo;
GRANT ON COMMIT REFRESH ON sa.x_pending_payment TO webcbo;
GRANT QUERY REWRITE ON sa.x_pending_payment TO cbo;
GRANT QUERY REWRITE ON sa.x_pending_payment TO clarify_administrator;
GRANT QUERY REWRITE ON sa.x_pending_payment TO clarify_user;
GRANT QUERY REWRITE ON sa.x_pending_payment TO corecbo;
GRANT QUERY REWRITE ON sa.x_pending_payment TO csrcbo;
GRANT QUERY REWRITE ON sa.x_pending_payment TO db_psi;
GRANT QUERY REWRITE ON sa.x_pending_payment TO posaapp_role;
GRANT QUERY REWRITE ON sa.x_pending_payment TO role_sa_update;
GRANT QUERY REWRITE ON sa.x_pending_payment TO soacbo;
GRANT QUERY REWRITE ON sa.x_pending_payment TO webcbo;
GRANT REFERENCES ON sa.x_pending_payment TO cbo;
GRANT REFERENCES ON sa.x_pending_payment TO corecbo;
GRANT REFERENCES ON sa.x_pending_payment TO csrcbo;
GRANT REFERENCES ON sa.x_pending_payment TO db_psi;
GRANT REFERENCES ON sa.x_pending_payment TO soacbo;
GRANT REFERENCES ON sa.x_pending_payment TO webcbo;
GRANT SELECT ON sa.x_pending_payment TO cbo;
GRANT SELECT ON sa.x_pending_payment TO clarify_administrator;
GRANT SELECT ON sa.x_pending_payment TO clarify_reporter;
GRANT SELECT ON sa.x_pending_payment TO clarify_user;
GRANT SELECT ON sa.x_pending_payment TO corecbo;
GRANT SELECT ON sa.x_pending_payment TO csrcbo;
GRANT SELECT ON sa.x_pending_payment TO db_psi;
GRANT SELECT ON sa.x_pending_payment TO dbit_mtoribiolopez;
GRANT SELECT ON sa.x_pending_payment TO openview;
GRANT SELECT ON sa.x_pending_payment TO posaapp_role;
GRANT SELECT ON sa.x_pending_payment TO report;
GRANT SELECT ON sa.x_pending_payment TO role_sa_select;
GRANT SELECT ON sa.x_pending_payment TO role_sa_update;
GRANT SELECT ON sa.x_pending_payment TO role_web_report;
GRANT SELECT ON sa.x_pending_payment TO soacbo;
GRANT SELECT ON sa.x_pending_payment TO webcbo;
GRANT UPDATE ON sa.x_pending_payment TO cbo;
GRANT UPDATE ON sa.x_pending_payment TO clarify_administrator;
GRANT UPDATE ON sa.x_pending_payment TO clarify_user;
GRANT UPDATE ON sa.x_pending_payment TO corecbo;
GRANT UPDATE ON sa.x_pending_payment TO csrcbo;
GRANT UPDATE ON sa.x_pending_payment TO db_psi;
GRANT UPDATE ON sa.x_pending_payment TO posaapp_role;
GRANT UPDATE ON sa.x_pending_payment TO role_sa_update;
GRANT UPDATE ON sa.x_pending_payment TO soacbo;
GRANT UPDATE ON sa.x_pending_payment TO webcbo;