GRANT ALTER ON sa.x_psd_log_info TO db_psi;
GRANT DEBUG ON sa.x_psd_log_info TO cbo;
GRANT DEBUG ON sa.x_psd_log_info TO corecbo;
GRANT DEBUG ON sa.x_psd_log_info TO csrcbo;
GRANT DEBUG ON sa.x_psd_log_info TO db_psi;
GRANT DEBUG ON sa.x_psd_log_info TO soacbo;
GRANT DEBUG ON sa.x_psd_log_info TO webcbo;
GRANT DELETE ON sa.x_psd_log_info TO cbo;
GRANT DELETE ON sa.x_psd_log_info TO corecbo;
GRANT DELETE ON sa.x_psd_log_info TO csrcbo;
GRANT DELETE ON sa.x_psd_log_info TO db_psi;
GRANT DELETE ON sa.x_psd_log_info TO soacbo;
GRANT DELETE ON sa.x_psd_log_info TO webcbo;
GRANT FLASHBACK ON sa.x_psd_log_info TO cbo;
GRANT FLASHBACK ON sa.x_psd_log_info TO corecbo;
GRANT FLASHBACK ON sa.x_psd_log_info TO csrcbo;
GRANT FLASHBACK ON sa.x_psd_log_info TO db_psi;
GRANT FLASHBACK ON sa.x_psd_log_info TO soacbo;
GRANT FLASHBACK ON sa.x_psd_log_info TO webcbo;
GRANT INDEX ON sa.x_psd_log_info TO cbo;
GRANT INDEX ON sa.x_psd_log_info TO corecbo;
GRANT INDEX ON sa.x_psd_log_info TO csrcbo;
GRANT INDEX ON sa.x_psd_log_info TO db_psi;
GRANT INDEX ON sa.x_psd_log_info TO soacbo;
GRANT INDEX ON sa.x_psd_log_info TO webcbo;
GRANT INSERT ON sa.x_psd_log_info TO cbo;
GRANT INSERT ON sa.x_psd_log_info TO corecbo;
GRANT INSERT ON sa.x_psd_log_info TO csrcbo;
GRANT INSERT ON sa.x_psd_log_info TO db_psi;
GRANT INSERT ON sa.x_psd_log_info TO soacbo;
GRANT INSERT ON sa.x_psd_log_info TO webcbo;
GRANT ON COMMIT REFRESH ON sa.x_psd_log_info TO cbo;
GRANT ON COMMIT REFRESH ON sa.x_psd_log_info TO corecbo;
GRANT ON COMMIT REFRESH ON sa.x_psd_log_info TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.x_psd_log_info TO db_psi;
GRANT ON COMMIT REFRESH ON sa.x_psd_log_info TO soacbo;
GRANT ON COMMIT REFRESH ON sa.x_psd_log_info TO webcbo;
GRANT QUERY REWRITE ON sa.x_psd_log_info TO cbo;
GRANT QUERY REWRITE ON sa.x_psd_log_info TO corecbo;
GRANT QUERY REWRITE ON sa.x_psd_log_info TO csrcbo;
GRANT QUERY REWRITE ON sa.x_psd_log_info TO db_psi;
GRANT QUERY REWRITE ON sa.x_psd_log_info TO soacbo;
GRANT QUERY REWRITE ON sa.x_psd_log_info TO webcbo;
GRANT REFERENCES ON sa.x_psd_log_info TO cbo;
GRANT REFERENCES ON sa.x_psd_log_info TO corecbo;
GRANT REFERENCES ON sa.x_psd_log_info TO csrcbo;
GRANT REFERENCES ON sa.x_psd_log_info TO db_psi;
GRANT REFERENCES ON sa.x_psd_log_info TO soacbo;
GRANT REFERENCES ON sa.x_psd_log_info TO webcbo;
GRANT SELECT ON sa.x_psd_log_info TO cbo;
GRANT SELECT ON sa.x_psd_log_info TO corecbo;
GRANT SELECT ON sa.x_psd_log_info TO csrcbo;
GRANT SELECT ON sa.x_psd_log_info TO db_psi;
GRANT SELECT ON sa.x_psd_log_info TO dbit_mtoribiolopez;
GRANT SELECT ON sa.x_psd_log_info TO soacbo;
GRANT SELECT ON sa.x_psd_log_info TO webcbo;
GRANT UPDATE ON sa.x_psd_log_info TO cbo;
GRANT UPDATE ON sa.x_psd_log_info TO corecbo;
GRANT UPDATE ON sa.x_psd_log_info TO csrcbo;
GRANT UPDATE ON sa.x_psd_log_info TO db_psi;
GRANT UPDATE ON sa.x_psd_log_info TO soacbo;
GRANT UPDATE ON sa.x_psd_log_info TO webcbo;