GRANT DELETE ON sa.x_republik_order_hdr TO role_tracfone_custom;
GRANT INSERT ON sa.x_republik_order_hdr TO role_tracfone_custom;
GRANT SELECT ON sa.x_republik_order_hdr TO apps_select;
GRANT SELECT ON sa.x_republik_order_hdr TO dbit_mtoribiolopez;
GRANT SELECT ON sa.x_republik_order_hdr TO role_tf_select;
GRANT SELECT ON sa.x_republik_order_hdr TO role_tracfone_custom;
GRANT SELECT ON sa.x_republik_order_hdr TO select_role;
GRANT UPDATE ON sa.x_republik_order_hdr TO apps_select;
GRANT UPDATE ON sa.x_republik_order_hdr TO role_tracfone_custom;