GRANT ALTER ON sa.x_selfheal_log TO cbo;
GRANT ALTER ON sa.x_selfheal_log TO clarify_user;
GRANT ALTER ON sa.x_selfheal_log TO corecbo;
GRANT ALTER ON sa.x_selfheal_log TO csrcbo;
GRANT ALTER ON sa.x_selfheal_log TO javadev;
GRANT ALTER ON sa.x_selfheal_log TO role_sa_update;
GRANT ALTER ON sa.x_selfheal_log TO soacbo;
GRANT ALTER ON sa.x_selfheal_log TO webcbo;
GRANT DEBUG ON sa.x_selfheal_log TO cbo;
GRANT DEBUG ON sa.x_selfheal_log TO clarify_user;
GRANT DEBUG ON sa.x_selfheal_log TO corecbo;
GRANT DEBUG ON sa.x_selfheal_log TO csrcbo;
GRANT DEBUG ON sa.x_selfheal_log TO javadev;
GRANT DEBUG ON sa.x_selfheal_log TO role_sa_update;
GRANT DEBUG ON sa.x_selfheal_log TO soacbo;
GRANT DEBUG ON sa.x_selfheal_log TO webcbo;
GRANT DELETE ON sa.x_selfheal_log TO cbo;
GRANT DELETE ON sa.x_selfheal_log TO clarify_user;
GRANT DELETE ON sa.x_selfheal_log TO corecbo;
GRANT DELETE ON sa.x_selfheal_log TO csrcbo;
GRANT DELETE ON sa.x_selfheal_log TO javadev;
GRANT DELETE ON sa.x_selfheal_log TO role_sa_update;
GRANT DELETE ON sa.x_selfheal_log TO soacbo;
GRANT DELETE ON sa.x_selfheal_log TO webcbo;
GRANT FLASHBACK ON sa.x_selfheal_log TO cbo;
GRANT FLASHBACK ON sa.x_selfheal_log TO clarify_user;
GRANT FLASHBACK ON sa.x_selfheal_log TO corecbo;
GRANT FLASHBACK ON sa.x_selfheal_log TO csrcbo;
GRANT FLASHBACK ON sa.x_selfheal_log TO javadev;
GRANT FLASHBACK ON sa.x_selfheal_log TO role_sa_update;
GRANT FLASHBACK ON sa.x_selfheal_log TO soacbo;
GRANT FLASHBACK ON sa.x_selfheal_log TO webcbo;
GRANT INDEX ON sa.x_selfheal_log TO cbo;
GRANT INDEX ON sa.x_selfheal_log TO corecbo;
GRANT INDEX ON sa.x_selfheal_log TO csrcbo;
GRANT INDEX ON sa.x_selfheal_log TO javadev;
GRANT INDEX ON sa.x_selfheal_log TO soacbo;
GRANT INDEX ON sa.x_selfheal_log TO webcbo;
GRANT INSERT ON sa.x_selfheal_log TO cbo;
GRANT INSERT ON sa.x_selfheal_log TO clarify_user;
GRANT INSERT ON sa.x_selfheal_log TO corecbo;
GRANT INSERT ON sa.x_selfheal_log TO csrcbo;
GRANT INSERT ON sa.x_selfheal_log TO javadev;
GRANT INSERT ON sa.x_selfheal_log TO role_sa_update;
GRANT INSERT ON sa.x_selfheal_log TO soacbo;
GRANT INSERT ON sa.x_selfheal_log TO webcbo;
GRANT ON COMMIT REFRESH ON sa.x_selfheal_log TO cbo;
GRANT ON COMMIT REFRESH ON sa.x_selfheal_log TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.x_selfheal_log TO corecbo;
GRANT ON COMMIT REFRESH ON sa.x_selfheal_log TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.x_selfheal_log TO javadev;
GRANT ON COMMIT REFRESH ON sa.x_selfheal_log TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.x_selfheal_log TO soacbo;
GRANT ON COMMIT REFRESH ON sa.x_selfheal_log TO webcbo;
GRANT QUERY REWRITE ON sa.x_selfheal_log TO cbo;
GRANT QUERY REWRITE ON sa.x_selfheal_log TO clarify_user;
GRANT QUERY REWRITE ON sa.x_selfheal_log TO corecbo;
GRANT QUERY REWRITE ON sa.x_selfheal_log TO csrcbo;
GRANT QUERY REWRITE ON sa.x_selfheal_log TO javadev;
GRANT QUERY REWRITE ON sa.x_selfheal_log TO role_sa_update;
GRANT QUERY REWRITE ON sa.x_selfheal_log TO soacbo;
GRANT QUERY REWRITE ON sa.x_selfheal_log TO webcbo;
GRANT REFERENCES ON sa.x_selfheal_log TO cbo;
GRANT REFERENCES ON sa.x_selfheal_log TO corecbo;
GRANT REFERENCES ON sa.x_selfheal_log TO csrcbo;
GRANT REFERENCES ON sa.x_selfheal_log TO javadev;
GRANT REFERENCES ON sa.x_selfheal_log TO soacbo;
GRANT REFERENCES ON sa.x_selfheal_log TO webcbo;
GRANT SELECT ON sa.x_selfheal_log TO cbo;
GRANT SELECT ON sa.x_selfheal_log TO clarify_user;
GRANT SELECT ON sa.x_selfheal_log TO corecbo;
GRANT SELECT ON sa.x_selfheal_log TO csrcbo;
GRANT SELECT ON sa.x_selfheal_log TO dbit_mtoribiolopez;
GRANT SELECT ON sa.x_selfheal_log TO javadev;
GRANT SELECT ON sa.x_selfheal_log TO role_sa_select;
GRANT SELECT ON sa.x_selfheal_log TO role_sa_update;
GRANT SELECT ON sa.x_selfheal_log TO role_tf_select;
GRANT SELECT ON sa.x_selfheal_log TO select_role;
GRANT SELECT ON sa.x_selfheal_log TO soacbo;
GRANT SELECT ON sa.x_selfheal_log TO webcbo;
GRANT UPDATE ON sa.x_selfheal_log TO cbo;
GRANT UPDATE ON sa.x_selfheal_log TO clarify_user;
GRANT UPDATE ON sa.x_selfheal_log TO corecbo;
GRANT UPDATE ON sa.x_selfheal_log TO csrcbo;
GRANT UPDATE ON sa.x_selfheal_log TO javadev;
GRANT UPDATE ON sa.x_selfheal_log TO role_sa_update;
GRANT UPDATE ON sa.x_selfheal_log TO soacbo;
GRANT UPDATE ON sa.x_selfheal_log TO webcbo;