GRANT ALTER ON sa.x_sl_subs TO cbo;
GRANT ALTER ON sa.x_sl_subs TO clarify_user;
GRANT ALTER ON sa.x_sl_subs TO corecbo;
GRANT ALTER ON sa.x_sl_subs TO csrcbo;
GRANT ALTER ON sa.x_sl_subs TO role_sa_update;
GRANT ALTER ON sa.x_sl_subs TO soacbo;
GRANT ALTER ON sa.x_sl_subs TO webcbo;
GRANT DEBUG ON sa.x_sl_subs TO cbo;
GRANT DEBUG ON sa.x_sl_subs TO clarify_user;
GRANT DEBUG ON sa.x_sl_subs TO corecbo;
GRANT DEBUG ON sa.x_sl_subs TO csrcbo;
GRANT DEBUG ON sa.x_sl_subs TO role_sa_update;
GRANT DEBUG ON sa.x_sl_subs TO soacbo;
GRANT DEBUG ON sa.x_sl_subs TO webcbo;
GRANT DELETE ON sa.x_sl_subs TO apex_sl_role;
GRANT DELETE ON sa.x_sl_subs TO cbo;
GRANT DELETE ON sa.x_sl_subs TO clarify_user;
GRANT DELETE ON sa.x_sl_subs TO corecbo;
GRANT DELETE ON sa.x_sl_subs TO csrcbo;
GRANT DELETE ON sa.x_sl_subs TO dbbu_mbharambe;
GRANT DELETE ON sa.x_sl_subs TO role_sa_update;
GRANT DELETE ON sa.x_sl_subs TO soacbo;
GRANT DELETE ON sa.x_sl_subs TO webcbo;
GRANT FLASHBACK ON sa.x_sl_subs TO cbo;
GRANT FLASHBACK ON sa.x_sl_subs TO clarify_user;
GRANT FLASHBACK ON sa.x_sl_subs TO corecbo;
GRANT FLASHBACK ON sa.x_sl_subs TO csrcbo;
GRANT FLASHBACK ON sa.x_sl_subs TO role_sa_update;
GRANT FLASHBACK ON sa.x_sl_subs TO soacbo;
GRANT FLASHBACK ON sa.x_sl_subs TO webcbo;
GRANT INDEX ON sa.x_sl_subs TO cbo;
GRANT INDEX ON sa.x_sl_subs TO corecbo;
GRANT INDEX ON sa.x_sl_subs TO csrcbo;
GRANT INDEX ON sa.x_sl_subs TO soacbo;
GRANT INDEX ON sa.x_sl_subs TO webcbo;
GRANT INSERT ON sa.x_sl_subs TO apex_sl_role;
GRANT INSERT ON sa.x_sl_subs TO cbo;
GRANT INSERT ON sa.x_sl_subs TO clarify_user;
GRANT INSERT ON sa.x_sl_subs TO corecbo;
GRANT INSERT ON sa.x_sl_subs TO csrcbo;
GRANT INSERT ON sa.x_sl_subs TO dbbu_mbharambe;
GRANT INSERT ON sa.x_sl_subs TO role_sa_update;
GRANT INSERT ON sa.x_sl_subs TO soacbo;
GRANT INSERT ON sa.x_sl_subs TO webcbo;
GRANT ON COMMIT REFRESH ON sa.x_sl_subs TO cbo;
GRANT ON COMMIT REFRESH ON sa.x_sl_subs TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.x_sl_subs TO corecbo;
GRANT ON COMMIT REFRESH ON sa.x_sl_subs TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.x_sl_subs TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.x_sl_subs TO soacbo;
GRANT ON COMMIT REFRESH ON sa.x_sl_subs TO webcbo;
GRANT QUERY REWRITE ON sa.x_sl_subs TO cbo;
GRANT QUERY REWRITE ON sa.x_sl_subs TO clarify_user;
GRANT QUERY REWRITE ON sa.x_sl_subs TO corecbo;
GRANT QUERY REWRITE ON sa.x_sl_subs TO csrcbo;
GRANT QUERY REWRITE ON sa.x_sl_subs TO role_sa_update;
GRANT QUERY REWRITE ON sa.x_sl_subs TO soacbo;
GRANT QUERY REWRITE ON sa.x_sl_subs TO webcbo;
GRANT REFERENCES ON sa.x_sl_subs TO cbo;
GRANT REFERENCES ON sa.x_sl_subs TO corecbo;
GRANT REFERENCES ON sa.x_sl_subs TO csrcbo;
GRANT REFERENCES ON sa.x_sl_subs TO soacbo;
GRANT REFERENCES ON sa.x_sl_subs TO webcbo;
GRANT SELECT ON sa.x_sl_subs TO apex_sl_role;
GRANT SELECT ON sa.x_sl_subs TO cbo;
GRANT SELECT ON sa.x_sl_subs TO clarify_user;
GRANT SELECT ON sa.x_sl_subs TO corecbo;
GRANT SELECT ON sa.x_sl_subs TO csrcbo;
GRANT SELECT ON sa.x_sl_subs TO dbbu_gigutierrez;
GRANT SELECT ON sa.x_sl_subs TO dbit_mtoribiolopez;
GRANT SELECT ON sa.x_sl_subs TO role_sa_select;
GRANT SELECT ON sa.x_sl_subs TO role_sa_update;
GRANT SELECT ON sa.x_sl_subs TO role_tf_select;
GRANT SELECT ON sa.x_sl_subs TO select_role;
GRANT SELECT ON sa.x_sl_subs TO soacbo;
GRANT SELECT ON sa.x_sl_subs TO webcbo;
GRANT UPDATE ON sa.x_sl_subs TO apex_sl_role;
GRANT UPDATE ON sa.x_sl_subs TO cbo;
GRANT UPDATE ON sa.x_sl_subs TO clarify_user;
GRANT UPDATE ON sa.x_sl_subs TO corecbo;
GRANT UPDATE ON sa.x_sl_subs TO csrcbo;
GRANT UPDATE ON sa.x_sl_subs TO dbbu_mbharambe;
GRANT UPDATE ON sa.x_sl_subs TO role_sa_update;
GRANT UPDATE ON sa.x_sl_subs TO soacbo;
GRANT UPDATE ON sa.x_sl_subs TO webcbo;