GRANT ALTER ON sa.x_subscriber_spr TO dbbu_oartigas;
GRANT ALTER ON sa.x_subscriber_spr TO itds_user;
GRANT DEBUG ON sa.x_subscriber_spr TO dbbu_oartigas;
GRANT DEBUG ON sa.x_subscriber_spr TO itds_user;
GRANT DELETE ON sa.x_subscriber_spr TO dbbu_oartigas;
GRANT DELETE ON sa.x_subscriber_spr TO dbit_kaborges;
GRANT DELETE ON sa.x_subscriber_spr TO itds_user;
GRANT FLASHBACK ON sa.x_subscriber_spr TO dbbu_oartigas;
GRANT FLASHBACK ON sa.x_subscriber_spr TO itds_user;
GRANT INDEX ON sa.x_subscriber_spr TO dbbu_oartigas;
GRANT INDEX ON sa.x_subscriber_spr TO itds_user;
GRANT INSERT ON sa.x_subscriber_spr TO dbbu_oartigas;
GRANT INSERT ON sa.x_subscriber_spr TO itds_user;
GRANT ON COMMIT REFRESH ON sa.x_subscriber_spr TO dbbu_oartigas;
GRANT ON COMMIT REFRESH ON sa.x_subscriber_spr TO itds_user;
GRANT QUERY REWRITE ON sa.x_subscriber_spr TO dbbu_oartigas;
GRANT QUERY REWRITE ON sa.x_subscriber_spr TO itds_user;
GRANT REFERENCES ON sa.x_subscriber_spr TO dbbu_oartigas;
GRANT REFERENCES ON sa.x_subscriber_spr TO itds_user;
GRANT SELECT ON sa.x_subscriber_spr TO cbo;
GRANT SELECT ON sa.x_subscriber_spr TO clarify_administrator;
GRANT SELECT ON sa.x_subscriber_spr TO clarify_user;
GRANT SELECT ON sa.x_subscriber_spr TO corecbo;
GRANT SELECT ON sa.x_subscriber_spr TO csrcbo;
GRANT SELECT ON sa.x_subscriber_spr TO dbbu_oartigas;
GRANT SELECT ON sa.x_subscriber_spr TO dbbu_ynegrin;
GRANT SELECT ON sa.x_subscriber_spr TO dbit_kaborges;
GRANT SELECT ON sa.x_subscriber_spr TO dbit_mtoribiolopez;
GRANT SELECT ON sa.x_subscriber_spr TO dbsqa_srajushringari;
GRANT SELECT ON sa.x_subscriber_spr TO gw1;
GRANT SELECT ON sa.x_subscriber_spr TO igate_batch;
GRANT SELECT ON sa.x_subscriber_spr TO itds_user;
GRANT SELECT ON sa.x_subscriber_spr TO itquser_data;
GRANT SELECT ON sa.x_subscriber_spr TO role_carrier_ops;
GRANT SELECT ON sa.x_subscriber_spr TO role_report_select;
GRANT SELECT ON sa.x_subscriber_spr TO role_sa_select;
GRANT SELECT ON sa.x_subscriber_spr TO role_sa_update;
GRANT SELECT ON sa.x_subscriber_spr TO role_tf_select;
GRANT SELECT ON sa.x_subscriber_spr TO select_role;
GRANT SELECT ON sa.x_subscriber_spr TO soacbo;
GRANT SELECT ON sa.x_subscriber_spr TO w3ci;
GRANT SELECT ON sa.x_subscriber_spr TO webcbo;
GRANT UPDATE ON sa.x_subscriber_spr TO dbbu_oartigas;
GRANT UPDATE ON sa.x_subscriber_spr TO dbit_kaborges;
GRANT UPDATE ON sa.x_subscriber_spr TO itds_user;
GRANT UPDATE ON sa.x_subscriber_spr TO itquser_data;
GRANT UPDATE ON sa.x_subscriber_spr TO mobapp_data;
GRANT UPDATE ON sa.x_subscriber_spr TO select_role;