GRANT ALTER ON sa.xsu_vmbc_response TO cbo;
GRANT ALTER ON sa.xsu_vmbc_response TO clarify_user;
GRANT ALTER ON sa.xsu_vmbc_response TO corecbo;
GRANT ALTER ON sa.xsu_vmbc_response TO csrcbo;
GRANT ALTER ON sa.xsu_vmbc_response TO role_sa_update;
GRANT ALTER ON sa.xsu_vmbc_response TO soacbo;
GRANT ALTER ON sa.xsu_vmbc_response TO webcbo;
GRANT DEBUG ON sa.xsu_vmbc_response TO cbo;
GRANT DEBUG ON sa.xsu_vmbc_response TO clarify_user;
GRANT DEBUG ON sa.xsu_vmbc_response TO corecbo;
GRANT DEBUG ON sa.xsu_vmbc_response TO csrcbo;
GRANT DEBUG ON sa.xsu_vmbc_response TO role_sa_update;
GRANT DEBUG ON sa.xsu_vmbc_response TO soacbo;
GRANT DEBUG ON sa.xsu_vmbc_response TO webcbo;
GRANT DELETE ON sa.xsu_vmbc_response TO cbo;
GRANT DELETE ON sa.xsu_vmbc_response TO clarify_user;
GRANT DELETE ON sa.xsu_vmbc_response TO corecbo;
GRANT DELETE ON sa.xsu_vmbc_response TO csrcbo;
GRANT DELETE ON sa.xsu_vmbc_response TO role_sa_update;
GRANT DELETE ON sa.xsu_vmbc_response TO soacbo;
GRANT DELETE ON sa.xsu_vmbc_response TO webcbo;
GRANT FLASHBACK ON sa.xsu_vmbc_response TO cbo;
GRANT FLASHBACK ON sa.xsu_vmbc_response TO clarify_user;
GRANT FLASHBACK ON sa.xsu_vmbc_response TO corecbo;
GRANT FLASHBACK ON sa.xsu_vmbc_response TO csrcbo;
GRANT FLASHBACK ON sa.xsu_vmbc_response TO role_sa_update;
GRANT FLASHBACK ON sa.xsu_vmbc_response TO soacbo;
GRANT FLASHBACK ON sa.xsu_vmbc_response TO webcbo;
GRANT INDEX ON sa.xsu_vmbc_response TO cbo;
GRANT INDEX ON sa.xsu_vmbc_response TO corecbo;
GRANT INDEX ON sa.xsu_vmbc_response TO csrcbo;
GRANT INDEX ON sa.xsu_vmbc_response TO soacbo;
GRANT INDEX ON sa.xsu_vmbc_response TO webcbo;
GRANT INSERT ON sa.xsu_vmbc_response TO cbo;
GRANT INSERT ON sa.xsu_vmbc_response TO clarify_user;
GRANT INSERT ON sa.xsu_vmbc_response TO corecbo;
GRANT INSERT ON sa.xsu_vmbc_response TO csrcbo;
GRANT INSERT ON sa.xsu_vmbc_response TO role_sa_update;
GRANT INSERT ON sa.xsu_vmbc_response TO soacbo;
GRANT INSERT ON sa.xsu_vmbc_response TO webcbo;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_response TO cbo;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_response TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_response TO corecbo;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_response TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_response TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_response TO soacbo;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_response TO webcbo;
GRANT QUERY REWRITE ON sa.xsu_vmbc_response TO cbo;
GRANT QUERY REWRITE ON sa.xsu_vmbc_response TO clarify_user;
GRANT QUERY REWRITE ON sa.xsu_vmbc_response TO corecbo;
GRANT QUERY REWRITE ON sa.xsu_vmbc_response TO csrcbo;
GRANT QUERY REWRITE ON sa.xsu_vmbc_response TO role_sa_update;
GRANT QUERY REWRITE ON sa.xsu_vmbc_response TO soacbo;
GRANT QUERY REWRITE ON sa.xsu_vmbc_response TO webcbo;
GRANT REFERENCES ON sa.xsu_vmbc_response TO cbo;
GRANT REFERENCES ON sa.xsu_vmbc_response TO corecbo;
GRANT REFERENCES ON sa.xsu_vmbc_response TO csrcbo;
GRANT REFERENCES ON sa.xsu_vmbc_response TO soacbo;
GRANT REFERENCES ON sa.xsu_vmbc_response TO webcbo;
GRANT SELECT ON sa.xsu_vmbc_response TO apex_sl_role;
GRANT SELECT ON sa.xsu_vmbc_response TO cbo;
GRANT SELECT ON sa.xsu_vmbc_response TO clarify_user;
GRANT SELECT ON sa.xsu_vmbc_response TO corecbo;
GRANT SELECT ON sa.xsu_vmbc_response TO csrcbo;
GRANT SELECT ON sa.xsu_vmbc_response TO dbit_mtoribiolopez;
GRANT SELECT ON sa.xsu_vmbc_response TO role_sa_select;
GRANT SELECT ON sa.xsu_vmbc_response TO role_sa_update;
GRANT SELECT ON sa.xsu_vmbc_response TO role_tf_select;
GRANT SELECT ON sa.xsu_vmbc_response TO select_role;
GRANT SELECT ON sa.xsu_vmbc_response TO soacbo;
GRANT SELECT ON sa.xsu_vmbc_response TO webcbo;
GRANT UPDATE ON sa.xsu_vmbc_response TO cbo;
GRANT UPDATE ON sa.xsu_vmbc_response TO clarify_user;
GRANT UPDATE ON sa.xsu_vmbc_response TO corecbo;
GRANT UPDATE ON sa.xsu_vmbc_response TO csrcbo;
GRANT UPDATE ON sa.xsu_vmbc_response TO role_sa_update;
GRANT UPDATE ON sa.xsu_vmbc_response TO soacbo;
GRANT UPDATE ON sa.xsu_vmbc_response TO webcbo;