GRANT DEBUG ON sa.xsu_solix_response_view TO cbo;
GRANT DEBUG ON sa.xsu_solix_response_view TO clarify_user;
GRANT DEBUG ON sa.xsu_solix_response_view TO csrcbo;
GRANT DEBUG ON sa.xsu_solix_response_view TO role_sa_update;
GRANT DEBUG ON sa.xsu_solix_response_view TO soacbo;
GRANT DEBUG ON sa.xsu_solix_response_view TO webcbo;
GRANT DELETE ON sa.xsu_solix_response_view TO cbo;
GRANT DELETE ON sa.xsu_solix_response_view TO clarify_user;
GRANT DELETE ON sa.xsu_solix_response_view TO csrcbo;
GRANT DELETE ON sa.xsu_solix_response_view TO role_sa_update;
GRANT DELETE ON sa.xsu_solix_response_view TO soacbo;
GRANT DELETE ON sa.xsu_solix_response_view TO webcbo;
GRANT FLASHBACK ON sa.xsu_solix_response_view TO cbo;
GRANT FLASHBACK ON sa.xsu_solix_response_view TO clarify_user;
GRANT FLASHBACK ON sa.xsu_solix_response_view TO csrcbo;
GRANT FLASHBACK ON sa.xsu_solix_response_view TO role_sa_update;
GRANT FLASHBACK ON sa.xsu_solix_response_view TO soacbo;
GRANT FLASHBACK ON sa.xsu_solix_response_view TO webcbo;
GRANT INSERT ON sa.xsu_solix_response_view TO cbo;
GRANT INSERT ON sa.xsu_solix_response_view TO clarify_user;
GRANT INSERT ON sa.xsu_solix_response_view TO csrcbo;
GRANT INSERT ON sa.xsu_solix_response_view TO role_sa_update;
GRANT INSERT ON sa.xsu_solix_response_view TO soacbo;
GRANT INSERT ON sa.xsu_solix_response_view TO webcbo;
GRANT MERGE VIEW ON sa.xsu_solix_response_view TO cbo;
GRANT MERGE VIEW ON sa.xsu_solix_response_view TO clarify_user;
GRANT MERGE VIEW ON sa.xsu_solix_response_view TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.xsu_solix_response_view TO cbo;
GRANT ON COMMIT REFRESH ON sa.xsu_solix_response_view TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.xsu_solix_response_view TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.xsu_solix_response_view TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.xsu_solix_response_view TO soacbo;
GRANT ON COMMIT REFRESH ON sa.xsu_solix_response_view TO webcbo;
GRANT QUERY REWRITE ON sa.xsu_solix_response_view TO cbo;
GRANT QUERY REWRITE ON sa.xsu_solix_response_view TO clarify_user;
GRANT QUERY REWRITE ON sa.xsu_solix_response_view TO csrcbo;
GRANT QUERY REWRITE ON sa.xsu_solix_response_view TO role_sa_update;
GRANT QUERY REWRITE ON sa.xsu_solix_response_view TO soacbo;
GRANT QUERY REWRITE ON sa.xsu_solix_response_view TO webcbo;
GRANT REFERENCES ON sa.xsu_solix_response_view TO cbo;
GRANT REFERENCES ON sa.xsu_solix_response_view TO csrcbo;
GRANT REFERENCES ON sa.xsu_solix_response_view TO soacbo;
GRANT REFERENCES ON sa.xsu_solix_response_view TO webcbo;
GRANT SELECT ON sa.xsu_solix_response_view TO apex_sl_role;
GRANT SELECT ON sa.xsu_solix_response_view TO cbo;
GRANT SELECT ON sa.xsu_solix_response_view TO clarify_user;
GRANT SELECT ON sa.xsu_solix_response_view TO csrcbo;
GRANT SELECT ON sa.xsu_solix_response_view TO dbit_mtoribiolopez;
GRANT SELECT ON sa.xsu_solix_response_view TO role_sa_select;
GRANT SELECT ON sa.xsu_solix_response_view TO role_sa_update;
GRANT SELECT ON sa.xsu_solix_response_view TO role_tf_select;
GRANT SELECT ON sa.xsu_solix_response_view TO soacbo;
GRANT SELECT ON sa.xsu_solix_response_view TO webcbo;
GRANT UPDATE ON sa.xsu_solix_response_view TO cbo;
GRANT UPDATE ON sa.xsu_solix_response_view TO clarify_user;
GRANT UPDATE ON sa.xsu_solix_response_view TO csrcbo;
GRANT UPDATE ON sa.xsu_solix_response_view TO role_sa_update;
GRANT UPDATE ON sa.xsu_solix_response_view TO soacbo;
GRANT UPDATE ON sa.xsu_solix_response_view TO webcbo;