GRANT ALTER ON sa.xsu_vmbc_request TO cbo;
GRANT ALTER ON sa.xsu_vmbc_request TO clarify_user;
GRANT ALTER ON sa.xsu_vmbc_request TO corecbo;
GRANT ALTER ON sa.xsu_vmbc_request TO csrcbo;
GRANT ALTER ON sa.xsu_vmbc_request TO role_sa_update;
GRANT ALTER ON sa.xsu_vmbc_request TO soacbo;
GRANT ALTER ON sa.xsu_vmbc_request TO webcbo;
GRANT DEBUG ON sa.xsu_vmbc_request TO cbo;
GRANT DEBUG ON sa.xsu_vmbc_request TO clarify_user;
GRANT DEBUG ON sa.xsu_vmbc_request TO corecbo;
GRANT DEBUG ON sa.xsu_vmbc_request TO csrcbo;
GRANT DEBUG ON sa.xsu_vmbc_request TO role_sa_update;
GRANT DEBUG ON sa.xsu_vmbc_request TO soacbo;
GRANT DEBUG ON sa.xsu_vmbc_request TO webcbo;
GRANT DELETE ON sa.xsu_vmbc_request TO cbo;
GRANT DELETE ON sa.xsu_vmbc_request TO clarify_user;
GRANT DELETE ON sa.xsu_vmbc_request TO corecbo;
GRANT DELETE ON sa.xsu_vmbc_request TO csrcbo;
GRANT DELETE ON sa.xsu_vmbc_request TO dbbu_mbharambe;
GRANT DELETE ON sa.xsu_vmbc_request TO role_sa_update;
GRANT DELETE ON sa.xsu_vmbc_request TO soacbo;
GRANT DELETE ON sa.xsu_vmbc_request TO webcbo;
GRANT FLASHBACK ON sa.xsu_vmbc_request TO cbo;
GRANT FLASHBACK ON sa.xsu_vmbc_request TO clarify_user;
GRANT FLASHBACK ON sa.xsu_vmbc_request TO corecbo;
GRANT FLASHBACK ON sa.xsu_vmbc_request TO csrcbo;
GRANT FLASHBACK ON sa.xsu_vmbc_request TO role_sa_update;
GRANT FLASHBACK ON sa.xsu_vmbc_request TO soacbo;
GRANT FLASHBACK ON sa.xsu_vmbc_request TO webcbo;
GRANT INDEX ON sa.xsu_vmbc_request TO cbo;
GRANT INDEX ON sa.xsu_vmbc_request TO corecbo;
GRANT INDEX ON sa.xsu_vmbc_request TO csrcbo;
GRANT INDEX ON sa.xsu_vmbc_request TO soacbo;
GRANT INDEX ON sa.xsu_vmbc_request TO webcbo;
GRANT INSERT ON sa.xsu_vmbc_request TO cbo;
GRANT INSERT ON sa.xsu_vmbc_request TO clarify_user;
GRANT INSERT ON sa.xsu_vmbc_request TO corecbo;
GRANT INSERT ON sa.xsu_vmbc_request TO csrcbo;
GRANT INSERT ON sa.xsu_vmbc_request TO dbbu_mbharambe;
GRANT INSERT ON sa.xsu_vmbc_request TO role_sa_update;
GRANT INSERT ON sa.xsu_vmbc_request TO soacbo;
GRANT INSERT ON sa.xsu_vmbc_request TO webcbo;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_request TO cbo;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_request TO clarify_user;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_request TO corecbo;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_request TO csrcbo;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_request TO role_sa_update;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_request TO soacbo;
GRANT ON COMMIT REFRESH ON sa.xsu_vmbc_request TO webcbo;
GRANT QUERY REWRITE ON sa.xsu_vmbc_request TO cbo;
GRANT QUERY REWRITE ON sa.xsu_vmbc_request TO clarify_user;
GRANT QUERY REWRITE ON sa.xsu_vmbc_request TO corecbo;
GRANT QUERY REWRITE ON sa.xsu_vmbc_request TO csrcbo;
GRANT QUERY REWRITE ON sa.xsu_vmbc_request TO role_sa_update;
GRANT QUERY REWRITE ON sa.xsu_vmbc_request TO soacbo;
GRANT QUERY REWRITE ON sa.xsu_vmbc_request TO webcbo;
GRANT REFERENCES ON sa.xsu_vmbc_request TO cbo;
GRANT REFERENCES ON sa.xsu_vmbc_request TO corecbo;
GRANT REFERENCES ON sa.xsu_vmbc_request TO csrcbo;
GRANT REFERENCES ON sa.xsu_vmbc_request TO soacbo;
GRANT REFERENCES ON sa.xsu_vmbc_request TO webcbo;
GRANT SELECT ON sa.xsu_vmbc_request TO apex_sl_role;
GRANT SELECT ON sa.xsu_vmbc_request TO cbo;
GRANT SELECT ON sa.xsu_vmbc_request TO clarify_user;
GRANT SELECT ON sa.xsu_vmbc_request TO corecbo;
GRANT SELECT ON sa.xsu_vmbc_request TO csrcbo;
GRANT SELECT ON sa.xsu_vmbc_request TO dbit_mtoribiolopez;
GRANT SELECT ON sa.xsu_vmbc_request TO role_sa_select;
GRANT SELECT ON sa.xsu_vmbc_request TO role_sa_update;
GRANT SELECT ON sa.xsu_vmbc_request TO role_sqa_tester;
GRANT SELECT ON sa.xsu_vmbc_request TO role_tf_select;
GRANT SELECT ON sa.xsu_vmbc_request TO select_role;
GRANT SELECT ON sa.xsu_vmbc_request TO soacbo;
GRANT SELECT ON sa.xsu_vmbc_request TO webcbo;
GRANT UPDATE ON sa.xsu_vmbc_request TO cbo;
GRANT UPDATE ON sa.xsu_vmbc_request TO clarify_user;
GRANT UPDATE ON sa.xsu_vmbc_request TO corecbo;
GRANT UPDATE ON sa.xsu_vmbc_request TO csrcbo;
GRANT UPDATE ON sa.xsu_vmbc_request TO dbbu_mbharambe;
GRANT UPDATE ON sa.xsu_vmbc_request TO role_sa_update;
GRANT UPDATE ON sa.xsu_vmbc_request TO soacbo;
GRANT UPDATE ON sa.xsu_vmbc_request TO webcbo;