GRANT DELETE ON sa.zip2tech_final TO role_sa_update;
GRANT INSERT ON sa.zip2tech_final TO role_sa_update;
GRANT SELECT ON sa.zip2tech_final TO dbit_mtoribiolopez;
GRANT SELECT ON sa.zip2tech_final TO role_sa_select;
GRANT SELECT ON sa.zip2tech_final TO role_sa_update;
GRANT SELECT ON sa.zip2tech_final TO role_tf_select;
GRANT SELECT ON sa.zip2tech_final TO select_no_pin;
GRANT SELECT ON sa.zip2tech_final TO select_role;
GRANT UPDATE ON sa.zip2tech_final TO role_sa_update;