CREATE OR REPLACE PACKAGE BODY sa.TFSOA_NTFY_LOGGING_PKG IS

PROCEDURE TF_PROCESS_FAILURE(
          p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
          p_NTFY_DB_OUTPUT_TYPE  OUT      TF_NTFY_DB_OUTPUT_TYPE) IS

BEGIN
 sa.TFSOA_NTFY_CORE_LOGGING_PKG.TF_STOREFORBATCHPROCESSING(p_NTFY_DB_INPUT_TYPE,p_NTFY_DB_OUTPUT_TYPE);
END  TF_PROCESS_FAILURE;


PROCEDURE TF_PROCESS_EXCEPTION(
          p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
          p_NTFY_DB_OUTPUT_TYPE  OUT      TF_NTFY_DB_OUTPUT_TYPE) IS
BEGIN
  sa.TFSOA_NTFY_CORE_LOGGING_PKG.TF_UPDATELOGENTRY(p_NTFY_DB_INPUT_TYPE,p_NTFY_DB_OUTPUT_TYPE);
END  TF_PROCESS_EXCEPTION;

PROCEDURE  TF_PROCESS_DISCARD(
           p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
           p_NTFY_DB_OUTPUT_TYPE  OUT      TF_NTFY_DB_OUTPUT_TYPE) IS
           BEGIN
sa.TFSOA_NTFY_CORE_LOGGING_PKG.TF_UPDATELOGENTRY(p_NTFY_DB_INPUT_TYPE,p_NTFY_DB_OUTPUT_TYPE);
sa.TFSOA_NTFY_CORE_LOGGING_PKG.TF_CREATEBILLINGLOGENTRY(p_NTFY_DB_INPUT_TYPE,p_NTFY_DB_OUTPUT_TYPE);
END  TF_PROCESS_DISCARD;


PROCEDURE TF_PROCESS_SUCCESS (
           p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
           p_NTFY_DB_OUTPUT_TYPE  OUT TF_NTFY_DB_OUTPUT_TYPE) IS
BEGIN

IF upper(p_NTFY_DB_INPUT_TYPE.p_channel_type) = 'EMAIL' THEN
    sa.TFSOA_NTFY_CORE_LOGGING_PKG.TF_STOREFORDELIVERYSTATUS(p_NTFY_DB_INPUT_TYPE,p_NTFY_DB_OUTPUT_TYPE);
 END IF;
    sa.TFSOA_NTFY_CORE_LOGGING_PKG.TF_UPDATELOGENTRY(p_NTFY_DB_INPUT_TYPE,p_NTFY_DB_OUTPUT_TYPE);
    sa.TFSOA_NTFY_CORE_LOGGING_PKG.TF_CREATEBILLINGLOGENTRY(p_NTFY_DB_INPUT_TYPE,p_NTFY_DB_OUTPUT_TYPE);

END  TF_PROCESS_SUCCESS;

END TFSOA_NTFY_LOGGING_PKG;
/