CREATE OR REPLACE PACKAGE sa."APEX_CREATE_FLASH_BATCH" AS
  TYPE SPLIT_TBL_TY IS TABLE OF VARCHAR2(500);
  PROCEDURE LOAD_FILE (P_USER VARCHAR2) ;
  PROCEDURE LOAD_FILE_EXPIRE (P_USER VARCHAR2);
  PROCEDURE CREATE_FLASH (P_USER IN VARCHAR2, P_EXP_DT IN NUMBER, P_FLASH_TEXT IN VARCHAR2, P_START_DATE IN VARCHAR2, P_END_DATE IN VARCHAR2, P_TITLE IN VARCHAR2, MSG OUT VARCHAR2);
  PROCEDURE EXPIRE_FLASH (P_USER IN VARCHAR2);
  PROCEDURE VALIDATE_USER(P_USER IN VARCHAR2, P_PWD IN VARCHAR2, P_PRIV OUT VARCHAR2, P_MSG OUT VARCHAR2, P_SUCCESS OUT NUMBER);

END;-- APEX_CREATE_FLASH_BATCH;
/