CREATE OR REPLACE PACKAGE sa."APEX_LOAD_ICCID_BATCH" AS
  TYPE SPLIT_TBL_TY IS TABLE OF VARCHAR2(500);
  PROCEDURE LOAD_FILE (P_USER IN VARCHAR2, P_SD IN VARCHAR2, P_MNC  IN VARCHAR2, P_PO IN VARCHAR2, P_PART IN VARCHAR2,P_LTE IN NUMBER) ;
  PROCEDURE INSERT_ICCID (P_USER IN VARCHAR2,  P_SD IN VARCHAR2, P_MNC IN VARCHAR2, P_PO IN VARCHAR2, P_PART IN VARCHAR2, P_LTE IN NUMBER, P_MESSAGE OUT VARCHAR2, P_COUNT OUT NUMBER);
  PROCEDURE VALIDATE_USER(P_USER IN VARCHAR2, P_PWD IN VARCHAR2, P_PRIV OUT VARCHAR2, P_MSG OUT VARCHAR2, P_SUCCESS OUT NUMBER);

END;-- APEX_LOAD_ICCID_BATCH
/