CREATE OR REPLACE PACKAGE sa.B2B_PROMOTION_PKG AS
  FUNCTION FN_CHECK_B2B_PROMO_BY_ORG
    (
      IP_ESN              IN sa.X_PROGRAM_ENROLLED.X_ESN%TYPE
      , IP_PROMO_OBJID    IN sa.TABLE_X_PROMOTION.OBJID%TYPE
    )
    RETURN NUMBER;
  PROCEDURE SP_INSERT_X_B2B_PROMO_ORG
		(
      IP_COMMERCE_ID		IN	sa.X_B2B_PROMO_ORG.X_COMMERCE_ID%TYPE
      , IP_PROMO_CODE		IN	sa.X_B2B_PROMO_ORG.X_PROMO_CODE%TYPE
      , IP_X_START_DATE	IN	sa.X_B2B_PROMO_ORG.X_START_DATE%TYPE
      , IP_X_END_DATE		IN	sa.X_B2B_PROMO_ORG.X_END_DATE%TYPE
      , IP_USER_CREATED	IN	sa.X_B2B_PROMO_ORG.USER_CREATED%TYPE
      , OP_ERROR_CODE     OUT NUMBER
      , OP_ERROR_MSG      OUT VARCHAR2
    );
END B2B_PROMOTION_PKG;
/