CREATE OR REPLACE PACKAGE sa.GENCODES_PKG IS
  user_exception       EXCEPTION;
  PROCEDURE INSERT_X_GENCODES_BRKD_HDR
    (
    IP_ESN                        			IN  sa.X_GENCODES_BREAKDOWN_HEADER.X_ESN%TYPE
    ,IP_CONFIG_ID                 			IN  sa.X_GENCODES_BREAKDOWN_HEADER.X_CONFIG_ID%TYPE
    ,IP_STATUS                    			IN  sa.X_GENCODES_BREAKDOWN_HEADER.X_STATUS%TYPE
    ,IP_IDN_USER_CREATED          			IN  sa.X_GENCODES_BREAKDOWN_HEADER.X_IDN_USER_CREATED%TYPE
    ,OP_GENCODES_B_HDR_OBJID	  			  OUT  sa.X_GENCODES_BREAKDOWN_HEADER.OBJID%TYPE
    ,OP_STATUS_CODE               			OUT  VARCHAR2
    ,OP_STATUS_MESSAGE            			OUT  VARCHAR2
    );
  PROCEDURE UPDATE_X_GENCODES_BRKD_HDR
    (
    IP_ESN                        			IN  sa.X_GENCODES_BREAKDOWN_HEADER.X_ESN%TYPE
    ,IP_CONFIG_ID                 			IN  sa.X_GENCODES_BREAKDOWN_HEADER.X_CONFIG_ID%TYPE
    ,IP_STATUS                    			IN  sa.X_GENCODES_BREAKDOWN_HEADER.X_STATUS%TYPE
    ,IP_IDN_USER_CHANGE_LAST      			IN  sa.X_GENCODES_BREAKDOWN_HEADER.X_IDN_USER_CHANGE_LAST%TYPE
    ,OP_STATUS_CODE               			OUT  VARCHAR2
    ,OP_STATUS_MESSAGE            			OUT  VARCHAR2
    );
  PROCEDURE INSERT_X_GENCODES_BRKD_DTL
    (
    IP_DTL_2_GENCODE_HDR_OBJID            	IN  sa.X_GENCODES_BREAKDOWN_DETAILS.X_DETAILS_2_GENCODES_HDR_OBJID%TYPE
    ,IP_CMD_NAME                          	IN  sa.X_GENCODES_BREAKDOWN_DETAILS.X_CMD_NAME%TYPE
    ,IP_CMD_STATUS                        	IN  sa.X_GENCODES_BREAKDOWN_DETAILS.X_CMD_STATUS%TYPE
    ,IP_IDN_USER_CREATED                  	IN  sa.X_GENCODES_BREAKDOWN_DETAILS.X_IDN_USER_CREATED%TYPE
    ,OP_GENCODES_B_DTL_OBJID	  			      OUT  sa.X_GENCODES_BREAKDOWN_DETAILS.OBJID%TYPE
    ,OP_STATUS_CODE                       	OUT  VARCHAR2
    ,OP_STATUS_MESSAGE                    	OUT  VARCHAR2
    );
  PROCEDURE UPDATE_X_GENCODES_BRKD_DTL
    (
    IP_DTL_2_GENCODE_HDR_OBJID            	IN  sa.X_GENCODES_BREAKDOWN_DETAILS.X_DETAILS_2_GENCODES_HDR_OBJID%TYPE
    ,IP_CMD_NAME                          	IN  sa.X_GENCODES_BREAKDOWN_DETAILS.X_CMD_NAME%TYPE
    ,IP_CMD_STATUS                        	IN  sa.X_GENCODES_BREAKDOWN_DETAILS.X_CMD_STATUS%TYPE
    ,IP_IDN_USER_CHANGE_LAST              	IN  sa.X_GENCODES_BREAKDOWN_DETAILS.X_IDN_USER_CHANGE_LAST%TYPE
    ,OP_STATUS_CODE                       	OUT  VARCHAR2
    ,OP_STATUS_MESSAGE                    	OUT  VARCHAR2
    );
END GENCODES_PKG;
/