CREATE OR REPLACE PACKAGE sa."OTA_SEND_LAST_ACK_SPEC_PKG" IS

	/************************************************************************************************|
	|    Copyright   Tracfone  Wireless Inc. All rights reserved                          	         |
	|                                                                                          	 |
	| NAME     :       OTA_SEND_LAST_ACK_SPEC_PKG  package                        	 		 |
	| PURPOSE  :       										 |
	| FREQUENCY:                                                                               	 |
	| PLATFORMS:    										 |
	|                                                                                          	 |
	| REVISIONS:                                                                               	 |
	| VERSION  DATE        WHO              PURPOSE                                         	 |
	| -------  ---------- -----             ------------------------------------------------------	 |
	| 1.0      03/11/05   Novak Lalovic     Initial revision                            		 |
	| 1.1	   03/23/05   Novak Lalovic     Added stored procedure get_resend_psms_codes		 |
	| 1.2	   03/24/05   Novak Lalovic	Added copyright and revision version info to this file   |
	| 1.3	   03/24/05   Novak Lalovic	Removed Show err and EXIT statements from the bottom of  |
	|					the file   						 |
	| 1.4	   03/24/05   Novak Lalovic	Adjusting PCVS and file version numbers to be the same   |
	|************************************************************************************************/

	/*********************************************************************************************
	| GET_OTA_PENDING_TRANS procedure is used by batch process (Java scheduled job)
	| to return a recordset (REF cursor) of all OTA PENDING transactions
	| that were created in database for the time period which is less
	| then SYSDATE minus time specified in the input parameter p_time_period_in.
	| This procedure executes the stored function OTA_EXTPROC_PKG.get_last_sent_ack_func
	| to get the DLL codes to be sent to the phones.
	| For each valid record, the codes will be sent by the Java program
	| in form of the OTA psms message. The phone will respond and send
	| MO psms message (the last ack) to us, which we will process as a regular OTA acknowledgment.
	| If OTA_EXTPROC_PKG.get_last_sent_ack_func is unable to get the
	| codes from DLL for any reason, it will return an error message
	| string and it will also insert one record into ERRORS table.
	| Java program will ignore this record because there are no valid
	| psms codes to send to the phone.
	| The whole functionality is designed to get the last OTA acknowledgment
	| generated by the phone that got lost and never received by Tracfone and close transactions
	| that are still OTA PENDING.
	**********************************************************************************************/
	PROCEDURE get_ota_pending_trans  (p_action_type_in		IN VARCHAR2
					, p_time_period_in		IN NUMBER -- number of minutes
					, p_query_results_out	OUT ota_extproc_pkg.REF_CUR_TYPE);

	/*********************************************************************************************
	| GET_RESEND_PSMS_CODES procedure is used by batch process (Java scheduled job)
	| to return a recordset (REF cursor) of all OTA PENDING transactions.
	| These transactions also must have a record in TABLE_X_OTA_TRANS_DTL with action type 269.
	| Action type 269 record is created when we requested last sent acknowledgment from the phone.
	| If the phone didn't respond and didn't send us the last acknowledgment, then we are going to
	| send the same codes that we originaly sent in our first attempt (redemption or activation codes).
	| For each record, the codes will be sent by the Java program
	| in the form of the OTA psms message.
	| The whole functionality is designed to resend the codes to the phone after the attempt
	| to receive the last acknowledgment from the phone failed.
	**********************************************************************************************/
	PROCEDURE get_resend_psms_codes  (p_action_type_in		IN VARCHAR2
					, p_time_period_in		IN NUMBER -- number of minutes
					, p_query_results_out	OUT ota_extproc_pkg.REF_CUR_TYPE);

END;
/