CREATE OR REPLACE PACKAGE sa.process_web_enrollment_pkg IS
-- Pre Payment Procs start
PROCEDURE p_get_enrollment_details ( i_esn              IN  VARCHAR2 ,
                                     i_program_param_id IN  NUMBER   ,
                                     i_language         IN  VARCHAR2 ,
                                     o_enrl_objid       OUT NUMBER   ,
                                     o_enrl_status      OUT VARCHAR2 ,
                                     o_code_num         OUT VARCHAR2 ,
                                     o_code_desc        OUT VARCHAR2 ,
                                     o_pb_error_code    OUT NUMBER   ,
                                     o_pb_error_msg     OUT VARCHAR2 ,
                                     o_error_code       OUT NUMBER   ,
                                     o_error_msg        OUT VARCHAR2 );
--
PROCEDURE p_get_purch_error_code ( i_application   IN  VARCHAR2 ,
	                               i_code_type     IN  VARCHAR2 ,
	                               i_code_value    IN  VARCHAR2 ,
	                               i_language      IN  VARCHAR2 ,
	                               o_code_num      OUT VARCHAR2 ,
	                               o_code_desc     OUT VARCHAR2 ,
	                               o_error_code    OUT NUMBER   ,
	                               o_error_msg     OUT VARCHAR2 );
--
PROCEDURE p_insert_program_purch_dtl ( i_esn               IN  VARCHAR2 ,
	                                   i_charge_amount     IN  NUMBER   ,
	                                   i_charge_desc       IN  VARCHAR2 ,
	                                   i_next_charge_date  IN  DATE     ,
	                                   i_program_enroll_id IN  NUMBER   ,
	                                   i_purch_hdr_id      IN  NUMBER   ,
	                                   i_combs_tax_amount  IN  NUMBER   ,
	                                   i_e911_tax_amount   IN  NUMBER   ,
	                                   i_usf_tax_amount    IN  NUMBER   ,
	                                   i_rcrf_tax_amount   IN  NUMBER   ,
	                                   o_error_code        OUT NUMBER   ,
	                                   o_error_msg         OUT VARCHAR2 );
--
PROCEDURE p_get_program_details ( i_program_param_id 	 IN  NUMBER              ,
	                              o_program_details_tab  OUT program_details_tab ,
	                              o_error_code           OUT NUMBER              ,
	                              o_error_msg            OUT VARCHAR2             );
--
PROCEDURE p_insert_program_enrolled ( i_esn               	  IN  VARCHAR2 ,
	                                  i_program_param_id 	  IN  NUMBER   ,
	                                  i_program_type      	  IN  VARCHAR2 ,
	                                  i_next_charge_date  	  IN  DATE     ,
	                                  i_enrl_reason       	  IN  VARCHAR2 ,
	                                  i_action_type			  IN  VARCHAR2 ,
	                                  i_action_txt			  IN  VARCHAR2 ,
	                                  i_web_user_id			  IN  NUMBER   ,
	                                  i_payment_src_id		  IN  NUMBER   ,
	                                  i_purch_hdr_id      	  IN  NUMBER   ,
	                                  i_promo_objid       	  IN  NUMBER   ,
	                                  i_agent_name  		  IN  VARCHAR2 ,
	                                  i_bus_org   			  IN  VARCHAR2 ,
	                                  i_source_system    	  IN  VARCHAR2 ,
	                                  i_language      		  IN  VARCHAR2 ,
	                                  o_program_name		  OUT VARCHAR2 ,
	                                  o_prog_enrl_id		  OUT NUMBER   ,
	                                  o_prog_trans_id		  OUT NUMBER   ,
	                                  o_prog_charge_freq	  OUT VARCHAR2 ,
	                                  o_prog_cycle_start_date OUT DATE     ,
	                                  o_prog_cycle_end_date	  OUT DATE     ,
	                                  o_prog_enrollmt_fee	  OUT NUMBER   ,
	                                  o_prog_monthly_fee	  OUT NUMBER   ,
	                                  o_prog_is_recurring	  OUT VARCHAR2 ,
	                                  o_error_code        	  OUT NUMBER   ,
	                                  o_error_msg         	  OUT VARCHAR2 );
--
PROCEDURE p_insert_pre_payment_details ( i_esn				  IN  VARCHAR2 ,
	                                     i_payment_src_id     IN  NUMBER   ,
	                                     i_program_type       IN  VARCHAR2 ,
	                                     i_payment_type		  IN  VARCHAR2 ,
	                                     i_agent_name         IN  VARCHAR2 ,
	                                     i_agent_recogn       IN  VARCHAR2 ,
	                                     i_web_user_id        IN  NUMBER   ,
	                                     i_cust_hostname      IN  VARCHAR2 ,
	                                     i_cust_ipaddress     IN  VARCHAR2 ,
	                                     i_purch_hdr2cr_purch IN  VARCHAR2 ,
	                                     i_amount	  		  IN  NUMBER   ,
	                                     i_combs_tax_amount	  IN  NUMBER   ,
	                                     i_e911_tax_amount 	  IN  NUMBER   ,
	                                     i_usf_tax_amount 	  IN  NUMBER   ,
	                                     i_rcrf_tax_amount	  IN  NUMBER   ,
	                                     i_discount_amount	  IN  NUMBER   ,
	                                     i_bus_org            IN  VARCHAR2 ,
	                                     i_source_system      IN  VARCHAR2 ,
	                                     i_language           IN  VARCHAR2 ,
	                                     o_purch_hdr_id	      OUT NUMBER   ,
	                                     o_error_code         OUT NUMBER   ,
	                                     o_error_msg          OUT VARCHAR2 );
--
PROCEDURE p_update_program_enrolled ( i_esn					  IN  VARCHAR2 ,
	                                  i_program_enroll_id     IN  NUMBER   ,
	                                  i_program_param_id      IN  NUMBER   ,
	                                  i_next_charge_date      IN  DATE         DEFAULT NULL,
	                                  i_enrl_reason           IN  VARCHAR2 ,
	                                  i_action_type           IN  VARCHAR2 ,
	                                  i_action_txt            IN  VARCHAR2 ,
	                                  i_web_user_id           IN  NUMBER   ,
	                                  i_payment_src_id        IN  NUMBER   ,
	                                  i_promo_objid           IN  NUMBER   ,
	                                  i_agent_name            IN  VARCHAR2 ,
	                                  i_bus_org               IN  VARCHAR2 ,
	                                  i_source_system         IN  VARCHAR2 ,
	                                  i_language              IN  VARCHAR2 ,
	                                  o_prog_charge_freq	  OUT VARCHAR2 ,
	                                  o_prog_cycle_start_date OUT DATE     ,
	                                  o_prog_cycle_end_date   OUT DATE     ,
	                                  o_prog_enrollmt_fee     OUT NUMBER   ,
	                                  o_prog_monthly_fee      OUT NUMBER   ,
	                                  o_prog_is_recurring     OUT VARCHAR2 ,
	                                  o_error_code            OUT NUMBER   ,
	                                  o_error_msg             OUT VARCHAR2 );
-- Pre Payment Procs end
-- Post Payment procs Start
PROCEDURE p_insert_enrol_log_details ( i_esn 			IN	VARCHAR2 ,
	                                   i_program_name 	IN  VARCHAR2 ,
	                                   i_log_title  	IN  VARCHAR2 ,
	                                   i_log_details 	IN 	VARCHAR2 ,
	                                   i_web_user_id 	IN 	NUMBER   ,
	                                   i_agent_name		IN  VARCHAR2 ,
	                                   i_source_system	IN  VARCHAR2 ,
	                                   o_error_code     OUT NUMBER   ,
	                                   o_error_msg      OUT VARCHAR2 );
--
PROCEDURE p_update_enrol_details_error ( i_esn 			 	  IN	VARCHAR2 ,
	                                     i_program_enroll_id  IN 	NUMBER   ,
	                                     i_program_param_id	  IN 	NUMBER   ,
	                                     i_purch_hdr_id		  IN 	NUMBER   ,
	                                     i_web_user_id		  IN 	NUMBER   ,
	                                     i_enroll_status      IN    VARCHAR2 ,
	                                     o_error_code         OUT   NUMBER   ,
	                                     o_error_msg          OUT   VARCHAR2 );
--
PROCEDURE p_update_enrol_details_success ( i_esn				IN  VARCHAR2 ,
	                                       i_program_enroll_id	IN  NUMBER   ,
	                                       i_prog_trans_id      IN  NUMBER   ,
	                                       i_next_exp_date      IN  DATE     ,
	                                       i_dealer_id			IN  VARCHAR2 ,
	                                       i_bus_org            IN  VARCHAR2 ,
	                                       o_error_code		    OUT NUMBER   ,
	                                       o_error_msg			OUT VARCHAR2 );
--
PROCEDURE p_update_post_paymnt_details ( i_purch_hdr_id			  IN  NUMBER   ,
	                                     i_enrl_op_status         IN  VARCHAR2 ,
	                                     i_request_id             IN  VARCHAR2 ,
	                                     i_avs                    IN  VARCHAR2 ,
	                                     i_ics_rcode              IN  VARCHAR2 ,
	                                     i_ics_rflag              IN  VARCHAR2 ,
	                                     i_ics_rmsg	              IN  VARCHAR2 ,
	                                     i_auth_request_id		  IN  VARCHAR2 ,
	                                     i_auth_auth_code		  IN  VARCHAR2 ,
	                                     i_auth_auth_avs	      IN  VARCHAR2 ,
	                                     i_auth_auth_response	  IN  VARCHAR2 ,
	                                     i_auth_auth_time         IN  VARCHAR2 ,
	                                     i_auth_rcode             IN  NUMBER   ,
	                                     i_auth_rflag             IN  VARCHAR2 ,
	                                     i_auth_rmsg              IN  VARCHAR2 ,
	                                     i_bill_bill_request_time IN  VARCHAR2 ,
	                                     i_bill_rcode             IN  NUMBER   ,
	                                     i_bill_rmsg              IN  VARCHAR2 ,
	                                     i_bill_rflag             IN  VARCHAR2 ,
	                                     i_bill_trans_ref_no	  IN  VARCHAR2 ,
	                                     i_auth_auth_amount       IN  NUMBER   ,
	                                     i_bill_bill_amount       IN  NUMBER   ,
	                                     i_auth_cv_result	      IN  VARCHAR2 ,
	                                     i_score_factors	      IN  VARCHAR2 ,
	                                     i_score_host_severity	  IN  VARCHAR2 ,
	                                     i_score_rcode	          IN  NUMBER   ,
	                                     i_score_rflag	          IN  VARCHAR2 ,
	                                     i_score_rmsg	          IN  VARCHAR2 ,
	                                     i_score_score_result	  IN  VARCHAR2 ,
	                                     i_score_time_local       IN  VARCHAR2 ,
	                                     o_num_rows				  OUT NUMBER   ,
	                                     o_error_code             OUT NUMBER   ,
	                                     o_error_msg              OUT VARCHAR2 );
-- Post Payment Procs end
END process_web_enrollment_pkg;
-- ANTHILL_TEST PLSQL/SA/Packages/process_web_enrollment_pkg.sql 	CR55214: 1.7
/