CREATE OR REPLACE PACKAGE sa.RESET_PASSWORD AS

    PROCEDURE CREATE_PASSWORD (L_NAME IN VARCHAR2, PIN IN VARCHAR2, V_CODE OUT NUMBER,V_CODE_MSG OUT VARCHAR2, V_PASSWD OUT VARCHAR2);
    PROCEDURE RESET_PASSWD (L_NAME VARCHAR2, V_ENC_PASSWD VARCHAR2, V_CODE OUT NUMBER,V_CODE_MSG OUT VARCHAR2);

END RESET_PASSWORD; 
/