CREATE OR REPLACE PACKAGE sa.REWARD_BENEFITS_N_VOUCHERS_PKG AS
/*
 CR32367
 Start date: 10-Mar-2015
*/
/*
 TYPE TYP_REWARD_BENEFITS IS RECORD (
 BENEFIT_ID NUMBER ---Table_x_benefits.objid
 ,BENEFIT_TYPE VARCHAR2(100) ---"REWARD_BENEFITS"
 ,BENEFIT_PROGRAM_NAME VARCHAR2(100) ---"UPGRADE_PLANS"
 ,BENEFIT_PROGRAM_OBJID NUMBER ---TABLE_X_BENEFIT_PROGRAMS.objid - lookup table objid
 ,BENEFIT_UNIT VARCHAR2(100) ---"DOLLARS"
 ,BENEFIT_VALUE VARCHAR2(100) ---"300" OR "200"
 ,PARTIAL_USAGE_ALLOWED VARCHAR2(1) ---"N" { Y | N }
 ,PURCH_USAGE_ALLOWED VARCHAR2(100) ---"DEVICE_ONLY"
 );

 TYPE REWARD_BENEFITS_TAB IS TABLE OF TYP_REWARD_BENEFITS
 ;

 TYPE TYP_REWARD_VOUCHERS IS RECORD (
 VOUCHER_ID VARCHAR2(50) ---table_x_vouchers.objid
 ,BENEFIT_ID NUMBER ---Table_x_benefits.objid
 ,BENEFIT_TYPE VARCHAR2(100) ---"REWARD_BENEFITS"
 ,BENEFIT_PROGRAM_NAME VARCHAR2(100) ---"UPGRADE_PLANS"
 ,BENEFIT_PROGRAM_OBJID NUMBER 			 ---TABLE_X_BENEFIT_PROGRAMS.objid - lookup table objid
 ,BENEFIT_UNIT VARCHAR2(100) ---"DOLLARS"
 ,BENEFIT_VALUE VARCHAR2(100) ---"300" OR "200"
 ,PARTIAL_USAGE_ALLOWED VARCHAR2(1) ---"N"
 ,PURCH_USAGE_ALLOWED VARCHAR2(100) ---"DEVICE_ONLY"
 );

 TYPE REWARD_VOUCHERS_TAB IS TABLE OF TYP_REWARD_VOUCHERS ;

 TYPE TYP_VOUCHER_ORDER IS RECORD (
 ORDER_ID VARCHAR2(50)
 ,ORDER_DATE DATE
 ,ORDER_SOURCE VARCHAR2(50)
 ,CUSTOMER_NAME VARCHAR2(200)
 ,CUSTOMER_ACCOUNT_ID VARCHAR2(200)
 ,CUSTOMER_MIN VARCHAR2(30)
 ,ORDER_AMOUNT NUMBER		 --the order amount (thats device cost + taxes etc)
 ,X_BENEFIT_AMOUNT NUMBER --actual benefit amount that has been used
 ,TAX_TOTAL NUMBER
 ,TAX_SALES NUMBER
 ,TAX_SALES_RATE NUMBER
 ,TAX_E911 NUMBER
 ,TAX_E911_RATE NUMBER
 ,TAX_USF NUMBER
 ,TAX_USF_RATE NUMBER
 ,TAX_RCRF NUMBER
 ,TAX_RCRF_RATE NUMBER
 ,SHIPPING_ADDRESS VARCHAR2(500)
 ,SHIPPING_AMOUNT NUMBER
 ,SHIPPING_METHOD VARCHAR2(500)
 );
 ---TYPE TYP_ORDER_INFO_TAB IS TABLE OF TYP_VOUCHER_ORDERS;

 TYPE TYP_VOUCHER_ORDER_DETAILS IS RECORD (
 ORDER_ID VARCHAR2(30)
 ,X_DESCRIPTION VARCHAR2(500)
 ,X_TYPE VARCHAR2(50)
 ,X_BRAND VARCHAR2(100)
 ,X_PART_NUMBER VARCHAR2(50)
 ,X_PART_SERIAL VARCHAR2(50)
 ,X_QUANTITY NUMBER
 ,X_MARKET_PRICE NUMBER
 ,X_SOLD_PRICE NUMBER
 );
 TYPE TYP_ORDER_DETAILS_TAB IS TABLE OF TYP_VOUCHER_ORDER_DETAILS ;

 TYPE TYP_VOUCHERS_ID_TAB IS TABLE OF VARCHAR2(50);
*/

 PROCEDURE P_GET_SUBSCRIBER_ID (
 IN_KEY IN VARCHAR2
 ,IN_VALUE IN VARCHAR2
 ,OUT_SUBSCRIBER_ID OUT VARCHAR2
 ,OUT_ERR_CODE OUT NUMBER
 ,OUT_ERR_MSG OUT VARCHAR2
 );

 PROCEDURE P_GET_REWARD_BENEFITS (
 IN_KEY IN VARCHAR2
 ,IN_VALUE IN VARCHAR2
 ,IN_PROGRAM_NAME IN VARCHAR2 -- "UPGRADE_PLANS"
 ,IN_BENEFIT_TYPE IN VARCHAR2 -- "REWARD_BENEFITS"
 ,OUT_REWARD_BENEFITS_LIST OUT sa.REWARD_BENEFITS_TAB
 ,OUT_ERR_CODE OUT NUMBER
 ,OUT_ERR_MSG OUT VARCHAR2
 );

 PROCEDURE P_CREATE_VOUCHER_ACCESS_TOKEN (
 IN_KEY IN VARCHAR2
 ,IN_VALUE IN VARCHAR2
 ,IN_PROGRAM_NAME IN VARCHAR2 -- "UPGRADE_PLANS"
 ,IN_BENEFIT_TYPE IN VARCHAR2 -- "REWARD_BENEFITS"
 ,IN_VENDOR_ID IN VARCHAR2 --
 ,OUT_VOUCHER_ACCESS_TOKEN OUT VARCHAR2
 ,OUT_ERR_CODE OUT NUMBER
 ,OUT_ERR_MSG OUT VARCHAR2
 );

 PROCEDURE P_CREATE_REWARD_VOUCHERS (
 IN_KEY IN VARCHAR2
 ,IN_VALUE IN VARCHAR2
 ,IN_PROGRAM_NAME IN VARCHAR2 -- "UPGRADE_PLANS"
 ,IN_BENEFIT_TYPE IN VARCHAR2 -- "REWARD_BENEFITS"
 ,IN_VOUCHER_ACCESS_TOKEN IN VARCHAR2
 ,OUT_VOUCHERS_LIST OUT sa.REWARD_VOUCHERS_TAB
 ,OUT_ERR_CODE OUT NUMBER
 ,OUT_ERR_MSG OUT VARCHAR2
 );

 PROCEDURE P_GET_VOUCHER_INFO (
 IN_VENDOR_ID IN VARCHAR2
 ,IN_VOUCHER_ACCESS_TOKEN IN VARCHAR2
 ,OUT_VOUCHERS_LIST OUT sa.REWARD_VOUCHERS_TAB
 ,OUT_TRANSACTION_ID OUT NUMBER
 ,OUT_ERR_CODE OUT NUMBER
 ,OUT_ERR_MSG OUT VARCHAR2
 );

 PROCEDURE P_INVALIDATE_VOUCHERS (
 IN_VOUCHER_ACCESS_TOKEN IN VARCHAR2
 ,IN_VOUCHERS_ID_LIST IN sa.TYP_VOUCHERS_ID_TAB
 ,IN_VENDOR_ID IN VARCHAR2
 ,OUT_TRANSACTION_ID OUT NUMBER
 ,OUT_ERR_CODE OUT NUMBER
 ,OUT_ERR_MSG OUT VARCHAR2
 ) ;

 PROCEDURE P_AUTHORIZE_VOUCHER_PAYMENT (
 IN_VOUCHER_ACCESS_TOKEN IN VARCHAR2
 ,IN_VOUCHERS_ID_LIST IN sa.TYP_VOUCHERS_ID_TAB
 ,IN_VENDOR_ID IN VARCHAR2
 ,IN_SETTLEMENT_FLAG IN VARCHAR2 DEFAULT 'N' -- { Y | N }
 ,IN_ORDER_INFO IN sa.TYP_VOUCHER_ORDER
 ,IN_ORDER_DETAILS_TAB IN sa.TYP_VOUCHER_ORDER_DETAILS_TAB
 ,OUT_TRANSACTION_ID OUT NUMBER
 ,OUT_ERR_CODE OUT NUMBER
 ,OUT_ERR_MSG OUT VARCHAR2
 );

 PROCEDURE P_SETTLE_VOUCHER_PAYMENT (
 IN_AUTH_TRANS_ID IN NUMBER
 ,IN_VOUCHER_ACCESS_TOKEN IN VARCHAR2
 ,IN_VENDOR_ID IN VARCHAR2
 ,IN_ORDER_ID IN VARCHAR2
 ,OUT_TRANSACTION_ID OUT NUMBER
 ,OUT_ERR_CODE OUT NUMBER
 ,OUT_ERR_MSG OUT VARCHAR2
 );

 PROCEDURE P_CANCEL_VOUCHER_PAYMENT (
 IN_AUTH_TRANS_ID IN NUMBER
 ,IN_VOUCHER_ACCESS_TOKEN IN VARCHAR2
 ,IN_VENDOR_ID IN VARCHAR2
 ,IN_ORDER_ID IN VARCHAR2
 ,OUT_TRANSACTION_ID OUT NUMBER
 ,OUT_ERR_CODE OUT NUMBER
 ,OUT_ERR_MSG OUT VARCHAR2
 );

 PROCEDURE P_REFUND_VOUCHER_PAYMENT (
 IN_SETTLEMENT_TRANS_ID IN NUMBER
 ,IN_VOUCHER_ACCESS_TOKEN IN VARCHAR2
 ,IN_VENDOR_ID IN VARCHAR2
 ,IN_ORDER_ID IN VARCHAR2
 ,OUT_TRANSACTION_ID OUT NUMBER
 ,OUT_ERR_CODE OUT NUMBER
 ,OUT_ERR_MSG OUT VARCHAR2
 );

 PROCEDURE P_REMOVE_PIN_BENEFITS (
  IN_SERVICE_PLAN_PIN IN VARCHAR2
 ,OUT_ERR_CODE OUT NUMBER
 ,OUT_ERR_MSG OUT VARCHAR2
 );

 PROCEDURE P_CREATE_REWARD_BENEFITS (
 IN_MIN IN VARCHAR2 DEFAULT NULL
 ,OUT_ERR_CODE OUT INTEGER
 ,OUT_ERR_MSG OUT VARCHAR2
 );

 FUNCTION F_IS_PIN_REFUNDABLE (
  IN_SERVICE_PLAN_PIN IN NUMBER
 ) RETURN BOOLEAN;

 FUNCTION F_GET_TRANSACTION_ID
 RETURN NUMBER;

 FUNCTION F_GET_PARAMETER_VALUE (IN_PARAMETER IN VARCHAR2)
 RETURN TABLE_X_PARAMETERS.X_PARAM_VALUE%TYPE;

 FUNCTION F_GET_UNIQUE_ID
 RETURN VARCHAR2;

 FUNCTION F_GET_EFFECTIVE_SERVICE_PLAN (
 IN_KEY IN VARCHAR2
 ,IN_VALUE IN VARCHAR2
 ) RETURN VARCHAR2;

 FUNCTION F_GET_EFF_SERVICE_PLAN_ID (
 IN_KEY IN VARCHAR2
 ,IN_VALUE IN VARCHAR2
 ) RETURN NUMBER;

 type typ_rec_benefits_hist is record(
 objid	 table_x_benefits.objid%type,
 x_trans_date	 table_x_point_trans.x_trans_date%type,
 x_min	 table_x_point_trans.x_min%type,
 x_esn	 table_x_point_trans.x_esn%type,
 x_points_action	 table_x_point_trans.x_points_action%type,
 x_benefit_value table_x_benefit_programs.x_benefit_value%type,
 points_action_reason	 table_x_point_trans.points_action_reason%type ,
 display_action_reason	 table_x_point_trans.points_action_reason%type
 );

 type tab_benefits_hist is table of typ_rec_benefits_hist;

 FUNCTION f_get_benefits_history(
 in_key IN VARCHAR2,
 in_value IN VARCHAR2 )
 RETURN tab_benefits_hist pipelined;

END  REWARD_BENEFITS_N_VOUCHERS_PKG;
/