CREATE OR REPLACE PACKAGE sa."RIM_SERVICE_PKG" is
PROCEDURE sp_create_rim_action_item
( p_action_item_id     IN  VARCHAR2, -- wg1.ig_transaction.ACTION_ITEM_ID VARCHAR2(30)
  op_msg    OUT VARCHAR2, -- Output Message
  op_status OUT VARCHAR2  -- Output Status S= Success, F= Failed,
  );

FUNCTION sp_rim_SIM ( p_action_item_id  in varchar2)
RETURN VARCHAR2;
--22798
FUNCTION VERIFY_BB_PC_ESN(P_ESN IN VARCHAR2)
RETURN VARCHAR2;

FUNCTION IF_BB_ESN(P_ESN IN VARCHAR2)
RETURN VARCHAR2;

FUNCTION SP_RIM_GSM_SIM (P_ACTION_ITEM_ID IN VARCHAR2)
RETURN VARCHAR2;

PROCEDURE SP_INS_RIM_DEACT_FOR_UPGRADE
( 	IN_CALL_TRAN_OBJ	IN  NUMBER, -- WG1.IG_TRANSACTION.ACTION_ITEM_ID VARCHAR2(30)
IP_MIN				IN  VARCHAR2,
IP_USEROBJID		IN  VARCHAR2,
IP_OLD_ESN			IN  VARCHAR2,
IP_NEW_ESN			IN 	VARCHAR2,
OP_MSG    			OUT VARCHAR2, -- OUTPUT MESSAGE
OP_STATUS 			OUT VARCHAR2  -- OUTPUT STATUS S= SUCCESS, F= FAILED
);

end RIM_SERVICE_PKG;
/