CREATE OR REPLACE PACKAGE sa.SP_MOBILE_BILLING AS
/***************************************************************************************************/
--$RCSfile: SP_MOBILE_BILLING_PKG_STRUCTURE.sql,v $
--$Revision: 1.14 $
--$Author: vlaad $
--$Date: 2016/08/29 23:15:35 $
--$ $Log: SP_MOBILE_BILLING_PKG_STRUCTURE.sql,v $
--$ Revision 1.14  2016/08/29 23:15:35  vlaad
--$ Updated for Data Club
--$
--$ Revision 1.13  2015/01/15 19:45:12  icanavan
--$ ADDED /
--$
--$ Revision 1.12  2014/12/17 13:48:48  bkayal
--$ commited for CR31367
--$
--$ Revision 1.11  2014/12/03 17:12:34  bkayal
--$ Added and modified few functionality
--$
--$ Revision 1.9  2014/09/25 13:32:51  dtunk
--$ Updated for CR28413 - web commerce for processing two new fields x_subscriptiontype , x_subscriptionunits
--$
--$ Revision 1.8  2014/09/23 19:50:22  dtunk
--$ Updated for CR28413 - web commerce for processing two new fields x_vendor_id , x_client_id
--$
--$ Revision 1.7  2014/09/17 23:51:02  dtunk
--$ Addred the commemts block
--$
--$ Revision 1.0  2014/02/26 20:26:10  dtunk
--$ CR24813 - Web Commerce
--$
/***************************************************************************************************/
  /*===============================================================================================*/
  /*                                                                                               */
  /* PURPOSE  : Package has been developed to mobile billing Db operation             */
  /*                                    */
  /*                                                                                               */
  /* REVISIONS  DATE       WHO            PURPOSE                                                  */
  /* --------------------------------------------------------------------------------------------- */
  /*            10/17/14   dtunk     CR28413: Web commerce */
  /*===============================================================================================*/

PROCEDURE INSERT_PURCHASE_DETAILS (
------------X_PROGRAM_PURCH_HDR
IP_X_RQST_SOURCE  				IN VARCHAR2,
IP_X_RQST_TYPE  				IN VARCHAR2,
IP_X_ICS_APPLICATIONS  			IN VARCHAR2,
IP_X_MERCHANT_ID  				IN VARCHAR2,
IP_X_MERCHANT_REF_NUMBER  		IN VARCHAR2,
IP_X_OFFER_NUM   				IN VARCHAR2,
IP_X_QUANTITY   				IN NUMBER,
IP_X_MERCHANT_PRODUCT_SKU   	IN VARCHAR2,
IP_X_PRODUCT_CODE    			IN VARCHAR2,
IP_X_IGNORE_AVS    				IN VARCHAR2,
IP_X_CUSTOMER_HOSTNAME 			IN VARCHAR2,
IP_X_CUSTOMER_IPADDRESS 		IN VARCHAR2,
IP_X_CUSTOMER_PHONE 			IN VARCHAR2,
IP_X_STATUS 					IN VARCHAR2,
IP_X_ESN 						IN VARCHAR2,
IP_X_AMOUNT 					IN NUMBER,
IP_X_TAX_AMOUNT 				IN NUMBER,
IP_PURCH_HDR2CREDITCARD 		IN NUMBER,
IP_PROG_HDR2X_PYMT_SRC 			IN NUMBER,
IP_PROG_HDR2WEB_USER 			IN NUMBER,
IP_X_PAYMENT_TYPE 				IN VARCHAR2,
IP_X_E911_TAX_AMOUNT 			IN NUMBER,
IP_X_USF_TAXAMOUNT 				IN NUMBER,
IP_X_RCRF_TAX_AMOUNT 			IN NUMBER,
IP_X_DISCOUNT_AMOUNT 			IN NUMBER,
IP_X_BILL_ZIP 					IN VARCHAR2,
------------X_PROGRAM_PURCH_HDR
------------X_PROGRAM_PURCH_DTL
IP_X_CHARGE_DESC                 IN VARCHAR2,
------------X_PROGRAM_PURCH_DTL
------------X_CONTENT_PURCH_DTL
IP_X_ITEM_NAME                   IN VARCHAR2,
IP_X_CAT                         IN VARCHAR2,
IP_X_SUBCAT                      IN VARCHAR2,
IP_X_ARTIST                      IN VARCHAR2,
IP_X_CHANNEL                     IN VARCHAR2,
IP_X_RETAILER_ID                 IN VARCHAR2,
IP_X_DELIVERY_STATUS             IN VARCHAR2,
IP_CONTENT_PROVIDER              IN VARCHAR2,
IP_ORDER_ID                      IN VARCHAR2,
IP_X_PART_NUM                    IN VARCHAR2,
IP_X_VENDOR_ID                    IN VARCHAR2,
IP_X_CLIENT_ID                    IN VARCHAR2,
IP_X_SUBSCRIPTION_TYPE            IN VARCHAR2,
IP_X_SUBSCRIPTION_UNITS           IN NUMBER,
------------X_CONTENT_PURCH_DTL
OP_PROGRAM_PURCHHDR_OBJID		 OUT NUMBER,
OP_ERRORNUM						 OUT VARCHAR2,
OP_ERRORMSG						 OUT VARCHAR2,
IP_IS_DATACLUB               IN VARCHAR2 DEFAULT 'N');

PROCEDURE GET_PROGRAM_PURCHASE_STATUS (
IP_ORDER_ID 					IN VARCHAR2,
IP_VENDOR_ID 					IN VARCHAR2,
IP_CLIENT_ID 					IN VARCHAR2,
OP_X_STATUS 					OUT VARCHAR2,
OP_RESPCODE 					OUT VARCHAR2,
OP_RESPMSG 					OUT VARCHAR2);


PROCEDURE GET_DEVICE_INFO (
P_IPMIN   				IN VARCHAR2,
P_BALANCE 				IN NUMBER,
P_BILLING_DIRECTION 	OUT VARCHAR2,
P_RESOLUTION_URL 		OUT VARCHAR2,
P_MIN 					OUT VARCHAR2,
P_OPESN 				OUT VARCHAR2,
P_DELIVERY_METHOD 		OUT VARCHAR2,
P_MANUFACTURER 			OUT VARCHAR2,
P_MODEL 				OUT VARCHAR2,
P_PART_CLASS 			OUT VARCHAR2,
P_PPE_ENABLED 			OUT VARCHAR2,
P_TOOLKIT_VERSION 		OUT VARCHAR2,
P_DEVICE_OS 			OUT VARCHAR2,
P_BACKBONE_CARRIER 		OUT VARCHAR2,
P_CONVERSION_FACTOR 	OUT VARCHAR2,
P_ACCOUNT_ID 			OUT VARCHAR2,
P_DEALER_ID 			OUT VARCHAR2,
P_DUE_DATE 				OUT VARCHAR2,
P_BRAND 				OUT VARCHAR2,
P_CHARGE_UNIT_TYPE 		OUT VARCHAR2,
P_ASSOCIATED_ACCOUNT 	OUT VARCHAR2,
OP_ERR_NUM 				OUT NUMBER,
OP_ERR_STRING 			OUT VARCHAR2);

PROCEDURE UPDATE_PROGRAM_PURCH_HDR (
IP_X_PROGRAM_PURCH_HDR_OBJID	IN NUMBER,
IP_X_STATUS 				            IN VARCHAR2,
IP_X_REQUEST_ID                	IN VARCHAR2,
IP_X_AUTH_REQUEST_ID           	IN VARCHAR2,
IP_X_AUTH_CODE                 	IN VARCHAR2,
IP_X_AUTH_TYPE                 	IN VARCHAR2,
IP_X_AUTH_AVS                  	IN VARCHAR2,
IP_X_AUTH_RESPONSE             	IN VARCHAR2,
IP_X_AUTH_TIME                 	IN VARCHAR2,
IP_X_AUTH_RCODE                	IN NUMBER,
IP_X_AUTH_RFLAG                	IN VARCHAR2,
IP_X_AUTH_RMSG                 	IN VARCHAR2,
IP_X_AUTH_AMOUNT               	IN NUMBER,
IP_X_ICS_RCODE                 	IN VARCHAR2,
IP_X_ICS_RFLAG                 	IN VARCHAR2,
IP_X_ICS_RMSG                  	IN VARCHAR2,
IP_X_BILL_REQUEST_TIME         	IN VARCHAR2,
IP_X_BILL_RCODE                	IN NUMBER,
IP_X_BILL_RFLAG                	IN VARCHAR2,
IP_X_BILL_RMSG                 	IN VARCHAR2,
IP_X_BILL_TRANS_REF_NO         	IN VARCHAR2,
IP_X_BILL_AMOUNT               	IN NUMBER,
OP_ERRORNUM						OUT VARCHAR2,
OP_ERRORMSG						OUT VARCHAR2,
IP_IS_DATACLUB               IN VARCHAR2 DEFAULT 'N');

/*=============== PROCEDURE UPDATE_PURCH_STATUS ===============*/
PROCEDURE UPDATE_PURCH_STATUS (
IP_X_STATUS 					IN VARCHAR2,
IP_ORDER_ID           IN VARCHAR2,
OP_PURCH_ID						OUT VARCHAR2,
OP_ERRORNUM						OUT VARCHAR2,
OP_ERRORMSG						OUT VARCHAR2);

FUNCTION UPDATE_CARD_STATUS(
IP_X_CUSTOMER_CC_NUMBER  IN VARCHAR2,
IP_X_CARD_STATUS          IN VARCHAR2
)
RETURN VARCHAR2;
PROCEDURE GET_SCRIPT_DETAILS(
IP_SCRIPT_VALUES	IN VARCHAR2,
IP_LANGUAGE 		IN VARCHAR2,
IP_SOURCESYSTEM 	IN VARCHAR2,
OP_RESULT_SET		OUT SYS_REFCURSOR,
OP_ERRORNUM	 		OUT VARCHAR2,
OP_ERRORMSG	 		OUT VARCHAR2);

PROCEDURE GET_MERCHANT_INFO (
IP_X_BUS_ORG			IN VARCHAR2,
OP_X_MERCHANT_ID 		OUT VARCHAR2,
OP_NEXT_VALUE   		OUT NUMBER,
OP_FORMAT       		OUT VARCHAR2,
OP_ERRORNUM 			OUT NUMBER,
OP_ERRORMSG 			OUT VARCHAR2);

PROCEDURE GET_PART_NUMBER_BY_PRICE(
IP_NAME				IN VARCHAR2,
IP_S_ORG_ID 		IN VARCHAR2,
IP_X_RETAIL_PRICE 	IN VARCHAR2,
IP_PART_NUMBER		IN VARCHAR2,
OP_OBJID			OUT VARCHAR2,
OP_PART_NUMBER		OUT VARCHAR2,
OP_ERRORNUM	 		OUT VARCHAR2,
OP_ERRORMSG	 		OUT VARCHAR2);


FUNCTION GET_OBJID_FROM_BUSORG (
IP_ORGID	IN VARCHAR2
)
RETURN VARCHAR2;

FUNCTION GET_OBJID_FROM_CREDITCARD (
IP_X_CUSTOMER_CC_NUMBER		IN VARCHAR2,
IP_X_CREDIT_CARD2BUS_ORG	IN VARCHAR2
)
RETURN VARCHAR2;

FUNCTION GET_STATUS_FROM_CREDITCARD (
IP_X_CUSTOMER_CC_NUMBER		IN VARCHAR2,
IP_X_CREDIT_CARD2BUS_ORG	IN VARCHAR2
)
RETURN VARCHAR2;

FUNCTION GET_OBJID_FROM_CERT (
IP_X_CERT		IN VARCHAR2,
IP_X_KEY_ALGO	IN VARCHAR2,
IP_X_CC_ALGO	IN VARCHAR2
)
RETURN VARCHAR2;

FUNCTION GET_OBJID_FROM_PAYMENTSOURCE (
IP_PYMT_SRC2X_CREDIT_CARD	IN VARCHAR2,
IP_PYMT_SRC2WEB_USER		IN VARCHAR2
)
RETURN VARCHAR2;

FUNCTION CHECK_MTM_CONTACT_CREDIT_CARD (
MTM_CONTACT_ID	IN VARCHAR2,
MTM_CREDIT_CARD_ID		IN VARCHAR2
)
RETURN VARCHAR2;

PROCEDURE GET_CREDIT_CARD_REQUEST_INFO (
IP_CC_OBJID				IN VARCHAR2,
OP_RESULT_SET			OUT SYS_REFCURSOR,
OP_ERRORNUM				OUT VARCHAR2,
OP_ERRORMSG				OUT VARCHAR2);

FUNCTION INSERT_PAYMENT_SOURCE (
IP_X_PYMT_SRC_NAME			IN VARCHAR2,
IP_PYMT_SRC2WEB_USER		IN VARCHAR2,
IP_PYMT_SRC2X_CREDIT_CARD	IN VARCHAR2,
IP_X_SOURCESYSTEM			IN VARCHAR2)
RETURN VARCHAR2;

FUNCTION INSERT_CREDIT_CARD (
IP_X_CUSTOMER_CC_NUMBER			IN VARCHAR2,
IP_X_CUSTOMER_CC_EXPMO			IN VARCHAR2,
IP_X_CUSTOMER_CC_EXPYR			IN VARCHAR2,
IP_X_CC_TYPE					IN VARCHAR2,
IP_X_CUSTOMER_CC_CV_NUMBER		IN VARCHAR2,
IP_X_CUSTOMER_FIRSTNAME			IN VARCHAR2,
IP_X_CUSTOMER_LASTNAME			IN VARCHAR2,
IP_X_CUSTOMER_PHONE				IN VARCHAR2,
IP_X_CUSTOMER_EMAIL				IN VARCHAR2,
IP_X_CREDIT_CARD2CONTACT		IN VARCHAR2,
IP_X_CREDIT_CARD2ADDRESS		IN VARCHAR2,
IP_X_CREDIT_CARD2BUS_ORG		IN VARCHAR2,
IP_X_CUST_CC_NUM_KEY			IN VARCHAR2,
IP_X_CUST_CC_NUM_ENC			IN VARCHAR2,
IP_CREDITCARD2CERT				IN VARCHAR2)
RETURN VARCHAR2;

PROCEDURE ADD_PAYMENT_CREDITCARD_DETAILS (
IP_WEBUSER_OBJID				IN VARCHAR2,
IP_TPI_ESN						IN VARCHAR2,
IP_BRAND_NAME					IN VARCHAR2,
IP_X_PYMT_TYPE					IN VARCHAR2,
IP_X_PYMT_SRC_NAME				IN VARCHAR2,
IP_X_SOURCESYSTEM				IN VARCHAR2,
IP_X_CUSTOMER_CC_NUMBER			IN VARCHAR2,
IP_X_CUSTOMER_CC_EXPMO			IN VARCHAR2,
IP_X_CUSTOMER_CC_EXPYR			IN VARCHAR2,
IP_X_CC_TYPE					IN VARCHAR2,
IP_X_CUSTOMER_CC_CV_NUMBER		IN VARCHAR2,
IP_X_CUSTOMER_PHONE				IN VARCHAR2,
IP_X_CUST_CC_NUM_KEY			IN VARCHAR2,
IP_X_CUST_CC_NUM_ENC			IN VARCHAR2,
IP_X_CERT						IN VARCHAR2,
IP_X_KEY_ALGO					IN VARCHAR2,
IP_X_CC_ALGO					IN VARCHAR2,

OP_RESULT_SET					OUT VARCHAR2,
OP_CONTACT_OBJID				OUT VARCHAR2,
OP_CC_OBJID						OUT VARCHAR2,
OP_PS_OBJID						OUT VARCHAR2,
OP_ERRORNUM						OUT VARCHAR2,
OP_ERRORMSG						OUT VARCHAR2);

PROCEDURE CALCTAX_VAS(
IP_ZIP_CODE                  IN VARCHAR2,
IP_PURCHASE_AMOUNT           IN NUMBER,
IP_MODEL_TYPE                IN VARCHAR2,
OP_PURCHASE_AMOUNT			 OUT NUMBER,
OP_MODEL_TAX_PERCENTAGE    	 OUT NUMBER,
OP_TAX_AMOUNT                OUT NUMBER,
OP_TOTAL_AMOUNT              OUT NUMBER,
OP_RESULT                    OUT VARCHAR2);
--OP_ERRORNUM					 OUT VARCHAR2,
--OP_ERRORMSG					 OUT VARCHAR2);

END SP_MOBILE_BILLING;
/