CREATE OR REPLACE PACKAGE sa."SP_PURCHASE" IS

PROCEDURE Insert_Purch_Det (IP_partnumbers              IN VARCHAR2,
                            Ip_PurchHdr_Objid           IN VARCHAR2,
                            Ip_Merch_Ref_Id             IN VARCHAR2,
                            Ip_SourceSystem             IN VARCHAR2,
                            Ip_Brand_Name               IN VARCHAR2,
                            Ip_Esn_Objid                IN NUMBER,
                            Ip_UserID                   IN VARCHAR2,
                            Ip_pincards                 IN varchar2,
                            Op_RedCards_PartInst_Objids OUT VARCHAR2,  /*(comma separated unique part inst objid) */
                            Op_PurchDtl_Objids          OUT VARCHAR2,   /* (comma separated unique objids)     */
                            Op_redcodes                 OUT varchar2,  /* (coma separated unique pin card number) */
                            Op_TotalCount               OUT NUMBER,
                            op_result                   OUT NUMBER,
                            Op_ErrorNum                 OUT VARCHAR2,
                            Op_ErrorMsg                 OUT  VARCHAR2 );

PROCEDURE Insert_Purch_Hdr ( ip_x_rqst_source 		IN   VARCHAR2,
                                                ip_x_rqst_type  			IN VARCHAR2,
                                                ip_x_rqst_date  			IN     DATE,
                                                ip_x_ics_applications 		IN  VARCHAR2,
                                                ip_x_merchant_id 		IN VARCHAR2,
                                                ip_x_merchant_ref_number 	IN VARCHAR2,
                                                ip_x_offer_num 			IN  VARCHAR2,
                                                ip_x_quantity 			IN  NUMBER,
                                                ip_x_ignore_bad_cv 		IN VARCHAR2,
                                                ip_x_ignore_avs 		IN     VARCHAR2,
                                                ip_x_disable_avs 		IN  VARCHAR2,
                                                ip_x_customer_hostname 		IN  VARCHAR2,
                                                ip_x_customer_ipaddress 		IN VARCHAR2,
                                                ip_x_auth_code 		IN VARCHAR2,
                                                ip_x_ics_rcode 			IN    NUMBER,
                                                ip_x_ics_rflag 			IN  VARCHAR2,
                                                ip_x_ics_rmsg 			IN  VARCHAR2,
                                                ip_x_request_id 		IN VARCHAR2,
                                                ip_x_auth_avs 			IN       VARCHAR2,
                                                ip_x_auth_response 		IN  VARCHAR2,
                                                ip_x_auth_time 			IN VARCHAR2,
                                                ip_x_auth_rcode 		IN NUMBER,
                                                ip_x_auth_rflag 			IN  VARCHAR2,
                                                ip_x_auth_rmsg 		IN  VARCHAR2,
                                                ip_x_score_factors 		IN   VARCHAR2,
                                                ip_x_score_host_severity 		IN VARCHAR2,
                                                ip_x_score_rcode 		IN NUMBER,
                                                ip_x_score_rflag 		IN VARCHAR2,
                                                ip_x_score_rmsg 		IN  VARCHAR2,
                                                ip_x_score_result 		IN NUMBER,
                                                ip_x_score_time_local 		IN  VARCHAR2,
                                                ip_x_bill_request_time 		IN  VARCHAR2,
                                                ip_x_bill_rcode 			IN   NUMBER,
                                                ip_x_bill_rflag 			IN  VARCHAR2,
                                                ip_x_bill_rmsg 			IN VARCHAR2,
                                                ip_x_bill_trans_ref_no 		IN  VARCHAR2,
                                                ip_x_customer_cc_number 	IN VARCHAR2,
                                                ip_x_customer_cc_expmo 	IN  VARCHAR2,
                                                ip_x_customer_cc_expyr 		IN  VARCHAR2,
                                                ip_x_customer_firstname 		IN VARCHAR2,
                                                ip_x_customer_lastname 		IN  VARCHAR2,
                                                ip_x_customer_phone 		IN VARCHAR2,
                                                ip_x_customer_email 		IN  VARCHAR2,
                                                ip_x_bill_address1 		IN VARCHAR2,
                                                ip_x_bill_address2 		IN  VARCHAR2,
                                                ip_x_bill_city 			IN     VARCHAR2,
                                                ip_x_bill_state 			IN  VARCHAR2,
                                                ip_x_bill_zip 			IN VARCHAR2,
                                                ip_x_bill_country 		IN    VARCHAR2,
                                                ip_x_esn 			IN    VARCHAR2,
                                                ip_x_cc_lastfour 		IN  VARCHAR2,
                                                ip_x_amount 			IN   NUMBER,
                                                ip_x_tax_amount 		IN  NUMBER,
                                                ip_x_e911_amount 		IN         NUMBER,
                                                ip_x_usf_amount     IN         NUMBER ,
                                                ip_x_rcrf_amount       IN     NUMBER ,
                                                ip_x_combs_amount       IN     NUMBER ,
                                                ip_x_discount_amount   IN     NUMBER,
                                                ip_x_shipping_cost IN         NUMBER ,
                                                ip_x_auth_amount 		IN    NUMBER,
                                                ip_x_bill_amount 		IN NUMBER,
                                                ip_x_purch_hdr2contact 	IN  NUMBER,
                                                ip_x_purch_hdr2user 		IN  NUMBER,
                                                ip_x_purch_hdr2esn 		IN     NUMBER,
                                                ip_x_purch_hdr2bank_acct 	IN  NUMBER,
                                                ip_x_purch_hdr2creditcard 	IN  NUMBER,
                                                Op_PurchHdr_objid    		OUT NUMBER,
                                                Op_ErrorNum              		OUT VARCHAR2,
                                                Op_ErrorMsg               		OUT  VARCHAR2 );

PROCEDURE Update_Purch_Hdr (ip_x_purch_hdr_objid          IN Number,
                            ip_x_auth_request_id          IN  VARCHAR2,
                            ip_x_auth_code 		            IN VARCHAR2 ,
                            ip_x_ics_rcode 		            IN    NUMBER,
                            ip_x_ics_rflag 		            IN  VARCHAR2 ,
                            ip_x_ics_rmsg 		            IN  VARCHAR2 ,
                            ip_x_request_id 		          IN VARCHAR2 ,
                            ip_x_auth_amount 		          IN    NUMBER ,
                            ip_x_auth_avs 		            IN       VARCHAR2 ,
                            ip_x_auth_response 		        IN  VARCHAR2 ,
                            ip_x_auth_time 		            IN VARCHAR2 ,
                            ip_x_auth_rcode 		          IN NUMBER,
                            ip_x_auth_rflag 		          IN  VARCHAR2 ,
                            ip_x_auth_rmsg 		            IN  VARCHAR2 ,
                            ip_x_auth_cv_result           IN VARCHAR2,
                            ip_x_score_factors 		        IN   VARCHAR2 ,
                            ip_x_score_host_severity 	    IN VARCHAR2 ,
                            ip_x_score_rcode 		          IN NUMBER,
                            ip_x_score_rflag 		          IN VARCHAR2 ,
                            ip_x_score_rmsg 		          IN  VARCHAR2 ,
                            ip_x_score_result 		        IN NUMBER,
                            ip_x_score_time_local 		    IN  VARCHAR2 ,
                            ip_x_bill_amount 		          IN NUMBER ,
                            ip_x_bill_request_time 		    IN  VARCHAR2 ,
                            ip_x_bill_rcode 		          IN   NUMBER,
                            ip_x_bill_rflag 		          IN  VARCHAR2 ,
                            ip_x_bill_rmsg 		            IN VARCHAR2 ,
                            ip_x_bill_trans_ref_no 		    IN  VARCHAR2 ,
                            ip_x_purch_hdr2x_rmsg_codes   IN NUMBER,
                            ip_x_rqst_source 	            IN   VARCHAR2 ,
                            ip_x_rqst_type  		          IN VARCHAR2 ,
                            ip_x_rqst_date  		          IN     DATE,
                            ip_x_user                     IN VARCHAR2,
                            Op_ErrorNum                   OUT VARCHAR2,
                            Op_ErrorMsg                   OUT  VARCHAR2);


END SP_PURCHASE;
/