CREATE OR REPLACE PACKAGE sa."TFSOA_NTFY_CORE_LOGGING_PKG"
IS
PROCEDURE TF_UPDATELOGENTRY(
          p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
          p_NTFY_DB_OUTPUT_TYPE  OUT      TF_NTFY_DB_OUTPUT_TYPE);

PROCEDURE TF_CREATEBILLINGLOGENTRY(
          p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
          p_NTFY_DB_OUTPUT_TYPE  OUT      TF_NTFY_DB_OUTPUT_TYPE);

PROCEDURE  TF_STOREFORDELIVERYSTATUS(
           p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
           p_NTFY_DB_OUTPUT_TYPE  OUT      TF_NTFY_DB_OUTPUT_TYPE);


PROCEDURE TF_STOREFORBATCHPROCESSING (
           p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
           p_NTFY_DB_OUTPUT_TYPE  OUT TF_NTFY_DB_OUTPUT_TYPE);
END TFSOA_NTFY_CORE_LOGGING_PKG ;
/