CREATE OR REPLACE PACKAGE sa.TFSOA_NTFY_LOGGING_PKG IS

PROCEDURE TF_PROCESS_FAILURE(
          p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
          p_NTFY_DB_OUTPUT_TYPE  OUT      TF_NTFY_DB_OUTPUT_TYPE);

PROCEDURE TF_PROCESS_EXCEPTION(
          p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
          p_NTFY_DB_OUTPUT_TYPE  OUT      TF_NTFY_DB_OUTPUT_TYPE);

PROCEDURE  TF_PROCESS_DISCARD(
           p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
           p_NTFY_DB_OUTPUT_TYPE  OUT      TF_NTFY_DB_OUTPUT_TYPE);


PROCEDURE TF_PROCESS_SUCCESS (
           p_NTFY_DB_INPUT_TYPE  IN  TF_NTFY_DB_INPUT_TYPE,
           p_NTFY_DB_OUTPUT_TYPE  OUT TF_NTFY_DB_OUTPUT_TYPE);

END TFSOA_NTFY_LOGGING_PKG;
/