CREATE OR REPLACE FORCE VIEW sa.paul_full_nxx_npa_list (x_npa,x_nxx) AS
SELECT TABLE_PART_INST.X_NPA, TABLE_PART_INST.X_NXX
FROM TABLE_X_CARRIER, TABLE_PART_INST
WHERE TABLE_X_CARRIER.OBJID = TABLE_PART_INST.PART_INST2CARRIER_MKT
GROUP BY TABLE_PART_INST.X_NPA, TABLE_PART_INST.X_NXX 
;