CREATE OR REPLACE FORCE VIEW sa.pcpv (pc_objid,part_class,activation_alert_title,ar_capable,apn_request,balance_metering,available_online,bluetooth,bus_org,custom_411,data_capable,data_speed,default_click_id,device_id_english,device_id_spanish,device_type,display_description,dll,extd_warranty,factory_click_id,factory_short_code,firmware,fm_radio,frequency_1,frequency_2,ild_type,initial_motricity_conversion,manufacturer,meid_phone,model_type,motricity_denomination,mp3player,multi_call,non_ppe,operating_system,ota_allowed,phone_gen,ppe_configuration,preloaded_click_id,preloaded_data_config,prl_instructions,product_selection,release_date,restricted_use,skip_sms,skip_vm,subsidy_cost,sub_source_system,technology,unlimited_plan,apply_def_activation_promo,has_wifi_calling,apn_source_type,sub_brand,send_welcome_sms,cbo_legacy_flag,block_triple_min_conv,volte,att_wifi_calling) AS
SELECT pc_objid,
          part_class,
          activation_alert_title,
          ar_capable,
          apn_request,
          balance_metering,
          available_online,
          bluetooth,
          bus_org,
          custom_411,
          data_capable,
          data_speed,
          default_click_id,
          device_id_english,
          device_id_spanish,
          device_type,
          display_description,
          dll,
          extd_warranty,
          factory_click_id,
          factory_short_code,
          firmware,
          fm_radio,
          frequency_1,
          frequency_2,
          ild_type,
          initial_motricity_conversion,
          TRIM (manufacturer),
          meid_phone,
          model_type,
          motricity_denomination,
          mp3player,
          multi_call,
          non_ppe,
          operating_system,
          ota_allowed,
          phone_gen,
          ppe_configuration,
          preloaded_click_id,
          preloaded_data_config,
          prl_instructions,
          product_selection,
          release_date,
          restricted_use,
          skip_sms,
          skip_vm,
          subsidy_cost,
          sub_source_system,
          technology,
          unlimited_plan,
          apply_def_activation_promo,
          has_wifi_calling,
          APN_SOURCE_TYPE,
          sub_brand,
          send_welcome_sms,
          CBO_LEGACY_FLAG,
		  BLOCK_TRIPLE_MIN_CONV,
		  VOLTE,
		  ATT_WIFI_CALLING
     FROM (SELECT * FROM pc_params_view) PIVOT (MAX (param_value)
                                         FOR param_name
                                         IN  ('ACTIVATION_ALERT_TITLE' AS ACTIVATION_ALERT_TITLE,
                                             'AR_CAPABLE' AS AR_CAPABLE,
                                             'APN_REQUEST' AS APN_REQUEST,
                                             'BALANCE_METERING' AS BALANCE_METERING,
                                             'AVAILABLE_ONLINE' AS AVAILABLE_ONLINE,
                                             'BLUETOOTH' AS BLUETOOTH,
                                             'BUS_ORG' AS BUS_ORG,
                                             'CUSTOM_411' AS CUSTOM_411,
                                             'DATA_CAPABLE' AS DATA_CAPABLE,
                                             'DATA_SPEED' AS DATA_SPEED,
                                             'DEFAULT_CLICK_ID' AS DEFAULT_CLICK_ID,
                                             'DEVICE_ID_ENGLISH' AS DEVICE_ID_ENGLISH,
                                             'DEVICE_ID_SPANISH' AS DEVICE_ID_SPANISH,
                                             'DEVICE_TYPE' AS DEVICE_TYPE,
                                             'DISPLAY_DESCRIPTION' AS DISPLAY_DESCRIPTION,
                                             'DLL' AS DLL,
                                             'EXTD_WARRANTY' AS EXTD_WARRANTY,
                                             'FACTORY_CLICK_ID' AS FACTORY_CLICK_ID,
                                             'FACTORY_SHORT_CODE' AS FACTORY_SHORT_CODE,
                                             'FIRMWARE' AS FIRMWARE,
                                             'FM_RADIO' AS FM_RADIO,
                                             'FREQUENCY_1' AS FREQUENCY_1,
                                             'FREQUENCY_2' AS FREQUENCY_2,
                                             'ILD_TYPE' AS ILD_TYPE,
                                             'INITIAL_MOTRICITY_CONVERSION' AS INITIAL_MOTRICITY_CONVERSION,
                                             'MANUFACTURER' AS MANUFACTURER,
                                             'MEID_PHONE' AS MEID_PHONE,
                                             'MODEL_TYPE' AS MODEL_TYPE,
                                             'MOTRICITY_DENOMINATION' AS MOTRICITY_DENOMINATION,
                                             'MP3PLAYER' AS MP3PLAYER,
                                             'MULTI_CALL' AS MULTI_CALL,
                                             'NON_PPE' AS NON_PPE,
                                             'OPERATING_SYSTEM' AS OPERATING_SYSTEM,
                                             'OTA_ALLOWED' AS OTA_ALLOWED,
                                             'PHONE_GEN' AS phone_gen,
                                             'PPE_CONFIGURATION' AS PPE_CONFIGURATION,
                                             'PRELOADED_CLICK_ID' AS PRELOADED_CLICK_ID,
                                             'PRELOADED_DATA_CONFIG' AS PRELOADED_DATA_CONFIG,
                                             'PRL_INSTRUCTIONS' AS PRL_INSTRUCTIONS,
                                             'PRODUCT_SELECTION' AS PRODUCT_SELECTION,
                                             'RELEASE_DATE' AS RELEASE_DATE,
                                             'RESTRICTED_USE' AS RESTRICTED_USE,
                                             'SKIP_SMS' AS SKIP_SMS,
                                             'SKIP_VM' AS SKIP_VM,
                                             'SUBSIDY_COST' AS SUBSIDY_COST,
                                             'SUB_SOURCE_SYSTEM' AS SUB_SOURCE_SYSTEM,
                                             'TECHNOLOGY' AS TECHNOLOGY,
                                             'UNLIMITED_PLAN' AS UNLIMITED_PLAN,
                                             'APPLY_DEF_ACTIVATION_PROMO' AS APPLY_DEF_ACTIVATION_PROMO,
                                             'HAS_WIFI_CALLING' AS HAS_WIFI_CALLING,
                                             'APN_SOURCE_TYPE' AS APN_SOURCE_TYPE,
                                             'SUB_BRAND' AS sub_brand,
                                             'SEND_WELCOME_SMS' AS SEND_WELCOME_SMS,
                                             'CBO_LEGACY_FLAG' AS CBO_LEGACY_FLAG,
											 'BLOCK_TRIPLE_MIN_CONV' AS BLOCK_TRIPLE_MIN_CONV,
											 'VOLTE' AS VOLTE,
											 'ATT_WIFI_CALLING' AS ATT_WIFI_CALLING
											 ));