CREATE OR REPLACE FORCE VIEW sa.pcrf_transaction_offers_view (pcrf_transaction_id,offer_01_id,offer_01_data_usage,offer_01_ttl,offer_01_redemption_date,offer_02_id,offer_02_data_usage,offer_02_ttl,offer_02_redemption_date,offer_03_id,offer_03_data_usage,offer_03_ttl,offer_03_redemption_date,offer_04_id,offer_04_data_usage,offer_04_ttl,offer_04_redemption_date,offer_05_id,offer_05_data_usage,offer_05_ttl,offer_05_redemption_date,offer_06_id,offer_06_data_usage,offer_06_ttl,offer_06_redemption_date,offer_07_id,offer_07_data_usage,offer_07_ttl,offer_07_redemption_date,offer_08_id,offer_08_data_usage,offer_08_ttl,offer_08_redemption_date,offer_09_id,offer_09_data_usage,offer_09_ttl,offer_09_redemption_date,offer_10_id,offer_10_data_usage,offer_10_ttl,offer_10_redemption_date,offer_11_id,offer_11_data_usage,offer_11_ttl,offer_11_redemption_date,offer_12_id,offer_12_data_usage,offer_12_ttl,offer_12_redemption_date,offer_13_id,offer_13_data_usage,offer_13_ttl,offer_13_redemption_date,offer_14_id,offer_14_data_usage,offer_14_ttl,offer_14_redemption_date,offer_15_id,offer_15_data_usage,offer_15_ttl,offer_15_redemption_date,offer_16_id,offer_16_data_usage,offer_16_ttl,offer_16_redemption_date,offer_17_id,offer_17_data_usage,offer_17_ttl,offer_17_redemption_date,offer_18_id,offer_18_data_usage,offer_18_ttl,offer_18_redemption_date,offer_19_id,offer_19_data_usage,offer_19_ttl,offer_19_redemption_date,offer_20_id,offer_20_data_usage,offer_20_ttl,offer_20_redemption_date,offer_21_id,offer_21_data_usage,offer_21_ttl,offer_21_redemption_date,offer_22_id,offer_22_data_usage,offer_22_ttl,offer_22_redemption_date,offer_23_id,offer_23_data_usage,offer_23_ttl,offer_23_redemption_date,offer_24_id,offer_24_data_usage,offer_24_ttl,offer_24_redemption_date,offer_25_id,offer_25_data_usage,offer_25_ttl,offer_25_redemption_date,offer_26_id,offer_26_data_usage,offer_26_ttl,offer_26_redemption_date,offer_27_id,offer_27_data_usage,offer_27_ttl,offer_27_redemption_date,offer_28_id,offer_28_data_usage,offer_28_ttl,offer_28_redemption_date,offer_29_id,offer_29_data_usage,offer_29_ttl,offer_29_redemption_date,offer_30_id,offer_30_data_usage,offer_30_ttl,offer_30_redemption_date,offer_31_id,offer_31_data_usage,offer_31_ttl,offer_31_redemption_date,offer_32_id,offer_32_data_usage,offer_32_ttl,offer_32_redemption_date,offer_33_id,offer_33_data_usage,offer_33_ttl,offer_33_redemption_date,offer_34_id,offer_34_data_usage,offer_34_ttl,offer_34_redemption_date,offer_35_id,offer_35_data_usage,offer_35_ttl,offer_35_redemption_date,offer_36_id,offer_36_data_usage,offer_36_ttl,offer_36_redemption_date,offer_37_id,offer_37_data_usage,offer_37_ttl,offer_37_redemption_date,offer_38_id,offer_38_data_usage,offer_38_ttl,offer_38_redemption_date,offer_39_id,offer_39_data_usage,offer_39_ttl,offer_39_redemption_date,offer_40_id,offer_40_data_usage,offer_40_ttl,offer_40_redemption_date,offer_41_id,offer_41_data_usage,offer_41_ttl,offer_41_redemption_date,offer_42_id,offer_42_data_usage,offer_42_ttl,offer_42_redemption_date,offer_43_id,offer_43_data_usage,offer_43_ttl,offer_43_redemption_date,offer_44_id,offer_44_data_usage,offer_44_ttl,offer_44_redemption_date,offer_45_id,offer_45_data_usage,offer_45_ttl,offer_45_redemption_date,offer_46_id,offer_46_data_usage,offer_46_ttl,offer_46_redemption_date,offer_47_id,offer_47_data_usage,offer_47_ttl,offer_47_redemption_date,offer_48_id,offer_48_data_usage,offer_48_ttl,offer_48_redemption_date,offer_49_id,offer_49_data_usage,offer_49_ttl,offer_49_redemption_date,offer_50_id,offer_50_data_usage,offer_50_ttl,offer_50_redemption_date) AS
SELECT pcrf_transaction_id,
       offer_01_id, offer_01_data_usage, offer_01_ttl, offer_01_redemption_date,
	   offer_02_id, offer_02_data_usage, offer_02_ttl, offer_02_redemption_date,
	   offer_03_id, offer_03_data_usage, offer_03_ttl, offer_03_redemption_date,
	   offer_04_id, offer_04_data_usage, offer_04_ttl, offer_04_redemption_date,
	   offer_05_id, offer_05_data_usage, offer_05_ttl, offer_05_redemption_date,
	   offer_06_id, offer_06_data_usage, offer_06_ttl, offer_06_redemption_date,
	   offer_07_id, offer_07_data_usage, offer_07_ttl, offer_07_redemption_date,
	   offer_08_id, offer_08_data_usage, offer_08_ttl, offer_08_redemption_date,
	   offer_09_id, offer_09_data_usage, offer_09_ttl, offer_09_redemption_date,
	   offer_10_id, offer_10_data_usage, offer_10_ttl, offer_10_redemption_date,
	   offer_11_id, offer_11_data_usage, offer_11_ttl, offer_11_redemption_date,
	   offer_12_id, offer_12_data_usage, offer_12_ttl, offer_12_redemption_date,
	   offer_13_id, offer_13_data_usage, offer_13_ttl, offer_13_redemption_date,
	   offer_14_id, offer_14_data_usage, offer_14_ttl, offer_14_redemption_date,
	   offer_15_id, offer_15_data_usage, offer_15_ttl, offer_15_redemption_date,
	   offer_16_id, offer_16_data_usage, offer_16_ttl, offer_16_redemption_date,
	   offer_17_id, offer_17_data_usage, offer_17_ttl, offer_17_redemption_date,
	   offer_18_id, offer_18_data_usage, offer_18_ttl, offer_18_redemption_date,
	   offer_19_id, offer_19_data_usage, offer_19_ttl, offer_19_redemption_date,
	   offer_20_id, offer_20_data_usage, offer_20_ttl, offer_20_redemption_date,
	   offer_21_id, offer_21_data_usage, offer_21_ttl, offer_21_redemption_date,
	   offer_22_id, offer_22_data_usage, offer_22_ttl, offer_22_redemption_date,
	   offer_23_id, offer_23_data_usage, offer_23_ttl, offer_23_redemption_date,
	   offer_24_id, offer_24_data_usage, offer_24_ttl, offer_24_redemption_date,
	   offer_25_id, offer_25_data_usage, offer_25_ttl, offer_25_redemption_date,
	   offer_26_id, offer_26_data_usage, offer_26_ttl, offer_26_redemption_date,
	   offer_27_id, offer_27_data_usage, offer_27_ttl, offer_27_redemption_date,
	   offer_28_id, offer_28_data_usage, offer_28_ttl, offer_28_redemption_date,
	   offer_29_id, offer_29_data_usage, offer_29_ttl, offer_29_redemption_date,
	   offer_30_id, offer_30_data_usage, offer_30_ttl, offer_30_redemption_date,
	   offer_31_id, offer_31_data_usage, offer_31_ttl, offer_31_redemption_date,
	   offer_32_id, offer_32_data_usage, offer_32_ttl, offer_32_redemption_date,
	   offer_33_id, offer_33_data_usage, offer_33_ttl, offer_33_redemption_date,
	   offer_34_id, offer_34_data_usage, offer_34_ttl, offer_34_redemption_date,
	   offer_35_id, offer_35_data_usage, offer_35_ttl, offer_35_redemption_date,
	   offer_36_id, offer_36_data_usage, offer_36_ttl, offer_36_redemption_date,
	   offer_37_id, offer_37_data_usage, offer_37_ttl, offer_37_redemption_date,
	   offer_38_id, offer_38_data_usage, offer_38_ttl, offer_38_redemption_date,
	   offer_39_id, offer_39_data_usage, offer_39_ttl, offer_39_redemption_date,
	   offer_40_id, offer_40_data_usage, offer_40_ttl, offer_40_redemption_date,
	   offer_41_id, offer_41_data_usage, offer_41_ttl, offer_41_redemption_date,
	   offer_42_id, offer_42_data_usage, offer_42_ttl, offer_42_redemption_date,
	   offer_43_id, offer_43_data_usage, offer_43_ttl, offer_43_redemption_date,
	   offer_44_id, offer_44_data_usage, offer_44_ttl, offer_44_redemption_date,
	   offer_45_id, offer_45_data_usage, offer_45_ttl, offer_45_redemption_date,
	   offer_46_id, offer_46_data_usage, offer_46_ttl, offer_46_redemption_date,
	   offer_47_id, offer_47_data_usage, offer_47_ttl, offer_47_redemption_date,
	   offer_48_id, offer_48_data_usage, offer_48_ttl, offer_48_redemption_date,
	   offer_49_id, offer_49_data_usage, offer_49_ttl, offer_49_redemption_date,
	   offer_50_id, offer_50_data_usage, offer_50_ttl, offer_50_redemption_date
FROM   (SELECT pcrf_transaction_id,
               offer_id,
               data_usage,
               ttl,
               redemption_date,
               RANK() OVER (PARTITION BY pcrf_transaction_id ORDER BY offer_id, redemption_date) rank
        FROM   x_pcrf_transaction_detail)
PIVOT  ( MAX(offer_id)   AS id,
         MAX(data_usage) AS data_usage,
         MAX(ttl) AS ttl,
         MAX(redemption_date) AS redemption_date FOR (rank) IN ( 1 AS offer_01,
                                                                 2 AS offer_02,
                                                                 3 AS offer_03,
                                                                 4 AS offer_04,
                                                                 5 AS offer_05,
                                                                 6 AS offer_06,
                                                                 7 AS offer_07,
                                                                 8 AS offer_08,
                                                                 9 AS offer_09,
                                                                 10 AS offer_10,
                                                                 11 AS offer_11,
                                                                 12 AS offer_12,
                                                                 13 AS offer_13,
                                                                 14 AS offer_14,
                                                                 15 AS offer_15,
                                                                 16 AS offer_16,
                                                                 17 AS offer_17,
                                                                 18 AS offer_18,
                                                                 19 AS offer_19,
                                                                 20 AS offer_20,
                                                                 21 AS offer_21,
                                                                 22 AS offer_22,
                                                                 23 AS offer_23,
                                                                 24 AS offer_24,
                                                                 25 AS offer_25,
                                                                 26 AS offer_26,
                                                                 27 AS offer_27,
                                                                 28 AS offer_28,
                                                                 29 AS offer_29,
                                                                 30 AS offer_30,
                                                                 31 AS offer_31,
                                                                 32 AS offer_32,
                                                                 33 AS offer_33,
                                                                 34 AS offer_34,
                                                                 35 AS offer_35,
                                                                 36 AS offer_36,
                                                                 37 AS offer_37,
                                                                 38 AS offer_38,
                                                                 39 AS offer_39,
                                                                 40 AS offer_40,
                                                                 41 AS offer_41,
                                                                 42 AS offer_42,
                                                                 43 AS offer_43,
                                                                 44 AS offer_44,
                                                                 45 AS offer_45,
                                                                 46 AS offer_46,
                                                                 47 AS offer_47,
                                                                 48 AS offer_48,
                                                                 49 AS offer_49,
                                                                 50 AS offer_50
                                                               )
       );