CREATE OR REPLACE FORCE VIEW sa.ppe_pc ("NAME",objid) AS
SELECT distinct PC.NAME  , PC.OBJID
FROM TABLE_X_PART_CLASS_PARAMS TP,
            TABLE_PART_CLASS PC,
            TABLE_X_PART_CLASS_VALUES TV
WHERE TV.VALUE2CLASS_PARAM=TP.OBJID
      AND TV.VALUE2PART_CLASS=PC.OBJID
and x_param_name='NON_PPE' and x_param_value='0';