CREATE OR REPLACE FORCE VIEW sa.table_rep_bugs (repl_objid,rep_master_objid,type_label,s_type_label,id_number,owner_name,s_owner_name,"CONDITION",s_condition,status,s_status) AS
select table_replicate.objid, table_replicate.cr_replicate2cr_master,
 table_replicate.release_rev, table_replicate.S_release_rev, table_replicate.id_number,
 table_user.login_name, table_user.S_login_name, table_condition.title, table_condition.S_title,
 table_gbst_elm.title, table_gbst_elm.S_title
 from table_bug table_replicate, table_user, table_condition, table_gbst_elm
 where table_condition.objid = table_replicate.bug_condit2condition
 AND table_gbst_elm.objid = table_replicate.bug_sts2gbst_elm
 AND table_replicate.cr_replicate2cr_master IS NOT NULL
 AND table_user.objid = table_replicate.bug_owner2user
 ;
COMMENT ON TABLE sa.table_rep_bugs IS 'View information of replicate CR. Used by form More Info (335)';
COMMENT ON COLUMN sa.table_rep_bugs.repl_objid IS 'Internal record number';
COMMENT ON COLUMN sa.table_rep_bugs.rep_master_objid IS 'Internal record number';
COMMENT ON COLUMN sa.table_rep_bugs.type_label IS 'Release version fixed in';
COMMENT ON COLUMN sa.table_rep_bugs.id_number IS 'Change request number; generated by auto-numbering';
COMMENT ON COLUMN sa.table_rep_bugs.owner_name IS 'User login name';
COMMENT ON COLUMN sa.table_rep_bugs."CONDITION" IS 'Title of condition';
COMMENT ON COLUMN sa.table_rep_bugs.status IS 'Name of status value';