CREATE OR REPLACE FORCE VIEW sa.table_assoc_bugs (dupl_objid,master_objid,type_label,s_type_label,id_number,owner_name,s_owner_name,"CONDITION",s_condition,status,s_status) AS
select table_duplicate.objid, table_duplicate.duplicate_bug2bug,
 table_duplicate.release_rev, table_duplicate.S_release_rev, table_duplicate.id_number,
 table_user.login_name, table_user.S_login_name, table_condition.title, table_condition.S_title,
 table_gbst_elm.title, table_gbst_elm.S_title
 from table_bug table_duplicate, table_user, table_condition, table_gbst_elm
 where table_user.objid = table_duplicate.bug_owner2user
 AND table_gbst_elm.objid = table_duplicate.bug_sts2gbst_elm
 AND table_duplicate.duplicate_bug2bug IS NOT NULL
 AND table_condition.objid = table_duplicate.bug_condit2condition
 ;
COMMENT ON TABLE sa.table_assoc_bugs IS 'Indexed by object type and property name. Used by form CR (334), CR More Info (335), Customer Info (336)';
COMMENT ON COLUMN sa.table_assoc_bugs.dupl_objid IS 'Internal record number';
COMMENT ON COLUMN sa.table_assoc_bugs.master_objid IS 'Internal record number';
COMMENT ON COLUMN sa.table_assoc_bugs.type_label IS 'Release version fixed in';
COMMENT ON COLUMN sa.table_assoc_bugs.id_number IS 'Change request number; generated by auto-numbering';
COMMENT ON COLUMN sa.table_assoc_bugs.owner_name IS 'User login name';
COMMENT ON COLUMN sa.table_assoc_bugs."CONDITION" IS 'Title of condition';
COMMENT ON COLUMN sa.table_assoc_bugs.status IS 'Name of status value';