CREATE OR REPLACE FORCE VIEW sa.vas_params_view (vas_service_id,vas_name,vas_param_name,vas_param_value,mobile_plan_type,mobile_description,mobile_description2,mobile_description3,mobile_description4,ild_rates_url) AS
SELECT P.OBJID VAS_SERVICE_ID,
    P.VAS_NAME,
    XVP.VAS_PARAM_NAME,
    XVV.VAS_PARAM_VALUE,
    P.MOBILE_PLAN_TYPE_SCRIPT_ID MOBILE_PLAN_TYPE,
    P.Mobile_Desc1_Script_Id MOBILE_DESCRIPTION,
    P.MOBILE_DESC2_SCRIPT_ID MOBILE_DESCRIPTION2,
    P.MOBILE_DESC3_SCRIPT_ID MOBILE_DESCRIPTION3,
    P.MOBILE_DESC4_SCRIPT_ID MOBILE_DESCRIPTION4,
    P.MOBILE_ILD_RATES_LINK ILD_RATES_URL
  FROM X_VAS_PARAMS XVP,
    X_VAS_VALUES XVV,
    X_VAS_PROGRAMS P
  WHERE XVV.VAS_PROGRAMS_OBJID(+) = P.OBJID
  AND XVV.VAS_PARAMS_OBJID    = XVP.OBJID (+)
  ORDER BY P.VAS_NAME,
    XVP.VAS_PARAM_NAME;