CREATE OR REPLACE FORCE VIEW sa.x_score_card_dealer_view_road (score_date,score_name,"ACTIVE",account_open,account_renew,cancellation,account_open_cost,account_renew_cost,cancellation_cost,posa_swipe) AS
select
       sch.score_date score_date,
       decode(decode(fd.flag_type,'T',sch.score_name,'OTHER'),
       'AMES ~ HARDWARE','AMES',
       'AMES DEPARTMENT - HARDWARE (DIP)' , 'AMES',
       'RADIO SHACK FRANCHISE - POSA'  ,'RADIO SHACK FRANCHISE',
       'RADIO SHACK FRAN'              ,'RADIO SHACK FRANCHISE',
       'ECKERD DRUGS CORP.'            ,'ECKERD DRUGS CORP.',
       'ECKERD CORP.  VENDOR 709081'   ,'ECKERD DRUGS CORP.',
       'ECKERDS CORP - MANUAL ORDERS'  ,'ECKERD DRUGS CORP.',
       'LOWES COMPANIES, INC.'         ,'LOWES COMPANIES, INC.',
       'LOWES COMPANIES INC.- POSA'    ,'LOWES COMPANIES, INC.',
       'NATIONAL PREPAID SER'          ,'NATIONAL PREPAID SER',
       'NATIONAL PREPAID WIRELESS-POSA','NATIONAL PREPAID SER',
       'PILOT CORPORATION'             ,'PILOT CORPORATION',
       'PILOT'                         ,'PILOT CORPORATION',
       'JC PENNEY CO - RETAIL'         ,'JC PENNEY RETAIL',
       'JC PENNEY RETAIL'              ,'JC PENNEY RETAIL',
       'WAL-MART STORES','WAL-MART STORES',
       'WAL-MART STORES, INC.','WAL-MART STORES',
       'WAL-MART MANUAL ORDERS','WAL-MART STORES',
       'STAPLES, INC.','STAPLES',
       'STAPLES','STAPLES',
       'JC PENNEY CO- CATALOG 9130','JC PENNEY CATALOG',
       'JC PENNEY CO- CATALOG 9131','JC PENNEY CATALOG',
       'JC PENNEY CO- CATALOG 9132','JC PENNEY CATALOG',
       'JC PENNEY CO- CATALOG 9316','JC PENNEY CATALOG',
       'JC PENNEY CO- CATALOG 9317','JC PENNEY CATALOG',
       'JC PENNEY FACTORY DIRECT'      ,'JC PENNEY CATALOG',
       'CIRCUIT CITY','CIRCUIT CITY',
       'CIRCUIT CITY STORES, INC.','CIRCUIT CITY',
       'CIRCUIT CITY STORES, INC.-HARDWARE','CIRCUIT CITY',
       'TARGET CORPORATION - AIRTIME','TARGET',
       'TARGET CORPORATION - HARDWARE','TARGET',
       'TARGET.DIRECT', 'TARGET',
       'K MART CORPORATION','K MART CORPORATION',
       'K MART CORPORATION - POSA','K MART CORPORATION',
       'K-MART CORPORATION','K MART CORPORATION',
       'K-MART MANUAL ORDERS','K MART CORPORATION',
       'OFFICE DEPOT','OFFICE DEPOT',
       'OFFICE DEPOT (AIRTIME)','OFFICE DEPOT',
       'OFFICE DEPOT (HARDWARE)','OFFICE DEPOT',
       decode(fd.flag_type,'T',sch.score_name,'OTHER')) score_name,
       sum(decode(sch.score_code,'ACTIVE',score_count,0))       ACTIVE,
       sum(decode(sch.score_code,'ACCOUNT OPEN',score_count,0))   Account_Open,
       sum(decode(sch.score_code,'ACCOUNT Renew',score_count,0))   Account_Renew,
       sum(decode(sch.score_code,'ACCOUNT CANCEL',score_count,0)) Cancellation,
       sum(decode(sch.score_code,'ACCOUNT OPEN COST',score_count,0)) Account_open_cost,
       sum(decode(sch.score_code,'ACCOUNT RENEW COST',score_count,0)) Account_Renew_cost,
       sum(decode(sch.score_code,'ACCOUNT CANCEL COST',score_count,0)) Cancellation_cost,
       sum(decode(sch.score_code,'POSA SWIPE COUNT',score_count,0)) POSA_SWIPE
  from (SELECT DISTINCT(name) NAME, flag_type  FROM table_flash_dealer) fd,
       x_score_card_history_ROAD sch
 where fd.name(+) = sch.score_name
   and sch.score_type = 'DEALER'
   -- and sch.score_date = trunc(sysdate -1)
 group by
          sch.score_date,
          decode(decode(fd.flag_type,'T',sch.score_name,'OTHER'),
          'AMES ~ HARDWARE','AMES',
          'AMES DEPARTMENT - HARDWARE (DIP)' , 'AMES',
          'RADIO SHACK FRANCHISE - POSA'  ,'RADIO SHACK FRANCHISE',
          'RADIO SHACK FRAN'              ,'RADIO SHACK FRANCHISE',
          'ECKERD DRUGS CORP.'            ,'ECKERD DRUGS CORP.',
          'ECKERD CORP.  VENDOR 709081'   ,'ECKERD DRUGS CORP.',
          'ECKERDS CORP - MANUAL ORDERS'  ,'ECKERD DRUGS CORP.',
          'LOWES COMPANIES, INC.'         ,'LOWES COMPANIES, INC.',
          'LOWES COMPANIES INC.- POSA'    ,'LOWES COMPANIES, INC.',
          'NATIONAL PREPAID SER'          ,'NATIONAL PREPAID SER',
          'NATIONAL PREPAID WIRELESS-POSA','NATIONAL PREPAID SER',
          'PILOT CORPORATION'             ,'PILOT CORPORATION',
          'PILOT'                         ,'PILOT CORPORATION',
          'JC PENNEY CO - RETAIL'         ,'JC PENNEY RETAIL',
          'JC PENNEY RETAIL'              ,'JC PENNEY RETAIL',
          'WAL-MART STORES','WAL-MART STORES',
          'WAL-MART STORES, INC.','WAL-MART STORES',
          'WAL-MART MANUAL ORDERS','WAL-MART STORES',
          'STAPLES, INC.','STAPLES',
          'STAPLES','STAPLES',
          'JC PENNEY CO- CATALOG 9130','JC PENNEY CATALOG',
          'JC PENNEY CO- CATALOG 9131','JC PENNEY CATALOG',
          'JC PENNEY CO- CATALOG 9132','JC PENNEY CATALOG',
          'JC PENNEY CO- CATALOG 9316','JC PENNEY CATALOG',
          'JC PENNEY CO- CATALOG 9317','JC PENNEY CATALOG',
          'JC PENNEY FACTORY DIRECT'      ,'JC PENNEY CATALOG',
          'CIRCUIT CITY','CIRCUIT CITY',
          'CIRCUIT CITY STORES, INC.','CIRCUIT CITY',
          'CIRCUIT CITY STORES, INC.-HARDWARE','CIRCUIT CITY',
          'TARGET CORPORATION - AIRTIME','TARGET',
          'TARGET CORPORATION - HARDWARE','TARGET',
          'TARGET.DIRECT', 'TARGET',
          'K MART CORPORATION','K MART CORPORATION',
          'K MART CORPORATION - POSA','K MART CORPORATION',
          'K-MART CORPORATION','K MART CORPORATION',
          'K-MART MANUAL ORDERS','K MART CORPORATION',
          'OFFICE DEPOT','OFFICE DEPOT',
          'OFFICE DEPOT (AIRTIME)','OFFICE DEPOT',
          'OFFICE DEPOT (HARDWARE)','OFFICE DEPOT',
          decode(fd.flag_type,'T',sch.score_name,'OTHER'));