CREATE TABLE sa."Activations" (
  npa VARCHAR2(5 BYTE) NOT NULL,
  nxx VARCHAR2(5 BYTE) NOT NULL,
  ratecenter VARCHAR2(15 BYTE) NOT NULL,
  "STATE" VARCHAR2(4 BYTE) NOT NULL,
  "SOURCE" VARCHAR2(4 BYTE) NOT NULL,
  "SWITCH" VARCHAR2(1 BYTE)
);