CREATE TABLE sa.adfcrm_toss_interface_t (
  created_by VARCHAR2(100 BYTE),
  creation_date DATE,
  ff_receive_date DATE,
  last_updated_by VARCHAR2(100 BYTE),
  last_update_date DATE,
  retailer_po_num VARCHAR2(20 BYTE),
  retailer_ship_date DATE,
  retailer_ship_to_address_id VARCHAR2(35 BYTE),
  serial_invalid_date DATE,
  serial_valid_insert_date DATE,
  tf_att_location VARCHAR2(100 BYTE),
  tf_a_keys VARCHAR2(40 BYTE),
  tf_bill_rate NUMBER,
  tf_bill_to_address_id NUMBER,
  tf_card_cost NUMBER,
  tf_card_cost_account VARCHAR2(150 BYTE),
  tf_card_pin_num VARCHAR2(100 BYTE),
  tf_commission_account VARCHAR2(150 BYTE),
  tf_commission_rate NUMBER,
  tf_error_id NUMBER,
  tf_ff_location_code VARCHAR2(100 BYTE),
  tf_ff_location_name VARCHAR2(100 BYTE),
  tf_financials_control_num VARCHAR2(100 BYTE),
  tf_financials_iface_date DATE,
  tf_gl_imported_flag VARCHAR2(3 BYTE),
  tf_invoiced_number NUMBER,
  tf_manuf_location_code VARCHAR2(100 BYTE),
  tf_manuf_location_name VARCHAR2(100 BYTE),
  tf_master_serial_num VARCHAR2(40 BYTE),
  tf_om_transaction_type_id NUMBER,
  tf_om_trans_type_name VARCHAR2(100 BYTE),
  tf_order_id NUMBER(22),
  tf_order_num VARCHAR2(40 BYTE),
  tf_order_price_list_id NUMBER,
  tf_part_num_parent VARCHAR2(100 BYTE),
  tf_part_num_transpose VARCHAR2(100 BYTE),
  tf_part_type VARCHAR2(100 BYTE),
  tf_phone_refurb_date DATE,
  tf_po_num VARCHAR2(100 BYTE),
  tf_receivables_account VARCHAR2(150 BYTE),
  tf_recognized_revenue_account VARCHAR2(150 BYTE),
  tf_redemption_extracted VARCHAR2(3 BYTE),
  tf_retail_rate NUMBER,
  tf_ret_location_code VARCHAR2(100 BYTE),
  tf_ret_location_name VARCHAR2(100 BYTE),
  tf_revenue_account VARCHAR2(150 BYTE),
  tf_serial_num VARCHAR2(100 BYTE),
  toss_att_customer VARCHAR2(100 BYTE),
  toss_att_location VARCHAR2(100 BYTE),
  toss_changed_retailer_id VARCHAR2(100 BYTE),
  toss_changed_retailer_name VARCHAR2(100 BYTE),
  toss_error_code VARCHAR2(100 BYTE),
  toss_extract_date DATE,
  toss_extract_flag VARCHAR2(100 BYTE),
  toss_location_update_date DATE,
  toss_location_update_flag VARCHAR2(40 BYTE),
  toss_phone_activation_date DATE,
  toss_posa_code VARCHAR2(100 BYTE),
  toss_posa_date DATE,
  toss_redemption_code VARCHAR2(100 BYTE),
  toss_redemption_date DATE,
  toss_redemption_extracted VARCHAR2(3 BYTE),
  transceiver_num VARCHAR2(100 BYTE)
);