CREATE TABLE sa.adfcrm_group_transaction_temp (
  objid NUMBER,
  "GROUP_ID" VARCHAR2(50 BYTE),
  group_name VARCHAR2(30 BYTE),
  transaction_type VARCHAR2(50 BYTE),
  web_user_objid VARCHAR2(50 BYTE),
  contact_objid VARCHAR2(50 BYTE),
  esn VARCHAR2(30 BYTE),
  sim VARCHAR2(30 BYTE),
  pin VARCHAR2(30 BYTE),
  zipcode VARCHAR2(50 BYTE),
  service_plan_id VARCHAR2(50 BYTE),
  "PRIORITY" VARCHAR2(50 BYTE),
  brand_name VARCHAR2(50 BYTE),
  insert_date DATE,
  status VARCHAR2(50 BYTE),
  update_date DATE,
  agent_name VARCHAR2(50 BYTE),
  port_current_esn VARCHAR2(50 BYTE),
  port_type VARCHAR2(50 BYTE),
  port_service_provider VARCHAR2(50 BYTE),
  port_current_brand VARCHAR2(50 BYTE),
  port_account_number VARCHAR2(50 BYTE),
  port_password_pin VARCHAR2(50 BYTE),
  port_first_name VARCHAR2(50 BYTE),
  port_last_name VARCHAR2(50 BYTE),
  port_min VARCHAR2(50 BYTE),
  port_last_4_ssn VARCHAR2(50 BYTE),
  port_address VARCHAR2(50 BYTE),
  port_city VARCHAR2(50 BYTE),
  port_state VARCHAR2(50 BYTE),
  port_zipcode VARCHAR2(50 BYTE),
  port_country VARCHAR2(50 BYTE),
  port_phone VARCHAR2(50 BYTE),
  port_email VARCHAR2(50 BYTE),
  case_id VARCHAR2(255 BYTE),
  case_objid VARCHAR2(255 BYTE),
  exchange_partnumber VARCHAR2(30 BYTE)
);
COMMENT ON COLUMN sa.adfcrm_group_transaction_temp.exchange_partnumber IS 'Exchange part number';