CREATE TABLE sa.broken_and_1753_1 (
  part_serial_no VARCHAR2(30 BYTE),
  x_part_inst_status VARCHAR2(20 BYTE),
  rc_redcode VARCHAR2(20 BYTE),
  pi_redcode VARCHAR2(30 BYTE),
  part_num VARCHAR2(30 BYTE),
  x_redeem_units NUMBER,
  revenue NUMBER,
  smp_length NUMBER,
  failed_max_x_red_date DATE,
  failed_x_smp VARCHAR2(30 BYTE),
  red_card2call_trans VARCHAR2(16 BYTE),
  flag VARCHAR2(11 BYTE),
  max_insert_date DATE,
  tf_serial_num VARCHAR2(100 BYTE),
  tf_card_pin_num VARCHAR2(100 BYTE),
  tf_ret_location_code VARCHAR2(100 BYTE),
  tf_ret_location_name VARCHAR2(100 BYTE),
  tf_invoiced_number NUMBER,
  tf_om_trans_type_name VARCHAR2(100 BYTE),
  toss_posa_date DATE,
  toss_posa_code VARCHAR2(100 BYTE),
  toss_redemption_date DATE,
  toss_redemption_code VARCHAR2(100 BYTE),
  tf_retail_rate NUMBER,
  tf_bill_rate NUMBER,
  last_update_date DATE,
  last_updated_by VARCHAR2(100 BYTE)
);
ALTER TABLE sa.broken_and_1753_1 ADD SUPPLEMENTAL LOG GROUP dmtsora128131881_0 (failed_max_x_red_date, failed_x_smp, flag, last_updated_by, last_update_date, max_insert_date, part_num, part_serial_no, pi_redcode, rc_redcode, red_card2call_trans, revenue, smp_length, tf_bill_rate, tf_card_pin_num, tf_invoiced_number, tf_om_trans_type_name, tf_retail_rate, tf_ret_location_code, tf_ret_location_name, tf_serial_num, toss_posa_code, toss_posa_date, toss_redemption_code, toss_redemption_date, x_part_inst_status, x_redeem_units) ALWAYS;