CREATE TABLE sa.carriers (
  ca_id CHAR(7 BYTE) NOT NULL,
  ca_name CHAR(35 BYTE) NOT NULL,
  ca_ad1 CHAR(30 BYTE),
  ca_ad2 CHAR(30 BYTE),
  ca_city CHAR(30 BYTE),
  ca_st CHAR(2 BYTE) NOT NULL,
  ca_zip CHAR(9 BYTE),
  ca_tel CHAR(10 BYTE),
  ca_fax CHAR(10 BYTE),
  ca_fed_id CHAR(10 BYTE),
  ca_side CHAR NOT NULL,
  ca_sys_id CHAR(5 BYTE) NOT NULL,
  ca_ipch CHAR(4 BYTE) NOT NULL,
  ca_lock CHAR(4 BYTE) NOT NULL,
  ca_pers CHAR(5 BYTE) NOT NULL,
  ca_rest_ov1 CHAR,
  ca_rest_ov2 CHAR,
  ca_rest_ov3 CHAR,
  ca_rest_ov4 CHAR,
  ca_ph_ov CHAR,
  ca_pin_req CHAR,
  ca_agent_id CHAR(7 BYTE),
  ca_market CHAR(3 BYTE),
  ca_bill_co CHAR(30 BYTE),
  ca_cutoff_d CHAR(2 BYTE),
  ca_m_bil_cycle CHAR(2 BYTE),
  ca_pay_terms CHAR(2 BYTE),
  ca_bill_form CHAR(10 BYTE),
  ca_cost_d_bil NUMBER(5,2),
  ca_act_fee NUMBER(5,2),
  ca_access_fee NUMBER(5,2),
  ca_tunit_cost NUMBER(5,2),
  ca_ld_carrier CHAR(3 BYTE),
  ca_auto_renew CHAR,
  ca_cont_len NUMBER(10),
  ca_early_dis_t CHAR(4 BYTE),
  ca_early_dis_am NUMBER(5,2),
  ca_temp_dis_po CHAR,
  ca_temp_dis_fee NUMBER(5,2),
  ca_react_serv NUMBER(5,2),
  ca_resp_fraud CHAR,
  ca_rec_start_d DATE NOT NULL,
  ca_modif DATE NOT NULL,
  ca_rec_end_d DATE,
  ca_hold_num NUMBER(10),
  ident_id NUMBER(18) NOT NULL,
  ca_change_pers NUMBER(10),
  ca_description VARCHAR2(60 BYTE),
  ca_line_expiration_days NUMBER(10)
);
ALTER TABLE sa.carriers ADD SUPPLEMENTAL LOG GROUP dmtsora301945356_0 (ca_access_fee, ca_act_fee, ca_ad1, ca_ad2, ca_agent_id, ca_bill_co, ca_bill_form, ca_city, ca_cost_d_bil, ca_cutoff_d, ca_fax, ca_fed_id, ca_id, ca_ipch, ca_ld_carrier, ca_lock, ca_market, ca_m_bil_cycle, ca_name, ca_pay_terms, ca_pers, ca_ph_ov, ca_pin_req, ca_rest_ov1, ca_rest_ov2, ca_rest_ov3, ca_rest_ov4, ca_side, ca_st, ca_sys_id, ca_tel, ca_tunit_cost, ca_zip) ALWAYS;
ALTER TABLE sa.carriers ADD SUPPLEMENTAL LOG GROUP dmtsora301945356_1 (ca_auto_renew, ca_change_pers, ca_cont_len, ca_description, ca_early_dis_am, ca_early_dis_t, ca_hold_num, ca_line_expiration_days, ca_modif, ca_react_serv, ca_rec_end_d, ca_rec_start_d, ca_resp_fraud, ca_temp_dis_fee, ca_temp_dis_po, ident_id) ALWAYS;