CREATE TABLE sa.case_err_bk (
  s_x_case_type VARCHAR2(25 BYTE),
  title VARCHAR2(30 BYTE),
  s_creation_time DATE,
  s_id_number NUMBER(38),
  s_phone_num VARCHAR2(20 BYTE),
  s_case_history LONG,
  s_case_originator2user VARCHAR2(20 BYTE),
  s_case_orig_first_name VARCHAR2(40 BYTE),
  s_case_orig_last_name VARCHAR2(40 BYTE),
  s_case_orig_phone VARCHAR2(40 BYTE),
  cust_id VARCHAR2(20 BYTE),
  s_priority VARCHAR2(3 BYTE),
  s_respsvrty2gbst_elm VARCHAR2(3 BYTE),
  s_sts2gbst_elm VARCHAR2(7 BYTE),
  s_address VARCHAR2(200 BYTE),
  s_address2 VARCHAR2(200 BYTE),
  s_city VARCHAR2(30 BYTE),
  s_state VARCHAR2(40 BYTE),
  s_zipcode VARCHAR2(20 BYTE),
  s_case_state2condition VARCHAR2(4 BYTE),
  s_description VARCHAR2(25 BYTE),
  s_calltype2gbst_elm VARCHAR2(10 BYTE),
  s_x_esn NUMBER(38),
  s_x_min NUMBER(38),
  s_install_date DATE,
  s_condition NUMBER(38),
  s_wipbin_time DATE,
  s_queue_time DATE,
  s_title VARCHAR2(4 BYTE),
  s_s_title VARCHAR2(4 BYTE),
  s_x_sequence_num NUMBER(38),
  s_dispatch_time DATE,
  s_first_resp_time DATE,
  s_act_code NUMBER(38),
  s_entry_time DATE,
  s_addnl_info VARCHAR2(255 BYTE),
  entry_name22gbst_elm VARCHAR2(8 BYTE),
  s_act_entry2user VARCHAR2(30 BYTE),
  case_wip2wipbin VARCHAR2(7 BYTE),
  error_text VARCHAR2(2000 BYTE)
);
ALTER TABLE sa.case_err_bk ADD SUPPLEMENTAL LOG GROUP dmtsora262885901_0 (cust_id, s_act_code, s_address, s_address2, s_calltype2gbst_elm, s_case_originator2user, s_case_orig_first_name, s_case_orig_last_name, s_case_orig_phone, s_case_state2condition, s_city, s_condition, s_creation_time, s_description, s_dispatch_time, s_first_resp_time, s_id_number, s_install_date, s_phone_num, s_priority, s_queue_time, s_respsvrty2gbst_elm, s_state, s_sts2gbst_elm, s_s_title, s_title, s_wipbin_time, s_x_case_type, s_x_esn, s_x_min, s_x_sequence_num, s_zipcode, title) ALWAYS;
ALTER TABLE sa.case_err_bk ADD SUPPLEMENTAL LOG GROUP dmtsora262885901_1 (case_wip2wipbin, entry_name22gbst_elm, error_text, s_act_entry2user, s_addnl_info, s_entry_time) ALWAYS;