CREATE TABLE sa.clfy_ofs_ship_info_stg (
  order_number VARCHAR2(40 BYTE),
  ship_to_name VARCHAR2(150 BYTE),
  bill_of_lading VARCHAR2(25 BYTE),
  container_number VARCHAR2(26 BYTE),
  carrier_scac_code VARCHAR2(30 BYTE),
  ship_from_address1 VARCHAR2(240 BYTE),
  ship_from_address2 VARCHAR2(240 BYTE),
  ship_from_city VARCHAR2(60 BYTE),
  ship_from_state VARCHAR2(60 BYTE),
  ship_from_postal VARCHAR2(60 BYTE),
  asn_type_code VARCHAR2(5 BYTE),
  tf_serial_num VARCHAR2(100 BYTE),
  tf_order_num VARCHAR2(40 BYTE),
  tf_part_num_transpose VARCHAR2(100 BYTE),
  tf_invoiced_number NUMBER,
  tf_part_type VARCHAR2(100 BYTE),
  tf_po_num VARCHAR2(100 BYTE),
  retailer_ship_date DATE,
  ff_receive_date DATE,
  tf_ff_location_name VARCHAR2(100 BYTE),
  tf_ff_location_code VARCHAR2(100 BYTE),
  tf_ret_location_code VARCHAR2(100 BYTE),
  tf_ret_location_name VARCHAR2(100 BYTE),
  tf_part_num_parent VARCHAR2(100 BYTE)
);