CREATE TABLE sa.clfy_ofs_main_rpt_stg (
  esn VARCHAR2(30 BYTE),
  part_inst_status VARCHAR2(20 BYTE),
  toss_posa_action VARCHAR2(40 BYTE),
  retailer VARCHAR2(80 BYTE),
  dealer_id VARCHAR2(80 BYTE),
  last_transact_date DATE,
  last_action_text VARCHAR2(20 BYTE),
  x_result VARCHAR2(20 BYTE),
  install_date DATE,
  service_end_dt DATE,
  contact_name VARCHAR2(61 BYTE),
  phone VARCHAR2(20 BYTE),
  tf_serial_num VARCHAR2(100 BYTE),
  ship_to_name VARCHAR2(150 BYTE),
  cust_trx_type_id NUMBER(15),
  invoice_number VARCHAR2(20 BYTE),
  trx_date DATE,
  purchase_order VARCHAR2(50 BYTE),
  order_number VARCHAR2(40 BYTE),
  tf_part_num_transpose VARCHAR2(100 BYTE),
  ff_receive_date DATE,
  tf_ff_location_name VARCHAR2(100 BYTE),
  tf_ff_location_code VARCHAR2(100 BYTE),
  tf_ret_location_code VARCHAR2(100 BYTE),
  tf_ret_location_name VARCHAR2(100 BYTE),
  bill_of_lading VARCHAR2(25 BYTE),
  container_number VARCHAR2(26 BYTE),
  carrier_scac_code VARCHAR2(30 BYTE),
  ship_from_address1 VARCHAR2(240 BYTE),
  ship_from_address2 VARCHAR2(240 BYTE),
  ship_from_city VARCHAR2(60 BYTE),
  ship_from_state VARCHAR2(60 BYTE),
  ship_from_postal VARCHAR2(60 BYTE),
  asn_type_code VARCHAR2(5 BYTE),
  retailer_ship_date DATE,
  tf_po_num VARCHAR2(100 BYTE)
);