CREATE TABLE sa.create_dealer_stg (
  master_agent_id VARCHAR2(50 BYTE),
  master_agent_name VARCHAR2(50 BYTE),
  first_name VARCHAR2(20 BYTE),
  last_name VARCHAR2(20 BYTE),
  email_id VARCHAR2(50 BYTE),
  "ROLE" VARCHAR2(50 BYTE),
  pin VARCHAR2(15 BYTE),
  "TYPE" VARCHAR2(50 BYTE),
  business_name VARCHAR2(50 BYTE),
  phone VARCHAR2(10 BYTE),
  address VARCHAR2(100 BYTE),
  city VARCHAR2(50 BYTE),
  "STATE" VARCHAR2(3 BYTE),
  zip VARCHAR2(5 BYTE),
  tax_id VARCHAR2(50 BYTE),
  spiff_code VARCHAR2(50 BYTE),
  "PASSWORD" VARCHAR2(10 BYTE),
  status_message VARCHAR2(1000 BYTE),
  update_date DATE,
  request_type VARCHAR2(1 BYTE),
  sd_ticket VARCHAR2(25 BYTE),
  insert_user VARCHAR2(50 BYTE),
  insert_date DATE
);