CREATE TABLE sa.dbautl_table_part_num_hist (
  objid NUMBER,
  notes VARCHAR2(255 BYTE),
  description VARCHAR2(255 BYTE),
  s_description VARCHAR2(255 BYTE),
  domain VARCHAR2(40 BYTE),
  s_domain VARCHAR2(40 BYTE),
  part_number VARCHAR2(30 BYTE),
  s_part_number VARCHAR2(30 BYTE),
  model_num VARCHAR2(20 BYTE),
  s_model_num VARCHAR2(20 BYTE),
  "ACTIVE" VARCHAR2(20 BYTE),
  std_warranty NUMBER,
  warr_start_key NUMBER,
  unit_measure VARCHAR2(8 BYTE),
  sn_track NUMBER,
  "FAMILY" VARCHAR2(20 BYTE),
  line VARCHAR2(20 BYTE),
  repair_type VARCHAR2(20 BYTE),
  part_type VARCHAR2(20 BYTE),
  weight VARCHAR2(20 BYTE),
  "DIMENSION" VARCHAR2(20 BYTE),
  dom_serialno NUMBER,
  dom_uniquesn NUMBER,
  dom_catalogs NUMBER,
  dom_boms NUMBER,
  dom_at_site NUMBER,
  dom_at_parts NUMBER,
  dom_at_domain NUMBER,
  dom_pt_used_bom NUMBER,
  dom_pt_used_dom NUMBER,
  dom_pt_used_warn NUMBER,
  incl_domain VARCHAR2(40 BYTE),
  is_sppt_prog NUMBER,
  prog_type NUMBER,
  dom_literature NUMBER,
  p_standalone NUMBER,
  p_as_parent NUMBER,
  p_as_child NUMBER,
  dom_is_service NUMBER,
  dev NUMBER,
  struct_type NUMBER,
  x_manufacturer VARCHAR2(20 BYTE),
  x_retailcost NUMBER(8,2),
  x_redeem_days NUMBER,
  x_redeem_units NUMBER,
  x_dll NUMBER,
  x_programmable_flag NUMBER,
  x_card_type VARCHAR2(20 BYTE),
  x_purch_qty NUMBER,
  x_purch_card NUMBER,
  x_technology VARCHAR2(20 BYTE),
  x_upc VARCHAR2(30 BYTE),
  x_web_description VARCHAR2(255 BYTE),
  x_display_seq NUMBER,
  x_web_card_desc VARCHAR2(100 BYTE),
  x_card_plan VARCHAR2(30 BYTE),
  x_wholesale_price NUMBER(8,2),
  x_sp_web_card_desc VARCHAR2(100 BYTE),
  x_product_code VARCHAR2(10 BYTE),
  x_sourcesystem VARCHAR2(30 BYTE),
  x_restricted_use NUMBER,
  x_cardless_bundle VARCHAR2(30 BYTE),
  part_num2part_class NUMBER,
  part_num2domain NUMBER,
  part_num2site NUMBER,
  x_exch_digital2part_num NUMBER,
  part_num2default_preload NUMBER,
  part_num2x_promotion NUMBER,
  x_extd_warranty NUMBER,
  x_ota_allowed VARCHAR2(10 BYTE),
  x_ota_dll VARCHAR2(10 BYTE),
  x_ild_type NUMBER,
  x_data_capable NUMBER,
  x_conversion NUMBER(19,4),
  x_meid_phone NUMBER,
  part_num2x_data_config NUMBER,
  part_num2bus_org NUMBER,
  device_lock_state VARCHAR2(30 BYTE),
  delete_dt TIMESTAMP,
  delete_by VARCHAR2(50 BYTE)
);