CREATE TABLE sa.dbautl_table_x_click_plan_hist (
  objid NUMBER,
  x_plan_id NUMBER,
  x_click_local NUMBER(4,2),
  x_click_ld NUMBER(4,2),
  x_click_rl NUMBER(4,2),
  x_click_rld NUMBER(4,2),
  x_grace_period NUMBER,
  x_is_default VARCHAR2(20 BYTE),
  x_status NUMBER,
  click_plan2dealer NUMBER,
  click_plan2carrier NUMBER,
  x_click_home_intl NUMBER(4,2),
  x_click_in_sms NUMBER(4,2),
  x_click_out_sms NUMBER(4,2),
  x_click_roam_intl NUMBER(4,2),
  x_click_type VARCHAR2(50 BYTE),
  x_grace_period_in NUMBER,
  x_home_inbound NUMBER(4,2),
  x_roam_inbound NUMBER(4,2),
  click_plan2part_num NUMBER,
  x_browsing_rate NUMBER(19,4),
  x_bus_org VARCHAR2(20 BYTE),
  x_mms_inbound NUMBER(19,4),
  x_mms_outbound NUMBER(19,4),
  x_technology VARCHAR2(20 BYTE),
  x_click_ild NUMBER(4,2),
  delete_dt TIMESTAMP,
  delete_by VARCHAR2(50 BYTE)
);