CREATE TABLE sa.dbautl_x_program_paramts_hist (
  objid NUMBER,
  x_program_name VARCHAR2(40 BYTE),
  x_program_desc VARCHAR2(1000 BYTE),
  x_type VARCHAR2(10 BYTE),
  x_csr_channel NUMBER,
  x_ivr_channel NUMBER,
  x_web_channel NUMBER,
  x_combine_self NUMBER,
  x_combine_other NUMBER,
  x_start_date DATE,
  x_end_date DATE,
  x_grp_esn_count NUMBER,
  x_is_recurring NUMBER,
  x_benefit_days NUMBER,
  x_handset_value VARCHAR2(15 BYTE),
  x_carrmkt_value VARCHAR2(15 BYTE),
  x_carrparent_value VARCHAR2(15 BYTE),
  x_ach_grace_period NUMBER,
  x_add_ph_window NUMBER,
  x_min_unit_rate_minutes NUMBER,
  x_min_unit_rate_cents NUMBER,
  x_grace_period_webcsr NUMBER,
  x_delay_enroll_ach_flag NUMBER,
  x_de_enroll_cutoff_code NUMBER,
  x_delivery_frq_code VARCHAR2(15 BYTE),
  x_first_delivery_date_code VARCHAR2(15 BYTE),
  x_incl_service_days NUMBER,
  x_stack_at_enroll VARCHAR2(10 BYTE),
  x_stack_dur_enroll VARCHAR2(10 BYTE),
  x_vol_deenro_ser_days_less NUMBER,
  x_deenroll_add_ser_days NUMBER,
  x_benefit_cutoff_code NUMBER,
  x_ser_days_float_ach NUMBER,
  x_ser_days_float_nonach NUMBER,
  x_paynow_grace_period_ach NUMBER,
  x_paynow_grace_period_non NUMBER,
  x_sales_tax_flag NUMBER,
  x_sales_tax_charge_cust NUMBER(1),
  x_additional_tax1 NUMBER,
  x_additional_tax2 NUMBER,
  x_charge_frq_code VARCHAR2(15 BYTE),
  x_bill_cyl_shift_days NUMBER,
  x_payment_method_code NUMBER,
  x_low_balance_units NUMBER,
  x_low_balance_dollars NUMBER,
  x_promo_incl_min_at NUMBER,
  x_promo_incl_min_op NUMBER,
  x_promo_incl_min_we NUMBER,
  x_incl_data_units NUMBER,
  x_incl_data_dollors NUMBER,
  x_promo_incr_min_at NUMBER,
  x_promo_incr_min_op NUMBER,
  x_promo_incr_min_we NUMBER,
  x_incr_data_units NUMBER,
  x_incr_data_dollors NUMBER,
  x_add_funds_min NUMBER,
  x_add_funds_max NUMBER,
  x_add_funds_incr NUMBER,
  x_promo_incl_grpmin_at NUMBER,
  x_promo_incl_grpmin_op NUMBER,
  x_promo_incl_grpmin_we NUMBER,
  x_incl_data_grpunits NUMBER,
  x_incl_data_grpdollors NUMBER,
  x_promo_incr_grpmin_at NUMBER,
  x_promo_incr_grpmin_op NUMBER,
  x_promo_incr_grpmin_we NUMBER,
  x_incr_data_grpunits NUMBER,
  x_incr_data_grpdollors NUMBER,
  x_add_grp_funds_min NUMBER,
  x_add_grp_funds_max NUMBER,
  x_add_grp_funds_incr NUMBER,
  x_incr_minutes_dlv_days NUMBER,
  x_incr_minutes_dlv_cyl NUMBER(2),
  x_incr_grp_minutes_dlv_days NUMBER,
  x_incr_grp_minutes_dlv_cyl NUMBER(2),
  prog_param2prtnum_enrlfee NUMBER,
  prog_param2prtnum_monfee NUMBER,
  prog_param2prtnum_grpenrlfee NUMBER,
  prog_param2prtnum_grpmonfee NUMBER,
  prog_param2bus_org NUMBER,
  x_prog_class VARCHAR2(10 BYTE),
  x_e911_tax_flag NUMBER,
  x_e911_tax_charge_cust NUMBER(1),
  x_bill_engine_flag NUMBER,
  x_rules_engine_flag NUMBER,
  x_notify_engine_flag NUMBER,
  x_off_channel NUMBER,
  x_ics_applications VARCHAR2(50 BYTE),
  x_membership_value VARCHAR2(30 BYTE),
  x_promo_group_value VARCHAR2(30 BYTE),
  x_retailer_value VARCHAR2(30 BYTE),
  x_sms_rate NUMBER,
  x_ild NUMBER,
  x_sweep_and_add_flag NUMBER,
  x_free_dial2site NUMBER,
  x_prg_script_id VARCHAR2(30 BYTE),
  x_prg_desc_script_id VARCHAR2(30 BYTE),
  delete_dt TIMESTAMP,
  delete_by VARCHAR2(50 BYTE)
);