CREATE TABLE sa.fix_multiple_min2esn (
  pi_esn_objid NUMBER(*,0),
  pi_esn VARCHAR2(30 BYTE),
  pi_esn_status VARCHAR2(20 BYTE),
  pi_min_objid NUMBER(*,0),
  pi_min VARCHAR2(30 BYTE),
  pi_min_status VARCHAR2(20 BYTE),
  part_to_esn2part_inst NUMBER(*,0),
  part_inst2site_part NUMBER(*,0),
  part_inst2x_pers NUMBER(*,0),
  sp_objid NUMBER(*,0),
  sp_x_service_id VARCHAR2(30 BYTE),
  sp_min VARCHAR2(30 BYTE),
  sp_status VARCHAR2(40 BYTE),
  sp_x_deact_reason VARCHAR2(40 BYTE),
  part_number VARCHAR2(30 BYTE),
  x_expire_dt DATE,
  service_end_dt DATE,
  esn_last_trans_time DATE,
  min_last_trans_time DATE,
  x_technology VARCHAR2(10 BYTE),
  x_refurb_flag NUMBER(*,0),
  carrier_id NUMBER(*,0),
  carrier_status VARCHAR2(30 BYTE),
  x_mkt_submkt_name VARCHAR2(40 BYTE),
  x_parent_name VARCHAR2(30 BYTE),
  x_status VARCHAR2(30 BYTE),
  x_next_available NUMBER(*,0),
  x_no_inventory NUMBER(*,0),
  part_inst2carrier_mkt NUMBER(*,0),
  caseobjid NUMBER(*,0),
  s_title VARCHAR2(80 BYTE),
  ct_objid NUMBER(*,0),
  ct_x_service_id VARCHAR2(30 BYTE),
  ct_x_min VARCHAR2(30 BYTE),
  ct_x_action_text VARCHAR2(30 BYTE),
  ct_x_transact_date DATE,
  ct_x_call_trans2carrier NUMBER(*,0),
  ct_call_trans2site_part NUMBER(*,0),
  ct_x_reason VARCHAR2(30 BYTE),
  task_id VARCHAR2(30 BYTE),
  igt_transaction_id NUMBER(*,0),
  igt_order_type VARCHAR2(30 BYTE),
  igt_esn VARCHAR2(30 BYTE),
  igt_min VARCHAR2(30 BYTE),
  igt_msid VARCHAR2(30 BYTE),
  igt_status VARCHAR2(20 BYTE),
  igt_update_date DATE,
  record_flag VARCHAR2(10 BYTE),
  comment_reason VARCHAR2(2000 BYTE),
  comment_detail VARCHAR2(2000 BYTE),
  run_date DATE,
  fix_date DATE
);