CREATE GLOBAL TEMPORARY TABLE sa.gtt_part_inst (
  objid NUMBER NOT NULL,
  part_good_qty NUMBER,
  part_bad_qty NUMBER,
  part_serial_no VARCHAR2(30 BYTE),
  part_mod VARCHAR2(10 BYTE),
  part_bin VARCHAR2(20 BYTE),
  last_pi_date DATE,
  pi_tag_no VARCHAR2(8 BYTE),
  last_cycle_ct DATE,
  next_cycle_ct DATE,
  last_mod_time DATE,
  last_trans_time DATE,
  transaction_id VARCHAR2(20 BYTE),
  date_in_serv DATE,
  warr_end_date DATE,
  repair_date DATE,
  part_status VARCHAR2(40 BYTE),
  pick_request VARCHAR2(255 BYTE),
  good_res_qty NUMBER,
  bad_res_qty NUMBER,
  dev NUMBER,
  x_insert_date DATE,
  x_sequence NUMBER,
  x_creation_date DATE,
  x_po_num VARCHAR2(30 BYTE),
  x_red_code VARCHAR2(30 BYTE),
  x_domain VARCHAR2(20 BYTE),
  x_deactivation_flag NUMBER,
  x_reactivation_flag NUMBER,
  x_cool_end_date DATE,
  x_part_inst_status VARCHAR2(20 BYTE),
  x_npa VARCHAR2(10 BYTE),
  x_nxx VARCHAR2(10 BYTE),
  x_ext VARCHAR2(10 BYTE),
  x_order_number VARCHAR2(40 BYTE),
  part_inst2inv_bin NUMBER,
  n_part_inst2part_mod NUMBER,
  fulfill2demand_dtl NUMBER,
  part_inst2x_pers NUMBER,
  part_inst2x_new_pers NUMBER,
  part_inst2carrier_mkt NUMBER,
  created_by2user NUMBER,
  status2x_code_table NUMBER,
  part_to_esn2part_inst NUMBER,
  x_part_inst2site_part NUMBER,
  x_ld_processed VARCHAR2(10 BYTE),
  dtl2part_inst NUMBER,
  eco_new2part_inst NUMBER,
  hdr_ind NUMBER,
  x_msid VARCHAR2(30 BYTE),
  x_part_inst2contact NUMBER,
  x_iccid VARCHAR2(30 BYTE),
  x_clear_tank NUMBER,
  x_port_in NUMBER,
  x_hex_serial_no VARCHAR2(30 BYTE),
  x_parent_part_serial_no VARCHAR2(30 BYTE),
  x_wf_mac_id VARCHAR2(50 BYTE),
  cpo_manufacturer VARCHAR2(240 BYTE),
  CONSTRAINT pk_gtt_part_inst PRIMARY KEY (objid)
)
ON COMMIT PRESERVE ROWS;
COMMENT ON TABLE sa.gtt_part_inst IS 'Global Temporary table to hold a part inst dummy record';