CREATE TABLE sa.lrp_template_final (
  carrier_name VARCHAR2(60 BYTE),
  carrier_status VARCHAR2(60 BYTE),
  carrier_status_alt VARCHAR2(30 BYTE),
  carrier_sim VARCHAR2(30 BYTE),
  carrier_change_flag VARCHAR2(1 BYTE),
  carrier_rate_plan VARCHAR2(60 BYTE),
  carrier_mdn VARCHAR2(20 BYTE),
  load_date DATE,
  pi_carrier VARCHAR2(30 BYTE),
  ct_carrier_src VARCHAR2(30 BYTE),
  brand VARCHAR2(40 BYTE),
  pn_part_number VARCHAR2(30 BYTE),
  pc_x_model_number VARCHAR2(30 BYTE),
  net10mp CHAR,
  pn_data_capable NUMBER,
  data_setting VARCHAR2(30 BYTE),
  pi_otaf_x_apn VARCHAR2(30 BYTE),
  pi_otaf_x_apn_new VARCHAR2(30 BYTE),
  pn_x_apn VARCHAR2(30 BYTE),
  pc_x_apn VARCHAR2(30 BYTE),
  pc_non_ppe VARCHAR2(250 BYTE),
  pn_x_dll NUMBER,
  pn_x_technology VARCHAR2(20 BYTE),
  spl_service_plan_desc VARCHAR2(250 BYTE),
  service_plan VARCHAR2(250 BYTE),
  last_redemption_type VARCHAR2(250 BYTE),
  data_source_src VARCHAR2(30 BYTE),
  ct_objid_src NUMBER,
  ct_x_min_src VARCHAR2(30 BYTE),
  ct_x_service_id_src VARCHAR2(30 BYTE),
  ct_x_transact_date_src DATE,
  ct_x_action_type_src VARCHAR2(20 BYTE),
  ct_x_result_src VARCHAR2(20 BYTE),
  ct_x_reason_src VARCHAR2(500 BYTE),
  ct_x_sub_sourcesystem_src VARCHAR2(30 BYTE),
  ct_x_call_trans2carrier_src NUMBER,
  ct_call_trans2site_part_src NUMBER,
  tt_task_id_src VARCHAR2(25 BYTE),
  ct_x_parent_id_src VARCHAR2(30 BYTE),
  ct_x_parent_name_src VARCHAR2(40 BYTE),
  ct_x_carrier_id_src NUMBER,
  ig_mdn_src VARCHAR2(30 BYTE),
  ig_min_src VARCHAR2(30 BYTE),
  ig_msid_src VARCHAR2(30 BYTE),
  ig_esn_src VARCHAR2(30 BYTE),
  ig_rate_plan_src VARCHAR2(60 BYTE),
  ig_transaction_id_src NUMBER,
  ig_action_item_id_src VARCHAR2(30 BYTE),
  ig_creation_date_src DATE,
  ig_update_date_src DATE,
  ig_rate_plan_source_table_src VARCHAR2(30 BYTE),
  sp_x_min_src VARCHAR2(30 BYTE),
  sp_x_msid_src VARCHAR2(30 BYTE),
  sp_x_service_id_src VARCHAR2(30 BYTE),
  sp_part_status_src VARCHAR2(40 BYTE),
  sp_part_status_alt_src VARCHAR2(8 BYTE),
  line_is_active_in_sp_alt_src VARCHAR2(1 BYTE),
  sp_site_part2part_info_src NUMBER,
  sp_install_date_src DATE,
  sp_x_expire_dt_src DATE,
  sp_service_end_dt_src DATE,
  sp_x_deact_reason_src VARCHAR2(30 BYTE),
  sp_x_zipcode_src VARCHAR2(20 BYTE),
  sp_objid_src NUMBER,
  sp_state_value_src VARCHAR2(20 BYTE),
  sp_x_iccid_src VARCHAR2(30 BYTE),
  pi_x_parent_id VARCHAR2(30 BYTE),
  pi_x_parent_name VARCHAR2(40 BYTE),
  pi_x_carrier_id NUMBER,
  pi_grace_period_gsm NUMBER,
  pi_grace_period_cdma NUMBER,
  pi_grace_period_tdma NUMBER,
  pi_grace_period_analog NUMBER,
  pi_canc_susp_days_gsm NUMBER,
  pi_canc_susp_days_cdma NUMBER,
  pi_canc_susp_days_tdma NUMBER,
  pi_canc_susp_days_analog NUMBER,
  pi_canc_susp_flag_gsm NUMBER,
  pi_canc_susp_flag_cdma NUMBER,
  pi_canc_susp_flag_tdma NUMBER,
  pi_canc_susp_flag_analog NUMBER,
  pi_esn_x_part_inst_status VARCHAR2(20 BYTE),
  pi_esn_objid NUMBER,
  pi_mdn_x_part_inst_status VARCHAR2(20 BYTE),
  pi_mdn_objid NUMBER,
  pi_mdn_part_inst2carrier_mkt NUMBER,
  pi_mdn_x_msid VARCHAR2(30 BYTE),
  pi_mdn_x_port_in NUMBER,
  pi_esn_x_iccid VARCHAR2(30 BYTE),
  pi_x_sim_inv_status VARCHAR2(30 BYTE),
  pi_esn_x_hex_serial_no VARCHAR2(30 BYTE),
  ig_min_rp VARCHAR2(30 BYTE),
  ig_msid_rp VARCHAR2(30 BYTE),
  ig_esn_rp VARCHAR2(30 BYTE),
  ig_rate_plan_rp VARCHAR2(60 BYTE),
  ig_transaction_id_rp NUMBER,
  ig_action_item_id_rp VARCHAR2(30 BYTE),
  ig_creation_date_rp DATE,
  ig_update_date_rp DATE,
  ig_rate_plan_date_rp DATE,
  ig_rate_plan_source_table_rp VARCHAR2(60 BYTE),
  lrc_sp_x_min VARCHAR2(30 BYTE),
  lrc_sp_x_service_id VARCHAR2(30 BYTE),
  lrc_sp_objid NUMBER,
  lrc_ct_x_transact_date DATE,
  lrc_ct_objid NUMBER,
  lrc_pn_part_number VARCHAR2(30 BYTE),
  lrc_part_description VARCHAR2(255 BYTE),
  lrc_x_red_date DATE,
  lrc_x_result VARCHAR2(20 BYTE),
  lrc_pn_x_redeem_units NUMBER,
  lrc_pn_x_redeem_days NUMBER,
  lrc_brand VARCHAR2(40 BYTE),
  lrc_source VARCHAR2(30 BYTE),
  ldct_objid NUMBER,
  ldct_x_service_id VARCHAR2(30 BYTE),
  ldct_x_transact_date DATE,
  ldct_x_action_type VARCHAR2(20 BYTE),
  ldct_x_result VARCHAR2(20 BYTE),
  ldct_x_reason VARCHAR2(500 BYTE),
  ldct_x_sub_sourcesystem VARCHAR2(30 BYTE),
  ldct_x_call_trans2carrier NUMBER,
  ldct_call_trans2site_part NUMBER,
  ldct_x_parent_id VARCHAR2(30 BYTE),
  ldct_x_parent_name VARCHAR2(40 BYTE),
  ldct_x_carrier_id NUMBER,
  exception_table_flag VARCHAR2(1 BYTE),
  ldsp_sp_x_min VARCHAR2(30 BYTE),
  ldsp_sp_x_service_id VARCHAR2(30 BYTE),
  ldsp_sp_part_status VARCHAR2(40 BYTE),
  ldsp_sp_site_part2part_info NUMBER,
  ldsp_sp_install_date DATE,
  ldsp_sp_x_expire_dt DATE,
  ldsp_sp_service_end_dt DATE,
  ldsp_sp_x_deact_reason VARCHAR2(30 BYTE),
  ldsp_sp_x_zipcode VARCHAR2(20 BYTE),
  ldsp_sp_objid NUMBER,
  ldsp_sp_state_value VARCHAR2(20 BYTE),
  ldsp_sp_x_iccid VARCHAR2(30 BYTE),
  line_recon_action VARCHAR2(30 BYTE),
  line_recon_rule VARCHAR2(60 BYTE),
  line_recon_status VARCHAR2(30 BYTE),
  rateplan_recon_action VARCHAR2(30 BYTE),
  rateplan_recon_rule VARCHAR2(60 BYTE),
  rateplan_recon_status VARCHAR2(30 BYTE),
  rateplan_recon_new_plan VARCHAR2(60 BYTE)
);