CREATE TABLE sa.national_cards (
  objid NUMBER,
  part_good_qty NUMBER,
  part_bad_qty NUMBER,
  part_serial_no VARCHAR2(30 BYTE),
  part_mod VARCHAR2(10 BYTE),
  part_bin VARCHAR2(20 BYTE),
  last_pi_date DATE,
  pi_tag_no VARCHAR2(8 BYTE),
  last_cycle_ct DATE,
  next_cycle_ct DATE,
  last_mod_time DATE,
  last_trans_time DATE,
  transaction_id VARCHAR2(20 BYTE),
  date_in_serv DATE,
  warr_end_date DATE,
  repair_date DATE,
  part_status VARCHAR2(40 BYTE),
  pick_request VARCHAR2(255 BYTE),
  good_res_qty NUMBER,
  bad_res_qty NUMBER,
  dev NUMBER,
  x_insert_date DATE,
  x_sequence NUMBER,
  x_creation_date DATE,
  x_po_num VARCHAR2(30 BYTE),
  x_red_code VARCHAR2(30 BYTE),
  x_domain VARCHAR2(20 BYTE),
  x_deactivation_flag NUMBER,
  x_reactivation_flag NUMBER,
  x_cool_end_date DATE,
  x_part_inst_status VARCHAR2(20 BYTE),
  x_npa VARCHAR2(10 BYTE),
  x_nxx VARCHAR2(10 BYTE),
  x_ext VARCHAR2(10 BYTE),
  x_order_number VARCHAR2(40 BYTE),
  part_inst2inv_bin NUMBER,
  n_part_inst2part_mod NUMBER,
  fulfill2demand_dtl NUMBER,
  part_inst2x_pers NUMBER,
  part_inst2x_new_pers NUMBER,
  part_inst2carrier_mkt NUMBER,
  created_by2user NUMBER,
  status2x_code_table NUMBER,
  part_to_esn2part_inst NUMBER,
  x_part_inst2site_part NUMBER,
  x_ld_processed VARCHAR2(10 BYTE),
  dtl2part_inst NUMBER,
  eco_new2part_inst NUMBER,
  hdr_ind NUMBER
);
ALTER TABLE sa.national_cards ADD SUPPLEMENTAL LOG GROUP dmtsora395526228_0 (bad_res_qty, date_in_serv, dev, good_res_qty, last_cycle_ct, last_mod_time, last_pi_date, last_trans_time, next_cycle_ct, objid, part_bad_qty, part_bin, part_good_qty, part_mod, part_serial_no, part_status, pick_request, pi_tag_no, repair_date, transaction_id, warr_end_date, x_cool_end_date, x_creation_date, x_deactivation_flag, x_domain, x_insert_date, x_npa, x_nxx, x_part_inst_status, x_po_num, x_reactivation_flag, x_red_code, x_sequence) ALWAYS;
ALTER TABLE sa.national_cards ADD SUPPLEMENTAL LOG GROUP dmtsora395526228_1 (created_by2user, dtl2part_inst, eco_new2part_inst, fulfill2demand_dtl, hdr_ind, n_part_inst2part_mod, part_inst2carrier_mkt, part_inst2inv_bin, part_inst2x_new_pers, part_inst2x_pers, part_to_esn2part_inst, status2x_code_table, x_ext, x_ld_processed, x_order_number, x_part_inst2site_part) ALWAYS;