CREATE TABLE sa.npanxx_bck_010208 (
  npa VARCHAR2(5 BYTE),
  nxx VARCHAR2(5 BYTE),
  carrier_id FLOAT,
  carrier_name VARCHAR2(255 BYTE),
  lead_time FLOAT,
  target_level FLOAT,
  ratecenter VARCHAR2(15 BYTE),
  "STATE" VARCHAR2(4 BYTE),
  carrier_id_description VARCHAR2(255 BYTE),
  "ZONE" VARCHAR2(100 BYTE),
  county VARCHAR2(50 BYTE),
  marketid FLOAT,
  mrkt_area VARCHAR2(33 BYTE),
  "SID" VARCHAR2(10 BYTE),
  technology VARCHAR2(20 BYTE),
  frequency1 NUMBER,
  frequency2 NUMBER,
  bta_mkt_number VARCHAR2(4 BYTE),
  bta_mkt_name VARCHAR2(100 BYTE),
  gsm_tech VARCHAR2(20 BYTE),
  cdma_tech VARCHAR2(20 BYTE),
  tdma_tech VARCHAR2(20 BYTE),
  mnc VARCHAR2(5 BYTE)
);