CREATE TABLE sa.paypal_trr (
  sec_shipping_add_line1 VARCHAR2(255 BYTE),
  sec_shipping_add_line2 VARCHAR2(255 BYTE),
  sec_shipping_add_city VARCHAR2(255 BYTE),
  sec_shipping_add_state VARCHAR2(255 BYTE),
  sec_shipping_add_country VARCHAR2(255 BYTE),
  sec_shipping_add_zip VARCHAR2(255 BYTE),
  load_name VARCHAR2(255 BYTE),
  load_date DATE,
  ch VARCHAR2(255 BYTE),
  transaction_id VARCHAR2(255 BYTE),
  invoice_id VARCHAR2(255 BYTE),
  paypal_reference_id VARCHAR2(255 BYTE),
  paypal_reference_id_type VARCHAR2(255 BYTE),
  transaction_event_code VARCHAR2(255 BYTE),
  transaction_initiation_date VARCHAR2(255 BYTE),
  transaction_completion_date VARCHAR2(255 BYTE),
  transaction_debit_or_credit VARCHAR2(255 BYTE),
  gross_transaction_amount VARCHAR2(255 BYTE),
  gross_transaction_currency VARCHAR2(255 BYTE),
  fee_debit_or_credit VARCHAR2(255 BYTE),
  fee_amount VARCHAR2(255 BYTE),
  fee_currency VARCHAR2(255 BYTE),
  transactional_status VARCHAR2(255 BYTE),
  insurance_amount VARCHAR2(255 BYTE),
  sales_tax_amount VARCHAR2(255 BYTE),
  shipping_amount VARCHAR2(255 BYTE),
  transaction_subject VARCHAR2(255 BYTE),
  transaction_note VARCHAR2(255 BYTE),
  payers_account_id VARCHAR2(255 BYTE),
  payer_address_status VARCHAR2(255 BYTE),
  item_name VARCHAR2(255 BYTE),
  item_id VARCHAR2(255 BYTE),
  option_1_name VARCHAR2(255 BYTE),
  option_1_value VARCHAR2(255 BYTE),
  option_2_name VARCHAR2(255 BYTE),
  option_2_value VARCHAR2(255 BYTE),
  auction_site VARCHAR2(255 BYTE),
  auction_buyer_id VARCHAR2(255 BYTE),
  auction_closing_date VARCHAR2(255 BYTE),
  shipping_address_line1 VARCHAR2(255 BYTE),
  shipping_address_line2 VARCHAR2(255 BYTE),
  shipping_address_city VARCHAR2(255 BYTE),
  shipping_address_state VARCHAR2(255 BYTE),
  shipping_address_zip VARCHAR2(255 BYTE),
  shipping_address_country VARCHAR2(255 BYTE),
  shipping_method VARCHAR2(255 BYTE),
  custom_field VARCHAR2(255 BYTE),
  billing_address_line1 VARCHAR2(255 BYTE),
  billing_address_line2 VARCHAR2(255 BYTE),
  billing_address_city VARCHAR2(255 BYTE),
  billing_address_state VARCHAR2(255 BYTE),
  billing_address_zip VARCHAR2(255 BYTE),
  billing_address_country VARCHAR2(255 BYTE),
  consumer_id VARCHAR2(255 BYTE),
  first_name VARCHAR2(255 BYTE),
  last_name VARCHAR2(255 BYTE),
  consumer_business_name VARCHAR2(255 BYTE),
  card_type VARCHAR2(255 BYTE),
  payment_source VARCHAR2(255 BYTE),
  shipping_name VARCHAR2(255 BYTE),
  authorization_review_status VARCHAR2(255 BYTE),
  protection_eligibility VARCHAR2(255 BYTE),
  payment_tracking_id VARCHAR2(255 BYTE),
  store_id VARCHAR2(255 BYTE),
  terminal_id VARCHAR2(255 BYTE),
  coupons VARCHAR2(255 BYTE),
  special_offers VARCHAR2(255 BYTE),
  loyalty_card_number VARCHAR2(255 BYTE),
  checkout_type VARCHAR2(255 BYTE),
  pl_reference_id VARCHAR2(255 BYTE),
  gift_card_id VARCHAR2(255 BYTE)
);
COMMENT ON COLUMN sa.paypal_trr.transaction_id IS 'Transaction ID of the money moving event. This ID is generated by PayPal exclusively and cannot be altered by merchant.';
COMMENT ON COLUMN sa.paypal_trr.invoice_id IS 'Invoice ID set by merchant with transaction. Uniqueness can be enforced by PayPal when the transaction is created.';
COMMENT ON COLUMN sa.paypal_trr.paypal_reference_id IS 'A PayPal reference ID is defined as a related, pre-existing transaction or event.';
COMMENT ON COLUMN sa.paypal_trr.paypal_reference_id_type IS 'One of the following 3-character codes:ODR: Order ID TXN: Transaction ID SUB: Subscription ID PAP: Preapproved Payment ID';
COMMENT ON COLUMN sa.paypal_trr.transaction_event_code IS 'Transaction event type or ?T-Code.';
COMMENT ON COLUMN sa.paypal_trr.transaction_initiation_date IS 'Date and time the transaction was initiated, in the following format: YYYY/MM/DD HH:MM:SS';
COMMENT ON COLUMN sa.paypal_trr.transaction_completion_date IS 'Date and time the transaction was completed, in the following format: YYYY/MM/DD HH:MM:SS';
COMMENT ON COLUMN sa.paypal_trr.transaction_debit_or_credit IS 'Direction of money movement of gross amount, as one of two literal strings: CR: Credit, DR: Debit';
COMMENT ON COLUMN sa.paypal_trr.gross_transaction_amount IS 'The amount of the payment?before fees?between the two parties. This field contains the gross transaction value for all transactions.';
COMMENT ON COLUMN sa.paypal_trr.gross_transaction_currency IS 'The consumer?s account number generated by PayPal (encrypted hash of the PayPal account number).';
COMMENT ON COLUMN sa.paypal_trr.fee_debit_or_credit IS 'Direction of money-movement for fee, as one of two literal strings: CR: Credit, DR: Debit';
COMMENT ON COLUMN sa.paypal_trr.fee_amount IS 'The record of fees associated with the settlement. All transactional fees are included in this amount. Fees are never amortized across several transactions. This field contains the fee amount value for all transactions where a transactional fee has been processed.';
COMMENT ON COLUMN sa.paypal_trr.fee_currency IS 'Currency of fee';
COMMENT ON COLUMN sa.paypal_trr.transactional_status IS 'A one-character code indicating the transaction status. Possible values are: S, D, P ,V, F';
COMMENT ON COLUMN sa.paypal_trr.insurance_amount IS 'The insurance amount reported by either PayPal or the merchant for the transaction.';
COMMENT ON COLUMN sa.paypal_trr.sales_tax_amount IS 'The sales tax amount reported by either PayPal or the merchant for the transaction';
COMMENT ON COLUMN sa.paypal_trr.shipping_amount IS 'The shipping amount reported by either PayPal or the merchant for the transaction.';
COMMENT ON COLUMN sa.paypal_trr.transaction_subject IS 'Subject of payment as passed through by the Payer to the Payee. This data is controlled by the payer exclusively in the interfaces through which it is sent. The transaction subject is a pass-through of data from the buyer to the merchant. Merchants should make sure to understand how they would like to share special requests, comments, or needs from the customers. It is not recommended to use this field for any special purpose.';
COMMENT ON COLUMN sa.paypal_trr.transaction_note IS 'Special note of payment as passed through by the Payer to the Payee. This data is controlled by the payer exclusively in the interfaces through which it is sent. The transaction note is the memo or note variable, a pass-through of data from the buyer to the merchant. Merchants should make sure to understand how they would like to share special requests, comments, or needs from the customers. This field might contain special customer requests, such as shipping instructions. Merchants are encouraged to direct their customers to the best interface for sharing this data during the purchase process.';
COMMENT ON COLUMN sa.paypal_trr.payers_account_id IS 'The email address of the payer in the payment transaction. If there is no payer, this value is blank.';
COMMENT ON COLUMN sa.paypal_trr.payer_address_status IS 'Whether the counterparty!|s shipping address is confirmed. One of two possible values: Y , N';
COMMENT ON COLUMN sa.paypal_trr.item_name IS 'Specified by buyer in the website Auction/Item Title field. Specified by seller in any of the following button-creation fields (item_name or item_name_x): PayPal Shopping Cart Item Name,Buy Now Item Name,Donations Item Name,Subscriptions Name';
COMMENT ON COLUMN sa.paypal_trr.item_id IS 'Specified by buyer in the website Auction/Item Title field. Specified by seller in any of the following button-creation fields (item_name or item_name_x): PayPal Shopping Cart Item Name,Buy Now Item Name,Donations Item Name,Subscriptions Name';
COMMENT ON COLUMN sa.paypal_trr.option_1_name IS 'Specified by seller in any of the following button-creation fields (on0 or on0_x): PayPal Shopping Cart Option 1 Name , Buy Now Option 1 Name, Subscription Option 1 Name';
COMMENT ON COLUMN sa.paypal_trr.option_1_value IS 'Entered by buyer in any of the following website fields: PayPal Shopping Cart Option 1 Value, Buy Now Option 1 Value,Subscription Option 1 Value,Specified by seller in any of the following button-creation fields:PayPal Shopping Cart Value 1 Choices,Buy Now Value 1 Choices,Subscription Value 1 Choices';
COMMENT ON COLUMN sa.paypal_trr.option_2_name IS 'Specified by seller in any of the following button-creation fields (on0 or on0_x): PayPal Shopping Cart Option 2 Name, Buy Now Option 2 Name, Subscription Option 2 Name';
COMMENT ON COLUMN sa.paypal_trr.option_2_value IS 'Entered by buyer in any of the following website fields: PayPal Shopping Cart Option 2 Value,Buy Now Option 2 Value,Subscription Option 2 Value,Specified by seller in any of the following button-creation fields:PayPal Shopping Cart Value 2 Choices,Buy Now Value 2 Choices,Subscription Value 2 Choices';
COMMENT ON COLUMN sa.paypal_trr.auction_site IS 'Name of Auction Site:eBay,Yahoo! Auctions,uBid.com,Amazon.com Auctions,MSN Auctions,BidVille,Other';
COMMENT ON COLUMN sa.paypal_trr.auction_buyer_id IS 'The ID of the buyer making the purchase in the auction. This ID can be different from the payer ID provided for the payment.';
COMMENT ON COLUMN sa.paypal_trr.auction_closing_date IS 'Closing date of eBay Auction Item. Reported only for eBay Auction Items.';
COMMENT ON COLUMN sa.paypal_trr.shipping_address_line1 IS 'Street address information of shipping address as specified by payer. This information is a pass-through of what was provided by the payer. Merchants should be aware that international addresses might contain non-street information in this field.';
COMMENT ON COLUMN sa.paypal_trr.shipping_address_line2 IS 'Street address information of shipping address as specified by payer. This information is a pass-through of what was provided by the payer. Merchants should be aware that international addresses might contain non-street information in this field.';
COMMENT ON COLUMN sa.paypal_trr.shipping_address_city IS 'City information of shipping address as specified by payer. This information is a pass-through of what was provided by the payer. Merchants should be aware that international addresses might contain non-city information in this field.';
COMMENT ON COLUMN sa.paypal_trr.shipping_address_state IS 'State, province, or territory of shipping address as specified by the payer. This information is a pass-through of what was provided by the purchaser. Merchants should be aware that international addresses may contain non-state information in this field. For example, the purchase might provide a prefecture name or leave the field blank if there is no state equivalent. ';
COMMENT ON COLUMN sa.paypal_trr.shipping_address_zip IS 'Postal code of shipping address as specified by the payer.';
COMMENT ON COLUMN sa.paypal_trr.shipping_address_country IS 'Country of shipping address as specified by the payer.';
COMMENT ON COLUMN sa.paypal_trr.shipping_method IS 'Shipping method associated with this order.';
COMMENT ON COLUMN sa.paypal_trr.custom_field IS 'Custom text set by the merchant with the transaction. Reserved exclusively for merchant use. The custom field differs from the Invoice ID  in that the custom field does not have any uniqueness restrictions, but by this same token is not searchable with PayPal search tools.';
COMMENT ON COLUMN sa.paypal_trr.billing_address_line1 IS 'Street Address information of billauthorized to receive the merchant address and has set the REQBILLINGADDRESS field in the either SetExpressCheckout or SetBillingAddressCustomer request. Otherwise, this field is blank.';
COMMENT ON COLUMN sa.paypal_trr.billing_address_line2 IS 'Street Address information of billing address of the payer. This information is provided only if the merchant is authorized to receive the merchant address and has set the REQBILLINGADDRESS field in the either SetExpressCheckout or SetBillingAddressCustomer request. Otherwise, this field is blank.';
COMMENT ON COLUMN sa.paypal_trr.billing_address_city IS 'City information of billing address of the payer. This information is provided only if the merchant is authorized to receive the merchant address and has set the REQBILLINGADDRESS field in the either SetExpressCheckout or SetBillingAddressCustomer request. Otherwise, this field is blank. ';
COMMENT ON COLUMN sa.paypal_trr.billing_address_state IS 'State, province, or territory of billing address of the payer.  This information is provided only if the merchantis authorized to receive the merchant address and has set the REQBILLINGADDRESS field in the either SetExpressCheckout or SetBillingAddressCustomer request. Otherwise, this field is blank.';
COMMENT ON COLUMN sa.paypal_trr.billing_address_zip IS 'Postal code of billing address of the payer. This information is provided only if the merchant is authorized to receive the merchant address and has set the REQBILLINGADDRESS field in the either SetExpressCheckout or SetBillingAddressCustomer request. Otherwise, this field is blank.';
COMMENT ON COLUMN sa.paypal_trr.billing_address_country IS 'Country of Billing address as specified by the payer.';
COMMENT ON COLUMN sa.paypal_trr.consumer_id IS 'The consumer?s account number generated by PayPal (encrypted hash of the PayPal account number).';
COMMENT ON COLUMN sa.paypal_trr.first_name IS 'Consumer?s given name (first name) as recorded in their PayPal account.';
COMMENT ON COLUMN sa.paypal_trr.last_name IS 'Consumer?s given name (Last name) as recorded in their PayPal account.';
COMMENT ON COLUMN sa.paypal_trr.consumer_business_name IS 'Consumer?s business name as recorded in their PayPal account. Business name is included in the TDR as applicable.';
COMMENT ON COLUMN sa.paypal_trr.card_type IS 'Card used in the transaction. Possible values: VISA,MASTERCARD,AMEX,BANKCARD,DISCOVER,DINERS,SWITCH,SOLO,GE,CARTES_BANCIARES,JCB,UNKNOWN';
COMMENT ON COLUMN sa.paypal_trr.payment_source IS 'Payers payment source. Possible values:Others,Direct Credit Card,Express Checkout,Virtual Terminal,PayPal Funds,Instant Transfer,Instant,Non-Instant,eCheck,Credit Card,Electronic Funds Transfer,Direct Debit,Buyer Credit,PayPal Pay Later,Plus Card,eBay MasterCard,PayPal Credit,Virtual Terminal Transaction,Payment with giropay,PayPal Credit,Debit Card';
COMMENT ON COLUMN sa.paypal_trr.shipping_name IS 'The name of the person to whom the item was shipped.';
COMMENT ON COLUMN sa.paypal_trr.authorization_review_status IS 'Indicates the current status of the transaction and whether it is under review. If the transaction is not considered for review, then the value is blank. If it is under review, then the status is either Green or Yellow.01 - Green,02 - Yellow,Blank';
COMMENT ON COLUMN sa.paypal_trr.protection_eligibility IS 'Indicates whether the transaction is eligible for protection.01 - Eligible,02 - Not eligible,03 - Partially eligible';
COMMENT ON COLUMN sa.paypal_trr.payment_tracking_id IS 'Unique ID specified by partners to obtain information about a payment or to request a refund.';