CREATE TABLE sa.paypal_stl (
  transaction_initiation_date DATE,
  transaction_completion_date DATE,
  file_name VARCHAR2(255 BYTE),
  load_date DATE,
  ch VARCHAR2(255 BYTE),
  transaction_id VARCHAR2(255 BYTE),
  invoice_id VARCHAR2(255 BYTE),
  paypal_reference_id VARCHAR2(255 BYTE),
  paypal_reference_id_type VARCHAR2(255 BYTE),
  transaction_event_code VARCHAR2(255 BYTE),
  transaction_debit_or_credit VARCHAR2(255 BYTE),
  gross_transaction_amount VARCHAR2(255 BYTE),
  gross_transaction_currency VARCHAR2(255 BYTE),
  fee_debit_or_credit VARCHAR2(255 BYTE),
  fee_amount VARCHAR2(255 BYTE),
  fee_currency VARCHAR2(255 BYTE),
  custom_field VARCHAR2(255 BYTE),
  consumer_id VARCHAR2(255 BYTE),
  payment_tracking_id VARCHAR2(255 BYTE),
  store_id VARCHAR2(255 BYTE),
  bank_reference_id VARCHAR2(255 BYTE),
  credit_transactional_fee VARCHAR2(255 BYTE),
  credit_promotional_fee VARCHAR2(255 BYTE),
  credit_term VARCHAR2(255 BYTE)
);
COMMENT ON COLUMN sa.paypal_stl.transaction_initiation_date IS 'Date and time the transaction was initiated';
COMMENT ON COLUMN sa.paypal_stl.transaction_completion_date IS 'Date and time the transaction was completed';
COMMENT ON COLUMN sa.paypal_stl.transaction_id IS 'Transaction ID of the money moving event. This ID is generated by PayPal exclusively and cannot be altered by merchant';
COMMENT ON COLUMN sa.paypal_stl.invoice_id IS 'Invoice ID set by merchant with transaction. Uniqueness can be enforced by PayPal when the transaction is created.';
COMMENT ON COLUMN sa.paypal_stl.paypal_reference_id IS 'A PayPal reference ID is defined as a related, preexisting transaction or event.';
COMMENT ON COLUMN sa.paypal_stl.paypal_reference_id_type IS 'One of the following 3-character codes:ODR: Order ID,TXN: Transaction ID,SUB: Subscription ID,PAP: Preapproved Payment ID';
COMMENT ON COLUMN sa.paypal_stl.transaction_event_code IS 'Transaction event type or ?T-Code.?';
COMMENT ON COLUMN sa.paypal_stl.transaction_debit_or_credit IS 'Direction of money movement of gross amount, as  one of two literal strings: CR: Credit DR: Debit';
COMMENT ON COLUMN sa.paypal_stl.gross_transaction_amount IS 'The amount of the payment?before fees?between the two parties. This field contains the gross transaction value for all transactions.';
COMMENT ON COLUMN sa.paypal_stl.gross_transaction_currency IS 'Currency of transaction.';
COMMENT ON COLUMN sa.paypal_stl.fee_debit_or_credit IS 'Direction of money-movement for fee, as one of two literal strings: CR: Credit DR: Debit';
COMMENT ON COLUMN sa.paypal_stl.fee_amount IS 'The record of fees associated with the settlement. All transactional fees are included in this amount. Fees are never amortized across several transactions. This field contains ';
COMMENT ON COLUMN sa.paypal_stl.fee_currency IS 'Currency of fee.';
COMMENT ON COLUMN sa.paypal_stl.custom_field IS 'Custom text set by the merchant with the transaction. Reserved exclusively for merchant use. In the Settlement Report, this field can include the unique ID of payments ';
COMMENT ON COLUMN sa.paypal_stl.consumer_id IS 'Invoice ID that you provided with the transaction. This value is assumed to be unique upon entry into the PayPal transaction database';
COMMENT ON COLUMN sa.paypal_stl.payment_tracking_id IS 'The consumer?s account number generated by PayPal (encrypted hash of the PayPal account number).';