CREATE TABLE sa.pcrf_transaction_offers (
  pcrf_transaction_id NUMBER(22) NOT NULL,
  offer_01_id VARCHAR2(50 BYTE),
  offer_01_data_usage NUMBER,
  offer_01_ttl DATE,
  offer_01_redemption_date DATE,
  offer_02_id VARCHAR2(50 BYTE),
  offer_02_data_usage NUMBER,
  offer_02_ttl DATE,
  offer_02_redemption_date DATE,
  offer_03_id VARCHAR2(50 BYTE),
  offer_03_data_usage NUMBER,
  offer_03_ttl DATE,
  offer_03_redemption_date DATE,
  offer_04_id VARCHAR2(50 BYTE),
  offer_04_data_usage NUMBER,
  offer_04_ttl DATE,
  offer_04_redemption_date DATE,
  offer_05_id VARCHAR2(50 BYTE),
  offer_05_data_usage NUMBER,
  offer_05_ttl DATE,
  offer_05_redemption_date DATE,
  offer_06_id VARCHAR2(50 BYTE),
  offer_06_data_usage NUMBER,
  offer_06_ttl DATE,
  offer_06_redemption_date DATE,
  offer_07_id VARCHAR2(50 BYTE),
  offer_07_data_usage NUMBER,
  offer_07_ttl DATE,
  offer_07_redemption_date DATE,
  offer_08_id VARCHAR2(50 BYTE),
  offer_08_data_usage NUMBER,
  offer_08_ttl DATE,
  offer_08_redemption_date DATE,
  offer_09_id VARCHAR2(50 BYTE),
  offer_09_data_usage NUMBER,
  offer_09_ttl DATE,
  offer_09_redemption_date DATE,
  offer_10_id VARCHAR2(50 BYTE),
  offer_10_data_usage NUMBER,
  offer_10_ttl DATE,
  offer_10_redemption_date DATE,
  offer_11_id VARCHAR2(50 BYTE),
  offer_11_data_usage NUMBER,
  offer_11_ttl DATE,
  offer_11_redemption_date DATE,
  offer_12_id VARCHAR2(50 BYTE),
  offer_12_data_usage NUMBER,
  offer_12_ttl DATE,
  offer_12_redemption_date DATE,
  offer_13_id VARCHAR2(50 BYTE),
  offer_13_data_usage NUMBER,
  offer_13_ttl DATE,
  offer_13_redemption_date DATE,
  offer_14_id VARCHAR2(50 BYTE),
  offer_14_data_usage NUMBER,
  offer_14_ttl DATE,
  offer_14_redemption_date DATE,
  offer_15_id VARCHAR2(50 BYTE),
  offer_15_data_usage NUMBER,
  offer_15_ttl DATE,
  offer_15_redemption_date DATE,
  offer_16_id VARCHAR2(50 BYTE),
  offer_16_data_usage NUMBER,
  offer_16_ttl DATE,
  offer_16_redemption_date DATE,
  offer_17_id VARCHAR2(50 BYTE),
  offer_17_data_usage NUMBER,
  offer_17_ttl DATE,
  offer_17_redemption_date DATE,
  offer_18_id VARCHAR2(50 BYTE),
  offer_18_data_usage NUMBER,
  offer_18_ttl DATE,
  offer_18_redemption_date DATE,
  offer_19_id VARCHAR2(50 BYTE),
  offer_19_data_usage NUMBER,
  offer_19_ttl DATE,
  offer_19_redemption_date DATE,
  offer_20_id VARCHAR2(50 BYTE),
  offer_20_data_usage NUMBER,
  offer_20_ttl DATE,
  offer_20_redemption_date DATE,
  offer_21_id VARCHAR2(50 BYTE),
  offer_21_data_usage NUMBER,
  offer_21_ttl DATE,
  offer_21_redemption_date DATE,
  offer_22_id VARCHAR2(50 BYTE),
  offer_22_data_usage NUMBER,
  offer_22_ttl DATE,
  offer_22_redemption_date DATE,
  offer_23_id VARCHAR2(50 BYTE),
  offer_23_data_usage NUMBER,
  offer_23_ttl DATE,
  offer_23_redemption_date DATE,
  offer_24_id VARCHAR2(50 BYTE),
  offer_24_data_usage NUMBER,
  offer_24_ttl DATE,
  offer_24_redemption_date DATE,
  offer_25_id VARCHAR2(50 BYTE),
  offer_25_data_usage NUMBER,
  offer_25_ttl DATE,
  offer_25_redemption_date DATE,
  offer_26_id VARCHAR2(50 BYTE),
  offer_26_data_usage NUMBER,
  offer_26_ttl DATE,
  offer_26_redemption_date DATE,
  offer_27_id VARCHAR2(50 BYTE),
  offer_27_data_usage NUMBER,
  offer_27_ttl DATE,
  offer_27_redemption_date DATE,
  offer_28_id VARCHAR2(50 BYTE),
  offer_28_data_usage NUMBER,
  offer_28_ttl DATE,
  offer_28_redemption_date DATE,
  offer_29_id VARCHAR2(50 BYTE),
  offer_29_data_usage NUMBER,
  offer_29_ttl DATE,
  offer_29_redemption_date DATE,
  offer_30_id VARCHAR2(50 BYTE),
  offer_30_data_usage NUMBER,
  offer_30_ttl DATE,
  offer_30_redemption_date DATE,
  offer_31_id VARCHAR2(50 BYTE),
  offer_31_data_usage NUMBER,
  offer_31_ttl DATE,
  offer_31_redemption_date DATE,
  offer_32_id VARCHAR2(50 BYTE),
  offer_32_data_usage NUMBER,
  offer_32_ttl DATE,
  offer_32_redemption_date DATE,
  offer_33_id VARCHAR2(50 BYTE),
  offer_33_data_usage NUMBER,
  offer_33_ttl DATE,
  offer_33_redemption_date DATE,
  offer_34_id VARCHAR2(50 BYTE),
  offer_34_data_usage NUMBER,
  offer_34_ttl DATE,
  offer_34_redemption_date DATE,
  offer_35_id VARCHAR2(50 BYTE),
  offer_35_data_usage NUMBER,
  offer_35_ttl DATE,
  offer_35_redemption_date DATE,
  offer_36_id VARCHAR2(50 BYTE),
  offer_36_data_usage NUMBER,
  offer_36_ttl DATE,
  offer_36_redemption_date DATE,
  offer_37_id VARCHAR2(50 BYTE),
  offer_37_data_usage NUMBER,
  offer_37_ttl DATE,
  offer_37_redemption_date DATE,
  offer_38_id VARCHAR2(50 BYTE),
  offer_38_data_usage NUMBER,
  offer_38_ttl DATE,
  offer_38_redemption_date DATE,
  offer_39_id VARCHAR2(50 BYTE),
  offer_39_data_usage NUMBER,
  offer_39_ttl DATE,
  offer_39_redemption_date DATE,
  offer_40_id VARCHAR2(50 BYTE),
  offer_40_data_usage NUMBER,
  offer_40_ttl DATE,
  offer_40_redemption_date DATE,
  offer_41_id VARCHAR2(50 BYTE),
  offer_41_data_usage NUMBER,
  offer_41_ttl DATE,
  offer_41_redemption_date DATE,
  offer_42_id VARCHAR2(50 BYTE),
  offer_42_data_usage NUMBER,
  offer_42_ttl DATE,
  offer_42_redemption_date DATE,
  offer_43_id VARCHAR2(50 BYTE),
  offer_43_data_usage NUMBER,
  offer_43_ttl DATE,
  offer_43_redemption_date DATE,
  offer_44_id VARCHAR2(50 BYTE),
  offer_44_data_usage NUMBER,
  offer_44_ttl DATE,
  offer_44_redemption_date DATE,
  offer_45_id VARCHAR2(50 BYTE),
  offer_45_data_usage NUMBER,
  offer_45_ttl DATE,
  offer_45_redemption_date DATE,
  offer_46_id VARCHAR2(50 BYTE),
  offer_46_data_usage NUMBER,
  offer_46_ttl DATE,
  offer_46_redemption_date DATE,
  offer_47_id VARCHAR2(50 BYTE),
  offer_47_data_usage NUMBER,
  offer_47_ttl DATE,
  offer_47_redemption_date DATE,
  offer_48_id VARCHAR2(50 BYTE),
  offer_48_data_usage NUMBER,
  offer_48_ttl DATE,
  offer_48_redemption_date DATE,
  offer_49_id VARCHAR2(50 BYTE),
  offer_49_data_usage NUMBER,
  offer_49_ttl DATE,
  offer_49_redemption_date DATE,
  offer_50_id VARCHAR2(50 BYTE),
  offer_50_data_usage NUMBER,
  offer_50_ttl DATE,
  offer_50_redemption_date DATE,
  CONSTRAINT pk_pcrf_transaction_offers PRIMARY KEY (pcrf_transaction_id)
);