CREATE TABLE sa.pers (
  pe_id CHAR(5 BYTE) NOT NULL,
  pe_sid CHAR(5 BYTE) NOT NULL,
  pe_s_lsid1 CHAR(5 BYTE),
  pe_s_lsid2 CHAR(5 BYTE),
  pe_s_lsid3 CHAR(5 BYTE),
  pe_s_lsid4 CHAR(5 BYTE),
  pe_s_lsid5 CHAR(5 BYTE),
  pe_s_area1 CHAR(3 BYTE) NOT NULL,
  pe_s_area2 CHAR(3 BYTE),
  pe_s_area3 CHAR(3 BYTE),
  pe_s_area4 CHAR(3 BYTE),
  pe_s_area5 CHAR(3 BYTE),
  pe_s_area6 CHAR(3 BYTE),
  pe_s_area7 CHAR(3 BYTE),
  pe_s_area8 CHAR(3 BYTE),
  pe_s_area9 CHAR(3 BYTE),
  pe_s_area10 CHAR(3 BYTE),
  pe_free_ar1 CHAR(3 BYTE),
  pe_free_ar2 CHAR(3 BYTE),
  pe_free_ar3 CHAR(3 BYTE),
  pe_free_pr1 CHAR(3 BYTE),
  pe_free_pr2 CHAR(3 BYTE),
  pe_free_pr3 CHAR(3 BYTE),
  pe_free_su1 CHAR(4 BYTE),
  pe_free_su2 CHAR(4 BYTE),
  pe_free_su3 CHAR(4 BYTE),
  pe_ld_res0 CHAR NOT NULL,
  pe_ld_res1 CHAR NOT NULL,
  pe_ld_res011 CHAR NOT NULL,
  pe_ld_res_roam CHAR NOT NULL,
  pe_click_h_n CHAR(4 BYTE) NOT NULL,
  pe_click_h_ld CHAR(4 BYTE) NOT NULL,
  pe_click_r_n CHAR(4 BYTE) NOT NULL,
  pe_click_r_ld CHAR(4 BYTE) NOT NULL,
  pe_par1_usa CHAR NOT NULL,
  pe_par2_min CHAR NOT NULL,
  pe_par3_noclk CHAR NOT NULL,
  pe_par4_deb_beep CHAR NOT NULL,
  pe_par5_trac CHAR NOT NULL,
  pe_grace_orig NUMBER(10) NOT NULL,
  pe_date DATE NOT NULL,
  ident_id NUMBER(18) NOT NULL,
  pe_s_lsid6 CHAR(5 BYTE),
  pe_a1_id VARCHAR2(15 BYTE),
  pe_country_code CHAR(4 BYTE),
  pe_click_plan NUMBER(18)
);
ALTER TABLE sa.pers ADD SUPPLEMENTAL LOG GROUP dmtsora1773728049_0 (pe_click_h_ld, pe_click_h_n, pe_click_r_n, pe_free_ar1, pe_free_ar2, pe_free_ar3, pe_free_pr1, pe_free_pr2, pe_free_pr3, pe_free_su1, pe_free_su2, pe_free_su3, pe_id, pe_ld_res0, pe_ld_res011, pe_ld_res1, pe_ld_res_roam, pe_sid, pe_s_area1, pe_s_area10, pe_s_area2, pe_s_area3, pe_s_area4, pe_s_area5, pe_s_area6, pe_s_area7, pe_s_area8, pe_s_area9, pe_s_lsid1, pe_s_lsid2, pe_s_lsid3, pe_s_lsid4, pe_s_lsid5) ALWAYS;
ALTER TABLE sa.pers ADD SUPPLEMENTAL LOG GROUP dmtsora1773728049_1 (ident_id, pe_a1_id, pe_click_plan, pe_click_r_ld, pe_country_code, pe_date, pe_grace_orig, pe_par1_usa, pe_par2_min, pe_par3_noclk, pe_par4_deb_beep, pe_par5_trac, pe_s_lsid6) ALWAYS;