CREATE TABLE sa.ph (
  ph_esn_num CHAR(11 BYTE) NOT NULL,
  ph_esn_hex CHAR(8 BYTE) NOT NULL,
  ph_old_type CHAR(2 BYTE) NOT NULL,
  ph_cust_id CHAR(14 BYTE),
  ph_carrier_id CHAR(7 BYTE),
  ph_cel_num CHAR(10 BYTE),
  ph_debsn CHAR(5 BYTE) NOT NULL,
  ph_odacc CHAR(3 BYTE) NOT NULL,
  ph_counter NUMBER(10) NOT NULL,
  ph_time_redeemed NUMBER(10) NOT NULL,
  ph_grp CHAR(5 BYTE),
  ph_active_due DATE,
  ph_last_red_time NUMBER(10),
  ph_last_red_date DATE,
  ph_def_pers CHAR(5 BYTE) NOT NULL,
  ph_po_num CHAR(10 BYTE),
  ph_ship_dt DATE,
  ph_version CHAR(4 BYTE),
  ph_modif_d DATE,
  ph_red_flag NUMBER(10),
  ph_cloned NUMBER(10),
  ph_cust_po_num CHAR(10 BYTE),
  ph_modif_n NUMBER(10),
  ph_pers CHAR(5 BYTE),
  ph_pers_d DATE,
  ph_alt_cel NUMBER(10),
  ph_dealer_id CHAR(7 BYTE),
  ph_p2g CHAR,
  ph_source VARCHAR2(7 BYTE),
  ph_akey CHAR(26 BYTE),
  ph_host CHAR(10 BYTE),
  ph_oper CHAR(10 BYTE),
  ph_first_code CHAR(25 BYTE),
  ph_notes CHAR(80 BYTE),
  ph_last_phone CHAR(10 BYTE),
  ph_time_flag CHAR(3 BYTE),
  ph_model_num NUMBER(10),
  ident_id NUMBER(18) NOT NULL,
  ph_numof_cards NUMBER(10),
  ph_reset_count NUMBER(10),
  ph_datetime_stamp DATE
);
ALTER TABLE sa.ph ADD SUPPLEMENTAL LOG GROUP dmtsora185878064_0 (ph_active_due, ph_akey, ph_alt_cel, ph_carrier_id, ph_cel_num, ph_cloned, ph_counter, ph_cust_id, ph_cust_po_num, ph_dealer_id, ph_debsn, ph_def_pers, ph_esn_hex, ph_esn_num, ph_first_code, ph_grp, ph_host, ph_last_red_date, ph_last_red_time, ph_modif_d, ph_modif_n, ph_odacc, ph_old_type, ph_oper, ph_p2g, ph_pers, ph_pers_d, ph_po_num, ph_red_flag, ph_ship_dt, ph_source, ph_time_redeemed, ph_version) ALWAYS;
ALTER TABLE sa.ph ADD SUPPLEMENTAL LOG GROUP dmtsora185878064_1 (ident_id, ph_datetime_stamp, ph_last_phone, ph_model_num, ph_notes, ph_numof_cards, ph_reset_count, ph_time_flag) ALWAYS;