CREATE GLOBAL TEMPORARY TABLE sa.quest_sl_temp_explain1 (
  "STATEMENT_ID" VARCHAR2(30 BYTE),
  plan_id NUMBER,
  "TIMESTAMP" DATE,
  remarks VARCHAR2(80 BYTE),
  operation VARCHAR2(30 BYTE),
  options VARCHAR2(255 BYTE),
  object_node VARCHAR2(128 BYTE),
  object_owner VARCHAR2(30 BYTE),
  object_name VARCHAR2(30 BYTE),
  object_alias VARCHAR2(65 BYTE),
  object_instance NUMBER,
  object_type VARCHAR2(30 BYTE),
  optimizer VARCHAR2(255 BYTE),
  search_columns NUMBER,
  "ID" NUMBER,
  parent_id NUMBER,
  "DEPTH" NUMBER,
  position NUMBER,
  "COST" NUMBER,
  "CARDINALITY" NUMBER,
  bytes NUMBER,
  other_tag VARCHAR2(255 BYTE),
  partition_start VARCHAR2(255 BYTE),
  partition_stop VARCHAR2(255 BYTE),
  partition_id NUMBER,
  "OTHER" LONG,
  distribution VARCHAR2(30 BYTE),
  cpu_cost NUMBER(38),
  io_cost NUMBER(38),
  temp_space NUMBER(38),
  access_predicates VARCHAR2(4000 BYTE),
  filter_predicates VARCHAR2(4000 BYTE)
)
ON COMMIT PRESERVE ROWS;