CREATE TABLE sa.react24 (
  ac_x_acct_num VARCHAR2(32 BYTE),
  ah_account_hist2x_account NUMBER,
  cn_first_name VARCHAR2(30 BYTE),
  cn_last_name VARCHAR2(30 BYTE),
  cn_phone VARCHAR2(20 BYTE),
  cn_x_cust_id VARCHAR2(80 BYTE),
  cr_contact_role2contact NUMBER(*,0),
  custsite_objid NUMBER,
  custsite_cust_primaddr2address NUMBER(*,0),
  x_service_id VARCHAR2(30 BYTE),
  objid NUMBER,
  transdate DATE,
  ct_x_service_id VARCHAR2(30 BYTE),
  ct_x_min VARCHAR2(30 BYTE),
  ct_x_transact_date DATE,
  ct_objid NUMBER,
  ct_x_sourcesystem VARCHAR2(30 BYTE),
  ct_x_call_trans2user NUMBER,
  ct_call_trans2site_part NUMBER,
  cd_x_code_name VARCHAR2(20 BYTE),
  sp_install_date DATE,
  sp_x_zipcode VARCHAR2(20 BYTE),
  sp_site_part2x_plan NUMBER,
  sp_state_value VARCHAR2(20 BYTE),
  sp_site_part2site NUMBER,
  sp_objid NUMBER,
  esnpi_x_po_num VARCHAR2(30 BYTE),
  esnpi_n_part_inst2part_mod NUMBER,
  esnpi_part_inst2inv_bin NUMBER,
  esnib_bin_name VARCHAR2(20 BYTE),
  esnst_objid NUMBER,
  esnst_site_id VARCHAR2(80 BYTE),
  esnst_name VARCHAR2(80 BYTE),
  cellpi_x_insert_date DATE,
  cellpi_part_inst2x_pers NUMBER,
  cellpi_objid NUMBER,
  cellpi_part_inst2carrier_mkt NUMBER,
  esnml_part_info2part_num NUMBER(*,0),
  esnpn_objid NUMBER,
  esnpn_part_number VARCHAR2(30 BYTE),
  esnpn_description VARCHAR2(255 BYTE),
  esnpn_x_technology VARCHAR2(20 BYTE),
  ca_objid NUMBER,
  ca_x_carrier_id NUMBER,
  ca_x_mkt_submkt_name VARCHAR2(30 BYTE),
  ca_x_carrier2address NUMBER,
  ca_carrier2carrier_group NUMBER,
  ca_x_act_technology VARCHAR2(20 BYTE),
  ca_x_act_analog NUMBER,
  ca_x_react_technology VARCHAR2(20 BYTE),
  ca_x_react_analog NUMBER,
  cg_objid NUMBER,
  cg_x_carrier_group_id NUMBER,
  cg_x_carrier_name VARCHAR2(30 BYTE),
  cg_x_group2address NUMBER,
  cgadd_address VARCHAR2(200 BYTE),
  cgadd_address_2 VARCHAR2(200 BYTE),
  cgadd_city VARCHAR2(30 BYTE),
  cgadd_state VARCHAR2(40 BYTE),
  cgadd_zipcode VARCHAR2(20 BYTE),
  cmadd_address VARCHAR2(200 BYTE),
  cmadd_address_2 VARCHAR2(200 BYTE),
  cmadd_city VARCHAR2(30 BYTE),
  cmadd_state VARCHAR2(40 BYTE),
  cmadd_zipcode VARCHAR2(20 BYTE),
  us_login_name VARCHAR2(30 BYTE),
  us_objid NUMBER,
  em_first_name VARCHAR2(30 BYTE),
  em_last_name VARCHAR2(30 BYTE),
  custadd_address VARCHAR2(200 BYTE),
  custadd_address_2 VARCHAR2(200 BYTE),
  custadd_city VARCHAR2(30 BYTE),
  custadd_state VARCHAR2(40 BYTE),
  custadd_zipcode VARCHAR2(20 BYTE)
);
ALTER TABLE sa.react24 ADD SUPPLEMENTAL LOG GROUP dmtsora1121495547_2 (custadd_address, custadd_address_2, custadd_city, custadd_state, custadd_zipcode, em_first_name, em_last_name, us_objid) ALWAYS;
ALTER TABLE sa.react24 ADD SUPPLEMENTAL LOG GROUP dmtsora1121495547_1 (ca_carrier2carrier_group, ca_objid, ca_x_act_analog, ca_x_act_technology, ca_x_carrier2address, ca_x_carrier_id, ca_x_mkt_submkt_name, ca_x_react_analog, ca_x_react_technology, cellpi_objid, cellpi_part_inst2carrier_mkt, cellpi_part_inst2x_pers, cellpi_x_insert_date, cgadd_address, cgadd_address_2, cgadd_city, cgadd_state, cgadd_zipcode, cg_objid, cg_x_carrier_group_id, cg_x_carrier_name, cg_x_group2address, cmadd_address, cmadd_address_2, cmadd_city, cmadd_state, cmadd_zipcode, esnml_part_info2part_num, esnpn_description, esnpn_objid, esnpn_part_number, esnpn_x_technology, us_login_name) ALWAYS;
ALTER TABLE sa.react24 ADD SUPPLEMENTAL LOG GROUP dmtsora1121495547_0 (ac_x_acct_num, ah_account_hist2x_account, cd_x_code_name, cn_first_name, cn_last_name, cn_phone, cn_x_cust_id, cr_contact_role2contact, ct_call_trans2site_part, ct_objid, ct_x_call_trans2user, ct_x_min, ct_x_service_id, ct_x_sourcesystem, ct_x_transact_date, custsite_cust_primaddr2address, custsite_objid, esnib_bin_name, esnpi_n_part_inst2part_mod, esnpi_part_inst2inv_bin, esnpi_x_po_num, esnst_name, esnst_objid, esnst_site_id, objid, sp_install_date, sp_objid, sp_site_part2site, sp_site_part2x_plan, sp_state_value, sp_x_zipcode, transdate, x_service_id) ALWAYS;