CREATE TABLE sa.red24 (
  ac_x_acct_num VARCHAR2(32 BYTE),
  ah_account_hist2x_account NUMBER,
  cellpi_part_serial_no VARCHAR2(30 BYTE),
  cellpi_x_insert_date DATE,
  cellpi_part_inst2x_pers NUMBER,
  cellpi_objid NUMBER,
  cellpi_part_inst2carrier_mkt NUMBER,
  ca_objid NUMBER,
  ca_x_carrier_id NUMBER,
  ca_x_mkt_submkt_name VARCHAR2(30 BYTE),
  ca_x_carrier2address NUMBER,
  ca_carrier2carrier_group NUMBER,
  cg_objid NUMBER,
  cg_x_carrier_group_id NUMBER,
  cg_x_carrier_name VARCHAR2(30 BYTE),
  cg_x_group2address NUMBER,
  cgadd_address VARCHAR2(200 BYTE),
  cgadd_address_2 VARCHAR2(200 BYTE),
  cgadd_city VARCHAR2(30 BYTE),
  cgadd_state VARCHAR2(40 BYTE),
  cgadd_zipcode VARCHAR2(20 BYTE),
  cmadd_address VARCHAR2(200 BYTE),
  cmadd_address_2 VARCHAR2(200 BYTE),
  cmadd_city VARCHAR2(30 BYTE),
  cmadd_state VARCHAR2(40 BYTE),
  cmadd_zipcode VARCHAR2(20 BYTE)
);
ALTER TABLE sa.red24 ADD SUPPLEMENTAL LOG GROUP dmtsora935726788_0 (ac_x_acct_num, ah_account_hist2x_account, ca_carrier2carrier_group, ca_objid, ca_x_carrier2address, ca_x_carrier_id, ca_x_mkt_submkt_name, cellpi_objid, cellpi_part_inst2carrier_mkt, cellpi_part_inst2x_pers, cellpi_part_serial_no, cellpi_x_insert_date, cgadd_address, cgadd_address_2, cgadd_city, cgadd_state, cgadd_zipcode, cg_objid, cg_x_carrier_group_id, cg_x_carrier_name, cg_x_group2address, cmadd_address, cmadd_address_2, cmadd_city, cmadd_state, cmadd_zipcode) ALWAYS;