CREATE TABLE sa.sn_pending_warrany_apollo (
  load_date DATE,
  manuf_code VARCHAR2(100 BYTE),
  dp_stream_no VARCHAR2(200 BYTE),
  record_type VARCHAR2(200 BYTE),
  client_batch_id VARCHAR2(200 BYTE),
  consumer_id_number VARCHAR2(80 BYTE),
  consumer_title VARCHAR2(30 BYTE),
  first_name VARCHAR2(30 BYTE),
  last_name VARCHAR2(30 BYTE),
  business_indicator VARCHAR2(200 BYTE),
  business_dba_name VARCHAR2(200 BYTE),
  service_address1 VARCHAR2(200 BYTE),
  service_address2 VARCHAR2(200 BYTE),
  service_city VARCHAR2(30 BYTE),
  service_state VARCHAR2(40 BYTE),
  service_zip VARCHAR2(20 BYTE),
  service_zip4 VARCHAR2(200 BYTE),
  service_country_code VARCHAR2(40 BYTE),
  phone_type1 VARCHAR2(200 BYTE),
  phone VARCHAR2(30 BYTE),
  phone1_usage_type VARCHAR2(200 BYTE),
  phone_type2 VARCHAR2(200 BYTE),
  phone_2 VARCHAR2(200 BYTE),
  phone2_usage_type VARCHAR2(200 BYTE),
  e_mail_address VARCHAR2(80 BYTE),
  language_code VARCHAR2(200 BYTE),
  middle_initial VARCHAR2(3 BYTE),
  dealerid VARCHAR2(200 BYTE),
  contract_number VARCHAR2(200 BYTE),
  contract_purchase_date DATE,
  equipment_purchase_date DATE,
  package_sequence_number VARCHAR2(38 BYTE),
  line_item VARCHAR2(200 BYTE),
  reporting_tag_contract1 VARCHAR2(200 BYTE),
  reporting_tag_contract2 VARCHAR2(200 BYTE),
  model_number VARCHAR2(40 BYTE),
  serial_number VARCHAR2(30 BYTE),
  quantity_sold VARCHAR2(200 BYTE),
  labor_warr VARCHAR2(200 BYTE),
  parts_warr VARCHAR2(200 BYTE),
  product_code VARCHAR2(200 BYTE),
  sku_number VARCHAR2(30 BYTE),
  contract_retail VARCHAR2(30 BYTE),
  equipment_retail VARCHAR2(30 BYTE),
  cancel_request_date VARCHAR2(200 BYTE),
  update_action_code VARCHAR2(200 BYTE),
  sv_pendingwarsales_filename VARCHAR2(30 BYTE)
);