CREATE TABLE sa.table_x_vas_login (
  objid NUMBER,
  x_login RAW(2000),
  x_password RAW(2000),
  x_key VARCHAR2(100 BYTE),
  x_parent_id NUMBER
);
COMMENT ON TABLE sa.table_x_vas_login IS 'THIS TABLE  SAVE THE ENCRYPT USER AND PASSWORD FOR CREDENTIAL BY PARENT_ID.';
COMMENT ON COLUMN sa.table_x_vas_login.objid IS 'OBJID NUMERIC GENERATE INTO THE SCRIPT ';
COMMENT ON COLUMN sa.table_x_vas_login.x_login IS ' IS THE CREDENTIAL USER FOR CARRIER SPECIFIC FOR PARENT ID';
COMMENT ON COLUMN sa.table_x_vas_login.x_password IS 'IS THE CREDENTIAL PASSWORD FOR CARRIER SPECIFIC FOR PARENT ID';
COMMENT ON COLUMN sa.table_x_vas_login.x_key IS 'IS THE KEY THAT ORACLE USE FOR TO ENCRYPT AND DECRYPT DATA ';
COMMENT ON COLUMN sa.table_x_vas_login.x_parent_id IS 'IS THE X_PARENT ID USED FOR ENCRYPT PASSWORD';