CREATE TABLE sa.table_x_promotion_srce (
  objid NUMBER,
  x_promo_code VARCHAR2(10 BYTE),
  x_promo_type VARCHAR2(30 BYTE),
  x_dollar_retail_cost NUMBER(6,2),
  x_start_date DATE,
  x_end_date DATE,
  x_units NUMBER,
  x_access_days NUMBER,
  x_promotion_text VARCHAR2(2000 BYTE),
  x_is_default NUMBER,
  x_sql_statement VARCHAR2(2000 BYTE),
  x_revenue_type VARCHAR2(20 BYTE),
  x_default_type VARCHAR2(15 BYTE),
  x_redeemable NUMBER,
  x_promo_technology VARCHAR2(20 BYTE),
  x_spanish_promo_text VARCHAR2(2000 BYTE),
  x_usage NUMBER,
  x_discount_amount NUMBER(10,2),
  x_discount_percent NUMBER(4,2),
  x_source_system VARCHAR2(7 BYTE),
  x_transaction_type VARCHAR2(20 BYTE),
  x_zip_required NUMBER,
  x_promo_desc VARCHAR2(200 BYTE),
  x_amigo_allowed NUMBER,
  x_program_type NUMBER,
  x_ship_start_date DATE,
  x_ship_end_date DATE,
  x_refurbished_allowed NUMBER,
  x_spanish_short_text VARCHAR2(35 BYTE),
  x_english_short_text VARCHAR2(35 BYTE),
  x_allow_stacking NUMBER,
  x_units_filter VARCHAR2(1000 BYTE),
  x_access_days_filter VARCHAR2(1000 BYTE),
  x_promo_code_filter VARCHAR2(1000 BYTE),
  x_group_name_filter VARCHAR2(1000 BYTE),
  promotion2bus_org NUMBER
);
ALTER TABLE sa.table_x_promotion_srce ADD SUPPLEMENTAL LOG GROUP dmtsora1794142_0 (objid, x_access_days, x_access_days_filter, x_allow_stacking, x_amigo_allowed, x_default_type, x_discount_amount, x_discount_percent, x_dollar_retail_cost, x_end_date, x_english_short_text, x_is_default, x_program_type, x_promo_code, x_promo_code_filter, x_promo_desc, x_promo_technology, x_promo_type, x_redeemable, x_refurbished_allowed, x_revenue_type, x_ship_end_date, x_ship_start_date, x_source_system, x_spanish_promo_text, x_spanish_short_text, x_sql_statement, x_start_date, x_transaction_type, x_units, x_units_filter, x_usage, x_zip_required) ALWAYS;
ALTER TABLE sa.table_x_promotion_srce ADD SUPPLEMENTAL LOG GROUP dmtsora1794142_1 (x_group_name_filter) ALWAYS;