CREATE TABLE sa.table_period_amt (
  objid NUMBER,
  bill_prd_amt NUMBER(19,4),
  prd_start_dt DATE,
  prd_end_dt DATE,
  rec_type NUMBER,
  status NUMBER,
  pay_due_dt DATE,
  last_gen_dt DATE,
  ref_start_dt DATE,
  ref_end_dt DATE,
  contract_id VARCHAR2(80 BYTE),
  s_contract_id VARCHAR2(80 BYTE),
  schedule_id VARCHAR2(40 BYTE),
  s_schedule_id VARCHAR2(40 BYTE),
  schedule_title VARCHAR2(80 BYTE),
  bill_group VARCHAR2(30 BYTE),
  frequency NUMBER,
  bill_option NUMBER,
  item_start_dt DATE,
  item_end_dt DATE,
  due_offset NUMBER,
  cycle_start_dt DATE,
  line_no NUMBER,
  svc_start_date DATE,
  svc_end_date DATE,
  chg_start_dt DATE,
  chg_end_dt DATE,
  quantity NUMBER,
  pro_prc NUMBER(19,4),
  net_prc NUMBER(19,4),
  contr_itm_objid NUMBER,
  cov_site_id VARCHAR2(80 BYTE),
  s_cov_site_id VARCHAR2(80 BYTE),
  part_number VARCHAR2(30 BYTE),
  s_part_number VARCHAR2(30 BYTE),
  unit_measure VARCHAR2(8 BYTE),
  serial_no VARCHAR2(30 BYTE),
  s_serial_no VARCHAR2(30 BYTE),
  currency VARCHAR2(20 BYTE),
  bill_to_site_id VARCHAR2(80 BYTE),
  s_bill_to_site_id VARCHAR2(80 BYTE),
  po_id VARCHAR2(60 BYTE),
  org_id VARCHAR2(40 BYTE),
  s_org_id VARCHAR2(40 BYTE),
  create_dt DATE,
  appl_id VARCHAR2(20 BYTE),
  last_update DATE,
  first_bill_dt DATE,
  extracted_dt DATE,
  extract_trk_id VARCHAR2(20 BYTE),
  status_dt DATE,
  invoice_no VARCHAR2(30 BYTE),
  arch_ind NUMBER,
  gross_prd_amt NUMBER(19,4),
  dev NUMBER,
  period2contr_schedule NUMBER(*,0),
  period2contr_itm NUMBER(*,0),
  gross_amt NUMBER(19,4)
);
ALTER TABLE sa.table_period_amt ADD SUPPLEMENTAL LOG GROUP dmtsora132055990_0 (bill_group, bill_option, bill_prd_amt, chg_end_dt, chg_start_dt, contract_id, contr_itm_objid, cov_site_id, cycle_start_dt, due_offset, frequency, item_end_dt, item_start_dt, last_gen_dt, line_no, net_prc, objid, pay_due_dt, prd_end_dt, prd_start_dt, pro_prc, quantity, rec_type, ref_end_dt, ref_start_dt, schedule_id, schedule_title, status, svc_end_date, svc_start_date, s_contract_id, s_cov_site_id, s_schedule_id) ALWAYS;
ALTER TABLE sa.table_period_amt ADD SUPPLEMENTAL LOG GROUP dmtsora132055990_1 (appl_id, arch_ind, bill_to_site_id, create_dt, currency, dev, extracted_dt, extract_trk_id, first_bill_dt, gross_amt, gross_prd_amt, invoice_no, last_update, org_id, part_number, period2contr_itm, period2contr_schedule, po_id, serial_no, status_dt, s_bill_to_site_id, s_org_id, s_part_number, s_serial_no, unit_measure) ALWAYS;