CREATE TABLE sa.table_num_scheme_base (
  objid NUMBER,
  "NAME" VARCHAR2(50 BYTE),
  "FORMAT" VARCHAR2(64 BYTE),
  start_value NUMBER,
  end_value NUMBER,
  next_value NUMBER,
  value_width NUMBER,
  padded NUMBER,
  date_order NUMBER,
  day_format NUMBER,
  month_format NUMBER,
  year_format NUMBER,
  time_format NUMBER,
  reset_period NUMBER,
  reset_time DATE,
  last_change DATE,
  jan VARCHAR2(8 BYTE),
  feb VARCHAR2(8 BYTE),
  mar VARCHAR2(8 BYTE),
  apr VARCHAR2(8 BYTE),
  may VARCHAR2(8 BYTE),
  jun VARCHAR2(8 BYTE),
  jul VARCHAR2(8 BYTE),
  aug VARCHAR2(8 BYTE),
  sep VARCHAR2(8 BYTE),
  oct VARCHAR2(8 BYTE),
  nov VARCHAR2(8 BYTE),
  "DEC" VARCHAR2(8 BYTE),
  dev NUMBER
);
ALTER TABLE sa.table_num_scheme_base ADD SUPPLEMENTAL LOG GROUP dmtsora1383721205_0 (apr, aug, date_order, day_format, "DEC", dev, end_value, feb, "FORMAT", jan, jul, jun, last_change, mar, may, month_format, "NAME", next_value, nov, objid, oct, padded, reset_period, reset_time, sep, start_value, time_format, value_width, year_format) ALWAYS;