CREATE TABLE sa.table_window_db (
  objid NUMBER,
  title VARCHAR2(255 BYTE),
  "ID" NUMBER,
  top_c NUMBER,
  bottom_c NUMBER,
  left_c NUMBER,
  right_c NUMBER,
  flags NUMBER,
  "TYPE" NUMBER,
  form NUMBER,
  intval1 NUMBER,
  intval2 NUMBER,
  intval3 NUMBER,
  min_width NUMBER,
  min_height NUMBER,
  description VARCHAR2(255 BYTE),
  dimmable NUMBER,
  dialog_name VARCHAR2(40 BYTE),
  ver_clarify VARCHAR2(40 BYTE),
  ver_customer VARCHAR2(40 BYTE),
  base_flag VARCHAR2(20 BYTE),
  "PRELOAD" VARCHAR2(20 BYTE),
  dlg_time_stamp DATE,
  factor_top NUMBER,
  factor_bottom NUMBER,
  factor_left NUMBER,
  factor_right NUMBER,
  ver_cl_srce VARCHAR2(40 BYTE),
  dev NUMBER,
  locale NUMBER,
  backcolor NUMBER,
  banner_color NUMBER,
  banner_icon NUMBER,
  value1 VARCHAR2(80 BYTE)
);
ALTER TABLE sa.table_window_db ADD SUPPLEMENTAL LOG GROUP dmtsora783696026_0 (backcolor, banner_color, banner_icon, base_flag, bottom_c, description, dev, dialog_name, dimmable, dlg_time_stamp, factor_bottom, factor_left, factor_right, factor_top, flags, form, "ID", intval1, intval2, intval3, left_c, locale, min_height, min_width, objid, "PRELOAD", right_c, title, top_c, "TYPE", ver_clarify, ver_cl_srce, ver_customer) ALWAYS;
ALTER TABLE sa.table_window_db ADD SUPPLEMENTAL LOG GROUP dmtsora783696026_1 (value1) ALWAYS;