CREATE TABLE sa.table_csc_incident (
  objid NUMBER,
  requestor_id VARCHAR2(80 BYTE),
  s_requestor_id VARCHAR2(80 BYTE),
  provider_id VARCHAR2(80 BYTE),
  s_provider_id VARCHAR2(80 BYTE),
  current_state NUMBER,
  requestor_severity NUMBER,
  provider_priority NUMBER,
  response_time VARCHAR2(30 BYTE),
  workflow_status VARCHAR2(30 BYTE),
  comments LONG,
  entitled NUMBER,
  ack_ind NUMBER,
  entitle_ind NUMBER,
  confirm_ind NUMBER,
  lack_ind NUMBER,
  wait_ind NUMBER,
  rpt_last VARCHAR2(30 BYTE),
  rpt_first VARCHAR2(30 BYTE),
  rpt_phone VARCHAR2(20 BYTE),
  rpt_fax VARCHAR2(20 BYTE),
  rpt_email VARCHAR2(80 BYTE),
  title VARCHAR2(80 BYTE),
  server_id NUMBER,
  prob_ind NUMBER,
  local_ind NUMBER,
  response_date DATE,
  trans_name VARCHAR2(80 BYTE),
  dev NUMBER,
  entitle2csc_agreement NUMBER(*,0),
  requestor2csc_contact NUMBER(*,0),
  provider2csc_contact NUMBER(*,0),
  incident2csc_org NUMBER(*,0),
  reporter2csc_contact NUMBER(*,0),
  incident2csc_product NUMBER(*,0)
);
ALTER TABLE sa.table_csc_incident ADD SUPPLEMENTAL LOG GROUP dmtsora1851702042_0 (ack_ind, confirm_ind, current_state, dev, entitle2csc_agreement, entitled, entitle_ind, incident2csc_org, lack_ind, local_ind, objid, prob_ind, provider2csc_contact, provider_id, provider_priority, reporter2csc_contact, requestor2csc_contact, requestor_id, requestor_severity, response_date, response_time, rpt_email, rpt_fax, rpt_first, rpt_last, rpt_phone, server_id, s_provider_id, s_requestor_id, title, trans_name, wait_ind, workflow_status) ALWAYS;
ALTER TABLE sa.table_csc_incident ADD SUPPLEMENTAL LOG GROUP dmtsora1851702042_1 (incident2csc_product) ALWAYS;
COMMENT ON TABLE sa.table_csc_incident IS 'Represents a customer support consortium service incident';
COMMENT ON COLUMN sa.table_csc_incident.objid IS 'Internal record number';
COMMENT ON COLUMN sa.table_csc_incident.requestor_id IS 'Service incident s ID that is generated by the requester. This is the official Service Incident ID when referred to by either party';
COMMENT ON COLUMN sa.table_csc_incident.provider_id IS 'Local service incident ID generated by the provider';
COMMENT ON COLUMN sa.table_csc_incident.current_state IS 'The current state of the SERVICE INCIDENT object in the virtual machine. From a user-defined popup list';
COMMENT ON COLUMN sa.table_csc_incident.requestor_severity IS 'The severity of the problem as defined by the requester; Values must be in the range 1-5 with 1 being most sever. Default=1';
COMMENT ON COLUMN sa.table_csc_incident.provider_priority IS 'The priority of the problem as defined by the provider; values must be in the range 1-5 with 1 being most sever. Default=1';
COMMENT ON COLUMN sa.table_csc_incident.response_time IS 'Promised/desired response time to the customer';
COMMENT ON COLUMN sa.table_csc_incident.workflow_status IS 'What the status of this incident is according to the workflow';
COMMENT ON COLUMN sa.table_csc_incident.comments IS 'Text description of the incident';
COMMENT ON COLUMN sa.table_csc_incident.entitled IS 'Whether the incident is entitled to service; i.e., 0=no, 1=yes. This is the entitlement as reported/received';
COMMENT ON COLUMN sa.table_csc_incident.ack_ind IS 'Indicates acknowledgment of the problem submission; i.e., 0=no acknowledgement 1=acknowleged, default=0';
COMMENT ON COLUMN sa.table_csc_incident.entitle_ind IS 'Indicates entitlement for service of the problem submission; i.e., 0=no entitlement 1=entitled, default=0. This is the internal entitlement state.';
COMMENT ON COLUMN sa.table_csc_incident.confirm_ind IS 'Indicates confirmation of close for the problem submission; i.e., 0=not confirmed 1=confimed, default=0';
COMMENT ON COLUMN sa.table_csc_incident.lack_ind IS 'Indicates whether information from requestor is lacking; i.e., 0=not lacking 1=is lacking, default=0';
COMMENT ON COLUMN sa.table_csc_incident.wait_ind IS 'Indicates waiting for confirmation of close for the problem submission; i.e., 0=not waiting 1=waiting, default=0';
COMMENT ON COLUMN sa.table_csc_incident.rpt_last IS 'Original reporting site contact. Contact s last name';
COMMENT ON COLUMN sa.table_csc_incident.rpt_first IS 'Original reporting site contact. Contact s first name';
COMMENT ON COLUMN sa.table_csc_incident.rpt_phone IS 'Original reporting site phone which includes area code, number and extension';
COMMENT ON COLUMN sa.table_csc_incident.rpt_fax IS 'Original reporting site fax number which includes area code, number and extension';
COMMENT ON COLUMN sa.table_csc_incident.rpt_email IS 'Original electronic mail address';
COMMENT ON COLUMN sa.table_csc_incident.title IS 'Title of the CSC incident';
COMMENT ON COLUMN sa.table_csc_incident.server_id IS 'Exchange prodocol server ID number';
COMMENT ON COLUMN sa.table_csc_incident.prob_ind IS 'Indicates if a problem has been submitted; 0=no, 1=yes, default=0';
COMMENT ON COLUMN sa.table_csc_incident.local_ind IS 'Indicates  whether a csc_incident originated; i.e., 0 = no originated remotely, 1 = yes, originated locally. Default=1.';
COMMENT ON COLUMN sa.table_csc_incident.response_date IS 'Date and time by which a response is needed';
COMMENT ON COLUMN sa.table_csc_incident.trans_name IS 'Name of the last transaction which was acknowledged for the Service Incident';
COMMENT ON COLUMN sa.table_csc_incident.dev IS 'Row version number for mobile distribution purposes';
COMMENT ON COLUMN sa.table_csc_incident.entitle2csc_agreement IS 'CSC agreement used for entitlement';
COMMENT ON COLUMN sa.table_csc_incident.requestor2csc_contact IS 'Requestor contact for the incident';
COMMENT ON COLUMN sa.table_csc_incident.provider2csc_contact IS 'Provider contact for the incident';
COMMENT ON COLUMN sa.table_csc_incident.incident2csc_org IS 'Requestor organization for the incident';
COMMENT ON COLUMN sa.table_csc_incident.reporter2csc_contact IS 'Reporter contact for the incident';
COMMENT ON COLUMN sa.table_csc_incident.incident2csc_product IS 'Csc_product involved in the incident';