CREATE TABLE sa.table_site_part_chained_data (
  objid NUMBER,
  instance_name VARCHAR2(80 BYTE),
  serial_no VARCHAR2(30 BYTE),
  s_serial_no VARCHAR2(30 BYTE),
  invoice_no VARCHAR2(30 BYTE),
  ship_date DATE,
  install_date DATE,
  warranty_date DATE,
  quantity NUMBER,
  mdbk VARCHAR2(80 BYTE),
  state_code NUMBER,
  state_value VARCHAR2(20 BYTE),
  modified NUMBER,
  level_to_part NUMBER,
  selected_prd VARCHAR2(5 BYTE),
  part_status VARCHAR2(40 BYTE),
  comments VARCHAR2(255 BYTE),
  level_to_bin NUMBER,
  bin_objid NUMBER,
  site_objid NUMBER,
  inst_objid NUMBER,
  dir_site_objid NUMBER,
  machine_id VARCHAR2(80 BYTE),
  service_end_dt DATE,
  dev NUMBER,
  x_service_id VARCHAR2(30 BYTE),
  x_min VARCHAR2(30 BYTE),
  x_pin VARCHAR2(20 BYTE),
  x_deact_reason VARCHAR2(30 BYTE),
  x_min_change_flag NUMBER,
  x_notify_carrier NUMBER,
  x_expire_dt DATE,
  x_zipcode VARCHAR2(20 BYTE),
  site_part2productbin NUMBER,
  site_part2site NUMBER,
  site_part2site_part NUMBER,
  site_part2part_info NUMBER,
  site_part2primary NUMBER,
  site_part2backup NUMBER,
  all_site_part2site NUMBER,
  site_part2part_detail NUMBER,
  site_part2x_new_plan NUMBER,
  site_part2x_plan NUMBER,
  x_msid VARCHAR2(30 BYTE),
  x_refurb_flag NUMBER,
  cmmtmnt_end_dt DATE,
  instance_id VARCHAR2(30 BYTE),
  site_part_ind NUMBER,
  status_dt DATE,
  x_iccid VARCHAR2(30 BYTE)
);
ALTER TABLE sa.table_site_part_chained_data ADD SUPPLEMENTAL LOG GROUP dmtsora1074532706_0 (bin_objid, comments, dev, dir_site_objid, install_date, instance_name, inst_objid, invoice_no, level_to_bin, level_to_part, machine_id, mdbk, modified, objid, part_status, quantity, selected_prd, serial_no, service_end_dt, ship_date, site_objid, state_code, state_value, s_serial_no, warranty_date, x_deact_reason, x_expire_dt, x_min, x_min_change_flag, x_notify_carrier, x_pin, x_service_id, x_zipcode) ALWAYS;
ALTER TABLE sa.table_site_part_chained_data ADD SUPPLEMENTAL LOG GROUP dmtsora1074532706_1 (all_site_part2site, cmmtmnt_end_dt, instance_id, site_part2backup, site_part2part_detail, site_part2part_info, site_part2primary, site_part2productbin, site_part2site, site_part2site_part, site_part2x_new_plan, site_part2x_plan, site_part_ind, status_dt, x_iccid, x_msid, x_refurb_flag) ALWAYS;