CREATE TABLE sa.table_inv_count (
  objid NUMBER,
  gen_date DATE,
  count_date DATE,
  recount_date DATE,
  tag_count VARCHAR2(40 BYTE),
  tag_recount VARCHAR2(40 BYTE),
  count_part_no VARCHAR2(40 BYTE),
  rev_perpetual VARCHAR2(10 BYTE),
  rev_counted VARCHAR2(10 BYTE),
  sn_perpetual VARCHAR2(30 BYTE),
  sn_counted VARCHAR2(30 BYTE),
  qty_good_perp NUMBER,
  qty_good_count NUMBER,
  qty_bad_perp NUMBER,
  qty_bad_count NUMBER,
  inv_loc_perp VARCHAR2(20 BYTE),
  inv_loc_count VARCHAR2(20 BYTE),
  inv_bin_perp VARCHAR2(20 BYTE),
  inv_bin_count VARCHAR2(20 BYTE),
  std_cost_perp NUMBER(19,4),
  std_cost_count NUMBER(19,4),
  ext_cost_perp NUMBER(19,4),
  ext_cost_count NUMBER(19,4),
  reconcile_date DATE,
  trans_id_out VARCHAR2(40 BYTE),
  trans_id_in VARCHAR2(40 BYTE),
  comments VARCHAR2(255 BYTE),
  status VARCHAR2(40 BYTE),
  blank_tag NUMBER,
  dev NUMBER,
  count2part_inst NUMBER(*,0),
  count2count_setup NUMBER(*,0),
  init_by2user NUMBER(*,0),
  counted_by2user NUMBER(*,0),
  recounted_by2user NUMBER(*,0),
  entered_by2user NUMBER(*,0),
  count2x_pi_hist NUMBER,
  abc_cd_cls VARCHAR2(8 BYTE),
  bin_objid_perp NUMBER,
  bin_type NUMBER,
  error_msg VARCHAR2(255 BYTE),
  ext_cost_final NUMBER(19,4),
  id_number VARCHAR2(32 BYTE),
  mod_objid NUMBER,
  mv_bin_perp VARCHAR2(20 BYTE),
  mv_objid_perp NUMBER,
  opened_ind NUMBER,
  qty_bad_final NUMBER,
  qty_good_final NUMBER,
  reinit_date DATE,
  std_cost_final NUMBER(19,4),
  trial_by2user NUMBER,
  trial_date DATE,
  vi_trans_in NUMBER,
  vi_trans_out NUMBER
);
ALTER TABLE sa.table_inv_count ADD SUPPLEMENTAL LOG GROUP dmtsora144418770_0 (blank_tag, comments, count2count_setup, count2part_inst, count_date, count_part_no, dev, ext_cost_count, ext_cost_perp, gen_date, init_by2user, inv_bin_count, inv_bin_perp, inv_loc_count, inv_loc_perp, objid, qty_bad_count, qty_bad_perp, qty_good_count, qty_good_perp, reconcile_date, recount_date, rev_counted, rev_perpetual, sn_counted, sn_perpetual, status, std_cost_count, std_cost_perp, tag_count, tag_recount, trans_id_in, trans_id_out) ALWAYS;
ALTER TABLE sa.table_inv_count ADD SUPPLEMENTAL LOG GROUP dmtsora144418770_1 (abc_cd_cls, bin_objid_perp, bin_type, count2x_pi_hist, counted_by2user, entered_by2user, error_msg, ext_cost_final, id_number, mod_objid, mv_bin_perp, mv_objid_perp, opened_ind, qty_bad_final, qty_good_final, recounted_by2user, reinit_date, std_cost_final, trial_by2user, trial_date, vi_trans_in, vi_trans_out) ALWAYS;