CREATE TABLE sa.table_x_order_type_rim (
  objid NUMBER NOT NULL,
  x_order_type VARCHAR2(30 BYTE) NOT NULL,
  x_status_rim VARCHAR2(30 BYTE) NOT NULL
);
COMMENT ON TABLE sa.table_x_order_type_rim IS 'THIS TABLE HAS ALL MAPPING BETWEEN ORDER TYPE IN IG_TRANSACTION AND ORDER TYPE RIM';
COMMENT ON COLUMN sa.table_x_order_type_rim.objid IS 'OBJID GENERATE BY SEQUENCE: SA.SEQU_TABLE_X_OT_RIM';
COMMENT ON COLUMN sa.table_x_order_type_rim.x_order_type IS ' ORDER_TYPE FROM GW1.IG_TRANSACTION.';
COMMENT ON COLUMN sa.table_x_order_type_rim.x_status_rim IS 'NEW STATUS RIM EQUIVALENT WITH X_ORDER_TYPE (ACTIVATION, SUSPEND,ETC)';