CREATE TABLE sa.table_part_auth (
  objid NUMBER,
  part_good_qoh NUMBER,
  part_bad_qoh NUMBER,
  repl_queue VARCHAR2(24 BYTE),
  pt_turn_ratio VARCHAR2(8 BYTE),
  part_avg_usage VARCHAR2(8 BYTE),
  part_serv_lev VARCHAR2(8 BYTE),
  part_last_pi DATE,
  part_pi_tag_no VARCHAR2(8 BYTE),
  pt_last_cycle DATE,
  part_minimum NUMBER,
  part_maximum NUMBER,
  part_rol NUMBER,
  part_roq NUMBER,
  opn_ord_qty NUMBER,
  allocate_exch NUMBER,
  allocate_repln NUMBER,
  allocate_other NUMBER,
  hard_salelimit NUMBER,
  hard_exchlimit NUMBER,
  hard_repllimit NUMBER,
  reorder_qty NUMBER,
  "ACTIVE" NUMBER,
  dev NUMBER,
  part_auth2inv_bin NUMBER(*,0),
  n_auth_parts2part_mod NUMBER(*,0),
  abc_cd_cls VARCHAR2(8 BYTE),
  active_cc_ind NUMBER,
  average_usage NUMBER(19,4),
  last_calc_val NUMBER(19,4),
  last_cycle_ct DATE,
  part_auth2count_setup NUMBER,
  part_auth2cycle_count NUMBER,
  part_auth2rollup NUMBER,
  primary2inv_locatn NUMBER,
  primary_ind NUMBER,
  times_cc_ct NUMBER,
  turn_ratio NUMBER(19,4)
);
ALTER TABLE sa.table_part_auth ADD SUPPLEMENTAL LOG GROUP dmtsora564061595_0 (abc_cd_cls, "ACTIVE", active_cc_ind, allocate_exch, allocate_other, allocate_repln, average_usage, dev, hard_exchlimit, hard_repllimit, hard_salelimit, last_calc_val, last_cycle_ct, n_auth_parts2part_mod, objid, opn_ord_qty, part_auth2count_setup, part_auth2cycle_count, part_auth2inv_bin, part_avg_usage, part_bad_qoh, part_good_qoh, part_last_pi, part_maximum, part_minimum, part_pi_tag_no, part_rol, part_roq, part_serv_lev, pt_last_cycle, pt_turn_ratio, reorder_qty, repl_queue) ALWAYS;
ALTER TABLE sa.table_part_auth ADD SUPPLEMENTAL LOG GROUP dmtsora564061595_1 (part_auth2rollup, primary2inv_locatn, primary_ind, times_cc_ct, turn_ratio) ALWAYS;