CREATE TABLE sa.table_x_carfea_1019_1431 (
  objid NUMBER,
  dev NUMBER,
  x_technology VARCHAR2(30 BYTE),
  x_rate_plan VARCHAR2(60 BYTE),
  x_voicemail NUMBER,
  x_vm_code VARCHAR2(30 BYTE),
  x_vm_package NUMBER,
  x_caller_id NUMBER,
  x_id_code VARCHAR2(30 BYTE),
  x_id_package NUMBER,
  x_sms NUMBER,
  x_sms_code VARCHAR2(30 BYTE),
  x_sms_package NUMBER,
  x_call_waiting NUMBER,
  x_cw_code VARCHAR2(30 BYTE),
  x_cw_package NUMBER,
  x_digital_feature VARCHAR2(30 BYTE),
  x_dig_feature NUMBER,
  x_feature2x_carrier NUMBER,
  x_smsc_number VARCHAR2(30 BYTE),
  x_data NUMBER,
  x_restricted_use NUMBER,
  x_switch_base_rate VARCHAR2(10 BYTE),
  x_features2bus_org NUMBER,
  x_is_swb_carrier NUMBER(1),
  x_mpn NUMBER,
  x_mpn_code VARCHAR2(30 BYTE),
  x_pool_name VARCHAR2(60 BYTE),
  create_mform_ig_flag VARCHAR2(1 BYTE)
);