CREATE TABLE sa.table_scr_run (
  objid NUMBER,
  score NUMBER,
  start_time DATE,
  end_time DATE,
  result VARCHAR2(20 BYTE),
  s_result VARCHAR2(20 BYTE),
  title VARCHAR2(255 BYTE),
  s_title VARCHAR2(255 BYTE),
  node_key VARCHAR2(255 BYTE),
  create_date DATE,
  arch_ind NUMBER,
  init_ind NUMBER,
  dev NUMBER,
  scr_run2call_script NUMBER(*,0),
  scr_run2contact NUMBER(*,0) DEFAULT 1,
  administered2user NUMBER(*,0),
  run_with2scr_run NUMBER(*,0),
  scr_run2probdesc NUMBER(*,0),
  scr_run2case NUMBER(*,0),
  scr_run2campaign NUMBER(*,0),
  scr_run2lead_source NUMBER(*,0),
  scr_run2site_part NUMBER(*,0),
  scr_run2opportunity NUMBER(*,0),
  scr_run2bug NUMBER(*,0),
  scr_run2contract NUMBER(*,0),
  scr_run2contr_itm NUMBER(*,0),
  scr_run2demand_dtl NUMBER(*,0),
  scr_run2employee NUMBER(*,0),
  scr_run2site NUMBER(*,0),
  scr_run2subcase NUMBER(*,0),
  scr_run2task NUMBER(*,0),
  scr_run2bus_org NUMBER(*,0),
  scr_run2interact NUMBER(*,0),
  scr_run2lead NUMBER
);
ALTER TABLE sa.table_scr_run ADD SUPPLEMENTAL LOG GROUP dmtsora307494802_0 (administered2user, arch_ind, create_date, dev, end_time, init_ind, node_key, objid, result, run_with2scr_run, score, scr_run2bug, scr_run2bus_org, scr_run2call_script, scr_run2campaign, scr_run2case, scr_run2contact, scr_run2contract, scr_run2contr_itm, scr_run2demand_dtl, scr_run2employee, scr_run2interact, scr_run2lead_source, scr_run2opportunity, scr_run2probdesc, scr_run2site, scr_run2site_part, scr_run2subcase, scr_run2task, start_time, s_result, s_title, title) ALWAYS;
ALTER TABLE sa.table_scr_run ADD SUPPLEMENTAL LOG GROUP dmtsora307494802_1 (scr_run2lead) ALWAYS;