CREATE TABLE sa.table_x_promotion_102102 (
  objid NUMBER,
  x_promo_code VARCHAR2(10 BYTE),
  x_promo_type VARCHAR2(30 BYTE),
  x_dollar_retail_cost NUMBER(6,2),
  x_start_date DATE,
  x_end_date DATE,
  x_units NUMBER,
  x_access_days NUMBER,
  x_promotion_text LONG,
  x_is_default NUMBER,
  x_sql_statement VARCHAR2(2000 BYTE),
  x_revenue_type VARCHAR2(20 BYTE),
  x_default_type VARCHAR2(15 BYTE),
  x_redeemable NUMBER,
  x_promo_technology VARCHAR2(20 BYTE),
  x_spanish_promo_text VARCHAR2(255 BYTE),
  x_discount_amount NUMBER(10,2),
  x_discount_percent NUMBER(4,2),
  x_source_system VARCHAR2(7 BYTE),
  x_transaction_type VARCHAR2(20 BYTE),
  x_usage NUMBER,
  x_zip_required NUMBER,
  x_promo_desc VARCHAR2(200 BYTE),
  x_amigo_allowed NUMBER
);