CREATE TABLE sa.table_menu_item (
  objid NUMBER,
  title VARCHAR2(80 BYTE),
  mkey NUMBER,
  flags NUMBER,
  "STATE" NUMBER,
  menu_bar NUMBER,
  pulldown VARCHAR2(80 BYTE),
  menu_tag NUMBER,
  position NUMBER,
  function_id NUMBER,
  mtif_accel_key NUMBER,
  mtif_accel_flag NUMBER,
  description VARCHAR2(255 BYTE),
  dimmable NUMBER,
  mtif_title VARCHAR2(80 BYTE),
  "NAME" VARCHAR2(80 BYTE),
  win_title VARCHAR2(80 BYTE),
  win_accel_key NUMBER,
  win_accel_flag NUMBER,
  mac_title VARCHAR2(80 BYTE),
  mac_accel_key NUMBER,
  mac_accel_flag NUMBER,
  dev NUMBER,
  menu_item2menu_bar NUMBER(*,0),
  icon_id NUMBER,
  subtype NUMBER,
  "TYPE" NUMBER
);
ALTER TABLE sa.table_menu_item ADD SUPPLEMENTAL LOG GROUP dmtsora210909057_0 (description, dev, dimmable, flags, function_id, icon_id, mac_accel_flag, mac_accel_key, mac_title, menu_bar, menu_item2menu_bar, menu_tag, mkey, mtif_accel_flag, mtif_accel_key, mtif_title, "NAME", objid, position, pulldown, "STATE", subtype, title, "TYPE", win_accel_flag, win_accel_key, win_title) ALWAYS;