CREATE TABLE sa.table_x_parent_his (
  "SID" NUMBER,
  "ACTION" VARCHAR2(10 BYTE),
  username VARCHAR2(30 BYTE),
  osuser VARCHAR2(100 BYTE),
  "PROCESS" VARCHAR2(100 BYTE),
  machine VARCHAR2(100 BYTE),
  terminal VARCHAR2(100 BYTE),
  "PROGRAM" VARCHAR2(100 BYTE),
  logon_time DATE,
  dt DATE,
  sql_text VARCHAR2(1000 BYTE),
  old_objid NUMBER(22),
  old_x_parent_name VARCHAR2(40 BYTE),
  old_x_parent_id VARCHAR2(30 BYTE),
  old_x_status VARCHAR2(30 BYTE),
  old_x_hold_analog_deac NUMBER(22),
  old_x_hold_digital_deac NUMBER(22),
  old_x_parent2temp_queue NUMBER(22),
  old_x_no_inventory NUMBER(22),
  old_x_vm_access_num VARCHAR2(20 BYTE),
  old_x_auto_port_in NUMBER(22),
  old_x_auto_port_out NUMBER(22),
  old_x_no_msid NUMBER(22),
  old_x_ota_carrier VARCHAR2(30 BYTE),
  old_x_ota_end_date DATE,
  old_x_ota_psms_address VARCHAR2(30 BYTE),
  old_x_ota_start_date DATE,
  old_x_next_available NUMBER(22),
  old_x_queue_name VARCHAR2(50 BYTE),
  old_x_block_port_in NUMBER(22),
  old_x_meid_carrier NUMBER(22),
  old_x_ota_react NUMBER(22),
  new_objid NUMBER(22),
  new_x_parent_name VARCHAR2(40 BYTE),
  new_x_parent_id VARCHAR2(30 BYTE),
  new_x_status VARCHAR2(30 BYTE),
  new_x_hold_analog_deac NUMBER(22),
  new_x_hold_digital_deac NUMBER(22),
  new_x_parent2temp_queue NUMBER(22),
  new_x_no_inventory NUMBER(22),
  new_x_vm_access_num VARCHAR2(20 BYTE),
  new_x_auto_port_in NUMBER(22),
  new_x_auto_port_out NUMBER(22),
  new_x_no_msid NUMBER(22),
  new_x_ota_carrier VARCHAR2(30 BYTE),
  new_x_ota_end_date DATE,
  new_x_ota_psms_address VARCHAR2(30 BYTE),
  new_x_ota_start_date DATE,
  new_x_next_available NUMBER(22),
  new_x_queue_name VARCHAR2(50 BYTE),
  new_x_block_port_in NUMBER(22),
  new_x_meid_carrier NUMBER(22),
  new_x_ota_react NUMBER(22),
  piece NUMBER
);