CREATE TABLE sa.table_x_parent_sit1 (
  objid NUMBER,
  x_parent_name VARCHAR2(40 BYTE),
  x_parent_id VARCHAR2(30 BYTE),
  x_status VARCHAR2(30 BYTE),
  x_hold_analog_deac NUMBER,
  x_hold_digital_deac NUMBER,
  x_parent2temp_queue NUMBER,
  x_no_inventory NUMBER,
  x_vm_access_num VARCHAR2(20 BYTE),
  x_auto_port_in NUMBER,
  x_auto_port_out NUMBER,
  x_no_msid NUMBER,
  x_ota_carrier VARCHAR2(30 BYTE),
  x_ota_end_date DATE,
  x_ota_psms_address VARCHAR2(30 BYTE),
  x_ota_start_date DATE,
  x_next_available NUMBER,
  x_queue_name VARCHAR2(50 BYTE),
  x_block_port_in NUMBER,
  x_meid_carrier NUMBER,
  x_ota_react NUMBER,
  x_agg_carr_code NUMBER
);