CREATE TABLE sa.table_part_used (
  objid NUMBER,
  price VARCHAR2(20 BYTE),
  install_serial VARCHAR2(30 BYTE),
  remove_serial VARCHAR2(30 BYTE),
  status VARCHAR2(10 BYTE),
  failure_status VARCHAR2(20 BYTE),
  install_qty NUMBER,
  remove_qty NUMBER,
  part_used_date DATE,
  trans_type VARCHAR2(20 BYTE),
  rem_part_num VARCHAR2(30 BYTE),
  rem_mod_level VARCHAR2(10 BYTE),
  rem_part_name VARCHAR2(255 BYTE),
  case_id_number VARCHAR2(255 BYTE),
  rem_move_type NUMBER,
  rem_notes VARCHAR2(60 BYTE),
  rem_stand_cost NUMBER(19,4),
  rem_trans_type NUMBER,
  rem_status NUMBER,
  ins_notes VARCHAR2(60 BYTE),
  ins_stand_cost NUMBER(19,4),
  ins_trans_type NUMBER,
  detail_number VARCHAR2(20 BYTE),
  inv_status VARCHAR2(20 BYTE),
  dtl_condtn VARCHAR2(80 BYTE),
  part_price NUMBER(19,4),
  dev NUMBER,
  part_used2assigned_eng NUMBER(*,0),
  part_used2site_part NUMBER(*,0),
  part_used2rem_site_part NUMBER(*,0),
  part_used2case NUMBER(*,0),
  part_used2inst_part_info NUMBER(*,0),
  part_used2rem_part_info NUMBER(*,0),
  part_used2inst_site_part NUMBER(*,0),
  part_used2remove_trans NUMBER(*,0),
  part_used2install_trans NUMBER(*,0),
  part_used2demand_dtl NUMBER(*,0)
);
ALTER TABLE sa.table_part_used ADD SUPPLEMENTAL LOG GROUP dmtsora918148005_0 (case_id_number, detail_number, dev, dtl_condtn, failure_status, install_qty, install_serial, ins_notes, ins_stand_cost, ins_trans_type, inv_status, objid, part_price, part_used2assigned_eng, part_used2case, part_used2inst_part_info, part_used2rem_part_info, part_used2rem_site_part, part_used2site_part, part_used_date, price, remove_qty, remove_serial, rem_mod_level, rem_move_type, rem_notes, rem_part_name, rem_part_num, rem_stand_cost, rem_status, rem_trans_type, status, trans_type) ALWAYS;
ALTER TABLE sa.table_part_used ADD SUPPLEMENTAL LOG GROUP dmtsora918148005_1 (part_used2demand_dtl, part_used2install_trans, part_used2inst_site_part, part_used2remove_trans) ALWAYS;