CREATE TABLE sa.table_svc_fld (
  objid NUMBER,
  dev NUMBER,
  fld_name VARCHAR2(128 BYTE),
  "PATH" VARCHAR2(255 BYTE),
  "TYPE" NUMBER,
  field_flags NUMBER,
  focus NUMBER,
  type_alpha VARCHAR2(20 BYTE),
  focus_alpha VARCHAR2(20 BYTE),
  object_path VARCHAR2(255 BYTE),
  object_inv_path VARCHAR2(255 BYTE),
  target_name VARCHAR2(64 BYTE),
  object_target_id NUMBER,
  object_cond VARCHAR2(255 BYTE),
  object_sqlfrom VARCHAR2(255 BYTE),
  object_sqlwhere VARCHAR2(255 BYTE),
  parent_path VARCHAR2(255 BYTE),
  parent_inv_path VARCHAR2(255 BYTE),
  parent_target VARCHAR2(64 BYTE),
  parent_target_id NUMBER,
  parent_rel VARCHAR2(64 BYTE),
  parent_cond VARCHAR2(255 BYTE),
  parent_sqlfrom VARCHAR2(255 BYTE),
  parent_sqlwhere VARCHAR2(255 BYTE),
  rel_focus VARCHAR2(64 BYTE),
  rel_path VARCHAR2(255 BYTE),
  rel_inv_path VARCHAR2(255 BYTE),
  rel_target VARCHAR2(64 BYTE),
  rel_target_id NUMBER,
  rel_cond VARCHAR2(255 BYTE),
  rel_sqlfrom VARCHAR2(255 BYTE),
  rel_sqlwhere VARCHAR2(255 BYTE),
  attrib_name VARCHAR2(64 BYTE),
  db_attrib_type NUMBER,
  is_flexible NUMBER,
  fml_attrib_type VARCHAR2(10 BYTE),
  fld2svc_rqst NUMBER,
  svc_fld2fld_def NUMBER
);
ALTER TABLE sa.table_svc_fld ADD SUPPLEMENTAL LOG GROUP dmtsora2001424649_0 (attrib_name, dev, field_flags, fld_name, focus, focus_alpha, object_cond, object_inv_path, object_path, object_sqlfrom, object_sqlwhere, object_target_id, objid, parent_cond, parent_inv_path, parent_path, parent_rel, parent_sqlfrom, parent_sqlwhere, parent_target, parent_target_id, "PATH", rel_cond, rel_focus, rel_inv_path, rel_path, rel_sqlfrom, rel_sqlwhere, rel_target, rel_target_id, target_name, "TYPE", type_alpha) ALWAYS;
ALTER TABLE sa.table_svc_fld ADD SUPPLEMENTAL LOG GROUP dmtsora2001424649_1 (db_attrib_type, fld2svc_rqst, fml_attrib_type, is_flexible, svc_fld2fld_def) ALWAYS;