CREATE TABLE sa.temp_sales_tax_10672 (
  objid NUMBER,
  x_zipcode VARCHAR2(10 BYTE),
  x_city VARCHAR2(28 BYTE),
  x_county VARCHAR2(25 BYTE),
  x_state VARCHAR2(2 BYTE),
  x_cntydef VARCHAR2(1 BYTE),
  x_default VARCHAR2(1 BYTE),
  x_cntyfips VARCHAR2(5 BYTE),
  x_statestax NUMBER,
  x_cntstax NUMBER,
  x_cntlclstax NUMBER,
  x_ctystax NUMBER,
  x_ctylclstax NUMBER,
  x_combstax NUMBER,
  x_eff_dt DATE,
  x_geocode VARCHAR2(10 BYTE),
  x_inout VARCHAR2(2 BYTE),
  x_e911foot VARCHAR2(255 BYTE),
  x_e911note VARCHAR2(255 BYTE),
  x_e911rate NUMBER(19,4),
  x_e911surcharge NUMBER(19,4),
  x_usf_taxrate NUMBER
);