CREATE TABLE sa.tf_iday (
  warehouse VARCHAR2(15 BYTE),
  item_no VARCHAR2(40 BYTE),
  item_description VARCHAR2(500 BYTE),
  mat_type VARCHAR2(200 BYTE),
  mat_class VARCHAR2(200 BYTE),
  on_hand NUMBER,
  allocated NUMBER,
  available NUMBER,
  returns NUMBER,
  quarantine NUMBER,
  sealedperfect NUMBER,
  sealedimperfect NUMBER,
  ntf NUMBER,
  cosmetic NUMBER,
  software NUMBER,
  obsolete NUMBER,
  functionality NUMBER,
  unprocessed NUMBER,
  attribute1 VARCHAR2(100 BYTE),
  attribute2 VARCHAR2(100 BYTE),
  attribute3 VARCHAR2(100 BYTE),
  attribute4 VARCHAR2(100 BYTE),
  attribute_date_1 DATE,
  attribute_date_2 DATE,
  attribute_date_3 DATE,
  attribute_date_4 DATE,
  attribute_number_1 NUMBER,
  attribute_number_2 NUMBER,
  attribute_number_3 NUMBER,
  attribute_number_4 NUMBER,
  creation_date DATE,
  created_by VARCHAR2(100 BYTE),
  last_update_date DATE,
  last_updated_by VARCHAR2(100 BYTE)
);