CREATE TABLE sa.tf_of_item_v_stgd2 (
  item_id NUMBER NOT NULL,
  part_number VARCHAR2(40 BYTE),
  description VARCHAR2(240 BYTE),
  redemption_units VARCHAR2(150 BYTE),
  redemption_days VARCHAR2(150 BYTE),
  dll VARCHAR2(150 BYTE),
  frequency VARCHAR2(150 BYTE),
  product_code VARCHAR2(150 BYTE),
  source_system VARCHAR2(150 BYTE),
  technology VARCHAR2(150 BYTE),
  "SOURCE" VARCHAR2(150 BYTE),
  programming_flag VARCHAR2(150 BYTE),
  clfy_domain VARCHAR2(150 BYTE),
  promo_code VARCHAR2(150 BYTE),
  upc VARCHAR2(25 BYTE),
  product_family VARCHAR2(40 BYTE),
  of_domain VARCHAR2(40 BYTE),
  posa_type VARCHAR2(40 BYTE),
  charge_code VARCHAR2(40 BYTE),
  serialized VARCHAR2(40 BYTE),
  stock_type VARCHAR2(40 BYTE),
  part_assignment VARCHAR2(9 BYTE),
  item_last_update_date DATE NOT NULL,
  cat_last_update_date DATE NOT NULL,
  parent_part_number VARCHAR2(4000 BYTE),
  rlt_last_update_date DATE,
  manufacturer VARCHAR2(150 BYTE),
  cardless_bundle_flag VARCHAR2(150 BYTE),
  replacement_options VARCHAR2(150 BYTE)
);
ALTER TABLE sa.tf_of_item_v_stgd2 ADD SUPPLEMENTAL LOG GROUP dmtsora1593338188_0 (cardless_bundle_flag, cat_last_update_date, charge_code, clfy_domain, description, dll, frequency, item_id, item_last_update_date, manufacturer, of_domain, parent_part_number, part_assignment, part_number, posa_type, product_code, product_family, programming_flag, promo_code, redemption_days, redemption_units, replacement_options, rlt_last_update_date, serialized, "SOURCE", source_system, stock_type, technology, upc) ALWAYS;