CREATE TABLE sa.tf_of_item_v_072407 (
  item_id NUMBER,
  part_number VARCHAR2(40 BYTE),
  description VARCHAR2(240 BYTE),
  redemption_units VARCHAR2(250 BYTE),
  redemption_days VARCHAR2(250 BYTE),
  dll VARCHAR2(250 BYTE),
  frequency VARCHAR2(250 BYTE),
  product_code VARCHAR2(250 BYTE),
  source_system VARCHAR2(250 BYTE),
  technology VARCHAR2(250 BYTE),
  "SOURCE" VARCHAR2(250 BYTE),
  programming_flag VARCHAR2(250 BYTE),
  clfy_domain VARCHAR2(250 BYTE),
  promo_code VARCHAR2(250 BYTE),
  data_phone VARCHAR2(250 BYTE),
  conversion_rate VARCHAR2(250 BYTE),
  extd_warranty VARCHAR2(250 BYTE),
  x_ota_allowed VARCHAR2(250 BYTE),
  x_ild_type VARCHAR2(250 BYTE),
  upc VARCHAR2(25 BYTE),
  product_family VARCHAR2(40 BYTE),
  of_domain VARCHAR2(40 BYTE),
  posa_type VARCHAR2(40 BYTE),
  charge_code VARCHAR2(40 BYTE),
  serialized VARCHAR2(40 BYTE),
  stock_type VARCHAR2(40 BYTE),
  part_assignment VARCHAR2(9 BYTE),
  item_last_update_date DATE,
  cat_last_update_date DATE,
  parent_part_number VARCHAR2(4000 BYTE),
  rlt_last_update_date DATE,
  manufacturer VARCHAR2(250 BYTE),
  cardless_bundle_flag VARCHAR2(250 BYTE),
  color VARCHAR2(250 BYTE),
  part_class VARCHAR2(250 BYTE),
  click_plan VARCHAR2(250 BYTE)
);
ALTER TABLE sa.tf_of_item_v_072407 ADD SUPPLEMENTAL LOG GROUP dmtsora2040160371_1 (click_plan, color, part_class) ALWAYS;
ALTER TABLE sa.tf_of_item_v_072407 ADD SUPPLEMENTAL LOG GROUP dmtsora2040160371_0 (cardless_bundle_flag, cat_last_update_date, charge_code, clfy_domain, conversion_rate, data_phone, description, dll, extd_warranty, frequency, item_id, item_last_update_date, manufacturer, of_domain, parent_part_number, part_assignment, part_number, posa_type, product_code, product_family, programming_flag, promo_code, redemption_days, redemption_units, rlt_last_update_date, serialized, "SOURCE", source_system, stock_type, technology, upc, x_ild_type, x_ota_allowed) ALWAYS;