CREATE TABLE sa.tf_of_item_v_phone_other (
  item_id NUMBER NOT NULL,
  part_number VARCHAR2(40 BYTE),
  description VARCHAR2(240 BYTE),
  redemption_units VARCHAR2(150 BYTE),
  redemption_days VARCHAR2(150 BYTE),
  dll VARCHAR2(150 BYTE),
  frequency VARCHAR2(150 BYTE),
  product_code VARCHAR2(150 BYTE),
  source_system VARCHAR2(150 BYTE),
  technology VARCHAR2(150 BYTE),
  "SOURCE" VARCHAR2(150 BYTE),
  programming_flag VARCHAR2(150 BYTE),
  clfy_domain VARCHAR2(150 BYTE),
  promo_code VARCHAR2(150 BYTE),
  data_phone VARCHAR2(150 BYTE),
  conversion_rate VARCHAR2(150 BYTE),
  extd_warranty VARCHAR2(150 BYTE),
  x_ota_allowed VARCHAR2(150 BYTE),
  x_ild_type VARCHAR2(150 BYTE),
  upc VARCHAR2(150 BYTE),
  product_family VARCHAR2(40 BYTE),
  of_domain VARCHAR2(150 BYTE),
  posa_type VARCHAR2(150 BYTE),
  charge_code VARCHAR2(150 BYTE),
  serialized VARCHAR2(150 BYTE),
  stock_type VARCHAR2(150 BYTE),
  part_assignment VARCHAR2(9 BYTE),
  item_last_update_date DATE,
  cat_last_update_date DATE NOT NULL,
  parent_part_number VARCHAR2(150 BYTE),
  rlt_last_update_date DATE,
  manufacturer VARCHAR2(150 BYTE),
  cardless_bundle_flag VARCHAR2(150 BYTE),
  color VARCHAR2(150 BYTE),
  part_class VARCHAR2(150 BYTE),
  click_plan VARCHAR2(150 BYTE),
  card_type VARCHAR2(150 BYTE),
  card_plan VARCHAR2(150 BYTE),
  clarify_flag VARCHAR2(150 BYTE),
  device_lock_state VARCHAR2(150 BYTE),
  rcs_capable VARCHAR2(150 BYTE)
);