CREATE TABLE sa.tf_soaprocess_activity_info (
  activity_info_id NUMBER NOT NULL,
  domainid VARCHAR2(250 BYTE),
  scaid VARCHAR2(250 BYTE),
  ecid VARCHAR2(250 BYTE),
  instanceid NUMBER NOT NULL,
  processname VARCHAR2(2000 BYTE),
  currentactivity VARCHAR2(1000 BYTE),
  originprocess VARCHAR2(2000 BYTE),
  originsourceid VARCHAR2(1000 BYTE),
  processstatus VARCHAR2(1000 BYTE),
  processtime TIMESTAMP,
  attribute1 VARCHAR2(1000 BYTE),
  attribute2 VARCHAR2(1000 BYTE),
  attribute3 VARCHAR2(1000 BYTE),
  attribute4 VARCHAR2(1000 BYTE),
  attribute5 VARCHAR2(1000 BYTE),
  faultdetails VARCHAR2(4000 BYTE),
  faultcode VARCHAR2(250 BYTE),
  faultsummary VARCHAR2(4000 BYTE),
  isreprocess NUMBER,
  inputpayload CLOB,
  "NOTIFICATION" sa.tf_soaprocess_notificationtype,
  headerlist sa.tf_soaprocess_headerlisttype,
  row_insert_date DATE DEFAULT SYSDATE,
  row_upd_date DATE DEFAULT SYSDATE,
  CONSTRAINT pk_soaprocess_activity_id PRIMARY KEY (activity_info_id)
);
COMMENT ON TABLE sa.tf_soaprocess_activity_info IS 'SOA Process activity information';