CREATE TABLE sa.tf_toss_interface_nor (
  row_id ROWID NOT NULL,
  tf_part_num_parent VARCHAR2(100 BYTE) NOT NULL,
  tf_part_num_transpose VARCHAR2(100 BYTE) NOT NULL,
  transceiver_num VARCHAR2(100 BYTE),
  tf_manuf_location_code VARCHAR2(100 BYTE),
  tf_ff_location_code VARCHAR2(100 BYTE),
  tf_ret_location_code VARCHAR2(100 BYTE),
  toss_extract_flag VARCHAR2(100 BYTE) NOT NULL,
  tf_serial_num VARCHAR2(100 BYTE) NOT NULL,
  tf_part_type VARCHAR2(100 BYTE) NOT NULL,
  tf_card_pin_num VARCHAR2(100 BYTE),
  tf_manuf_location_name VARCHAR2(100 BYTE),
  tf_order_num VARCHAR2(40 BYTE),
  creation_date DATE NOT NULL,
  created_by VARCHAR2(100 BYTE) NOT NULL,
  ff_receive_date DATE,
  retailer_ship_date DATE,
  serial_invalid_date DATE,
  toss_changed_retailer_name VARCHAR2(100 BYTE),
  serial_valid_insert_date DATE,
  tf_phone_refurb_date DATE,
  last_updated_by VARCHAR2(100 BYTE) NOT NULL,
  last_update_date DATE NOT NULL,
  toss_extract_date DATE,
  tf_financials_control_num VARCHAR2(100 BYTE),
  ship_to_id NUMBER(15),
  modobjid VARCHAR2(30 BYTE),
  binobjid VARCHAR2(25 BYTE)
);