CREATE TABLE sa.tmo_rmv (
  zip VARCHAR2(5 BYTE),
  "ZONE" VARCHAR2(100 BYTE),
  st VARCHAR2(2 BYTE)
);
ALTER TABLE sa.tmo_rmv ADD SUPPLEMENTAL LOG GROUP dmtsora1594893028_0 (st, zip, "ZONE") ALWAYS;