CREATE TABLE sa.tmp_cc_old_cert (
  objid NUMBER,
  x_customer_cc_number VARCHAR2(255 BYTE),
  x_customer_cc_expmo VARCHAR2(2 BYTE),
  x_customer_cc_expyr VARCHAR2(4 BYTE),
  x_cc_type VARCHAR2(20 BYTE),
  x_customer_cc_cv_number VARCHAR2(20 BYTE),
  x_customer_firstname VARCHAR2(20 BYTE),
  x_customer_lastname VARCHAR2(20 BYTE),
  x_customer_phone VARCHAR2(20 BYTE),
  x_customer_email VARCHAR2(50 BYTE),
  x_max_purch_amt NUMBER,
  x_max_trans_per_month NUMBER,
  x_max_purch_amt_per_month NUMBER,
  x_changedate DATE,
  x_original_insert_date DATE,
  x_changedby VARCHAR2(20 BYTE),
  x_moms_maiden VARCHAR2(20 BYTE),
  x_credit_card2contact NUMBER,
  x_credit_card2address NUMBER,
  x_card_status VARCHAR2(10 BYTE),
  x_max_ild_purch_amt NUMBER,
  x_max_ild_purch_month NUMBER,
  x_credit_card2bus_org NUMBER,
  x_cust_cc_num_key VARCHAR2(255 BYTE),
  x_cust_cc_num_enc VARCHAR2(255 BYTE),
  creditcard2cert NUMBER
);