CREATE TABLE sa.tmp_sm_contact (
  objid NUMBER,
  first_name VARCHAR2(30 BYTE),
  s_first_name VARCHAR2(30 BYTE),
  last_name VARCHAR2(30 BYTE),
  s_last_name VARCHAR2(30 BYTE),
  phone VARCHAR2(20 BYTE),
  fax_number VARCHAR2(20 BYTE),
  e_mail VARCHAR2(80 BYTE),
  mail_stop VARCHAR2(30 BYTE),
  expertise_lev NUMBER,
  title VARCHAR2(30 BYTE),
  hours VARCHAR2(30 BYTE),
  salutation VARCHAR2(20 BYTE),
  mdbk VARCHAR2(80 BYTE),
  state_code NUMBER,
  state_value VARCHAR2(20 BYTE),
  address_1 VARCHAR2(200 BYTE),
  address_2 VARCHAR2(200 BYTE),
  city VARCHAR2(30 BYTE),
  "STATE" VARCHAR2(40 BYTE),
  zipcode VARCHAR2(20 BYTE),
  country VARCHAR2(40 BYTE),
  status NUMBER,
  arch_ind NUMBER,
  alert_ind NUMBER,
  dev NUMBER,
  caller2user NUMBER(*,0),
  contact2x_carrier NUMBER,
  x_cust_id VARCHAR2(80 BYTE),
  x_dateofbirth DATE,
  x_gender VARCHAR2(20 BYTE),
  x_middle_initial VARCHAR2(3 BYTE),
  x_mobilenumber VARCHAR2(20 BYTE),
  x_no_address_flag NUMBER,
  x_no_name_flag NUMBER,
  x_pagernumber VARCHAR2(20 BYTE),
  x_ss_number VARCHAR2(20 BYTE),
  x_no_phone_flag NUMBER,
  update_stamp DATE,
  x_new_esn VARCHAR2(20 BYTE),
  x_email_status NUMBER,
  x_html_ok NUMBER,
  x_email_prompt_count NUMBER,
  x_phone_prompt_count NUMBER,
  x_roadside_status NUMBER,
  x_autopay_update_flag NUMBER,
  mobile_phone VARCHAR2(20 BYTE),
  x_pin VARCHAR2(6 BYTE),
  x_serv_dt_remind_flag NUMBER,
  x_sign_reqd NUMBER,
  x_spl_offer_flg NUMBER,
  x_spl_prog_flg NUMBER
);