CREATE TABLE sa.tmp_cc_trans_failed (
  objid NUMBER NOT NULL,
  x_esn VARCHAR2(30 BYTE),
  x_amount NUMBER(10,2),
  x_type VARCHAR2(30 BYTE),
  x_zipcode NUMBER,
  x_sourcesystem VARCHAR2(30 BYTE),
  x_insert_date DATE,
  x_charge_date DATE,
  x_pec_customer NUMBER,
  x_charge_type VARCHAR2(30 BYTE),
  x_enrolled_date DATE,
  x_start_date DATE,
  x_reason VARCHAR2(255 BYTE),
  x_exp_date DATE,
  x_delivery_cycle_number NUMBER,
  x_enroll_amount NUMBER(10,2),
  x_language VARCHAR2(7 BYTE),
  x_payment_type VARCHAR2(20 BYTE),
  x_grace_period NUMBER(3),
  x_cooling_period NUMBER(3),
  x_service_days NUMBER(3),
  x_cooling_exp_date DATE,
  x_enrollment_status VARCHAR2(30 BYTE),
  x_is_grp_primary NUMBER(1),
  x_tot_grace_period_given NUMBER,
  x_next_charge_date DATE,
  x_next_delivery_date DATE,
  x_update_stamp DATE,
  x_update_user VARCHAR2(40 BYTE),
  pgm_enroll2pgm_parameter NUMBER,
  pgm_enroll2pgm_group NUMBER,
  pgm_enroll2site_part NUMBER,
  pgm_enroll2part_inst NUMBER,
  pgm_enroll2contact NUMBER,
  pgm_enroll2web_user NUMBER,
  pgm_enroll2x_pymt_src NUMBER,
  x_wait_exp_date DATE,
  pgm_enroll2x_promotion NUMBER,
  pgm_enroll2prog_hdr NUMBER,
  x_termscond_accepted NUMBER,
  x_service_delivery_date DATE,
  default_denomination NUMBER,
  cc_objid NUMBER,
  x_customer_cc_number VARCHAR2(255 BYTE),
  x_customer_cc_expmo VARCHAR2(2 BYTE),
  x_customer_cc_expyr VARCHAR2(4 BYTE),
  x_cc_type VARCHAR2(20 BYTE),
  x_customer_cc_cv_number VARCHAR2(20 BYTE),
  x_customer_firstname VARCHAR2(20 BYTE),
  x_customer_lastname VARCHAR2(20 BYTE),
  x_customer_phone VARCHAR2(20 BYTE),
  x_customer_email VARCHAR2(50 BYTE),
  x_max_purch_amt NUMBER,
  x_max_trans_per_month NUMBER,
  x_max_purch_amt_per_month NUMBER,
  x_changedate DATE,
  x_original_insert_date DATE,
  x_changedby VARCHAR2(20 BYTE),
  x_moms_maiden VARCHAR2(20 BYTE),
  x_credit_card2contact NUMBER,
  x_credit_card2address NUMBER,
  x_card_status VARCHAR2(10 BYTE),
  x_max_ild_purch_amt NUMBER,
  x_max_ild_purch_month NUMBER,
  x_credit_card2bus_org NUMBER,
  x_cust_cc_num_key VARCHAR2(255 BYTE),
  x_cust_cc_num_enc VARCHAR2(255 BYTE),
  creditcard2cert NUMBER
);