CREATE TABLE sa.tstahis_table_x_sim_inv (
  objid NUMBER,
  x_sim_serial_no VARCHAR2(30 BYTE),
  x_sim_inv_status VARCHAR2(30 BYTE),
  x_sim_mnc VARCHAR2(6 BYTE),
  x_inv_insert_date DATE,
  x_last_ship_date DATE,
  x_sim_po_number VARCHAR2(30 BYTE),
  x_sim_order_number VARCHAR2(40 BYTE),
  x_last_update_date DATE,
  x_sim_inv2part_mod NUMBER,
  x_created_by2user NUMBER,
  x_sim_status2x_code_table NUMBER,
  x_sim_inv2inv_bin NUMBER,
  x_pin1 VARCHAR2(30 BYTE),
  x_pin2 VARCHAR2(30 BYTE),
  x_puk1 VARCHAR2(30 BYTE),
  x_puk2 VARCHAR2(30 BYTE),
  x_qty NUMBER,
  x_sim_inv_hist2x_sim_inv NUMBER,
  x_sim_inv_his2user VARCHAR2(30 BYTE),
  x_change_date DATE,
  osuser VARCHAR2(30 BYTE),
  triggering_record_type VARCHAR2(6 BYTE)
);