CREATE TABLE sa.tstahis_ig_transaction (
  objid NUMBER,
  action_item_id VARCHAR2(30 BYTE),
  carrier_id VARCHAR2(30 BYTE),
  order_type VARCHAR2(30 BYTE),
  "MIN" VARCHAR2(30 BYTE),
  esn VARCHAR2(30 BYTE),
  esn_hex VARCHAR2(30 BYTE),
  old_esn VARCHAR2(30 BYTE),
  old_esn_hex VARCHAR2(30 BYTE),
  pin VARCHAR2(30 BYTE),
  phone_manf VARCHAR2(30 BYTE),
  end_user VARCHAR2(40 BYTE),
  account_num VARCHAR2(30 BYTE),
  market_code VARCHAR2(30 BYTE),
  rate_plan VARCHAR2(60 BYTE),
  ld_provider VARCHAR2(30 BYTE),
  sequence_num VARCHAR2(30 BYTE),
  dealer_code VARCHAR2(30 BYTE),
  transmission_method VARCHAR2(30 BYTE),
  fax_num VARCHAR2(40 BYTE),
  online_num VARCHAR2(40 BYTE),
  email VARCHAR2(45 BYTE),
  network_login VARCHAR2(30 BYTE),
  network_password VARCHAR2(30 BYTE),
  system_login VARCHAR2(30 BYTE),
  system_password VARCHAR2(30 BYTE),
  "TEMPLATE" VARCHAR2(30 BYTE),
  exe_name VARCHAR2(160 BYTE),
  com_port VARCHAR2(40 BYTE),
  status VARCHAR2(30 BYTE),
  status_message VARCHAR2(256 BYTE),
  fax_batch_size VARCHAR2(30 BYTE),
  fax_batch_q_time VARCHAR2(30 BYTE),
  expidite VARCHAR2(30 BYTE),
  trans_prof_key VARCHAR2(30 BYTE),
  q_transaction VARCHAR2(30 BYTE),
  online_num2 VARCHAR2(49 BYTE),
  fax_num2 VARCHAR2(40 BYTE),
  creation_date DATE,
  update_date DATE,
  blackout_wait DATE,
  tux_iti_server VARCHAR2(20 BYTE),
  transaction_id NUMBER(10),
  technology_flag VARCHAR2(30 BYTE),
  voice_mail VARCHAR2(30 BYTE),
  voice_mail_package VARCHAR2(30 BYTE),
  caller_id VARCHAR2(30 BYTE),
  caller_id_package VARCHAR2(30 BYTE),
  call_waiting VARCHAR2(30 BYTE),
  call_waiting_package VARCHAR2(30 BYTE),
  rtp_server VARCHAR2(30 BYTE),
  digital_feature_code VARCHAR2(30 BYTE),
  state_field VARCHAR2(30 BYTE),
  zip_code VARCHAR2(30 BYTE),
  msid VARCHAR2(30 BYTE),
  new_msid_flag VARCHAR2(10 BYTE),
  sms VARCHAR2(30 BYTE),
  sms_package VARCHAR2(30 BYTE),
  iccid VARCHAR2(30 BYTE),
  old_min VARCHAR2(30 BYTE),
  digital_feature VARCHAR2(30 BYTE),
  ota_type VARCHAR2(10 BYTE),
  rate_center_no VARCHAR2(30 BYTE),
  application_system VARCHAR2(30 BYTE),
  subscriber_update VARCHAR2(1 BYTE),
  download_date DATE,
  prl_number VARCHAR2(80 BYTE),
  amount NUMBER(6,2),
  balance NUMBER(12,2),
  language VARCHAR2(12 BYTE),
  exp_date DATE,
  ig_transaction2user VARCHAR2(30 BYTE),
  x_change_date DATE,
  osuser VARCHAR2(30 BYTE),
  triggering_record_type VARCHAR2(6 BYTE),
  ig_tran_hist2ig_tran_act_item VARCHAR2(30 BYTE)
);