CREATE TABLE sa.tstahis_table_task (
  objid NUMBER,
  title VARCHAR2(80 BYTE),
  s_title VARCHAR2(80 BYTE),
  notes VARCHAR2(2000 BYTE),
  start_date DATE,
  due_date DATE,
  comp_date DATE,
  "ACTIVE" NUMBER,
  task_id VARCHAR2(25 BYTE),
  s_task_id VARCHAR2(25 BYTE),
  arch_ind NUMBER,
  dev NUMBER,
  task_sts2gbst_elm NUMBER,
  task_priority2gbst_elm NUMBER,
  type_task2gbst_elm NUMBER,
  sm_task2opportunity NUMBER,
  task_originator2user NUMBER,
  task_owner2user NUMBER,
  task2contact NUMBER,
  task_gen2cls_factory NUMBER,
  task_for2bus_org NUMBER,
  task_state2condition NUMBER,
  task_wip2wipbin NUMBER,
  task_currq2queue NUMBER,
  task_prevq2queue NUMBER,
  sm_task2contract NUMBER,
  task2lead NUMBER,
  task2lit_req NUMBER,
  task2task_desc NUMBER,
  update_stamp DATE,
  x_account_num VARCHAR2(40 BYTE),
  x_activation_timeframe VARCHAR2(40 BYTE),
  x_current_method VARCHAR2(30 BYTE),
  x_expedite NUMBER,
  x_fax_file VARCHAR2(80 BYTE),
  x_original_method VARCHAR2(30 BYTE),
  x_queued_flag VARCHAR2(10 BYTE),
  x_task2site_part NUMBER,
  x_task2x_call_trans NUMBER,
  x_task2x_order_type NUMBER,
  x_task2x_topp_err_codes NUMBER,
  x_trans_login VARCHAR2(30 BYTE),
  x_rate_plan VARCHAR2(30 BYTE),
  x_ota_type VARCHAR2(10 BYTE),
  task_hist2task NUMBER,
  task_his2user VARCHAR2(30 BYTE),
  x_change_date DATE,
  osuser VARCHAR2(30 BYTE),
  triggering_record_type VARCHAR2(6 BYTE)
);