CREATE TABLE sa.tstahis_table_x_red_card (
  objid NUMBER,
  red_card2call_trans NUMBER,
  red_smp2inv_smp NUMBER,
  red_smp2x_pi_hist NUMBER,
  x_access_days NUMBER,
  x_red_code VARCHAR2(20 BYTE),
  x_red_date DATE,
  x_red_units NUMBER,
  x_smp VARCHAR2(30 BYTE),
  x_status VARCHAR2(255 BYTE),
  x_result VARCHAR2(20 BYTE),
  x_created_by2user NUMBER,
  x_inv_insert_date DATE,
  x_last_ship_date DATE,
  x_order_number VARCHAR2(40 BYTE),
  x_po_num VARCHAR2(30 BYTE),
  x_red_card2inv_bin NUMBER,
  x_red_card2part_mod NUMBER,
  x_red_card_hist2x_red_card NUMBER,
  x_red_card_his2user VARCHAR2(30 BYTE),
  x_change_date DATE,
  osuser VARCHAR2(30 BYTE),
  triggering_record_type VARCHAR2(6 BYTE)
);