CREATE TABLE sa.tstahis_table_act_entry (
  objid NUMBER,
  act_code NUMBER,
  entry_time DATE,
  addnl_info VARCHAR2(255 BYTE),
  "PROXY" VARCHAR2(30 BYTE),
  removed NUMBER,
  dev NUMBER,
  act_entry2case NUMBER(*,0),
  act_entry2subcase NUMBER(*,0),
  act_entry2probdesc NUMBER(*,0),
  act_entry2workaround NUMBER(*,0),
  act_entry2user NUMBER(*,0),
  act_entry2reject_msg NUMBER(*,0),
  act_entry2notes_log NUMBER(*,0),
  act_entry2phone_log NUMBER(*,0),
  act_entry2resrch_log NUMBER(*,0),
  act_entry2commit_log NUMBER(*,0),
  act_entry2escalation NUMBER(*,0),
  act_entry2onsite_log NUMBER(*,0),
  act_entry2email_log NUMBER(*,0),
  act_entry2site_part NUMBER(*,0),
  act_entry2site NUMBER(*,0),
  act_entry2bug NUMBER(*,0),
  entry_name2gbst_elm NUMBER(*,0),
  act_entry_child2parent NUMBER(*,0),
  act_entry2biz_cal_hdr NUMBER(*,0),
  act_entry2schedule NUMBER(*,0),
  act_entry2disptchfe NUMBER(*,0),
  act_entry2employee NUMBER(*,0),
  act_entry2demand_dtl NUMBER(*,0),
  act_entry2doc_inst NUMBER(*,0),
  act_entry2part_trans NUMBER(*,0),
  act_entry2opportunity NUMBER(*,0),
  act_entry2contract NUMBER(*,0),
  act_entry2job NUMBER(*,0),
  act_entry2contact NUMBER(*,0),
  act_entry2task NUMBER(*,0),
  act_entry2exchange NUMBER(*,0),
  act_entry2exch_log NUMBER(*,0),
  act_entry2contr_itm NUMBER(*,0),
  act_entry2count_setup NUMBER,
  focus_lowid NUMBER,
  focus_type NUMBER,
  act_entry_hist2act_entry NUMBER,
  act_entry_his2user VARCHAR2(30 BYTE),
  x_change_date DATE,
  osuser VARCHAR2(30 BYTE),
  triggering_record_type VARCHAR2(6 BYTE)
);