CREATE TABLE sa.upd_table_x_pi_hist (
  objid NUMBER,
  status_hist2x_code_table NUMBER,
  x_change_date DATE,
  x_change_reason VARCHAR2(30 BYTE),
  x_cool_end_date DATE,
  x_creation_date DATE,
  x_deactivation_flag NUMBER,
  x_domain VARCHAR2(20 BYTE),
  x_ext VARCHAR2(10 BYTE),
  x_insert_date DATE,
  x_npa VARCHAR2(10 BYTE),
  x_nxx VARCHAR2(10 BYTE),
  x_old_ext VARCHAR2(10 BYTE),
  x_old_npa VARCHAR2(10 BYTE),
  x_old_nxx VARCHAR2(10 BYTE),
  x_part_bin VARCHAR2(20 BYTE),
  x_part_inst_status VARCHAR2(20 BYTE),
  x_part_mod VARCHAR2(10 BYTE),
  x_part_serial_no VARCHAR2(30 BYTE),
  x_part_status VARCHAR2(40 BYTE),
  x_pi_hist2carrier_mkt NUMBER,
  x_pi_hist2inv_bin NUMBER,
  x_pi_hist2part_inst NUMBER,
  x_pi_hist2part_mod NUMBER,
  x_pi_hist2user NUMBER,
  x_pi_hist2x_new_pers NUMBER,
  x_pi_hist2x_pers NUMBER,
  x_po_num VARCHAR2(30 BYTE),
  x_reactivation_flag NUMBER,
  x_red_code VARCHAR2(30 BYTE),
  x_sequence NUMBER,
  x_warr_end_date DATE,
  dev NUMBER,
  fulfill_hist2demand_dtl NUMBER,
  part_to_esn_hist2part_inst NUMBER,
  x_bad_res_qty NUMBER,
  x_date_in_serv DATE,
  x_good_res_qty NUMBER,
  x_last_cycle_ct DATE,
  x_last_mod_time DATE,
  x_last_pi_date DATE,
  x_last_trans_time DATE,
  x_next_cycle_ct DATE,
  x_order_number VARCHAR2(40 BYTE),
  x_part_bad_qty NUMBER,
  x_part_good_qty NUMBER,
  x_pi_tag_no VARCHAR2(8 BYTE),
  x_pick_request VARCHAR2(255 BYTE),
  x_repair_date DATE,
  x_transaction_id VARCHAR2(20 BYTE),
  x_pi_hist2site_part NUMBER,
  x_msid VARCHAR2(30 BYTE),
  x_pi_hist2contact NUMBER
);
ALTER TABLE sa.upd_table_x_pi_hist ADD SUPPLEMENTAL LOG GROUP dmtsora19575382_1 (fulfill_hist2demand_dtl, part_to_esn_hist2part_inst, x_bad_res_qty, x_date_in_serv, x_good_res_qty, x_last_cycle_ct, x_last_mod_time, x_last_pi_date, x_last_trans_time, x_msid, x_next_cycle_ct, x_order_number, x_part_bad_qty, x_part_good_qty, x_pick_request, x_pi_hist2contact, x_pi_hist2site_part, x_pi_tag_no, x_repair_date, x_transaction_id) ALWAYS;
ALTER TABLE sa.upd_table_x_pi_hist ADD SUPPLEMENTAL LOG GROUP dmtsora19575382_0 (dev, objid, status_hist2x_code_table, x_change_date, x_change_reason, x_cool_end_date, x_creation_date, x_deactivation_flag, x_domain, x_ext, x_insert_date, x_npa, x_nxx, x_old_ext, x_old_npa, x_old_nxx, x_part_bin, x_part_inst_status, x_part_mod, x_part_serial_no, x_part_status, x_pi_hist2carrier_mkt, x_pi_hist2inv_bin, x_pi_hist2part_inst, x_pi_hist2part_mod, x_pi_hist2user, x_pi_hist2x_new_pers, x_pi_hist2x_pers, x_po_num, x_reactivation_flag, x_red_code, x_sequence, x_warr_end_date) ALWAYS;