CREATE TABLE sa.wex_shipping_mtd (
  po VARCHAR2(50 BYTE),
  line_no VARCHAR2(20 BYTE),
  item_code VARCHAR2(20 BYTE),
  class_to VARCHAR2(20 BYTE),
  description VARCHAR2(500 BYTE),
  qty VARCHAR2(20 BYTE),
  "SERIAL" VARCHAR2(100 BYTE),
  order_date DATE,
  ship_date DATE,
  via VARCHAR2(50 BYTE),
  tracking_inf VARCHAR2(50 BYTE),
  bp_order VARCHAR2(30 BYTE),
  ship_to VARCHAR2(50 BYTE),
  ship_add1 VARCHAR2(100 BYTE),
  ship_add2 VARCHAR2(100 BYTE),
  ship_city VARCHAR2(100 BYTE),
  ship_st VARCHAR2(100 BYTE),
  ship_zip VARCHAR2(10 BYTE),
  bill_to VARCHAR2(100 BYTE),
  bill_add1 VARCHAR2(100 BYTE),
  bill_add2 VARCHAR2(100 BYTE),
  bill_city VARCHAR2(50 BYTE),
  bill_st VARCHAR2(100 BYTE),
  bill_zip VARCHAR2(20 BYTE),
  pkg VARCHAR2(20 BYTE),
  whse VARCHAR2(20 BYTE),
  cust_code VARCHAR2(100 BYTE),
  promo VARCHAR2(20 BYTE),
  discount VARCHAR2(20 BYTE),
  sales VARCHAR2(20 BYTE),
  freight_amt VARCHAR2(20 BYTE),
  tax_amt VARCHAR2(30 BYTE),
  merchant_ref VARCHAR2(60 BYTE),
  order_time VARCHAR2(20 BYTE),
  cc_phone VARCHAR2(20 BYTE),
  cc_type VARCHAR2(20 BYTE),
  cc_number VARCHAR2(50 BYTE),
  email_address VARCHAR2(90 BYTE),
  resulting_seq_no VARCHAR2(30 BYTE),
  approval_code VARCHAR2(30 BYTE),
  creation_date DATE
);