CREATE TABLE sa.x_autopay_pending (
  objid NUMBER,
  x_creation_date DATE,
  x_esn VARCHAR2(15 BYTE),
  x_program_type NUMBER,
  x_account_status NUMBER,
  x_status VARCHAR2(1 BYTE),
  x_start_date DATE,
  x_end_date DATE,
  x_cycle_number VARCHAR2(10 BYTE),
  x_program_name VARCHAR2(25 BYTE),
  x_enroll_date DATE,
  x_first_name VARCHAR2(30 BYTE),
  x_last_name VARCHAR2(30 BYTE),
  x_receive_status VARCHAR2(1 BYTE),
  x_agent_id VARCHAR2(10 BYTE),
  x_autopay_details2site_part NUMBER,
  x_autopay_details2x_part_inst NUMBER,
  x_autopay_details2contact NUMBER,
  x_transaction_type VARCHAR2(3 BYTE),
  x_source_flag VARCHAR2(20 BYTE),
  x_address1 VARCHAR2(50 BYTE),
  x_city VARCHAR2(10 BYTE),
  x_state VARCHAR2(10 BYTE),
  x_zipcode VARCHAR2(10 BYTE),
  x_contact_phone VARCHAR2(10 BYTE),
  x_transaction_amount NUMBER,
  x_promocode VARCHAR2(5 BYTE),
  x_enroll_fee_flag VARCHAR2(1 BYTE),
  x_uniquerecord NUMBER,
  x_enroll_amount NUMBER,
  x_source VARCHAR2(3 BYTE),
  x_language_flag VARCHAR2(7 BYTE),
  x_payment_type VARCHAR2(6 BYTE)
);
ALTER TABLE sa.x_autopay_pending ADD SUPPLEMENTAL LOG GROUP dmtsora629579825_0 (objid, x_account_status, x_address1, x_agent_id, x_autopay_details2contact, x_autopay_details2site_part, x_autopay_details2x_part_inst, x_city, x_contact_phone, x_creation_date, x_cycle_number, x_end_date, x_enroll_amount, x_enroll_date, x_enroll_fee_flag, x_esn, x_first_name, x_language_flag, x_last_name, x_payment_type, x_program_name, x_program_type, x_promocode, x_receive_status, x_source, x_source_flag, x_start_date, x_state, x_status, x_transaction_amount, x_transaction_type, x_uniquerecord, x_zipcode) ALWAYS;