CREATE TABLE sa.x_bogo_configuration_bkp (
  objid NUMBER(10),
  brand VARCHAR2(50 BYTE),
  part_class VARCHAR2(40 BYTE),
  phone_part_no VARCHAR2(30 BYTE),
  dealer_name VARCHAR2(80 BYTE),
  dealer_id VARCHAR2(80 BYTE),
  action_type VARCHAR2(20 BYTE),
  eligible_service_plan NUMBER(22),
  channel VARCHAR2(30 BYTE),
  bogo_part_number VARCHAR2(30 BYTE),
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  msg_script_id VARCHAR2(50 BYTE),
  red_card_pin_part_class VARCHAR2(40 BYTE),
  card_pin_part_class VARCHAR2(240 BYTE),
  esn_part_class VARCHAR2(240 BYTE),
  esn_part_number VARCHAR2(240 BYTE),
  esn_dealer_id VARCHAR2(240 BYTE),
  esn_dealer_name VARCHAR2(240 BYTE),
  tsp_id NUMBER(22),
  appl_execution_id NUMBER(22),
  bogo_status VARCHAR2(240 BYTE),
  created_by NUMBER(22),
  updated_by NUMBER(22)
);