CREATE TABLE sa.x_cert_his (
  "SID" NUMBER,
  "ACTION" VARCHAR2(10 BYTE),
  username VARCHAR2(30 BYTE),
  osuser VARCHAR2(100 BYTE),
  "PROCESS" VARCHAR2(100 BYTE),
  machine VARCHAR2(100 BYTE),
  terminal VARCHAR2(100 BYTE),
  "PROGRAM" VARCHAR2(100 BYTE),
  logon_time DATE,
  dt DATE,
  old_objid NUMBER,
  old_x_cert VARCHAR2(64 BYTE),
  old_x_key_algo VARCHAR2(128 BYTE),
  old_x_cc_algo VARCHAR2(128 BYTE),
  old_create_date TIMESTAMP,
  old_notes VARCHAR2(255 BYTE),
  new_objid NUMBER,
  new_x_cert VARCHAR2(64 BYTE),
  new_x_key_algo VARCHAR2(128 BYTE),
  new_x_cc_algo VARCHAR2(128 BYTE),
  new_create_date TIMESTAMP,
  new_notes VARCHAR2(255 BYTE)
);