CREATE TABLE sa.x_code_table_hist (
  objid NUMBER,
  x_code_name VARCHAR2(20 BYTE),
  x_code_number VARCHAR2(20 BYTE),
  x_code_type VARCHAR2(20 BYTE),
  x_value NUMBER,
  x_text LONG,
  new_x_value NUMBER,
  email_require_flag VARCHAR2(1 BYTE),
  email_date DATE,
  x_change_date DATE,
  osuser VARCHAR2(30 BYTE),
  triggering_record_type VARCHAR2(6 BYTE),
  x_code_table_hist2user NUMBER
);
ALTER TABLE sa.x_code_table_hist ADD SUPPLEMENTAL LOG GROUP dmtsora462267790_0 (email_date, email_require_flag, new_x_value, objid, osuser, triggering_record_type, x_change_date, x_code_name, x_code_number, x_code_table_hist2user, x_code_type, x_value) ALWAYS;
COMMENT ON TABLE sa.x_code_table_hist IS 'Changes to table_x_code_tables are stored in this table, the entries are generated by a trigger on the source table';
COMMENT ON COLUMN sa.x_code_table_hist.objid IS 'Internal record number, Primary Key';
COMMENT ON COLUMN sa.x_code_table_hist.x_code_name IS 'Code Name, Description';
COMMENT ON COLUMN sa.x_code_table_hist.x_code_number IS 'Code Number';
COMMENT ON COLUMN sa.x_code_table_hist.x_code_type IS 'Code Type: AT Action Type, CS Card Status, DA Deactivation Reason, LS Line Status, PS Phone status, SIM SIM Status, SL Safe Link Status, SS Sub-Sourcesystem--> Obsolete, AP Parameter-->Obsolete';
COMMENT ON COLUMN sa.x_code_table_hist.x_value IS 'Optional Value Flag for the code';
COMMENT ON COLUMN sa.x_code_table_hist.x_text IS 'Comments associated to code value change';
COMMENT ON COLUMN sa.x_code_table_hist.new_x_value IS 'New Value Flag  for the code';
COMMENT ON COLUMN sa.x_code_table_hist.email_require_flag IS 'Send email required: Y/N';
COMMENT ON COLUMN sa.x_code_table_hist.email_date IS 'Date email sent';
COMMENT ON COLUMN sa.x_code_table_hist.x_change_date IS 'Date of Value Change';
COMMENT ON COLUMN sa.x_code_table_hist.osuser IS 'Operating System User that performed the change.';
COMMENT ON COLUMN sa.x_code_table_hist.x_code_table_hist2user IS 'Foreign Key to Table_user.objid';