CREATE TABLE sa.x_contract_responses (
  objid NUMBER,
  x_status_date DATE,
  x_status VARCHAR2(20 BYTE),
  x_sourcesystem VARCHAR2(30 BYTE),
  x_client_batch_id VARCHAR2(30 BYTE),
  x_customer_id NUMBER,
  x_contract_no VARCHAR2(30 BYTE),
  x_esn VARCHAR2(30 BYTE),
  x_min VARCHAR2(30 BYTE),
  x_action_code VARCHAR2(3 BYTE),
  x_error_code VARCHAR2(1000 BYTE),
  x_error_desc VARCHAR2(1000 BYTE),
  x_result VARCHAR2(1000 BYTE),
  x_refund NUMBER(22)
);
COMMENT ON TABLE sa.x_contract_responses IS 'CONTAINS THE PROCESSING RESULTS OF FILE SENT TO THIRD PARTY (SN) AS WELL AS UPDATES THAT APPLY FOR EXISTING CONTRACTS.';
COMMENT ON COLUMN sa.x_contract_responses.objid IS 'INTERNAL UNIQUE IDENTIFIER.';
COMMENT ON COLUMN sa.x_contract_responses.x_status_date IS 'DATE IN WHICH THE STATUS IS SET.';
COMMENT ON COLUMN sa.x_contract_responses.x_status IS 'STATUS (NEW,PROCESSED,FAILED).';
COMMENT ON COLUMN sa.x_contract_responses.x_sourcesystem IS 'SOURCE SYSTEM (EX. SERVICENET).';
COMMENT ON COLUMN sa.x_contract_responses.x_client_batch_id IS 'BATCH NUMBER THAT CLIENT CAN OPTIONALLY USE.';
COMMENT ON COLUMN sa.x_contract_responses.x_customer_id IS 'UNIQUE IDENTIFIER OF INDIVIDUAL CONSUMER.';
COMMENT ON COLUMN sa.x_contract_responses.x_contract_no IS 'UNIQUE IDENTIFIER FOR THE CONTRACT.';
COMMENT ON COLUMN sa.x_contract_responses.x_esn IS 'PHONE SERIAL NUMBER.';
COMMENT ON COLUMN sa.x_contract_responses.x_min IS 'TELEPHONE NUMBER (MIN).';
COMMENT ON COLUMN sa.x_contract_responses.x_action_code IS 'INDICATES UPDATE EVENT TO CONTRACT/CONSUMER DATA (001 NEW SALE,010 CANCEL A CONTRACT,100 UPDATE CUSTOMER INFO,115 UPDATE TO PRODUCT)';
COMMENT ON COLUMN sa.x_contract_responses.x_error_code IS 'INDICATES THE ERROR CODE THAT OCCURRED WITH THE SPECIFIC CONTRACT OR WILL CONTAIN THE CONTRACT # THAT WAS CREATED UPON SUCCESSFUL UPLOAD';
COMMENT ON COLUMN sa.x_contract_responses.x_error_desc IS 'INDICATES THE ERROR DESCRIPTION THAT OCCURRED WITH THE SPECIFIC CONTRACT OR THAT THE CONTRACT WAS SUCCESSFULLY UPLOADED';
COMMENT ON COLUMN sa.x_contract_responses.x_result IS 'DESCRIBES THE PROCESS RESULT (EX. NOT ENROLLMENT PENDING, ALREADY HAS A HP PROGRAM ENROLLED OR ESN/MIN IS NOT ACTIVE) OR ""ENROLLED"" WHEN IS PROCESSED SUCCESSFULLY';
COMMENT ON COLUMN sa.x_contract_responses.x_refund IS 'RETAIL REFUND (EXCLUSIVE OF TAXES)';