CREATE TABLE sa.x_cwl7 (
  f_units NUMBER,
  f_x_access NUMBER,
  f_x_smp VARCHAR2(30 BYTE),
  f_call_trans_objid NUMBER,
  f_part_number VARCHAR2(30 BYTE),
  f_part_objid NUMBER,
  f_description VARCHAR2(255 BYTE),
  f_part_type VARCHAR2(20 BYTE),
  ct_objid NUMBER,
  ct_call_trans2site_part NUMBER,
  ct_x_action_type VARCHAR2(20 BYTE),
  ct_x_call_trans2carrier NUMBER,
  ct_x_call_trans2dealer NUMBER,
  ct_x_call_trans2user NUMBER,
  ct_x_line_status VARCHAR2(20 BYTE),
  ct_x_min VARCHAR2(30 BYTE),
  ct_x_service_id VARCHAR2(30 BYTE),
  ct_x_sourcesystem VARCHAR2(30 BYTE),
  ct_x_transact_date DATE,
  ct_x_total_units NUMBER,
  ct_x_action_text VARCHAR2(20 BYTE),
  ct_x_reason VARCHAR2(20 BYTE),
  ct_x_result VARCHAR2(20 BYTE),
  cardpi_part_serial_no VARCHAR2(30 BYTE),
  cardpi_x_red_code VARCHAR2(30 BYTE),
  cardpi_part_inst2inv_bin NUMBER,
  esnpi_n_part_inst2part_mod NUMBER,
  esnpi_part_inst2inv_bin NUMBER,
  esnpi_x_po_num VARCHAR2(30 BYTE),
  cellpi_x_insert_date DATE,
  cellpi_part_inst2x_pers NUMBER,
  cellpi_objid NUMBER,
  cellpi_part_inst2carrier_mkt NUMBER,
  sp_install_date DATE,
  sp_x_zipcode VARCHAR2(20 BYTE),
  sp_site_part2x_plan NUMBER,
  sp_site_part2site NUMBER,
  sp_objid NUMBER,
  ah_account_hist2x_account NUMBER,
  cn_first_name VARCHAR2(30 BYTE),
  cn_last_name VARCHAR2(30 BYTE),
  cn_phone VARCHAR2(20 BYTE),
  cr_contact_role2site NUMBER(*,0)
);
ALTER TABLE sa.x_cwl7 ADD SUPPLEMENTAL LOG GROUP dmtsora414295196_0 (cardpi_part_inst2inv_bin, cardpi_part_serial_no, cardpi_x_red_code, cellpi_objid, cellpi_part_inst2carrier_mkt, cellpi_part_inst2x_pers, cellpi_x_insert_date, ct_call_trans2site_part, ct_objid, ct_x_action_text, ct_x_action_type, ct_x_call_trans2carrier, ct_x_call_trans2dealer, ct_x_call_trans2user, ct_x_line_status, ct_x_min, ct_x_reason, ct_x_result, ct_x_service_id, ct_x_sourcesystem, ct_x_total_units, ct_x_transact_date, esnpi_n_part_inst2part_mod, esnpi_part_inst2inv_bin, esnpi_x_po_num, f_call_trans_objid, f_description, f_part_number, f_part_objid, f_part_type, f_units, f_x_access, f_x_smp) ALWAYS;
ALTER TABLE sa.x_cwl7 ADD SUPPLEMENTAL LOG GROUP dmtsora414295196_1 (ah_account_hist2x_account, cn_first_name, cn_last_name, cn_phone, cr_contact_role2site, sp_install_date, sp_objid, sp_site_part2site, sp_site_part2x_plan, sp_x_zipcode) ALWAYS;