CREATE TABLE sa.x_duggi_ota_part_num (
  pi_objid NUMBER,
  part_serial_no VARCHAR2(30 BYTE),
  transaction_id VARCHAR2(20 BYTE),
  x_part_inst_status VARCHAR2(20 BYTE),
  objid NUMBER,
  dev NUMBER,
  x_redemption_menu VARCHAR2(30 BYTE),
  x_handset_lock VARCHAR2(30 BYTE),
  x_low_units VARCHAR2(30 BYTE),
  x_ota_features2part_num NUMBER,
  x_ota_features2part_inst NUMBER,
  x_psms_destination_addr VARCHAR2(30 BYTE),
  x_ild_account VARCHAR2(30 BYTE),
  x_ild_carr_status VARCHAR2(30 BYTE),
  x_ild_prog_status VARCHAR2(30 BYTE),
  x_ild_counter NUMBER,
  x_close_count NUMBER,
  x_current_conv_rate NUMBER(19,4),
  x_spp_pin_on VARCHAR2(30 BYTE),
  x_buy_airtime_menu VARCHAR2(30 BYTE),
  x_spp_promo_code VARCHAR2(30 BYTE),
  current_config2x_data_config NUMBER,
  new_config2x_data_config NUMBER,
  x_data_config_prog_counter NUMBER,
  part_number VARCHAR2(30 BYTE),
  x_technology VARCHAR2(20 BYTE),
  x_dll NUMBER,
  x_ota_allowed VARCHAR2(10 BYTE),
  x_restricted_use NUMBER,
  status VARCHAR2(10 BYTE)
);
ALTER TABLE sa.x_duggi_ota_part_num ADD SUPPLEMENTAL LOG GROUP dmtsora1698777088_0 (current_config2x_data_config, dev, new_config2x_data_config, objid, part_number, part_serial_no, pi_objid, status, transaction_id, x_buy_airtime_menu, x_close_count, x_current_conv_rate, x_data_config_prog_counter, x_dll, x_handset_lock, x_ild_account, x_ild_carr_status, x_ild_counter, x_ild_prog_status, x_low_units, x_ota_allowed, x_ota_features2part_inst, x_ota_features2part_num, x_part_inst_status, x_psms_destination_addr, x_redemption_menu, x_restricted_use, x_spp_pin_on, x_spp_promo_code, x_technology) ALWAYS;