CREATE TABLE sa.x_employee_hist (
  objid NUMBER,
  first_name VARCHAR2(30 BYTE),
  s_first_name VARCHAR2(30 BYTE),
  last_name VARCHAR2(30 BYTE),
  s_last_name VARCHAR2(30 BYTE),
  mail_stop VARCHAR2(30 BYTE),
  phone VARCHAR2(20 BYTE),
  alt_phone VARCHAR2(20 BYTE),
  fax VARCHAR2(20 BYTE),
  beeper VARCHAR2(20 BYTE),
  e_mail VARCHAR2(80 BYTE),
  labor_rate NUMBER,
  field_eng NUMBER,
  acting_supvr NUMBER,
  available NUMBER,
  avail_note VARCHAR2(255 BYTE),
  employee_no VARCHAR2(8 BYTE),
  normal_biz_high VARCHAR2(32 BYTE),
  normal_biz_mid VARCHAR2(32 BYTE),
  normal_biz_low VARCHAR2(32 BYTE),
  after_biz_high VARCHAR2(32 BYTE),
  after_biz_mid VARCHAR2(32 BYTE),
  after_biz_low VARCHAR2(32 BYTE),
  work_group VARCHAR2(80 BYTE),
  wg_strt_date DATE,
  site_strt_date DATE,
  voice_mail_box VARCHAR2(20 BYTE),
  local_login VARCHAR2(30 BYTE),
  local_password VARCHAR2(30 BYTE),
  allow_proxy NUMBER,
  printer VARCHAR2(30 BYTE),
  on_call_hw NUMBER,
  on_call_sw NUMBER,
  case_threshold NUMBER,
  dev NUMBER,
  employee2user NUMBER(*,0),
  emp_supvr2employee NUMBER(*,0),
  supp_person_off2site NUMBER(*,0),
  cc_list2bug NUMBER(*,0),
  empl_hrs2biz_cal_hdr NUMBER(*,0),
  employee2contact NUMBER(*,0),
  x_dashboard NUMBER,
  x_error_code_maint NUMBER,
  x_order_types NUMBER,
  x_q_maint NUMBER,
  x_select_trans_prof NUMBER,
  x_update_set NUMBER,
  x_allow_script NUMBER,
  x_allow_roadside NUMBER,
  salutation VARCHAR2(20 BYTE),
  title VARCHAR2(30 BYTE),
  employee_hist2employee NUMBER,
  employee_hist2user NUMBER,
  x_change_date DATE,
  osuser VARCHAR2(30 BYTE),
  triggering_record_type VARCHAR2(6 BYTE)
);