CREATE TABLE sa.x_load_iccid_tmp (
  row_id ROWID NOT NULL,
  iccid VARCHAR2(100 BYTE),
  quantity NUMBER,
  pin1 VARCHAR2(60 BYTE),
  puk1 VARCHAR2(60 BYTE),
  pin2 VARCHAR2(60 BYTE),
  puk2 VARCHAR2(60 BYTE),
  imsi VARCHAR2(60 BYTE),
  attribute1 VARCHAR2(240 BYTE),
  attribute2 VARCHAR2(240 BYTE),
  attribute3 VARCHAR2(240 BYTE),
  attribute4 VARCHAR2(240 BYTE),
  sim_processed VARCHAR2(240 BYTE),
  creation_date DATE,
  created_by VARCHAR2(60 BYTE),
  last_update_date DATE,
  last_updated_by VARCHAR2(60 BYTE),
  po_num VARCHAR2(20 BYTE),
  sku_num VARCHAR2(40 BYTE),
  vendor VARCHAR2(40 BYTE),
  tf_num VARCHAR2(30 BYTE),
  byop_extract_flag VARCHAR2(1 BYTE),
  expiration_date DATE,
  error_details VARCHAR2(200 BYTE),
  pa_pk VARCHAR2(100 BYTE),
  ma_pk VARCHAR2(100 BYTE),
  in_pk VARCHAR2(100 BYTE),
  request_id NUMBER(22)
);