CREATE TABLE sa.x_mtm_ret_flow_scn_action (
  objid NUMBER,
  x_act2ret_flw NUMBER,
  x_act2ret_scn NUMBER,
  x_action VARCHAR2(50 BYTE),
  w_enr_script_id VARCHAR2(15 BYTE),
  w_not_enr_script_id VARCHAR2(15 BYTE),
  spl_script_id VARCHAR2(15 BYTE),
  warning_id VARCHAR2(15 BYTE)
);
COMMENT ON TABLE sa.x_mtm_ret_flow_scn_action IS 'CONFIGURES THE AVAILABLE ACTIONS BASED ON FLOWS AND SCENARIOS.';
COMMENT ON COLUMN sa.x_mtm_ret_flow_scn_action.objid IS 'UNIQUE VALUES POPULATED USING SEQUENCE(SEQ_RET_FLOW_SCN_ACTION).';
COMMENT ON COLUMN sa.x_mtm_ret_flow_scn_action.x_act2ret_flw IS 'OBJID OF X_RETENTION_FLOWS.';
COMMENT ON COLUMN sa.x_mtm_ret_flow_scn_action.x_act2ret_scn IS 'OBJID OF X_RETENTION_SCENARIOS.';
COMMENT ON COLUMN sa.x_mtm_ret_flow_scn_action.x_action IS 'AVAILABLE ACTION(S) FOR PARTICULAR FLOW AND SCENARIO.
APPLY_NOW = APPLY MONTHLY CHARGES AND DELIVER BENEFITS NOW. CHANGE NEXT CHARGE DATE TO NEW DUE DATE.
 ENROLL_NOW = CHARGE CC, ENROLL IN PLAN, AND DELIVER PLAN BENEFITS NOW. SET NEXT CHARGE DATE TO NEW DUE DATE.
ENROLL_ON_DUE_DATE = PROCESS DB ENROLLMENT IN PLAN BUT CC CHARGE AND BENEFITS DELIVERY TO HAPPEN ON DUE DATE.
ADD_NOW = ADD AIRTIME CARD NOW.
ADD_TO_RESERVE = ADD AIRTIME CARD TO RESERVE.';
COMMENT ON COLUMN sa.x_mtm_ret_flow_scn_action.warning_id IS 'Warning Script Id';