CREATE TABLE sa.x_partner_transaction_log (
  objid NUMBER NOT NULL,
  creation_date DATE NOT NULL,
  transaction_id VARCHAR2(255 BYTE) NOT NULL,
  client_id VARCHAR2(100 BYTE),
  source_system VARCHAR2(30 BYTE),
  zipcode VARCHAR2(20 BYTE),
  esn VARCHAR2(30 BYTE),
  sim VARCHAR2(30 BYTE),
  pin VARCHAR2(30 BYTE),
  enroll_plan_id NUMBER,
  pymt_first_name VARCHAR2(30 BYTE),
  pymt_last_name VARCHAR2(30 BYTE),
  pymt_phone_number VARCHAR2(20 BYTE),
  pymt_email VARCHAR2(80 BYTE),
  pymt_address_1 VARCHAR2(200 BYTE),
  pymt_address_2 VARCHAR2(200 BYTE),
  pymt_city VARCHAR2(30 BYTE),
  pymt_state VARCHAR2(40 BYTE),
  pymt_zipcode VARCHAR2(20 BYTE),
  pymt_source_type VARCHAR2(20 BYTE),
  pymt_nickname VARCHAR2(30 BYTE),
  pymt_cardtype VARCHAR2(20 BYTE),
  pymt_account_number VARCHAR2(255 BYTE),
  pymt_exp_year VARCHAR2(4 BYTE),
  pymt_exp_month VARCHAR2(2 BYTE),
  pymt_cvv VARCHAR2(20 BYTE),
  account_email VARCHAR2(50 BYTE),
  account_pswd VARCHAR2(255 BYTE),
  service_name VARCHAR2(50 BYTE),
  transaction_status VARCHAR2(400 BYTE),
  paymentobjid NUMBER,
  authcode VARCHAR2(30 BYTE)
);
COMMENT ON TABLE sa.x_partner_transaction_log IS 'TO STORE PARTNER TRANSACTIONS LOG  AND SUPPORT THE PROCESS COMMISSIONS PAYMENT';
COMMENT ON COLUMN sa.x_partner_transaction_log.objid IS 'INTERNAL RECORD ID';
COMMENT ON COLUMN sa.x_partner_transaction_log.creation_date IS 'TIMESTAMP WHEN RECORD IS CREATED';
COMMENT ON COLUMN sa.x_partner_transaction_log.transaction_id IS 'CLIENT TRANSACTION ID';
COMMENT ON COLUMN sa.x_partner_transaction_log.client_id IS 'CLIENT ID';
COMMENT ON COLUMN sa.x_partner_transaction_log.source_system IS 'SOURCE SYSTEM';
COMMENT ON COLUMN sa.x_partner_transaction_log.zipcode IS 'ZIP CODE';
COMMENT ON COLUMN sa.x_partner_transaction_log.esn IS 'ESN';
COMMENT ON COLUMN sa.x_partner_transaction_log.sim IS 'SIM';
COMMENT ON COLUMN sa.x_partner_transaction_log.pin IS 'PIN NUMBER RELATED WITH THE ACTIVATION PROCESS (OPTIONAL)';
COMMENT ON COLUMN sa.x_partner_transaction_log.enroll_plan_id IS 'REFERENCE TO  X_PROGRAM_PARAMETERS.OBJID';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_first_name IS 'CUSTOMER FIRST NAME';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_last_name IS 'CUSTOMER LAST NAME';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_phone_number IS 'PHONE NUMBER';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_email IS 'CUSTOMER EMAIL ADDRESS';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_address_1 IS 'ADDRESS ASSOCIATED TO THE PAYMENT';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_address_2 IS 'ADDRESS ASSOCIATED TO THE PAYMENT';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_city IS 'CITY ASSOCIATED TO THE PAYMENT';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_state IS 'STATE ASSOCIATED TO THE PAYMENT';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_zipcode IS 'ZIPCODE ASSOCIATED TO THE PAYMENT';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_source_type IS 'PAYMENT SOURCE TYPE (FORM OF PAYMENT)';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_nickname IS 'PAYMENT SOURCE NICKNAME';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_cardtype IS 'CARD TYPE (AMEX, VISA, DISCOVER, MASTERCARD, ETC)';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_account_number IS 'ACCOUNT NUMBER';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_exp_year IS 'CARD EXPIRATION YEAR NUMBER EG =2001';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_exp_month IS 'CARD EXPIRATION MONTH NUMBER EG =12';
COMMENT ON COLUMN sa.x_partner_transaction_log.pymt_cvv IS 'CVV2 NUMBER FOR ADDITIONAL CARD VALIDATION EG =47E';
COMMENT ON COLUMN sa.x_partner_transaction_log.account_email IS 'CUSTOMER ACCOUNT EMAIL';
COMMENT ON COLUMN sa.x_partner_transaction_log.account_pswd IS 'CUSTOMER ACCOUNT PASSWORD';
COMMENT ON COLUMN sa.x_partner_transaction_log.service_name IS 'SERVICE NAME WITH FAILURE, IN CASE OF FAILURES THIS COLUMN WILL HAVE THE NAME OF THE SERVICE THAT FAILED';
COMMENT ON COLUMN sa.x_partner_transaction_log.transaction_status IS 'TRANSACTION RESULT "SUCCESS" WHEN PASS OR ERROR DESCRIPTION WHEN FAIL';
COMMENT ON COLUMN sa.x_partner_transaction_log.paymentobjid IS 'REFERENCE TO X_PAYMENT_SOURCE.OBJID';
COMMENT ON COLUMN sa.x_partner_transaction_log.authcode IS 'TRANSACTION ID GENERATED BY CYBERSOURCE   (IDEM X_PROGRAM_PURCH_HDR.X_MERCHANT_REF_NUMBER)';