CREATE TABLE sa.x_pcrf_transaction_jt (
  objid NUMBER(22) NOT NULL,
  "MIN" VARCHAR2(30 BYTE),
  esn VARCHAR2(30 BYTE),
  subscriber_id VARCHAR2(50 BYTE),
  "GROUP_ID" VARCHAR2(50 BYTE),
  order_type VARCHAR2(30 BYTE),
  phone_manufacturer VARCHAR2(30 BYTE),
  action_type VARCHAR2(1 BYTE),
  sim VARCHAR2(30 BYTE),
  zipcode VARCHAR2(10 BYTE),
  service_plan_id NUMBER(22),
  case_id NUMBER(22),
  pcrf_status_code VARCHAR2(2 BYTE) NOT NULL,
  status_message VARCHAR2(1000 BYTE),
  web_objid NUMBER(22),
  brand VARCHAR2(40 BYTE),
  sourcesystem VARCHAR2(30 BYTE),
  "TEMPLATE" VARCHAR2(30 BYTE),
  rate_plan VARCHAR2(60 BYTE),
  blackout_wait_date DATE,
  retry_count NUMBER(10),
  data_usage NUMBER(14,2),
  hi_speed_data_usage NUMBER(14,2),
  conversion_factor VARCHAR2(50 BYTE),
  dealer_id VARCHAR2(80 BYTE),
  denomination VARCHAR2(50 BYTE),
  pcrf_parent_name VARCHAR2(40 BYTE),
  propagate_flag NUMBER(4),
  service_plan_type VARCHAR2(50 BYTE),
  part_inst_status VARCHAR2(30 BYTE),
  phone_model VARCHAR2(50 BYTE),
  content_delivery_format VARCHAR2(50 BYTE),
  language VARCHAR2(30 BYTE),
  wf_mac_id VARCHAR2(50 BYTE),
  pcrf_cos VARCHAR2(30 BYTE),
  ttl DATE,
  future_ttl DATE,
  redemption_date DATE,
  insert_timestamp DATE NOT NULL,
  update_timestamp DATE NOT NULL,
  mdn VARCHAR2(30 BYTE),
  contact_objid NUMBER(22)
);