CREATE TABLE sa.x_queue_event_log (
  objid NUMBER NOT NULL,
  esn VARCHAR2(30 BYTE),
  event_name VARCHAR2(100 BYTE),
  "MIN" VARCHAR2(30 BYTE),
  msid VARCHAR2(30 BYTE),
  call_trans_objid NUMBER,
  action_type VARCHAR2(20 BYTE),
  action_text VARCHAR2(30 BYTE),
  reason VARCHAR2(500 BYTE),
  sourcesystem VARCHAR2(30 BYTE),
  sub_sourcesystem VARCHAR2(30 BYTE),
  bus_org_id VARCHAR2(50 BYTE),
  "PRIORITY" NUMBER(2) DEFAULT 1,
  site_part_objid NUMBER,
  queue_event_log_status VARCHAR2(1 BYTE) DEFAULT 'N',
  seconds_delay NUMBER(4) DEFAULT 0,
  enqueue_output_message VARCHAR2(500 BYTE),
  enqueue_timestamp DATE,
  dequeue_timestamp DATE,
  ignore_duplicate_flag VARCHAR2(1 BYTE) DEFAULT 'N',
  insert_timestamp DATE DEFAULT SYSDATE,
  update_timestamp DATE DEFAULT SYSDATE,
  ig_transaction_id NUMBER,
  ig_order_type VARCHAR2(30 BYTE),
  payload sa.q_payload_t,
  request XMLTYPE,
  response XMLTYPE,
  http_code NUMBER,
  retry_count NUMBER,
  smps sa.smplist,
  CONSTRAINT pk_queue_event_log PRIMARY KEY (objid),
  CONSTRAINT fk1_queue_event_log FOREIGN KEY (queue_event_log_status) REFERENCES sa.x_queue_event_log_status (queue_event_log_status)
);
COMMENT ON TABLE sa.x_queue_event_log IS 'Global Temporary table to hold temporary events';