CREATE TABLE sa.x_republik_order_stg (
  call_date DATE,
  product_code1 VARCHAR2(10 BYTE),
  product_code2 VARCHAR2(10 BYTE),
  product_code3 VARCHAR2(10 BYTE),
  ship_firstname VARCHAR2(30 BYTE),
  ship_lastname CHAR(30 BYTE),
  ship_address1 VARCHAR2(200 BYTE),
  ship_address2 VARCHAR2(200 BYTE),
  ship_city VARCHAR2(30 BYTE),
  ship_state VARCHAR2(40 BYTE),
  ship_zip VARCHAR2(20 BYTE),
  phone VARCHAR2(20 BYTE),
  email VARCHAR2(80 BYTE),
  expedite_ship VARCHAR2(1 BYTE),
  bill_firstname VARCHAR2(30 BYTE),
  bill_lastname VARCHAR2(30 BYTE),
  bill_address1 VARCHAR2(200 BYTE),
  bill_address2 VARCHAR2(200 BYTE),
  bill_city VARCHAR2(30 BYTE),
  bill_state VARCHAR2(40 BYTE),
  bill_zip VARCHAR2(20 BYTE),
  cc_type VARCHAR2(1 BYTE),
  cc_number VARCHAR2(1000 BYTE),
  cc_exp_date DATE,
  check_acct_bank_name VARCHAR2(40 BYTE),
  check_acct_bank_loc VARCHAR2(30 BYTE),
  check_number NUMBER,
  check_acct_number VARCHAR2(53 BYTE),
  merch_order_number VARCHAR2(40 BYTE) NOT NULL,
  auth_apr_code VARCHAR2(6 BYTE),
  amount NUMBER,
  taxes NUMBER,
  authed_total NUMBER,
  ani VARCHAR2(10 BYTE),
  number_dialed VARCHAR2(20 BYTE),
  call_disp_code VARCHAR2(4 BYTE),
  payment_method VARCHAR2(6 BYTE),
  tech_zip VARCHAR2(7 BYTE),
  west_product_code VARCHAR2(6 BYTE),
  approval_status NUMBER,
  sourcesystem VARCHAR2(30 BYTE)
);
ALTER TABLE sa.x_republik_order_stg ADD SUPPLEMENTAL LOG GROUP dmtsora1892787701_0 (amount, authed_total, auth_apr_code, bill_address1, bill_address2, bill_city, bill_firstname, bill_lastname, bill_state, bill_zip, call_date, cc_exp_date, cc_number, cc_type, check_acct_bank_loc, check_acct_bank_name, check_acct_number, check_number, email, expedite_ship, merch_order_number, phone, product_code1, product_code2, product_code3, ship_address1, ship_address2, ship_city, ship_firstname, ship_lastname, ship_state, ship_zip, taxes) ALWAYS;
ALTER TABLE sa.x_republik_order_stg ADD SUPPLEMENTAL LOG GROUP dmtsora1892787701_1 (ani, approval_status, call_disp_code, number_dialed, payment_method, sourcesystem, tech_zip, west_product_code) ALWAYS;