CREATE TABLE sa.x_republik_order_hdr (
  toss_order_id NUMBER NOT NULL,
  call_date DATE,
  ship_firstname VARCHAR2(30 BYTE),
  ship_lastname VARCHAR2(30 BYTE),
  ship_address1 VARCHAR2(200 BYTE),
  ship_address2 VARCHAR2(200 BYTE),
  ship_city VARCHAR2(30 BYTE),
  ship_state VARCHAR2(40 BYTE),
  ship_zip VARCHAR2(20 BYTE),
  phone VARCHAR2(20 BYTE),
  email VARCHAR2(80 BYTE),
  expedite_ship VARCHAR2(1 BYTE),
  bill_firstname VARCHAR2(30 BYTE),
  bill_lastname VARCHAR2(30 BYTE),
  bill_address1 VARCHAR2(200 BYTE),
  bill_address2 VARCHAR2(200 BYTE),
  bill_city VARCHAR2(30 BYTE),
  bill_state VARCHAR2(40 BYTE),
  bill_zip VARCHAR2(20 BYTE),
  cc_type VARCHAR2(20 BYTE),
  cc_number VARCHAR2(1000 BYTE),
  cc_exp_date DATE,
  check_acct_bank_name VARCHAR2(40 BYTE),
  check_acct_bank_loc VARCHAR2(30 BYTE),
  check_number NUMBER,
  check_acct_number VARCHAR2(53 BYTE),
  merch_order_number VARCHAR2(40 BYTE),
  auth_apr_code VARCHAR2(6 BYTE),
  amount NUMBER,
  taxes NUMBER,
  authed_total NUMBER,
  ani VARCHAR2(10 BYTE),
  number_dialed VARCHAR2(20 BYTE),
  url VARCHAR2(200 BYTE),
  call_disp_code VARCHAR2(4 BYTE),
  tech_zip VARCHAR2(7 BYTE),
  last_updated_date DATE,
  last_order_status VARCHAR2(20 BYTE),
  ofs_extract_flag VARCHAR2(20 BYTE),
  ofs_extract_date DATE,
  ff_name VARCHAR2(20 BYTE),
  ff_inbound_flag VARCHAR2(20 BYTE),
  ff_inbound_date DATE,
  ff_outbound_flag VARCHAR2(20 BYTE),
  ff_outbound_date DATE,
  last_updated_by VARCHAR2(50 BYTE),
  created_by VARCHAR2(50 BYTE),
  created_date DATE,
  payment_method VARCHAR2(20 BYTE),
  sourcesystem VARCHAR2(30 BYTE),
  west_product_code VARCHAR2(6 BYTE),
  approval_status NUMBER
);
ALTER TABLE sa.x_republik_order_hdr ADD SUPPLEMENTAL LOG GROUP dmtsora1270071070_1 (approval_status, call_disp_code, created_by, created_date, ff_inbound_date, ff_inbound_flag, ff_name, ff_outbound_date, ff_outbound_flag, last_order_status, last_updated_by, last_updated_date, ofs_extract_date, ofs_extract_flag, payment_method, sourcesystem, tech_zip, url, west_product_code) ALWAYS;
ALTER TABLE sa.x_republik_order_hdr ADD SUPPLEMENTAL LOG GROUP dmtsora1270071070_0 (amount, ani, authed_total, auth_apr_code, bill_address1, bill_address2, bill_city, bill_firstname, bill_lastname, bill_state, bill_zip, call_date, cc_exp_date, cc_number, cc_type, check_acct_bank_loc, check_acct_bank_name, check_acct_number, check_number, email, expedite_ship, merch_order_number, number_dialed, phone, ship_address1, ship_address2, ship_city, ship_firstname, ship_lastname, ship_state, ship_zip, taxes, toss_order_id) ALWAYS;