CREATE TABLE sa.x_rebate_info (
  "BATCH" VARCHAR2(50 BYTE),
  "TRANSACTION" VARCHAR2(50 BYTE),
  first_name VARCHAR2(30 BYTE),
  last_name VARCHAR2(30 BYTE),
  address1 VARCHAR2(200 BYTE),
  address2 VARCHAR2(200 BYTE),
  city VARCHAR2(30 BYTE),
  "STATE" VARCHAR2(40 BYTE),
  zip VARCHAR2(20 BYTE),
  offer VARCHAR2(100 BYTE),
  enter_date DATE,
  deal_objid NUMBER,
  deal_name VARCHAR2(80 BYTE),
  deal_id VARCHAR2(80 BYTE),
  esn VARCHAR2(30 BYTE),
  status VARCHAR2(50 BYTE),
  receive_date DATE,
  times_processed NUMBER(7),
  phone VARCHAR2(30 BYTE),
  email VARCHAR2(80 BYTE),
  red_code VARCHAR2(30 BYTE),
  act_date DATE
);