CREATE TABLE sa.x_road_ftp (
  objid NUMBER,
  service_id VARCHAR2(30 BYTE),
  part_serial_no VARCHAR2(30 BYTE),
  program_name VARCHAR2(80 BYTE),
  first_name VARCHAR2(30 BYTE),
  last_name VARCHAR2(30 BYTE),
  address_1 VARCHAR2(200 BYTE),
  address_2 VARCHAR2(200 BYTE),
  city VARCHAR2(30 BYTE),
  "STATE" VARCHAR2(40 BYTE),
  zipcode VARCHAR2(20 BYTE),
  phone VARCHAR2(20 BYTE),
  e_mail VARCHAR2(80 BYTE),
  info_reqd VARCHAR2(10 BYTE),
  trans_type VARCHAR2(10 BYTE),
  activation_date DATE,
  service_start_date DATE,
  service_end_date DATE,
  deactivation_date DATE,
  deact_reason VARCHAR2(30 BYTE),
  term NUMBER,
  wholesale_cost NUMBER,
  card_plan VARCHAR2(10 BYTE),
  card_type VARCHAR2(20 BYTE),
  wholesale_refund NUMBER,
  customer_refund NUMBER,
  refund_percent NUMBER,
  ftp_create_status VARCHAR2(20 BYTE),
  ftp_create_date DATE,
  orafin_post VARCHAR2(1000 BYTE),
  dep1_first_name VARCHAR2(40 BYTE),
  dep1_last_name VARCHAR2(40 BYTE),
  dep2_first_name VARCHAR2(40 BYTE),
  dep2_last_name VARCHAR2(40 BYTE),
  dep3_first_name VARCHAR2(40 BYTE),
  dep3_last_name VARCHAR2(40 BYTE),
  dep4_first_name VARCHAR2(40 BYTE),
  dep4_last_name VARCHAR2(40 BYTE),
  dependent_count NUMBER,
  promo_objid NUMBER,
  promo_code VARCHAR2(30 BYTE),
  call_trans_objid NUMBER,
  sourcesystem VARCHAR2(30 BYTE),
  road_dealer_objid NUMBER,
  road_dealer_id VARCHAR2(80 BYTE),
  road_dealer_name VARCHAR2(80 BYTE),
  road_part_num_objid NUMBER,
  road_part_number VARCHAR2(30 BYTE),
  road_part_description VARCHAR2(255 BYTE),
  road_part_retailcost NUMBER(8,2),
  user_objid NUMBER,
  user_login_name VARCHAR2(30 BYTE),
  user_first_name VARCHAR2(30 BYTE),
  user_last_name VARCHAR2(30 BYTE),
  last_update_date DATE NOT NULL,
  last_updated_by VARCHAR2(30 BYTE) NOT NULL
);
ALTER TABLE sa.x_road_ftp ADD SUPPLEMENTAL LOG GROUP dmtsora747374240_0 (activation_date, address_1, address_2, card_plan, card_type, city, customer_refund, deactivation_date, deact_reason, dep1_first_name, dep1_last_name, dep2_first_name, e_mail, first_name, ftp_create_date, ftp_create_status, info_reqd, last_name, objid, orafin_post, part_serial_no, phone, program_name, refund_percent, service_end_date, service_id, service_start_date, "STATE", term, trans_type, wholesale_cost, wholesale_refund, zipcode) ALWAYS;
ALTER TABLE sa.x_road_ftp ADD SUPPLEMENTAL LOG GROUP dmtsora747374240_1 (call_trans_objid, dep2_last_name, dep3_first_name, dep3_last_name, dep4_first_name, dep4_last_name, dependent_count, last_updated_by, last_update_date, promo_code, promo_objid, road_dealer_id, road_dealer_name, road_dealer_objid, road_part_description, road_part_number, road_part_num_objid, road_part_retailcost, sourcesystem, user_first_name, user_last_name, user_login_name, user_objid) ALWAYS;