CREATE TABLE sa.x_rtr_trans_detail (
  objid NUMBER NOT NULL,
  order_detail_id NUMBER,
  rtr_trans_header_objid NUMBER,
  part_num_parent VARCHAR2(100 BYTE),
  serial_num VARCHAR2(100 BYTE),
  red_code VARCHAR2(100 BYTE),
  pin_status_code VARCHAR2(100 BYTE),
  extract_flag VARCHAR2(1 BYTE),
  extract_date DATE,
  site_id VARCHAR2(40 BYTE),
  rtr_trans_type VARCHAR2(40 BYTE),
  upc VARCHAR2(30 BYTE),
  "MIN" VARCHAR2(30 BYTE),
  esn VARCHAR2(100 BYTE),
  amount NUMBER,
  status VARCHAR2(500 BYTE),
  sim VARCHAR2(30 BYTE),
  insert_timestamp DATE,
  update_timestamp DATE,
  CONSTRAINT pk_rtr_trans_detail PRIMARY KEY (objid),
  CONSTRAINT fk1_rtr_trans_detail FOREIGN KEY (status) REFERENCES sa.x_rtr_trans_detail_status (rtr_trans_detail_status),
  CONSTRAINT fk2_rtr_trans_detail FOREIGN KEY (rtr_trans_header_objid) REFERENCES sa.x_rtr_trans_header (objid)
);