CREATE TABLE sa.x_settlements_history (
  objid NUMBER,
  record_type VARCHAR2(50 BYTE),
  submission_date DATE,
  pid VARCHAR2(50 BYTE),
  pid_short_name VARCHAR2(50 BYTE),
  submission_no VARCHAR2(50 BYTE),
  record_no VARCHAR2(50 BYTE),
  entity_type VARCHAR2(50 BYTE),
  entity_no VARCHAR2(50 BYTE),
  currency VARCHAR2(50 BYTE),
  merchant_order VARCHAR2(50 BYTE),
  rdfi VARCHAR2(50 BYTE),
  account_no VARCHAR2(50 BYTE),
  expiration_date VARCHAR2(50 BYTE),
  amount VARCHAR2(50 BYTE),
  mop VARCHAR2(50 BYTE),
  action_code VARCHAR2(50 BYTE),
  auth_date DATE,
  auth_code VARCHAR2(50 BYTE),
  auth_response_code VARCHAR2(50 BYTE),
  trace_no VARCHAR2(50 BYTE),
  invoice_no VARCHAR2(50 BYTE),
  dealer_no VARCHAR2(50 BYTE),
  mcc VARCHAR2(50 BYTE),
  cc_num_enc VARCHAR2(100 BYTE),
  set_history2set_log NUMBER,
  recon_date DATE,
  recon_amount NUMBER,
  bin_no VARCHAR2(50 BYTE),
  x_status VARCHAR2(50 BYTE),
  x_insert_date DATE DEFAULT SYSDATE,
  x_update_date DATE,
  CONSTRAINT x_setlmnts_hist2setlmnt_log_fk FOREIGN KEY (set_history2set_log) REFERENCES sa.x_settlement_log (objid)
);
COMMENT ON TABLE sa.x_settlements_history IS 'History for SETTLEMENT Transactions';
COMMENT ON COLUMN sa.x_settlements_history.objid IS 'Internal Record ID';
COMMENT ON COLUMN sa.x_settlements_history.submission_date IS 'Settlement date';
COMMENT ON COLUMN sa.x_settlements_history.pid IS 'Paymentech ID (for merchant)';
COMMENT ON COLUMN sa.x_settlements_history.entity_no IS 'Paymentech Division number';
COMMENT ON COLUMN sa.x_settlements_history.currency IS 'Currency type';
COMMENT ON COLUMN sa.x_settlements_history.merchant_order IS 'Reference number generated by Paymentech. Called as Bill Trans ref no by Cybersource and in TracFone systems';
COMMENT ON COLUMN sa.x_settlements_history.rdfi IS 'Routing number for Checking and Savings accounts';
COMMENT ON COLUMN sa.x_settlements_history.account_no IS 'Credit card number or Checking or Savings account number.. For now will be last 4 digits';
COMMENT ON COLUMN sa.x_settlements_history.expiration_date IS 'Credit card Expiration date';
COMMENT ON COLUMN sa.x_settlements_history.amount IS 'Amount Settled';
COMMENT ON COLUMN sa.x_settlements_history.mop IS 'Method of Payment';
COMMENT ON COLUMN sa.x_settlements_history.action_code IS 'Action Code (Refund or Deposit)';
COMMENT ON COLUMN sa.x_settlements_history.auth_date IS 'Authorization date (could be different from Settlement date)';
COMMENT ON COLUMN sa.x_settlements_history.auth_code IS 'Authorization code';
COMMENT ON COLUMN sa.x_settlements_history.auth_response_code IS 'Authorization Response code';
COMMENT ON COLUMN sa.x_settlements_history.cc_num_enc IS 'TracFOne Internal Encryption key';
COMMENT ON COLUMN sa.x_settlements_history.set_history2set_log IS 'Foreign key reference';
COMMENT ON COLUMN sa.x_settlements_history.recon_date IS 'Reconciliation Date (for future purpose)';
COMMENT ON COLUMN sa.x_settlements_history.recon_amount IS 'Reconciliation Date (for future purpose)';
COMMENT ON COLUMN sa.x_settlements_history.bin_no IS 'First 6 digits of Credit card number';
COMMENT ON COLUMN sa.x_settlements_history.x_status IS 'Reconciliation Status (for future purpose)';
COMMENT ON COLUMN sa.x_settlements_history.x_insert_date IS 'Record Insert Date';
COMMENT ON COLUMN sa.x_settlements_history.x_update_date IS 'Record Update Date ';