CREATE TABLE sa.x_sl_deliver_benefits_stg (
  "ROW_NUMBER" NUMBER,
  objid NUMBER,
  x_esn VARCHAR2(30 BYTE),
  x_type VARCHAR2(10 BYTE),
  x_delivery_cycle_number NUMBER,
  x_enrollment_status VARCHAR2(30 BYTE),
  x_is_grp_primary NUMBER,
  x_next_delivery_date DATE,
  pgm_enroll2pgm_parameter NUMBER,
  x_incl_service_days NUMBER,
  x_delivery_frq_code VARCHAR2(15 BYTE),
  x_promo_incl_min_at NUMBER,
  x_promo_incr_min_at NUMBER,
  x_wait_exp_date DATE,
  x_promo_incl_grpmin_at NUMBER,
  x_promo_incr_grpmin_at NUMBER,
  x_incr_minutes_dlv_cyl NUMBER,
  x_incr_minutes_dlv_days NUMBER,
  x_incr_grp_minutes_dlv_cyl NUMBER,
  x_incr_grp_minutes_dlv_days NUMBER,
  x_stack_dur_enroll VARCHAR2(10 BYTE),
  pgm_enroll2site_part NUMBER,
  pgm_enroll2x_promotion NUMBER,
  prog_param2bus_org NUMBER,
  pgm_enroll2web_user NUMBER,
  p_name VARCHAR2(40 BYTE),
  x_tot_grace_period_given NUMBER,
  x_amount NUMBER,
  x_sourcesystem VARCHAR2(30 BYTE),
  exp_date DATE,
  sw_flag VARCHAR2(30 BYTE),
  site_part_objid NUMBER,
  x_sweep_and_add_flag NUMBER,
  processed_flag VARCHAR2(1 BYTE),
  processed_date DATE,
  insert_timestamp DATE,
  future_days NUMBER
);
COMMENT ON TABLE sa.x_sl_deliver_benefits_stg IS 'Staging table for SL Benefit delivery';