CREATE TABLE sa.x_sl_invoice (
  objid NUMBER,
  x_batch_date DATE,
  x_lifeline_id NUMBER,
  x_bill_part_serial_no VARCHAR2(80 BYTE),
  x_current_part_serial_no VARCHAR2(80 BYTE),
  x_bill_x_min VARCHAR2(30 BYTE),
  x_current_x_min VARCHAR2(30 BYTE),
  x_phone_status VARCHAR2(20 BYTE),
  x_activation_zipcode VARCHAR2(20 BYTE),
  x_ll_status VARCHAR2(30 BYTE),
  x_act_date DATE,
  x_part_number VARCHAR2(30 BYTE),
  x_first_name VARCHAR2(100 BYTE),
  x_last_name VARCHAR2(100 BYTE),
  x_home_phone VARCHAR2(20 BYTE),
  x_ship_address_1 VARCHAR2(200 BYTE),
  x_ship_address_2 VARCHAR2(200 BYTE),
  x_ship_city VARCHAR2(30 BYTE),
  x_ship_state VARCHAR2(60 BYTE),
  x_ship_zipcode VARCHAR2(60 BYTE),
  x_ship_date DATE,
  x_tracking_no VARCHAR2(30 BYTE),
  x_enrolldate DATE,
  x_deenroll VARCHAR2(5 BYTE),
  x_deenroll_date DATE,
  x_bill VARCHAR2(5 BYTE),
  x_program_start_date DATE,
  x_carrier_id NUMBER(22),
  x_carrier_name VARCHAR2(30 BYTE),
  x_texas VARCHAR2(4 BYTE),
  x_bill_address1 VARCHAR2(200 BYTE),
  x_bill_address2 VARCHAR2(200 BYTE),
  x_bill_city VARCHAR2(30 BYTE),
  x_bill_state VARCHAR2(40 BYTE),
  x_bill_zip5 VARCHAR2(20 BYTE),
  x_approved_carrier VARCHAR2(5 BYTE),
  x_exclusion VARCHAR2(100 BYTE),
  x_bill_status VARCHAR2(5 BYTE),
  x_invoice_reason VARCHAR2(200 BYTE),
  x_ratecenter_st VARCHAR2(40 BYTE),
  x_eucl_rate NUMBER,
  x_bill_program_name VARCHAR2(40 BYTE),
  x_current_program_name VARCHAR2(40 BYTE),
  x_benefit_deliv_date DATE,
  x_ota_status VARCHAR2(30 BYTE),
  x_ota_units NUMBER(22)
);
COMMENT ON TABLE sa.x_sl_invoice IS 'TO STORE INVOICING DATA FOR SAFELINK CUSTOMERS';
COMMENT ON COLUMN sa.x_sl_invoice.objid IS 'INTERNAL RECORD ID';
COMMENT ON COLUMN sa.x_sl_invoice.x_batch_date IS 'TIMESTAMP IN WHICH THE INVOICE WAS GENERATED';
COMMENT ON COLUMN sa.x_sl_invoice.x_lifeline_id IS '3RD PARTY CUSTOMER ID';
COMMENT ON COLUMN sa.x_sl_invoice.x_bill_part_serial_no IS 'ESN AT BENEFITS DELIVERY TIME ';
COMMENT ON COLUMN sa.x_sl_invoice.x_current_part_serial_no IS 'ESN WHEN INVOICE CREATED ';
COMMENT ON COLUMN sa.x_sl_invoice.x_bill_x_min IS 'MIN AT BENEFITS DELIVERY TIME ';
COMMENT ON COLUMN sa.x_sl_invoice.x_current_x_min IS 'MIN WHEN INVOICE CREATED ';
COMMENT ON COLUMN sa.x_sl_invoice.x_phone_status IS 'PART INST STATUS (AT BENEFITS DELIVERY TIME) ';
COMMENT ON COLUMN sa.x_sl_invoice.x_activation_zipcode IS 'ZIP USED TO ACTIVATE PHONE ';
COMMENT ON COLUMN sa.x_sl_invoice.x_ll_status IS 'PROGRAM ENROLLED STATUS (WHEN INVOICE CREATED) ';
COMMENT ON COLUMN sa.x_sl_invoice.x_act_date IS 'ACTIVATION DATE STORED IN X_SL_CURRENTVALS AT INVOICING GENERATED TIME';
COMMENT ON COLUMN sa.x_sl_invoice.x_part_number IS 'BILLING PART NUMBER (AT BENEFITS DELIVERY TIME) ';
COMMENT ON COLUMN sa.x_sl_invoice.x_first_name IS 'DATA FROM VMBC WHICH ARE STORED IN X_SL_SUBS AT INVOICING GENERATED TIME ';
COMMENT ON COLUMN sa.x_sl_invoice.x_last_name IS 'DATA FROM VMBC WHICH ARE STORED IN X_SL_SUBS AT INVOICING GENERATED TIME ';
COMMENT ON COLUMN sa.x_sl_invoice.x_home_phone IS 'DATA FROM VMBC WHICH ARE STORED IN X_SL_SUBS AT INVOICING GENERATED TIME ';
COMMENT ON COLUMN sa.x_sl_invoice.x_ship_address_1 IS 'ADDRESS THAT PHONE WAS SHIPPED TO FROM THE TICKET ';
COMMENT ON COLUMN sa.x_sl_invoice.x_ship_address_2 IS 'ADDRESS THAT PHONE WAS SHIPPED TO FROM THE TICKET ';
COMMENT ON COLUMN sa.x_sl_invoice.x_ship_city IS 'CITY THAT PHONE WAS SHIPPED TO FROM THE TICKET ';
COMMENT ON COLUMN sa.x_sl_invoice.x_ship_state IS 'STATE THAT PHONE WAS SHIPPED TO FROM THE TICKET ';
COMMENT ON COLUMN sa.x_sl_invoice.x_ship_zipcode IS 'ZIPCODE THAT PHONE WAS SHIPPED TO FROM THE TICKET ';
COMMENT ON COLUMN sa.x_sl_invoice.x_ship_date IS 'SHIPMENT DATE WHEN THAT PHONE WAS SHIPPED TO FROM THE TICKET ';
COMMENT ON COLUMN sa.x_sl_invoice.x_tracking_no IS 'TRACKING NUMBER TO ENSURE THAT PHONE WAS RECEIVED ';
COMMENT ON COLUMN sa.x_sl_invoice.x_enrolldate IS 'LAST TIME ENROLLED, FROM X_SL_CURRENT_VALS AT INVOICING GENERATED TIME';
COMMENT ON COLUMN sa.x_sl_invoice.x_deenroll IS 'FLAG = Y IF DEENROLLED, FROM X_SL_CURRENT_VALS ';
COMMENT ON COLUMN sa.x_sl_invoice.x_deenroll_date IS 'LAST TIME ENROLLED, FROM X_SL_CURRENT_VALS ';
COMMENT ON COLUMN sa.x_sl_invoice.x_bill IS 'WHEN CURRENTLY ENROLLED IS Y OR DEENROLL FLAG (3 CHARACTERS)';
COMMENT ON COLUMN sa.x_sl_invoice.x_program_start_date IS 'PROGRAM START DATE STORED IN X_SL_CURRENTVALS AT INVOICING GENERATED TIME';
COMMENT ON COLUMN sa.x_sl_invoice.x_carrier_id IS 'CARRIER ID (AT BENEFITS DELIVERY TIME) ';
COMMENT ON COLUMN sa.x_sl_invoice.x_carrier_name IS 'CARRIER NAME (AT BENEFITS DELIVERY TIME) ';
COMMENT ON COLUMN sa.x_sl_invoice.x_texas IS 'LIFELINE TEXAS';
COMMENT ON COLUMN sa.x_sl_invoice.x_bill_address1 IS 'DATA FROM VMBC ENROLLMENT TABLES, WHICH ARE STORED IN X_SL_SUBS AT INVOICING GENERATED TIME ';
COMMENT ON COLUMN sa.x_sl_invoice.x_bill_address2 IS 'DATA FROM VMBC ENROLLMENT TABLES, WHICH ARE STORED IN X_SL_SUBS AT INVOICING GENERATED TIME ';
COMMENT ON COLUMN sa.x_sl_invoice.x_bill_city IS 'DATA FROM VMBC ENROLLMENT TABLES, WHICH ARE STORED IN X_SL_SUBS AT INVOICING GENERATED TIME ';
COMMENT ON COLUMN sa.x_sl_invoice.x_bill_state IS 'DATA FROM VMBC ENROLLMENT TABLES, WHICH ARE STORED IN X_SL_SUBS AT INVOICING GENERATED TIME ';
COMMENT ON COLUMN sa.x_sl_invoice.x_bill_zip5 IS 'DATA FROM VMBC ENROLLMENT TABLES, WHICH ARE STORED IN X_SL_SUBS AT INVOICING GENERATED TIME ';
COMMENT ON COLUMN sa.x_sl_invoice.x_approved_carrier IS 'FLAG (Y/N)';
COMMENT ON COLUMN sa.x_sl_invoice.x_exclusion IS 'NUMBER WHICH INDICATE THE TYPE OF THE EXCLUSION (2=DUPLICATE SERIAL NUMBER,..,4=DUPLICATE CUSTOMER ADDRESS,...,9=T-XMIN NUMBER)';
COMMENT ON COLUMN sa.x_sl_invoice.x_bill_status IS 'FLAG (Y/N) LIFELINE IS APPROVED FOR BILLING';
COMMENT ON COLUMN sa.x_sl_invoice.x_invoice_reason IS 'INVOICE REASON';
COMMENT ON COLUMN sa.x_sl_invoice.x_ratecenter_st IS 'COMBINATION OF RC AND STATE FROM CARRIERZONES ';
COMMENT ON COLUMN sa.x_sl_invoice.x_eucl_rate IS 'TIER I PRICE FROM KFR ';
COMMENT ON COLUMN sa.x_sl_invoice.x_bill_program_name IS 'WHICH PROGRAM THE CUSTOMER WAS ENROLLED IN WHEN THE BENEFITS WERE DELIVERED ';
COMMENT ON COLUMN sa.x_sl_invoice.x_current_program_name IS 'CURRENT PROGRAM STORED IN X_SL_CURRENTVALS AT INVOICING GENERATED TIME';
COMMENT ON COLUMN sa.x_sl_invoice.x_benefit_deliv_date IS 'LATEST DATE WHICH BENEFITS WERE DELIVERED ';
COMMENT ON COLUMN sa.x_sl_invoice.x_ota_status IS 'OTA PSMS TEXT STATUS RELATED UNITS DELIVERED';
COMMENT ON COLUMN sa.x_sl_invoice.x_ota_units IS 'TOTAL UNITS DELIVERED OTA FROM AUDIT DEPT, INCLUDES ALL PROMO UNITS ';