CREATE TABLE sa.x_subscriber_spr_hist_jt (
  objid NUMBER(22) NOT NULL,
  subscriber_spr_objid NUMBER(22) NOT NULL,
  change_date DATE NOT NULL,
  pcrf_min VARCHAR2(30 BYTE),
  pcrf_esn VARCHAR2(30 BYTE),
  pcrf_subscriber_id VARCHAR2(50 BYTE),
  pcrf_group_id VARCHAR2(50 BYTE),
  pcrf_parent_name VARCHAR2(40 BYTE),
  pcrf_cos VARCHAR2(30 BYTE),
  pcrf_base_ttl DATE,
  pcrf_last_redemption_date DATE,
  brand VARCHAR2(40 BYTE),
  phone_manufacturer VARCHAR2(30 BYTE),
  phone_model VARCHAR2(50 BYTE),
  content_delivery_format VARCHAR2(50 BYTE),
  denomination VARCHAR2(50 BYTE),
  conversion_factor VARCHAR2(50 BYTE),
  dealer_id VARCHAR2(80 BYTE),
  rate_plan VARCHAR2(60 BYTE),
  propagate_flag NUMBER(4),
  pcrf_transaction_id NUMBER(22),
  service_plan_type VARCHAR2(50 BYTE),
  service_plan_id NUMBER(22),
  queued_days NUMBER(3),
  language VARCHAR2(30 BYTE),
  part_inst_status VARCHAR2(30 BYTE),
  bus_org_objid NUMBER(22),
  contact_objid NUMBER(22),
  web_user_objid NUMBER(22),
  usage_host_id VARCHAR2(3 BYTE),
  wf_mac_id VARCHAR2(50 BYTE),
  expired_usage_date DATE,
  subscriber_status_code VARCHAR2(3 BYTE),
  curr_throttle_policy_id NUMBER(22),
  curr_throttle_eff_date DATE,
  insert_timestamp DATE NOT NULL,
  update_timestamp DATE NOT NULL,
  future_ttl DATE
);