CREATE TABLE sa.x_subscriber_enrollments (
  objid NUMBER NOT NULL,
  pgm_enrolled_objid NUMBER,
  x_esn VARCHAR2(30 BYTE) NOT NULL,
  enrollment_type VARCHAR2(40 BYTE) NOT NULL,
  enrolled_status VARCHAR2(30 BYTE) NOT NULL,
  enrolled_program VARCHAR2(30 BYTE) NOT NULL,
  enroll_rqst_channel VARCHAR2(30 BYTE),
  enr_inception_promo VARCHAR2(30 BYTE),
  enr_recurring_promo VARCHAR2(30 BYTE),
  pay_src_objid NUMBER NOT NULL,
  wu_objid NUMBER NOT NULL,
  cust_name VARCHAR2(100 BYTE),
  cust_address VARCHAR2(150 BYTE),
  cust_email VARCHAR2(100 BYTE),
  cust_ccexpd VARCHAR2(10 BYTE),
  enroll_start_date DATE,
  next_charge_date DATE,
  bill_acct_num VARCHAR2(30 BYTE),
  bill_grp_num VARCHAR2(30 BYTE),
  updated_by VARCHAR2(30 BYTE),
  insert_timestamp DATE DEFAULT SYSDATE,
  CONSTRAINT pk_tbl_x_sub_enrollments PRIMARY KEY (objid)
);