CREATE TABLE sa.x_subscriber_spr_jt (
  objid NUMBER(22) NOT NULL,
  pcrf_min VARCHAR2(30 BYTE),
  pcrf_esn VARCHAR2(30 BYTE),
  pcrf_subscriber_id VARCHAR2(50 BYTE),
  pcrf_group_id VARCHAR2(50 BYTE),
  pcrf_parent_name VARCHAR2(40 BYTE),
  pcrf_cos VARCHAR2(30 BYTE),
  pcrf_base_ttl DATE,
  pcrf_last_redemption_date DATE,
  brand VARCHAR2(40 BYTE),
  phone_manufacturer VARCHAR2(30 BYTE),
  phone_model VARCHAR2(50 BYTE),
  content_delivery_format VARCHAR2(50 BYTE),
  denomination VARCHAR2(50 BYTE),
  conversion_factor VARCHAR2(50 BYTE),
  dealer_id VARCHAR2(80 BYTE),
  rate_plan VARCHAR2(60 BYTE),
  propagate_flag NUMBER(4),
  pcrf_transaction_id NUMBER(22),
  service_plan_type VARCHAR2(50 BYTE),
  service_plan_id NUMBER(22),
  queued_days NUMBER(3),
  language VARCHAR2(30 BYTE),
  part_inst_status VARCHAR2(30 BYTE),
  bus_org_objid NUMBER(22),
  contact_objid NUMBER(22),
  web_user_objid NUMBER(22),
  wf_mac_id VARCHAR2(50 BYTE),
  expired_usage_date DATE,
  subscriber_status_code VARCHAR2(3 BYTE),
  curr_throttle_policy_id NUMBER(22),
  curr_throttle_eff_date DATE,
  zipcode VARCHAR2(10 BYTE),
  insert_timestamp DATE NOT NULL,
  update_timestamp DATE NOT NULL,
  future_ttl DATE,
  pcrf_mdn VARCHAR2(30 BYTE),
  meter_voice NUMBER(22),
  meter_sms NUMBER(22),
  meter_data NUMBER(22),
  meter_ild NUMBER(22),
  esn_part_number VARCHAR2(30 BYTE),
  esn_nickname VARCHAR2(50 BYTE),
  sim_part_number VARCHAR2(30 BYTE),
  iccid VARCHAR2(30 BYTE),
  carrier_objid NUMBER(22),
  service_plan_part_number VARCHAR2(30 BYTE),
  byod_indicator NUMBER(1),
  enrolled_autorefill_flag VARCHAR2(1 BYTE),
  enrolled_next_charge_date DATE,
  enrolled_date DATE,
  manage_reserve_id NUMBER(1),
  meter_source_voice NUMBER(22),
  meter_source_sms NUMBER(22),
  meter_source_data NUMBER(22),
  meter_source_ild NUMBER(22)
);