CREATE TABLE sa.x_trans_profile_hist (
  objid NUMBER,
  x_change_type VARCHAR2(20 BYTE),
  x_change_date DATE NOT NULL,
  x_change_user VARCHAR2(40 BYTE),
  x_transmit_method_old VARCHAR2(20 BYTE),
  x_transmit_method_new VARCHAR2(20 BYTE),
  x_exception_old NUMBER,
  x_exception_new NUMBER,
  x_fax_number_old VARCHAR2(30 BYTE),
  x_fax_number_new VARCHAR2(30 BYTE),
  x_online_number_old VARCHAR2(45 BYTE),
  x_online_number_new VARCHAR2(45 BYTE),
  x_network_login_old VARCHAR2(30 BYTE),
  x_network_login_new VARCHAR2(30 BYTE),
  x_network_password_old VARCHAR2(30 BYTE),
  x_network_password_new VARCHAR2(30 BYTE),
  x_system_login_old VARCHAR2(30 BYTE),
  x_system_login_new VARCHAR2(30 BYTE),
  x_system_password_old VARCHAR2(30 BYTE),
  x_system_password_new VARCHAR2(30 BYTE),
  x_template_old VARCHAR2(80 BYTE),
  x_template_new VARCHAR2(80 BYTE),
  x_email_old VARCHAR2(45 BYTE),
  x_email_new VARCHAR2(45 BYTE),
  x_profile_name_old VARCHAR2(30 BYTE),
  x_profile_name_new VARCHAR2(30 BYTE),
  x_default_queue_old VARCHAR2(30 BYTE),
  x_default_queue_new VARCHAR2(30 BYTE),
  x_carrier_phone_old VARCHAR2(30 BYTE),
  x_carrier_phone_new VARCHAR2(30 BYTE),
  x_exception_queue_old VARCHAR2(30 BYTE),
  x_exception_queue_new VARCHAR2(30 BYTE),
  x_batch_quantity_old VARCHAR2(5 BYTE),
  x_batch_quantity_new VARCHAR2(5 BYTE),
  x_batch_delay_max_old VARCHAR2(10 BYTE),
  x_batch_delay_max_new VARCHAR2(10 BYTE),
  x_transmit_template_old VARCHAR2(30 BYTE),
  x_transmit_template_new VARCHAR2(30 BYTE),
  x_online_num2_old VARCHAR2(30 BYTE),
  x_online_num2_new VARCHAR2(30 BYTE),
  x_fax_num2_old VARCHAR2(30 BYTE),
  x_fax_num2_new VARCHAR2(30 BYTE),
  x_description_old VARCHAR2(200 BYTE),
  x_description_new VARCHAR2(200 BYTE),
  x_trans_profile2wk_work_hr_old NUMBER,
  x_trans_profile2wk_work_hr_new NUMBER,
  x_trans_exception2wk_work_hr_o NUMBER,
  x_trans_exception2wk_work_hr_n NUMBER,
  x_ici_system_old VARCHAR2(30 BYTE),
  x_ici_system_new VARCHAR2(30 BYTE),
  x_analog_deact_old VARCHAR2(30 BYTE),
  x_analog_deact_new VARCHAR2(30 BYTE),
  x_analog_rework_old VARCHAR2(30 BYTE),
  x_analog_rework_new VARCHAR2(30 BYTE),
  x_d_batch_delay_max_old VARCHAR2(10 BYTE),
  x_d_batch_delay_max_new VARCHAR2(10 BYTE),
  x_d_batch_quantity_old VARCHAR2(5 BYTE),
  x_d_batch_quantity_new VARCHAR2(5 BYTE),
  x_d_carrier_phone_old VARCHAR2(30 BYTE),
  x_d_carrier_phone_new VARCHAR2(30 BYTE),
  x_d_email_old VARCHAR2(45 BYTE),
  x_d_email_new VARCHAR2(45 BYTE),
  x_d_fax_num2_old VARCHAR2(30 BYTE),
  x_d_fax_num2_new VARCHAR2(30 BYTE),
  x_d_fax_number_old VARCHAR2(30 BYTE),
  x_d_fax_number_new VARCHAR2(30 BYTE),
  x_d_ici_system_old VARCHAR2(30 BYTE),
  x_d_ici_system_new VARCHAR2(30 BYTE),
  x_d_network_login_old VARCHAR2(30 BYTE),
  x_d_network_login_new VARCHAR2(30 BYTE),
  x_d_network_password_old VARCHAR2(30 BYTE),
  x_d_network_password_new VARCHAR2(30 BYTE),
  x_d_online_num2_old VARCHAR2(30 BYTE),
  x_d_online_num2_new VARCHAR2(30 BYTE),
  x_d_online_number_old VARCHAR2(45 BYTE),
  x_d_online_number_new VARCHAR2(45 BYTE),
  x_d_system_login_old VARCHAR2(30 BYTE),
  x_d_system_login_new VARCHAR2(30 BYTE),
  x_d_system_password_old VARCHAR2(30 BYTE),
  x_d_system_password_new VARCHAR2(30 BYTE),
  x_d_template_old VARCHAR2(80 BYTE),
  x_d_template_new VARCHAR2(80 BYTE),
  x_d_trans_template_old VARCHAR2(30 BYTE),
  x_d_trans_template_new VARCHAR2(30 BYTE),
  x_d_transmit_method_old VARCHAR2(20 BYTE),
  x_d_transmit_method_new VARCHAR2(20 BYTE),
  x_digital_act_old VARCHAR2(30 BYTE),
  x_digital_act_new VARCHAR2(30 BYTE),
  x_digital_deact_old VARCHAR2(30 BYTE),
  x_digital_deact_new VARCHAR2(30 BYTE),
  x_digital_rework_old VARCHAR2(30 BYTE),
  x_digital_rework_new VARCHAR2(30 BYTE),
  x_upgrade_old VARCHAR2(30 BYTE),
  x_upgrade_new VARCHAR2(30 BYTE),
  d_trans_profile2wk_work_hr_old NUMBER,
  d_trans_profile2wk_work_hr_new NUMBER,
  x_gsm_act_old VARCHAR2(30 BYTE),
  x_gsm_act_new VARCHAR2(30 BYTE),
  x_gsm_batch_delay_max_old VARCHAR2(10 BYTE),
  x_gsm_batch_delay_max_new VARCHAR2(10 BYTE),
  x_gsm_batch_quantity_old VARCHAR2(5 BYTE),
  x_gsm_batch_quantity_new VARCHAR2(5 BYTE),
  x_gsm_carrier_phone_old VARCHAR2(30 BYTE),
  x_gsm_carrier_phone_new VARCHAR2(30 BYTE),
  x_gsm_deact_old VARCHAR2(30 BYTE),
  x_gsm_deact_new VARCHAR2(30 BYTE),
  x_gsm_email_old VARCHAR2(45 BYTE),
  x_gsm_email_new VARCHAR2(45 BYTE),
  x_gsm_fax_num2_old VARCHAR2(30 BYTE),
  x_gsm_fax_num2_new VARCHAR2(30 BYTE),
  x_gsm_fax_number_old VARCHAR2(30 BYTE),
  x_gsm_fax_number_new VARCHAR2(30 BYTE),
  x_gsm_ici_system_old VARCHAR2(30 BYTE),
  x_gsm_ici_system_new VARCHAR2(30 BYTE),
  x_gsm_network_login_old VARCHAR2(30 BYTE),
  x_gsm_network_login_new VARCHAR2(30 BYTE),
  x_gsm_network_password_old VARCHAR2(30 BYTE),
  x_gsm_network_password_new VARCHAR2(30 BYTE),
  x_gsm_online_num2_old VARCHAR2(30 BYTE),
  x_gsm_online_num2_new VARCHAR2(30 BYTE),
  x_gsm_online_number_old VARCHAR2(45 BYTE),
  x_gsm_online_number_new VARCHAR2(45 BYTE),
  x_gsm_rework_old VARCHAR2(30 BYTE),
  x_gsm_rework_new VARCHAR2(30 BYTE),
  x_gsm_trans_template_old VARCHAR2(30 BYTE),
  x_gsm_trans_template_new VARCHAR2(30 BYTE),
  x_gsm_transmit_method_old VARCHAR2(20 BYTE),
  x_gsm_transmit_method_new VARCHAR2(20 BYTE),
  x_debug_analog_old NUMBER,
  x_debug_analog_new NUMBER,
  x_debug_digital_old NUMBER,
  x_debug_digital_new NUMBER,
  x_debug_gsm_old NUMBER,
  x_debug_gsm_new NUMBER,
  x_sui_analog_old NUMBER,
  x_sui_analog_new NUMBER,
  x_sui_digital_old NUMBER,
  x_sui_digital_new NUMBER,
  x_sui_gsm_old NUMBER,
  x_sui_gsm_new NUMBER,
  x_timeout_analog_old NUMBER,
  x_timeout_analog_new NUMBER,
  x_timeout_digital_old NUMBER,
  x_timeout_digital_new NUMBER,
  x_timeout_gsm_old NUMBER,
  x_timeout_gsm_new NUMBER,
  x_int_port_in_rework_old VARCHAR2(30 BYTE),
  x_int_port_in_rework_new VARCHAR2(30 BYTE)
);
ALTER TABLE sa.x_trans_profile_hist ADD SUPPLEMENTAL LOG GROUP dmtsora1500551_0 (objid, x_batch_quantity_old, x_carrier_phone_new, x_carrier_phone_old, x_change_date, x_change_type, x_change_user, x_default_queue_new, x_default_queue_old, x_email_new, x_email_old, x_exception_new, x_exception_old, x_exception_queue_new, x_exception_queue_old, x_fax_number_new, x_fax_number_old, x_network_login_new, x_network_login_old, x_network_password_new, x_network_password_old, x_online_number_new, x_online_number_old, x_profile_name_new, x_profile_name_old, x_system_login_new, x_system_login_old, x_system_password_new, x_system_password_old, x_template_new, x_template_old, x_transmit_method_new, x_transmit_method_old) ALWAYS;
ALTER TABLE sa.x_trans_profile_hist ADD SUPPLEMENTAL LOG GROUP dmtsora1500551_1 (x_analog_deact_new, x_analog_deact_old, x_analog_rework_new, x_analog_rework_old, x_batch_delay_max_new, x_batch_delay_max_old, x_batch_quantity_new, x_description_new, x_description_old, x_d_batch_delay_max_new, x_d_batch_delay_max_old, x_d_batch_quantity_new, x_d_batch_quantity_old, x_d_carrier_phone_new, x_d_carrier_phone_old, x_d_email_new, x_d_email_old, x_d_fax_num2_new, x_d_fax_num2_old, x_d_fax_number_new, x_d_fax_number_old, x_fax_num2_new, x_fax_num2_old, x_ici_system_new, x_ici_system_old, x_online_num2_new, x_online_num2_old, x_transmit_template_new, x_transmit_template_old, x_trans_exception2wk_work_hr_n, x_trans_exception2wk_work_hr_o, x_trans_profile2wk_work_hr_new, x_trans_profile2wk_work_hr_old) ALWAYS;
ALTER TABLE sa.x_trans_profile_hist ADD SUPPLEMENTAL LOG GROUP dmtsora1500551_2 (d_trans_profile2wk_work_hr_new, d_trans_profile2wk_work_hr_old, x_digital_act_new, x_digital_act_old, x_digital_deact_new, x_digital_deact_old, x_digital_rework_new, x_digital_rework_old, x_d_ici_system_new, x_d_ici_system_old, x_d_network_login_new, x_d_network_login_old, x_d_network_password_new, x_d_network_password_old, x_d_online_num2_new, x_d_online_num2_old, x_d_online_number_new, x_d_online_number_old, x_d_system_login_new, x_d_system_login_old, x_d_system_password_new, x_d_system_password_old, x_d_template_new, x_d_template_old, x_d_transmit_method_new, x_d_transmit_method_old, x_d_trans_template_new, x_d_trans_template_old, x_gsm_act_new, x_gsm_act_old, x_gsm_batch_delay_max_old, x_upgrade_new, x_upgrade_old) ALWAYS;
ALTER TABLE sa.x_trans_profile_hist ADD SUPPLEMENTAL LOG GROUP dmtsora1500551_3 (x_debug_analog_new, x_debug_analog_old, x_debug_digital_new, x_debug_digital_old, x_gsm_batch_delay_max_new, x_gsm_batch_quantity_new, x_gsm_batch_quantity_old, x_gsm_carrier_phone_new, x_gsm_carrier_phone_old, x_gsm_deact_new, x_gsm_deact_old, x_gsm_email_new, x_gsm_email_old, x_gsm_fax_num2_new, x_gsm_fax_num2_old, x_gsm_fax_number_new, x_gsm_fax_number_old, x_gsm_ici_system_new, x_gsm_ici_system_old, x_gsm_network_login_new, x_gsm_network_login_old, x_gsm_network_password_new, x_gsm_network_password_old, x_gsm_online_num2_new, x_gsm_online_num2_old, x_gsm_online_number_new, x_gsm_online_number_old, x_gsm_rework_new, x_gsm_rework_old, x_gsm_transmit_method_new, x_gsm_transmit_method_old, x_gsm_trans_template_new, x_gsm_trans_template_old) ALWAYS;
ALTER TABLE sa.x_trans_profile_hist ADD SUPPLEMENTAL LOG GROUP dmtsora1500551_4 (x_debug_gsm_new, x_debug_gsm_old, x_int_port_in_rework_new, x_int_port_in_rework_old, x_sui_analog_new, x_sui_analog_old, x_sui_digital_new, x_sui_digital_old, x_sui_gsm_new, x_sui_gsm_old, x_timeout_analog_new, x_timeout_analog_old, x_timeout_digital_new, x_timeout_digital_old, x_timeout_gsm_new, x_timeout_gsm_old) ALWAYS;