CREATE TABLE sa.xerox_response_log (
  ocn VARCHAR2(10 BYTE),
  subscriber_account_number VARCHAR2(50 BYTE),
  customer_code VARCHAR2(50 BYTE),
  ults_telephone_number VARCHAR2(10 BYTE),
  name_prefix VARCHAR2(50 BYTE),
  name_first VARCHAR2(50 BYTE),
  name_initial VARCHAR2(50 BYTE),
  name_last VARCHAR2(50 BYTE),
  name_suffix VARCHAR2(50 BYTE),
  "NAME" VARCHAR2(250 BYTE),
  service_address_1 VARCHAR2(100 BYTE),
  service_address_2 VARCHAR2(100 BYTE),
  service_address_city VARCHAR2(50 BYTE),
  service_address_state VARCHAR2(2 BYTE),
  service_address_zip_5 VARCHAR2(5 BYTE),
  service_address_zip_4 VARCHAR2(4 BYTE),
  billing_name VARCHAR2(150 BYTE),
  billing_name_first VARCHAR2(50 BYTE),
  billing_name_first_initial VARCHAR2(50 BYTE),
  billing_name_first_last VARCHAR2(50 BYTE),
  billing_address_1 VARCHAR2(100 BYTE),
  billing_address_2 VARCHAR2(100 BYTE),
  billing_address_3 VARCHAR2(100 BYTE),
  billing_address_4 VARCHAR2(100 BYTE),
  billing_address_5 VARCHAR2(100 BYTE),
  billing_city VARCHAR2(50 BYTE),
  billing_state_code VARCHAR2(2 BYTE),
  billing_zip_5 VARCHAR2(5 BYTE),
  billing_zip_4 VARCHAR2(4 BYTE),
  contact_phone_number VARCHAR2(50 BYTE),
  language_code VARCHAR2(2 BYTE),
  braille_large_font VARCHAR2(1 BYTE),
  ults_service_start_date DATE,
  ults_recertification_date VARCHAR2(20 BYTE),
  prior_ults_telephone_number VARCHAR2(10 BYTE),
  disconnect_date DATE,
  tty_qualified_second_line VARCHAR2(1 BYTE),
  activity_type VARCHAR2(1 BYTE),
  processing_date DATE,
  ults_decicision_date DATE,
  ults_record_type VARCHAR2(1 BYTE),
  ults_decision VARCHAR2(1 BYTE),
  ults_effective_date DATE,
  ults_denial_code VARCHAR2(200 BYTE),
  ults_action_taken VARCHAR2(255 BYTE),
  uts_action_take_date_time DATE,
  tribal_lands VARCHAR2(1 BYTE),
  service_type VARCHAR2(1 BYTE),
  rate_group VARCHAR2(30 BYTE),
  load_date DATE,
  x_source VARCHAR2(255 BYTE),
  ults_update_status VARCHAR2(255 BYTE),
  ulte_activity_code VARCHAR2(200 BYTE),
  current_ocn VARCHAR2(10 BYTE),
  modified_effective_date DATE
);