CREATE TABLE sa.xxtf_e911_tax_recon_tbl (
  cash_receipt_id NUMBER NOT NULL,
  ofs_check_no VARCHAR2(100 BYTE),
  receipt_date DATE,
  customer_check_no VARCHAR2(100 BYTE),
  check_bank VARCHAR2(100 BYTE),
  check_account VARCHAR2(100 BYTE),
  check_amount NUMBER,
  fisrt_name VARCHAR2(100 BYTE),
  last_name VARCHAR2(100 BYTE),
  address1 VARCHAR2(100 BYTE),
  address2 VARCHAR2(100 BYTE),
  city VARCHAR2(100 BYTE),
  "STATE" VARCHAR2(100 BYTE),
  zip VARCHAR2(100 BYTE),
  phone_number VARCHAR2(100 BYTE),
  llid VARCHAR2(100 BYTE),
  esn VARCHAR2(100 BYTE),
  payment_type VARCHAR2(100 BYTE),
  returned VARCHAR2(1 BYTE),
  tax_state VARCHAR2(100 BYTE),
  last_updated_by NUMBER(15),
  last_update_date DATE,
  last_update_login NUMBER(15),
  created_by NUMBER(15),
  creation_date DATE,
  return_date DATE,
  line_num NUMBER,
  file_name VARCHAR2(250 BYTE)
);
COMMENT ON TABLE sa.xxtf_e911_tax_recon_tbl IS 'Table to store the Check payments for Safelink e911 which are received through OFS';