CREATE TABLE sa.zip2tech_simprofiles (
  zip VARCHAR2(5 BYTE),
  carrier VARCHAR2(150 BYTE),
  sim_type NUMBER,
  tech2 VARCHAR2(20 BYTE),
  pref NUMBER
);
COMMENT ON TABLE sa.zip2tech_simprofiles IS 'MAPS THE SIM PROFILE FOR THE BYOP PROGRAM, MAINTAINED BY CARRIER OPS FOR THE INTERFACE TO BRIGHT POINT';
COMMENT ON COLUMN sa.zip2tech_simprofiles.zip IS 'ZIPCODE, USED AS A QUERY PARAMETER';
COMMENT ON COLUMN sa.zip2tech_simprofiles.carrier IS 'CARRIER, USED AS A QUERY PARAMETER';
COMMENT ON COLUMN sa.zip2tech_simprofiles.sim_type IS 'NUMBER 1=REGULAR, 2=MICRO, POSSIBLE EXPANSION: 4,8 ETC WITH 3 MEANING BOTH1AND2, ETC, USED AS A QUERY PARAMETER';
COMMENT ON COLUMN sa.zip2tech_simprofiles.tech2 IS 'TECHNOLOGY RETURNED TO BRIGHTPOINT';
COMMENT ON COLUMN sa.zip2tech_simprofiles.pref IS 'WHEN MORE THAN ONE TECHNOLOGY IS AVAILABLE WILL DETERMINE WHICH ONE TO USE 0=NOT, 1=PREFERRED';