CREATE OR REPLACE TRIGGER sa.CT_DUE_DATE_TRIGGER BEFORE insert or UPDATE ON sa.TABLE_X_CALL_TRANS REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW BEGIN
  IF :new.X_NEW_DUE_DATE < to_date('01/01/0003','MM/DD/YYYY') then
     :new.X_NEW_DUE_DATE  := to_date('01/01/1753','MM/DD/YYYY');
END IF;
END;
/