CREATE OR REPLACE TRIGGER sa.PI_WARR_DATE_TRIGGER BEFORE insert or UPDATE ON sa.TABLE_PART_INST REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW BEGIN
  IF :new.WARR_END_DATE < to_date('01/01/0003','MM/DD/YYYY') then
     :new.WARR_END_DATE  := to_date('01/01/1753','MM/DD/YYYY');
END IF;
END;
/