CREATE OR REPLACE TRIGGER sa.SITE_WARR_DATE_TRIGGER BEFORE insert or UPDATE ON sa.TABLE_SITE_PART REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW BEGIN
  IF :new.WARRANTY_DATE < to_date('01/01/0003','MM/DD/YYYY') then
     :new.WARRANTY_DATE  := to_date('01/01/1753','MM/DD/YYYY');
END IF;
END;
/