CREATE OR REPLACE TRIGGER sa.T_MTM_CONTACT46_X_CREDIT_CARD3 before INSERT ON sa.MTM_CONTACT46_X_CREDIT_CARD3 FOR EACH ROW BEGIN
  if :NEW.MTM_CREDIT_CARD2CONTACT is null then
    :NEW.MTM_CREDIT_CARD2CONTACT := -1;
  end if;
  if :NEW.MTM_CONTACT2X_CREDIT_CARD is null then
    :NEW.MTM_CONTACT2X_CREDIT_CARD := -1;
  end if;
END T_MTM_CONTACT46_X_CREDIT_CARD3;
/