CREATE OR REPLACE TRIGGER sa.TRG_table_site_JT
before insert or update or delete on sa.table_site
for each row
declare
act varchar2(10);
sysdt date := sysdate;
begin
  if deleting then
    act := 'D';
  elsif updating then
     act := 'U';
  else
     act := 'I';
  end if;
if  :OLD.TYPE    ='3' or  :NEW.TYPE     =3 then
  for c1 in (     select /*+ ordered rule */ s.*
            from v$session s
            where  s.audsid = userenv('sessionid') )
  loop
       insert into sa.table_site_hist (
                                SID          ,
                                ACTION       ,
                                USERNAME     ,
                                OSUSER       ,
                                PROCESS      ,
                                MACHINE      ,
                                TERMINAL     ,
                                PROGRAM      ,
                                LOGON_TIME   ,
                                DT           ,
 OLD_OBJID                              ,            
 OLD_SITE_ID                ,
 OLD_NAME                   ,
 OLD_S_NAME                 ,
 OLD_EXTERNAL_ID            ,
 OLD_TYPE                   ,
 OLD_LOGISTICS_TYPE         ,
 OLD_IS_SUPPORT             ,
 OLD_REGION                 ,
 OLD_S_REGION               ,
 OLD_DISTRICT               ,
 OLD_S_DISTRICT             ,
 OLD_DEPOT                  ,
 OLD_CONTR_LOGIN            ,
 OLD_CONTR_PASSWD           ,
 OLD_IS_DEFAULT             ,
 OLD_NOTES                  ,
 OLD_SPEC_CONSID            ,
 OLD_MDBK                   ,
 OLD_STATE_CODE             ,
 OLD_STATE_VALUE            ,
 OLD_INDUSTRY_TYPE          ,
 OLD_APPL_TYPE              ,
 OLD_CUT_DATE               ,
 OLD_SITE_TYPE              ,
 OLD_STATUS                 ,
 OLD_ARCH_IND               ,
 OLD_ALERT_IND              ,
 OLD_PHONE                  ,
 OLD_FAX                    ,
 OLD_DEV                    ,
 OLD_CHILD_SITE2SITE        ,
 OLD_SUPPORT_OFFICE2SITE    ,
 OLD_CUST_PRIMADDR2ADDRESS  ,
 OLD_CUST_BILLADDR2ADDRESS  ,
 OLD_CUST_SHIPADDR2ADDRESS  ,
 OLD_SITE_SUPPORT2EMPLOYEE  ,
 OLD_SITE_ALTSUPP2EMPLOYEE  ,
 OLD_REPORT_SITE2BUG        ,
 OLD_PRIMARY2BUS_ORG        ,
 OLD_SITE2EXCH_PROTOCOL     ,
 OLD_DEALER2X_PROMOTION     ,
 OLD_X_SMP_OPTIONAL         ,
 OLD_UPDATE_STAMP           ,
 OLD_X_FIN_CUST_ID          ,
 OLD_SHIP_VIA               ,
 OLD_X_COMMERCE_ID          ,
 OLD_X_SHIP_LOC_ID          ,
 OLD_X_REFERRAL_ID          ,
 NEW_OBJID                              ,            
 NEW_SITE_ID                ,
 NEW_NAME                   ,
 NEW_S_NAME                 ,
 NEW_EXTERNAL_ID            ,
 NEW_TYPE                   ,
 NEW_LOGISTICS_TYPE         ,
 NEW_IS_SUPPORT             ,
 NEW_REGION                 ,
 NEW_S_REGION               ,
 NEW_DISTRICT               ,
 NEW_S_DISTRICT             ,
 NEW_DEPOT                  ,
 NEW_CONTR_LOGIN            ,
 NEW_CONTR_PASSWD           ,
 NEW_IS_DEFAULT             ,
 NEW_NOTES                  ,
 NEW_SPEC_CONSID            ,
 NEW_MDBK                   ,
 NEW_STATE_CODE             ,
 NEW_STATE_VALUE            ,
 NEW_INDUSTRY_TYPE          ,
 NEW_APPL_TYPE              ,
 NEW_CUT_DATE               ,
 NEW_SITE_TYPE              ,
 NEW_STATUS                 ,
 NEW_ARCH_IND               ,
 NEW_ALERT_IND              ,
 NEW_PHONE                  ,
 NEW_FAX                    ,
 NEW_DEV                    ,
 NEW_CHILD_SITE2SITE        ,
 NEW_SUPPORT_OFFICE2SITE    ,
 NEW_CUST_PRIMADDR2ADDRESS  ,
 NEW_CUST_BILLADDR2ADDRESS  ,
 NEW_CUST_SHIPADDR2ADDRESS  ,
 NEW_SITE_SUPPORT2EMPLOYEE  ,
 NEW_SITE_ALTSUPP2EMPLOYEE  ,
 NEW_REPORT_SITE2BUG        ,
 NEW_PRIMARY2BUS_ORG        ,
 NEW_SITE2EXCH_PROTOCOL     ,
 NEW_DEALER2X_PROMOTION     ,
 NEW_X_SMP_OPTIONAL         ,
 NEW_UPDATE_STAMP           ,
 NEW_X_FIN_CUST_ID          ,
 NEW_SHIP_VIA               ,
 NEW_X_COMMERCE_ID          ,
 NEW_X_SHIP_LOC_ID          ,
 NEW_X_REFERRAL_ID          
)
                      values ( c1.sid,
                               act,
                               c1.username,
                               c1.osuser,
                               c1.process,
                               c1.machine,
                               c1.terminal,
                               c1.program,
                               c1.logon_time,
                               sysdt,
 :OLD.OBJID                              ,            
 :OLD.SITE_ID                ,
 :OLD.NAME                   ,
 :OLD.S_NAME                 ,
 :OLD.EXTERNAL_ID            ,
 :OLD.TYPE                   ,
 :OLD.LOGISTICS_TYPE         ,
 :OLD.IS_SUPPORT             ,
 :OLD.REGION                 ,
 :OLD.S_REGION               ,
 :OLD.DISTRICT               ,
 :OLD.S_DISTRICT             ,
 :OLD.DEPOT                  ,
 :OLD.CONTR_LOGIN            ,
 :OLD.CONTR_PASSWD           ,
 :OLD.IS_DEFAULT             ,
 :OLD.NOTES                  ,
 :OLD.SPEC_CONSID            ,
 :OLD.MDBK                   ,
 :OLD.STATE_CODE             ,
 :OLD.STATE_VALUE            ,
 :OLD.INDUSTRY_TYPE          ,
 :OLD.APPL_TYPE              ,
 :OLD.CUT_DATE               ,
 :OLD.SITE_TYPE              ,
 :OLD.STATUS                 ,
 :OLD.ARCH_IND               ,
 :OLD.ALERT_IND              ,
 :OLD.PHONE                  ,
 :OLD.FAX                    ,
 :OLD.DEV                    ,
 :OLD.CHILD_SITE2SITE        ,
 :OLD.SUPPORT_OFFICE2SITE    ,
 :OLD.CUST_PRIMADDR2ADDRESS  ,
 :OLD.CUST_BILLADDR2ADDRESS  ,
 :OLD.CUST_SHIPADDR2ADDRESS  ,
 :OLD.SITE_SUPPORT2EMPLOYEE  ,
 :OLD.SITE_ALTSUPP2EMPLOYEE  ,
 :OLD.REPORT_SITE2BUG        ,
 :OLD.PRIMARY2BUS_ORG        ,
 :OLD.SITE2EXCH_PROTOCOL     ,
 :OLD.DEALER2X_PROMOTION     ,
 :OLD.X_SMP_OPTIONAL         ,
 :OLD.UPDATE_STAMP           ,
 :OLD.X_FIN_CUST_ID          ,
 :OLD.SHIP_VIA               ,
 :OLD.X_COMMERCE_ID          ,
 :OLD.X_SHIP_LOC_ID          ,
 :OLD.X_REFERRAL_ID          ,
 :NEW.OBJID                              ,            
 :NEW.SITE_ID                ,
 :NEW.NAME                   ,
 :NEW.S_NAME                 ,
 :NEW.EXTERNAL_ID            ,
 :NEW.TYPE                   ,
 :NEW.LOGISTICS_TYPE         ,
 :NEW.IS_SUPPORT             ,
 :NEW.REGION                 ,
 :NEW.S_REGION               ,
 :NEW.DISTRICT               ,
 :NEW.S_DISTRICT             ,
 :NEW.DEPOT                  ,
 :NEW.CONTR_LOGIN            ,
 :NEW.CONTR_PASSWD           ,
 :NEW.IS_DEFAULT             ,
 :NEW.NOTES                  ,
 :NEW.SPEC_CONSID            ,
 :NEW.MDBK                   ,
 :NEW.STATE_CODE             ,
 :NEW.STATE_VALUE            ,
 :NEW.INDUSTRY_TYPE          ,
 :NEW.APPL_TYPE              ,
 :NEW.CUT_DATE               ,
 :NEW.SITE_TYPE              ,
 :NEW.STATUS                 ,
 :NEW.ARCH_IND               ,
 :NEW.ALERT_IND              ,
 :NEW.PHONE                  ,
 :NEW.FAX                    ,
 :NEW.DEV                    ,
 :NEW.CHILD_SITE2SITE        ,
 :NEW.SUPPORT_OFFICE2SITE    ,
 :NEW.CUST_PRIMADDR2ADDRESS  ,
 :NEW.CUST_BILLADDR2ADDRESS  ,
 :NEW.CUST_SHIPADDR2ADDRESS  ,
 :NEW.SITE_SUPPORT2EMPLOYEE  ,
 :NEW.SITE_ALTSUPP2EMPLOYEE  ,
 :NEW.REPORT_SITE2BUG        ,
 :NEW.PRIMARY2BUS_ORG        ,
 :NEW.SITE2EXCH_PROTOCOL     ,
 :NEW.DEALER2X_PROMOTION     ,
 :NEW.X_SMP_OPTIONAL         ,
 :NEW.UPDATE_STAMP           ,
 :NEW.X_FIN_CUST_ID          ,
 :NEW.SHIP_VIA               ,
 :NEW.X_COMMERCE_ID          ,
 :NEW.X_SHIP_LOC_ID          ,
 :NEW.X_REFERRAL_ID          
 );
  end loop;
end if;  
end;
/