CREATE OR REPLACE TRIGGER sa."TRG_EXPIRE_ACC_GRP_BENEFIT" BEFORE INSERT  ON sa.X_EXPIRE_ACCOUNT_GROUP_BENEFIT

 REFERENCING OLD AS OLD NEW AS NEW

FOR EACH ROW

BEGIN

IF :new.insert_timestamp IS NULL THEN
:NEW.insert_timestamp := SYSDATE;
END IF;

END;
/