CREATE OR REPLACE TRIGGER sa."TRG_PART_NUM_BIUD"
BEFORE INSERT OR UPDATE OR DELETE ON sa.TABLE_PART_NUM
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
 v_action VARCHAR2(1);
 v_osuser  varchar2(50);
 v_userid varchar2(30);

BEGIN
      IF INSERTING  THEN
         v_action := 'I' ;
      ELSIF  UPDATING THEN
         v_action := 'U' ;
      ELSE
         v_action := 'D' ;
      END IF;

      select objid,
             sys_context('USERENV','OS_USER')
      into  v_userid,
            v_osuser
      from table_user where upper(login_name) = upper(user);
      INSERT INTO x_PART_NUM_HIST
                  ( OBJID,
                    NOTES,
                    DESCRIPTION,
                    S_DESCRIPTION,
                    DOMAIN,
                    S_DOMAIN,
                    PART_NUMBER,
                    S_PART_NUMBER,
                    MODEL_NUM,
                    S_MODEL_NUM,
                    ACTIVE,
                    STD_WARRANTY,
                    WARR_START_KEY,
                    UNIT_MEASURE,
                    SN_TRACK,
                    FAMILY,
                    LINE,
                    REPAIR_TYPE,
                    PART_TYPE,
                    WEIGHT,
                    DIMENSION,
                    DOM_SERIALNO,
                    DOM_UNIQUESN,
                    DOM_CATALOGS,
                    DOM_BOMS,
                    DOM_AT_SITE,
                    DOM_AT_PARTS,
                    DOM_AT_DOMAIN,
                    DOM_PT_USED_BOM,
                    DOM_PT_USED_DOM,
                    DOM_PT_USED_WARN,
                    INCL_DOMAIN,
                    IS_SPPT_PROG,
                    PROG_TYPE,
                    DOM_LITERATURE,
                    P_STANDALONE,
                    P_AS_PARENT,
                    P_AS_CHILD,
                    DOM_IS_SERVICE,
                    DEV,
                    STRUCT_TYPE,
                    X_MANUFACTURER,
                    X_RETAILCOST,
                    X_REDEEM_DAYS,
                    X_REDEEM_UNITS,
                    X_DLL,
                    X_PROGRAMMABLE_FLAG,
                    X_CARD_TYPE,
                    X_PURCH_QTY,
                    X_PURCH_CARD,
                    X_TECHNOLOGY,
                    X_UPC,
                    X_WEB_DESCRIPTION,
                    X_DISPLAY_SEQ,
                    X_WEB_CARD_DESC,
                    X_CARD_PLAN,
                    X_WHOLESALE_PRICE,
                    X_SP_WEB_CARD_DESC,
                    X_PRODUCT_CODE,
                    X_SOURCESYSTEM,
                    X_RESTRICTED_USE,
                    X_CARDLESS_BUNDLE,
                    PART_NUM2PART_CLASS,
                    PART_NUM2DOMAIN,
                    PART_NUM2SITE,
                    X_EXCH_DIGITAL2PART_NUM,
                    PART_NUM2DEFAULT_PRELOAD,
                    PART_NUM2X_PROMOTION,
                    X_EXTD_WARRANTY,
                    X_OTA_ALLOWED,
                    X_OTA_DLL,
                    X_ILD_TYPE,
                    PARTNUM_HIST2PART_NUM,
                    PARTNUM_HIST2USER,
                    X_CHANGE_DATE,
                    OSUSER,
                    TRIGGERING_RECORD_TYPE)
           VALUES ( seq_x_part_num_hist.nextval,
                    decode(v_action,'I',:new.NOTES,:old.NOTES),
                    decode(v_action,'I',:new.DESCRIPTION,:old.DESCRIPTION),
                    decode(v_action,'I',:new.S_DESCRIPTION,:old.S_DESCRIPTION),
                    decode(v_action,'I',:new.DOMAIN,:old.DOMAIN),
                    decode(v_action,'I',:new.S_DOMAIN,:old.S_DOMAIN),
                    decode(v_action,'I',:new.PART_NUMBER,:old.PART_NUMBER),
                    decode(v_action,'I',:new.S_PART_NUMBER,:old.S_PART_NUMBER),
                    decode(v_action,'I',:new.MODEL_NUM,:old.MODEL_NUM),
                    decode(v_action,'I',:new.S_MODEL_NUM,:old.S_MODEL_NUM),
                    decode(v_action,'I',:new.ACTIVE,:old.ACTIVE),
                    decode(v_action,'I',:new.STD_WARRANTY,:old.STD_WARRANTY),
                    decode(v_action,'I',:new.WARR_START_KEY,:old.WARR_START_KEY),
                    decode(v_action,'I',:new.UNIT_MEASURE,:old.UNIT_MEASURE),
                    decode(v_action,'I',:new.SN_TRACK,:old.SN_TRACK),
                    decode(v_action,'I',:new.FAMILY,:old.FAMILY),
                    decode(v_action,'I',:new.LINE,:old.LINE),
                    decode(v_action,'I',:new.REPAIR_TYPE,:old.REPAIR_TYPE),
                    decode(v_action,'I',:new.PART_TYPE,:old.PART_TYPE),
                    decode(v_action,'I',:new.WEIGHT,:old.WEIGHT),
                    decode(v_action,'I',:new.DIMENSION,:old.DIMENSION),
                    decode(v_action,'I',:new.DOM_SERIALNO,:old.DOM_SERIALNO),
                    decode(v_action,'I',:new.DOM_UNIQUESN,:old.DOM_UNIQUESN),
                    decode(v_action,'I',:new.DOM_CATALOGS,:old.DOM_CATALOGS),
                    decode(v_action,'I',:new.DOM_BOMS,:old.DOM_BOMS),
                    decode(v_action,'I',:new.DOM_AT_SITE,:old.DOM_AT_SITE),
                    decode(v_action,'I',:new.DOM_AT_PARTS,:old.DOM_AT_PARTS),
                    decode(v_action,'I',:new.DOM_AT_DOMAIN,:old.DOM_AT_DOMAIN),
                    decode(v_action,'I',:new.DOM_PT_USED_BOM,:old.DOM_PT_USED_BOM),
                    decode(v_action,'I',:new.DOM_PT_USED_DOM,:old.DOM_PT_USED_DOM),
                    decode(v_action,'I',:new.DOM_PT_USED_WARN,:old.DOM_PT_USED_WARN),
                    decode(v_action,'I',:new.INCL_DOMAIN,:old.INCL_DOMAIN),
                    decode(v_action,'I',:new.IS_SPPT_PROG,:old.IS_SPPT_PROG),
                    decode(v_action,'I',:new.PROG_TYPE,:old.PROG_TYPE),
                    decode(v_action,'I',:new.DOM_LITERATURE,:old.DOM_LITERATURE),
                    decode(v_action,'I',:new.P_STANDALONE,:old.P_STANDALONE),
                    decode(v_action,'I',:new.P_AS_PARENT,:old.P_AS_PARENT),
                    decode(v_action,'I',:new.P_AS_CHILD,:old.P_AS_CHILD),
                    decode(v_action,'I',:new.DOM_IS_SERVICE,:old.DOM_IS_SERVICE),
                    decode(v_action,'I',:new.DEV,:old.DEV),
                    decode(v_action,'I',:new.STRUCT_TYPE,:old.STRUCT_TYPE),
                    decode(v_action,'I',:new.X_MANUFACTURER,:old.X_MANUFACTURER),
                    decode(v_action,'I',:new.X_RETAILCOST,:old.X_RETAILCOST),
                    decode(v_action,'I',:new.X_REDEEM_DAYS,:old.X_REDEEM_DAYS),
                    decode(v_action,'I',:new.X_REDEEM_UNITS,:old.X_REDEEM_UNITS),
                    decode(v_action,'I',:new.X_DLL,:old.X_DLL),
                    decode(v_action,'I',:new.X_PROGRAMMABLE_FLAG,:old.X_PROGRAMMABLE_FLAG),
                    decode(v_action,'I',:new.X_CARD_TYPE,:old.X_CARD_TYPE),
                    decode(v_action,'I',:new.X_PURCH_QTY,:old.X_PURCH_QTY),
                    decode(v_action,'I',:new.X_PURCH_CARD,:old.X_PURCH_CARD),
                    decode(v_action,'I',:new.X_TECHNOLOGY,:old.X_TECHNOLOGY),
                    decode(v_action,'I',:new.X_UPC,:old.X_UPC),
                    decode(v_action,'I',:new.X_WEB_DESCRIPTION,:old.X_WEB_DESCRIPTION),
                    decode(v_action,'I',:new.X_DISPLAY_SEQ,:old.X_DISPLAY_SEQ),
                    decode(v_action,'I',:new.X_WEB_CARD_DESC,:old.X_WEB_CARD_DESC),
                    decode(v_action,'I',:new.X_CARD_PLAN,:old.X_CARD_PLAN),
                    decode(v_action,'I',:new.X_WHOLESALE_PRICE,:old.X_WHOLESALE_PRICE),
                    decode(v_action,'I',:new.X_SP_WEB_CARD_DESC,:old.X_SP_WEB_CARD_DESC),
                    decode(v_action,'I',:new.X_PRODUCT_CODE,:old.X_PRODUCT_CODE),
                    decode(v_action,'I',:new.X_SOURCESYSTEM,:old.X_SOURCESYSTEM),
                    decode(v_action,'I',:new.X_RESTRICTED_USE,:old.X_RESTRICTED_USE),
                    decode(v_action,'I',:new.X_CARDLESS_BUNDLE,:old.X_CARDLESS_BUNDLE),
                    decode(v_action,'I',:new.PART_NUM2PART_CLASS,:old.PART_NUM2PART_CLASS),
                    decode(v_action,'I',:new.PART_NUM2DOMAIN,:old.PART_NUM2DOMAIN),
                    decode(v_action,'I',:new.PART_NUM2SITE,:old.PART_NUM2SITE),
                    decode(v_action,'I',:new.X_EXCH_DIGITAL2PART_NUM,:old.X_EXCH_DIGITAL2PART_NUM),
                    decode(v_action,'I',:new.PART_NUM2DEFAULT_PRELOAD,:old.PART_NUM2DEFAULT_PRELOAD),
                    decode(v_action,'I',:new.PART_NUM2X_PROMOTION,:old.PART_NUM2X_PROMOTION),
                    decode(v_action,'I',:new.X_EXTD_WARRANTY,:old.X_EXTD_WARRANTY),
                    decode(v_action,'I',:new.X_OTA_ALLOWED,:old.X_OTA_ALLOWED),
                    decode(v_action,'I',:new.X_OTA_DLL,:old.X_OTA_DLL),
                    decode(v_action,'I',:new.X_ILD_TYPE,:old.X_ILD_TYPE),
                    :old.OBJID,       --OBJID OF TABLE_PART_NUM
                    v_userid,         --OBJID OF TABLE_USER
                    SYSDATE,
                    v_osuser,
                    decode(v_action,'I','INSERT','U','UPDATE','D','DELETE'));
EXCEPTION
   WHEN OTHERS THEN
          insert_error_tab_proc ( 'Exception caught '||sqlerrm,
                                 '' ,
                                 'TRG_PART_NUM_BUID');
END;
/