CREATE OR REPLACE TRIGGER sa.trg_pageplus_addon_benefit BEFORE INSERT OR UPDATE ON sa.x_pageplus_addon_benefit  REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :NEW.UPDATE_TIMESTAMP := SYSDATE;
END;
/