CREATE OR REPLACE TRIGGER sa.TRG_STG_VZW_WAP_CASES BEFORE INSERT  ON  sa.STG_VZW_WAP_CASES
REFERENCING NEW AS NEW OLD  AS OLD
FOR EACH ROW
BEGIN
 SELECT 'OS USER: '|| SYS_CONTEXT('USERENV', 'OS_USER')||' '||'ORACLE USER: '||SYS_CONTEXT('USERENV', 'SESSION_USER')   INTO :NEW.INSERTED_BY FROM DUAL;
END;
/