CREATE OR REPLACE TRIGGER sa.TRIG_X_SLSUBS_CURRVALS
AFTER INSERT ON sa.X_SL_SUBS REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
IF INSERTING THEN
 BEGIN
  IF :new.lid IS NOT NULL THEN
    INSERT INTO sa.X_SL_CURRENTVALS (objid,lid)
    VALUES (sa.SEQ_X_SL_CURRENTVALS.nextval,:new.lid);
  END IF;
 EXCEPTION WHEN OTHERS THEN
  raise_application_error(-200120,SUBSTR('Error in TRIG_X_SLSUBS_CURRVALS While inserting into SA.X_SL_CURRENTVALS '||SQLERRM,1,255));
 END;
END IF;
END;
/