CREATE OR REPLACE TRIGGER sa."TRIG_X_JOB_DATA_BUDR" BEFORE  DELETE ON sa.X_JOB_DATA REFERENCING OLD AS OLD NEW AS NEW

FOR EACH ROW

DISABLE BEGIN
    raise_application_error (-20140,SUBSTR(' DELETE FROM X_JOB_DATA TABLE IS NOT ALLOWED '||SQLERRM,1,255));
END;
/