CREATE OR REPLACE TRIGGER sa.TSTAHIS_TRG_IG_TRANSACTION
BEFORE INSERT OR UPDATE OR DELETE ON GW1.IG_TRANSACTION
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DISABLE DECLARE
v_action VARCHAR2(1);
 v_osuser  varchar2(50);
 v_userid varchar2(30);
BEGIN
      IF INSERTING  THEN
         v_action := 'I' ;
      ELSIF  UPDATING THEN
         v_action := 'U' ;
      ELSE
         v_action := 'D' ;
      END IF;
select username, osuser
 into  v_userid,
            v_osuser
from v$session s
where s.audsid = userenv('sessionid');
      INSERT INTO sa.TSTAHIS_IG_TRANSACTION
                  ( OBJID,
ACTION_ITEM_ID,
CARRIER_ID,
ORDER_TYPE,
MIN,
ESN,
ESN_HEX,
OLD_ESN,
OLD_ESN_HEX,
PIN,
PHONE_MANF,
END_USER,
ACCOUNT_NUM,
MARKET_CODE,
RATE_PLAN,
LD_PROVIDER,
SEQUENCE_NUM,
DEALER_CODE,
TRANSMISSION_METHOD,
FAX_NUM,
ONLINE_NUM,
EMAIL,
NETWORK_LOGIN,
NETWORK_PASSWORD,
SYSTEM_LOGIN,
SYSTEM_PASSWORD,
TEMPLATE,
EXE_NAME,
COM_PORT,
STATUS,
STATUS_MESSAGE,
FAX_BATCH_SIZE,
FAX_BATCH_Q_TIME,
EXPIDITE,
TRANS_PROF_KEY,
Q_TRANSACTION,
ONLINE_NUM2,
FAX_NUM2,
CREATION_DATE,
UPDATE_DATE,
BLACKOUT_WAIT,
TUX_ITI_SERVER,
TRANSACTION_ID,
TECHNOLOGY_FLAG,
VOICE_MAIL,
VOICE_MAIL_PACKAGE,
CALLER_ID,
CALLER_ID_PACKAGE,
CALL_WAITING,
CALL_WAITING_PACKAGE,
RTP_SERVER,
DIGITAL_FEATURE_CODE,
STATE_FIELD,
ZIP_CODE,
MSID,
NEW_MSID_FLAG,
SMS,
SMS_PACKAGE,
ICCID,
OLD_MIN,
DIGITAL_FEATURE,
OTA_TYPE,
RATE_CENTER_NO,
APPLICATION_SYSTEM,
SUBSCRIBER_UPDATE,
DOWNLOAD_DATE,
PRL_NUMBER,
AMOUNT,
BALANCE,
LANGUAGE,
EXP_DATE,
                    IG_TRAN_HIST2IG_TRAN_ACT_ITEM,
                    IG_TRANSACTION2USER,
                    X_CHANGE_DATE,
                    OSUSER,
                    TRIGGERING_RECORD_TYPE )
           VALUES ( sa.SEQ_TSTAHIS_X_ZERO_OUT_MAX.nextval,
decode(v_action,'I',:new.ACTION_ITEM_ID,:old.ACTION_ITEM_ID),
decode(v_action,'I',:new.CARRIER_ID,:old.CARRIER_ID),
decode(v_action,'I',:new.ORDER_TYPE,:old.ORDER_TYPE),
decode(v_action,'I',:new.MIN,:old.MIN),
decode(v_action,'I',:new.ESN,:old.ESN),
decode(v_action,'I',:new.ESN_HEX,:old.ESN_HEX),
decode(v_action,'I',:new.OLD_ESN,:old.OLD_ESN),
decode(v_action,'I',:new.OLD_ESN_HEX,:old.OLD_ESN_HEX),
decode(v_action,'I',:new.PIN,:old.PIN),
decode(v_action,'I',:new.PHONE_MANF,:old.PHONE_MANF),
decode(v_action,'I',:new.END_USER,:old.END_USER),
decode(v_action,'I',:new.ACCOUNT_NUM,:old.ACCOUNT_NUM),
decode(v_action,'I',:new.MARKET_CODE,:old.MARKET_CODE),
decode(v_action,'I',:new.RATE_PLAN,:old.RATE_PLAN),
decode(v_action,'I',:new.LD_PROVIDER,:old.LD_PROVIDER),
decode(v_action,'I',:new.SEQUENCE_NUM,:old.SEQUENCE_NUM),
decode(v_action,'I',:new.DEALER_CODE,:old.DEALER_CODE),
decode(v_action,'I',:new.TRANSMISSION_METHOD,:old.TRANSMISSION_METHOD),
decode(v_action,'I',:new.FAX_NUM,:old.FAX_NUM),
decode(v_action,'I',:new.ONLINE_NUM,:old.ONLINE_NUM),
decode(v_action,'I',:new.EMAIL,:old.EMAIL),
decode(v_action,'I',:new.NETWORK_LOGIN,:old.NETWORK_LOGIN),
decode(v_action,'I',:new.NETWORK_PASSWORD,:old.NETWORK_PASSWORD),
decode(v_action,'I',:new.SYSTEM_LOGIN,:old.SYSTEM_LOGIN),
decode(v_action,'I',:new.SYSTEM_PASSWORD,:old.SYSTEM_PASSWORD),
decode(v_action,'I',:new.TEMPLATE,:old.TEMPLATE),
decode(v_action,'I',:new.EXE_NAME,:old.EXE_NAME),
decode(v_action,'I',:new.COM_PORT,:old.COM_PORT),
decode(v_action,'I',:new.STATUS,:old.STATUS),
decode(v_action,'I',:new.STATUS_MESSAGE,:old.STATUS_MESSAGE),
decode(v_action,'I',:new.FAX_BATCH_SIZE,:old.FAX_BATCH_SIZE),
decode(v_action,'I',:new.FAX_BATCH_Q_TIME,:old.FAX_BATCH_Q_TIME),
decode(v_action,'I',:new.EXPIDITE,:old.EXPIDITE),
decode(v_action,'I',:new.TRANS_PROF_KEY,:old.TRANS_PROF_KEY),
decode(v_action,'I',:new.Q_TRANSACTION,:old.Q_TRANSACTION),
decode(v_action,'I',:new.ONLINE_NUM2,:old.ONLINE_NUM2),
decode(v_action,'I',:new.FAX_NUM2,:old.FAX_NUM2),
decode(v_action,'I',:new.CREATION_DATE,:old.CREATION_DATE),
decode(v_action,'I',:new.UPDATE_DATE,:old.UPDATE_DATE),
decode(v_action,'I',:new.BLACKOUT_WAIT,:old.BLACKOUT_WAIT),
decode(v_action,'I',:new.TUX_ITI_SERVER,:old.TUX_ITI_SERVER),
decode(v_action,'I',:new.TRANSACTION_ID,:old.TRANSACTION_ID),
decode(v_action,'I',:new.TECHNOLOGY_FLAG,:old.TECHNOLOGY_FLAG),
decode(v_action,'I',:new.VOICE_MAIL,:old.VOICE_MAIL),
decode(v_action,'I',:new.VOICE_MAIL_PACKAGE,:old.VOICE_MAIL_PACKAGE),
decode(v_action,'I',:new.CALLER_ID,:old.CALLER_ID),
decode(v_action,'I',:new.CALLER_ID_PACKAGE,:old.CALLER_ID_PACKAGE),
decode(v_action,'I',:new.CALL_WAITING,:old.CALL_WAITING),
decode(v_action,'I',:new.CALL_WAITING_PACKAGE,:old.CALL_WAITING_PACKAGE),
decode(v_action,'I',:new.RTP_SERVER,:old.RTP_SERVER),
decode(v_action,'I',:new.DIGITAL_FEATURE_CODE,:old.DIGITAL_FEATURE_CODE),
decode(v_action,'I',:new.STATE_FIELD,:old.STATE_FIELD),
decode(v_action,'I',:new.ZIP_CODE,:old.ZIP_CODE),
decode(v_action,'I',:new.MSID,:old.MSID),
decode(v_action,'I',:new.NEW_MSID_FLAG,:old.NEW_MSID_FLAG),
decode(v_action,'I',:new.SMS,:old.SMS),
decode(v_action,'I',:new.SMS_PACKAGE,:old.SMS_PACKAGE),
decode(v_action,'I',:new.ICCID,:old.ICCID),
decode(v_action,'I',:new.OLD_MIN,:old.OLD_MIN),
decode(v_action,'I',:new.DIGITAL_FEATURE,:old.DIGITAL_FEATURE),
decode(v_action,'I',:new.OTA_TYPE,:old.OTA_TYPE),
decode(v_action,'I',:new.RATE_CENTER_NO,:old.RATE_CENTER_NO),
decode(v_action,'I',:new.APPLICATION_SYSTEM,:old.APPLICATION_SYSTEM),
decode(v_action,'I',:new.SUBSCRIBER_UPDATE,:old.SUBSCRIBER_UPDATE),
decode(v_action,'I',:new.DOWNLOAD_DATE,:old.DOWNLOAD_DATE),
decode(v_action,'I',:new.PRL_NUMBER,:old.PRL_NUMBER),
decode(v_action,'I',:new.AMOUNT,:old.AMOUNT),
decode(v_action,'I',:new.BALANCE,:old.BALANCE),
decode(v_action,'I',:new.LANGUAGE,:old.LANGUAGE),
decode(v_action,'I',:new.EXP_DATE,:old.EXP_DATE),
                     decode(v_action,'I',:new.ACTION_ITEM_ID,:old.ACTION_ITEM_ID), --ACTION_ITEM_ID OF IG_TRANSACTION
                    v_userid,         --OBJID OF TABLE_USER
                    SYSDATE,
                    v_osuser,
                    decode(v_action,'I','INSERT','U','UPDATE','D','DELETE'));
EXCEPTION
   WHEN OTHERS THEN
          insert_error_tab_proc ( 'Exception caught '||sqlerrm,
                                :old.ACTION_ITEM_ID ,
                                 'TSTAHIS_TRG_IG_TRANSACTION');
END;
/