CREATE OR REPLACE TRIGGER sa."X_SUBSCRIBER_ACTION_B_U"
BEFORE 	UPDATE ON sa.X_PAGEPLUS_SUBSCRIBER_ACTION REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  :NEW.UPDATE_TIMESTAMP := SYSDATE;
END;
/