set serveroutput on size 1000000
Set linesize 5000
set head off
select 'DATABASE NAME: '||name 
from  v$database;
PROMPT ******* INVALID OBJECTS COUNTS  *******
select OWNER,object_type, count(*)
from dba_objects
where  status='INVALID'
group by OWNER,object_type;
PROMPT ******* STATEMENT TO COMPILE INVALID OBJECTS *******
SELECT 'ALTER ' || OBJECT_TYPE|| ' '||OWNER ||'.'|| OBJECT_NAME || ' COMPILE; '
FROM DBA_OBJECTS
WHERE OBJECT_TYPE IN ('FUNCTION','PACKAGE','QUEUE','TABLE','PROCEDURE','TRIGGER','VIEW', 'SYNONYM', 'LIBRARY','MATERIALIZED VIEW','TYPE')
AND OWNER in ('SA','GW1','REPORT','W3CI','SADLL','TOPPAPP')   AND STATUS='INVALID'
UNION
SELECT 'ALTER PACKAGE '||OWNER ||'.'|| OBJECT_NAME || ' COMPILE BODY; '
FROM DBA_OBJECTS
WHERE OWNER in ('SA','GW1','REPORT','W3CI','TOPPAPP','SADLL')   AND STATUS='INVALID'
AND OBJECT_TYPE='PACKAGE BODY' 
UNION
SELECT 'ALTER TYPE '||OWNER ||'.'|| OBJECT_NAME || ' COMPILE BODY; '
FROM DBA_OBJECTS
WHERE OWNER in ('SA','GW1','REPORT','W3CI','TOPPAPP','SADLL')   AND STATUS='INVALID'
AND OBJECT_TYPE='TYPE BODY' ;

set head on
